<?php 
$data           = $this->data;
$formSubmit     = $this->url(array("module"=> "admin","controller"=>"registresuretes", "action" => "edit"), "default",true);
$backList       = $this->url(array("module"=> "admin","controller"=>"registresuretes", "action" => "list")  , "default",true);
$basePath       = VIEW_BASE_PATH;
$domaines       = $this->domaines;
$localites      = $this->localites;
$situations     = array("Célibataire" => "Célibataire", "Marié(e)" => "Marié(e)", "Divorcé(e)" => "Divorcé(e)", "Veuf(ve)" => "Veuf(ve)");
$me             = Sirah_Fabric::getUser();
$searchUrl        = $this->url(array("module" => "admin","controller" =>"ajaxres", "action" => "searchrc"  ), "default",true);
$checkLibUrl      = $this->url(array("module" => "admin","controller" =>"ajaxres", "action" => "checkrclib"), "default",true);
$checkNumUrl      = $this->url(array("module" => "admin","controller" =>"ajaxres", "action" => "checkrcnum"), "default",true);
$linkSearchParent = $this->url(array("module" => "admin","controller" =>"ajaxres", "action" => "registreslist","parentform" =>"editRegistreForm", "selectCmdKey"=> "selectRegistre","selectedKey"=>"parentid","selectedVal"=>"parentnum"), "default");
$parentid         = $this->parentid;
$parentNumRc      = $this->parentNum;
$representantid   = $this->representantid;
?>
<?php $this->headStyle()->captureStart() ?>
.input-document{width:250px;display:inline-block;}
.form-horizontal .checkbox, .form-horizontal .checkbox-inline,.form-horizontal .control-label, .form-horizontal .radio, .form-horizontal .radio-inline {padding-top:0!important}
.grpChosen{width:100px !important;}
<?php $this->headStyle()->captureEnd()   ?>
<?php
$jq     = $this->jQuery();  
$onLoad = "
jQuery('#parentnum').click(function(event){event.preventDefault();jQuery('.searchRegistre').trigger('click'); });
jQuery('.searchRegistre').click(function(event){
		event.preventDefault();
		var filterListDialog  = jQuery('<div></div>').attr('id','filterListRegistres').addClass('modal-medium');             		 
        filterListDialog.dialog2({title:'Rechercher un registre de commerce',content:'".$linkSearchParent."',autoOpen:false,modalClass:'modal-wide',removeOnClose:true,closeOnEscape: true, closeOnOverlayClick: true,showCloseHandle:true,initialLoadText:'Chargement...'});        		            		
        filterListDialog.dialog2('open'); 
});
jQuery('#selectRegistre').bind('selectThis' , function(event, param1 ) {
       event.preventDefault();
	   var  parentid = parseInt(jQuery('#createRegistreForm').find('#paiementid').val() );
	   if( !parentid && param1 ) {
		    parentid =  param1;
			jQuery('#createRegistreForm').find('#parentid').val(param1)
	   }
	   jQuery('#filterListRegistres').dialog2('close');
       document.location.href = '".$formSubmit."/parentid/'+parentid;	   
});
jQuery('#numero').change(function(){
    var numero = jQuery(this).val();
    if( numero.length < 14 ) {
	    SIRAH.dialog.alert('Entrez un numéro de registre valide','Erreur de saisie');
        return;
    }
    if( numero.length >= 14){
	  var  formSelector = jQuery('#createRegistreForm');
	  jQuery('#numRcSearching').html('Vérification du numéro RC...');
	  setTimeout(function(){
	  SIRAH.request.get(formSelector,'".$searchUrl."',{beforeSend:function(){},			   
		   success : function( data ) {
			jQuery('#numRcSearching').html('');
			if( data.error !== undefined   ) {
				SIRAH.dialog.alert(data.error,'Erreur de saisie');
                return data;
			}
			if( data.success !== undefined ) {
			   if( data.numero !== undefined) {
				   jQuery('#numero').val(data.numero);
			   }			   
			   if((data.success !== undefined) && (data.date_enregistrement_day !== undefined ) ) {
				   jQuery('#date_day').val(data.date_enregistrement_day);
				   jQuery('#date_day').trigger('chosen:updated');
			   }
			   if((data.success !== undefined) && (data.date_enregistrement_month !== undefined ) ) {
				   jQuery('#date_month').val(data.date_enregistrement_month);
				   jQuery('#date_month').trigger('chosen:updated');
			   }
			   if((data.success !== undefined) && (data.date_enregistrement_year !== undefined ) ) {
				   jQuery('#date_year').val(data.date_enregistrement_year);
				   jQuery('#date_year').trigger('chosen:updated');
			   }
			}
		  }
       });}, 500);
    }
});
jQuery('input:checkbox').bootstrapSwitch();
jQuery('input:checkbox').on('switchChange.bootstrapSwitch', function(event, state) {
	if((state == true) && (this.name =='find_documents')) {
		jQuery('#findDocumentsOptions').removeClass('hide');
		jQuery('.manualFindDocuments').addClass('hide'); 
	} 
	if((state == false) && (this.name =='find_documents')){
		jQuery('#findDocumentsOptions').addClass('hide');
		jQuery('.manualFindDocuments').removeClass('hide');
	}
});
jQuery('input:checkbox, input:radio').uniform();
jQuery('.chosen').chosen({allow_single_deselect:true,no_results_text: 'Aucun element ne correspond à ', width:'100%'});
jQuery('input[name=\'find_documents\']').click(function( event ){
        if(jQuery(this).is(':checked')) {
             jQuery('#findDocumentsOptions').removeClass('hide');
			 jQuery('.manualFindDocuments').addClass('hide');
        } else {
             jQuery('#findDocumentsOptions').addClass('hide');
			 jQuery('.manualFindDocuments').removeClass('hide');
        } 
});
jQuery('#docmini').filestyle({buttonText:'Rechercher un document',classButton:'btn btn-primary',classInput:'input-inline form-control input-document',classIcon:'glyph-icon icon-folder-open',icon: true});
jQuery('#docoriginal').filestyle({buttonText:'Rechercher un document',classButton:'btn btn-primary',classInput:'input-inline form-control input-document',classIcon:'glyph-icon icon-folder-open',icon: true});
jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});   
jQuery('#editButton').click(function(e){
      e.preventDefault();      
      var  formSelector = jQuery('#editRegistreForm');
      var  libelle      = jQuery.trim(formSelector.find('#libelle').val());
      var  numero       = jQuery.trim(formSelector.find('#numero').val());

      if( SIRAH.util.isEmpty( numero )){
		  SIRAH.dialog.alert('Entrez un numéro de registre valide','Erreur de saisie');
          return;
      }       
      formSelector.submit();
   }); ";  
  $jq->addOnLoad($onLoad);
  $jq->addJavascriptFile( $basePath . "/js/bootstrap/bootstrap-filestyle.js");
  $jq->addJavascriptFile( $basePath . "/assets-minified/widgets/uniform/uniform.js");
  $jq->addStylesheet(     $basePath . "/assets-minified/widgets/uniform/uniform.css" );
  $jq->addJavascriptFile( $basePath . "/assets-minified/widgets/input-switch/inputswitch.js");
  $jq->addStylesheet(     $basePath . "/assets-minified/widgets/input-switch/inputswitch.css" );
?>
<div     class="content-box">    
    <h3 class="content-box-header content-box-header-alt bg-default">ETAPE 1 <small> Les informations de la sûrété </small></h3>
    <form method="post" action="<?php echo $formSubmit; ?>" id="editRegistreForm" class="form-horizontal mrg15T row" role="form" enctype="multipart/form-data">
     <input type="hidden" name="registreid"     id="registreid"     value="<?php echo intval($data['registreid']); ?>" />
     <input type="hidden" name="representantid" id="representantid" value="<?php echo intval($data['representantid']); ?>" />	 
      <div class="form-group"> 
        <label class="col-sm-3 col-md-3 control-label" title="Le numéro RC doit contenir 16 caractères"> Numéro RC* : </label>
        <div   class="col-sm-9 col-md-9"> 
		    <div class="input-group">
		            <input disabled="disabled" style="text-transform:uppercase" maxlength="16" type="text" name="parentnum" id="parentnum" class="form-control" placeholder="Numéro du Registre INITIAL" value="<?php echo $parentNumRc; ?>" />
		        <div class="input-group-btn">
				    <button id="searchRegistre" title="Selectionnez un registre de commerce" type="submit" class="btn btn-primary searchRegistre"><span class="glyph-icon icon-search"></span> Selectionner un registre de commerce </button>
				</div>
			</div>
				<input type="hidden" name="selectRegistre" id="selectRegistre"  /> 
				<input type="hidden" name="parentid"       id="parentid" value="<?php echo intval($data['parentid']); ?>" />
		</div>        
	  </div>
     <div class="form-group"> 
           <label class="col-sm-3 control-label" title="Le numéro d'inscription doit contenir 14 caractères"> Numéro d'inscription* : </label>
           <div   class="col-sm-6"> <input style="text-transform:uppercase" maxlength="14" type="text" name="numero" id="numero" class="form-control" placeholder="Numéro d'inscription" value="<?php echo $data["numero"]; ?>" /></div>        
           <div   class="col-sm-3" id="numRcSearching"> </div>
	  </div>
	  <div  class="form-group">
			<label class="col-sm-12 col-md-3 control-label"> Nom du Constituant: </label> 
			<div   class="col-sm-12 col-md-9"><input type="text" name="nom_constituant" id="nom_constituant" value="<?php echo $filters['nom_constituant'];?>" class="form-control" placeholder="Saisir le nom et prénom du constituant (Facultatif) " /></div>
		</div>
		<div  class="form-group">
			<label class="col-sm-12 col-md-3 control-label"> Numéro RCCM du Constituant: </label> 
			<div   class="col-sm-12 col-md-9"><input type="text" name="numrccm_constituant" id="numrccm_constituant" value="<?php echo $filters['numrccm_constituant'];?>" class="form-control" placeholder="Saisir le numéro RCCM du constituant (Facultatif) " /></div>
		</div>
		<div  class="form-group">
			<label class="col-sm-12 col-md-3 control-label"> Titre Constitutif: </label> 
			<div   class="col-sm-12 col-md-9"><input type="text" name="libelle" id="libelle" value="<?php echo $filters['libelle'];?>" class="form-control" placeholder="Saisir le Titre Constitutif de la Surété " /></div>
		</div>
      <div class="form-group"> 
           <label class="col-sm-3 control-label"> Type de sûrété* : </label>
           <div   class="col-sm-9"> <?php echo $this->formSelect("type", intval($data["type"]), array("class"=>"form-control chosen"), $this->types); ?> </div>   
      </div>
      <div class="form-group">    
            <label class="col-sm-3 col-md-3 control-label"> Date d'enregistrement*: </label>
            <div   class="col-sm-9 col-md-9">
			  <div class="input-group">
			    <?php echo $this->formSelect("date_day"  , $data["date_day"]  , array("class" => "form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?> 
                <span class="input-group-btn" style="width:0px;"></span>
				<?php echo $this->formSelect('date_month', $data["date_month"], array("class" => "form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?>
                <span class="input-group-btn" style="width:0px;"></span>
				<?php echo $this->formSelect('date_year' , $data["date_year"] , array("class" => "form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1960, intval(date("Y")) ) );?>             
              </div>
			</div>
	  </div>      
      <?php if(($me->isAdmin() || $me->isOPS()) && !intval($data["localiteid"])): ?>
      <div class="form-group"> 
           <label class="col-sm-3 control-label"> Localité* : </label>
           <div   class="col-sm-9"> <?php echo $this->formSelect("localiteid", intval($data["localiteid"]  ), array("class"=>"form-control chosen"), $localites); ?> </div>   
      </div>
      <?php else: ?> 
      <input type="hidden" name="localiteid"  id="localiteid" value="<?php echo intval($data['localiteid']); ?>" />
      <?php endif; ?> 
      <!--	  
	  <div class="form-group">    
            <label class="col-sm-3 control-label"> Période de validité*: </label>
            <div   class="col-sm-5">
			  <div class = "input-group">
			    <?php echo $this->formSelect("periodstart_day"  , $data["periodstart_day"]  , array("class" => "form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?> 
                <span class="input-group-btn" style="width:0px;"></span>
				<?php echo $this->formSelect('periodstart_month', $data["periodstart_month"], array("class" => "form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?>
                <span class="input-group-btn" style="width:0px;"></span>
				<?php echo $this->formSelect('periodstart_year' , $data["periodstart_year"] , array("class" => "form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1960, intval(date("Y")) ) );?>             
              </div>
			</div>
			<div   class="col-sm-4">
			  <div class = "input-group">
			    <?php echo $this->formSelect("periodend_day"  , $data["periodend_day"]  , array("class" => "form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?> 
                <span class="input-group-btn" style="width:0px;"></span>
				<?php echo $this->formSelect('periodend_month', $data["periodend_month"], array("class" => "form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?>
                <span class="input-group-btn" style="width:0px;"></span>
				<?php echo $this->formSelect('periodend_year' , $data["periodend_year"] , array("class" => "form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1960, intval(date("Y")) ) );?>             
              </div>
			</div>
	  </div>
	  -->
      <div class="form-group"> 
           <label class="col-sm-3 control-label"> Description des biens : </label>
           <div   class="col-sm-9"> <input type="text" name="description" id="description" class="form-control" value="<?php echo $data["description"]; ?>" placeholder="Décrivez les biens sur lesquels la sûrété est constituée" /></div>       
      </div>	  
      <div class="form-group"> 
           <label class="col-sm-3 control-label"> Montant garanti : </label>
           <div   class="col-sm-9"> <input type="text" name="valeur" id="valeur" class="form-control" value="<?php echo $data["valeur"]; ?>" placeholder="Montant maximum garanti" /></div>       
      </div>
	  <?php if(!$representantid): ?>
	  <h3 class="content-box-header content-box-header-alt bg-default mrg10R mrg10L mrg10B">ETAPE 2 <small> Les informations du constituant </small></h3>
      <div class="form-group"> 
           <label class="col-sm-3 control-label"> Nom & Prénom*: </label>
           <div   class="col-sm-9"> 
		     <div class="input-group">
		      <input type="text" name="nom"    id="nom"    class="form-control" value="<?php echo $data["nom"]; ?>"    placeholder="Nom de famille" />
              <span class="input-group-btn" style="width:0px;"></span>
			  <input type="text" name="prenom" id="prenom" class="form-control" value="<?php echo $data["prenom"]; ?>" placeholder="Prénom" />      
            </div>
		 </div>  
	  </div>	  
      <div class="form-group"> 
           <label class="col-sm-3 control-label"> Adresse*: </label>
           <div   class="col-sm-9"> <input type="text" name="adresse" id="adresse" class="form-control" value="<?php echo $data["adresse"]; ?>" placeholder="Adresse" /></div>       
      </div>	  
      <div class="form-group"> 
           <label class="col-sm-3 control-label"> Numéro de téléphone: </label>
           <div   class="col-sm-9"> <input type="text" name="telephone" id="telephone" class="form-control" value="<?php echo $data["telephone"]; ?>" placeholder="Numéro de téléphone" /></div>       
      </div>	  
      <div class="form-group">    
            <label class="col-sm-3 control-label"> Date & lieu de naissance*: </label>
			<div   class="col-sm-9">
			   <div class = "input-group">
			       <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect("date_naissance_day", $data["date_naissance_day"]  , array("class" => "form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?></span>
				   <span class="input-group-btn" style="width:0px;"></span>
				   <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect('date_naissance_month', $data["date_naissance_month"], array("class" => "form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?> </span>
			       <span class="input-group-btn" style="width:0px;"></span>
				   <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect('date_naissance_year' , $data["date_naissance_year"] , array("class" => "form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1900, intval(date("Y")) ) );?></span>
				   <span class="input-group-btn" style="width:0px;"></span>
				   <input style="height:40px;" type="text" name="lieunaissance" id="lieunaissance" class="form-control" value="<?php echo $data["lieunaissance"]; ?>" placeholder="Lieu de naissance" />
			   </div>
			</div>    
      </div>
	  <div class="form-group"> 
           <label class="col-sm-3 control-label"> Sexe*: </label>
           <div   class="col-sm-3 radio radio-primary"> 
		     <label class="radio-inline pull-left"><input type="radio" name="sexe" id="sexe-m" value="M" <?php if($data["sexe"] == "M") echo "checked"; ?>> Homme </label>          
             <label class="radio-inline pull-left"><input type="radio" name="sexe" id="sexe-f" value="F" <?php if($data["sexe"] == "F") echo "checked"; ?>> Femme </label>
		   </div>        
      </div>
	  <div class="form-group">          
         <label class="col-sm-3 control-label"> Nationalité* : </label>
         <div class="col-sm-9"> <?php echo $this->formSelect("country", $data['country'], array("class" => "form-control chosen") , $this->countries());?> </div>
      </div>
	  <div class="form-group"> 
           <label class="col-sm-3 control-label"> Situation matrimoniale*: </label>
           <div   class="col-sm-9"> <?php echo $this->formSelect("marital_status", $data["marital_status"], array("class" => "form-control"), $situations); ?> </div>        
      </div>
	  <div class="form-group"> 
           <label class="col-sm-3 control-label"> N° passport ou N°CNIB*: </label>
           <div   class="col-sm-9"> <input type="text" name="passport" id="passport" class="form-control" value="<?php echo $data["passport"]; ?>" placeholder="Le numéro d'identité (CNIB ou PASSPORT)" /></div>        
      </div>
	  <?php endif; ?> 
      <div class="form-group"> 
           <label class="col-sm-3 control-label"> Indexation automatique: </label>
           <div   class="col-sm-9" style="height:32px;"> <input type="checkbox" data-on-color="primary" name="find_documents" class="input-switch" data-size="medium" data-on-text="Oui" data-off-text="Non" <?php echo (intval($data["find_documents"]) == 1) ? 'checked' : ''; ?> value="1"></div>
      </div>
	  <div class="form-group"> 
           <label class="col-sm-3 control-label"> Contrôle de la qualité: </label>
           <div   class="col-sm-9" style="height:32px;"> <input type="checkbox" data-on-color="primary" name="check_documents" class="input-switch" data-size="medium" data-on-text="Oui" data-off-text="Non" <?php echo (intval($data["check_documents"]) == 1) ? 'checked' : ''; ?> value="1"></div>
      </div>
	  <div id="findDocumentsOptions" class="form-group <?php echo (intval($data["find_documents"]) == 0) ? 'hide' :''; ?> "> 
	    <label class="col-sm-3 control-label"> Dossier source*: </label>
		<div   class="col-sm-9"> <input type="text" name="find_documents_src" id="find_documents_src" class="form-control" placeholder="Dossier source de stockage des documents" value="<?php echo $data["find_documents_src"]; ?>" /></div> 
	  </div>
	  <div class="form-group manualFindDocuments <?php echo (intval($data["find_documents"]) == 1) ? 'hide' :''; ?> "> 
           <label class="col-sm-3 control-label"> Le formulaire * : </label>
           <div   class="col-sm-9"> <input type="file" name="docmini" id="docmini"    /></div>        
     </div>
     <div class="form-group manualFindDocuments <?php echo (intval($data["find_documents"]) == 1) ? 'hide' :''; ?>"> 
           <label class="col-sm-3 control-label"> Le fond de dossier* : </label>
           <div   class="col-sm-9"> <input type="file" name="docoriginal"  id="docoriginal"    /></div>        
     </div>	    
    </form>
 
    <?php 
    $buttonsbar  = $this->Btnbar(array("class" => "button-pane") , $this->jqueryHandler());
    $toolCreate  = $buttonsbar->button("Mettre à jour les informations","save")->setPriority("primary");
    $toolCancel  = $buttonsbar->button("Annuler et revenir sur la liste","ban");
     
    $toolCreate->setAttributes(array("type" => "submit", "class" => "btn btn-success"));
    $toolCancel->setAttributes(array("type" => "submit"));
     
    $buttonsbar->add($toolCreate ,"editButton");
    $buttonsbar->add($toolCancel ,"cancelCreationButton");
    
    if( !$this->isAjax )
        echo $buttonsbar;
    ?>
</div>

<?php     
   if( $this->isAjax) {
   	   echo $this->jQuery();
   }
   
   ?>