<?php 
$data       = $this->data;
$formSubmit = $this->url(array("module"=>"admin","controller"=>"articles","action"=>"edit"),"default",true);
$backList   = $this->url(array("module"=>"admin","controller"=>"articles","action"=>"list"),"default",true);
 
$jq         = $this->jQuery(); 
$onLoad     = "var composantes = []; var souscomposantes=[]; var axespecifiques =[]; \n ";
 
$onLoad    .= "
 
jQuery('.chosen').chosen({allow_single_deselect:true,no_results_text:  'Aucun element ne correspond à ',width:'100%',placeholder_text_single:'Sélectionnez un élement'});
jQuery('#catid').chosen({allow_single_deselect:true,no_results_text:'Aucune catégorie d\'articles ne correspond à ', width:'100%'});

";
$onLoad      .= " 
tinymce.init({selector:'textarea',language:'fr_FR',plugins:[
'advlist autolink lists link image charmap print preview hr anchor pagebreak',
'searchreplace wordcount visualblocks visualchars code fullscreen',
'insertdatetime media nonbreaking save table contextmenu directionality',
'template paste textcolor colorpicker textpattern imagetools codesample toc help emoticons hr'
],
toolbar1: 'formatselect | bold italic  strikethrough  forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
image_advtab:true});
jQuery('#photogarde').filestyle({buttonText:'Chercher une photo',classButton:'btn btn-primary',classInput:'input-inline form-control',classIcon:'glyph-icon icon-folder-open',icon: true});
jQuery('#articledoc').filestyle({buttonText:'Chercher un document',classButton:'btn btn-primary',classInput:'input-inline form-control',classIcon:'glyph-icon icon-folder-open',icon: true});

jQuery('.chosen').chosen({allow_single_deselect:true,no_results_text: 'Aucun element ne correspond à ',width:'100%',placeholder_text_single:'Sélectionnez un élement'});
jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});  
jQuery('#editButton').click(function(e){
	e.preventDefault();    
	var formSelector = jQuery('#editArticleForm');
	var title        = formSelector.find('#title').val();
	var catid        = parseInt(formSelector.find('#catid').val());
	var contenu      = tinymce.get('content').getContent();
	var introtext    = tinymce.get('introtext').getContent();

	if(SIRAH.util.isEmpty(title)) {
	   jQuery('#title-validation-message').html('');
	   SIRAH.error.raise('title-validation-message', 'Saisissez le titre de l\'article');
	   return;
	} else {
	   jQuery('#title-validation-message').html('');
	}
	if(!catid) {
	   jQuery('#categorie-validation-message').html('');
	   SIRAH.error.raise('categorie-validation-message', 'Sélectionnez une catégorie');
	   return;
	} else {
	   jQuery('#categorie-validation-message').html('');
	}	
	formSelector.find('#content').val(contenu); 
	formSelector.find('#introtext').val(introtext);  
	formSelector.submit();
}); ";
$basePath           = VIEW_BASE_PATH;
$jq->addOnLoad( $onLoad );
$jq->addStyleSheet(    $basePath ."/assets-minified/widgets/pickadate/themes/default.css");
$jq->addStyleSheet(    $basePath ."/assets-minified/widgets/pickadate/themes/default.date.css");
$jq->addStyleSheet(    $basePath ."/assets-minified/widgets/pickadate/themes/default.time.css");
$jq->addJavascriptFile($basePath ."/assets-minified/widgets/pickadate/picker.js");
$jq->addJavascriptFile($basePath ."/assets-minified/widgets/pickadate/picker.date.js");
$jq->addJavascriptFile($basePath ."/assets-minified/widgets/pickadate/picker.time.js");
$jq->addJavascriptFile($basePath ."/assets-minified/widgets/pickadate/translations/fr_FR.js");
$jq->addJavascriptFile($basePath."/js/jquery.dynamic-select.min.js");
$jq->addJavascriptFile($basePath.'/js/chosen/ajaxchosen.min.js');
$jq->addJavascriptFile($basePath."/js/bootstrap/bootstrap-filestyle.js");
$jq->addJavascriptFile($basePath."/js/editors/tinymce2/tinymce.min.js");
?>
<?php $this->headStyle()->captureStart() ?>
.bootstrap-filestyle input{float:left;width:70%;}
.bootstrap-filestyle label{float:left;width:30%;}
.input-photo{width:250px;display:inline-block;}
.form-horizontal .checkbox, .form-horizontal .checkbox-inline, .form-horizontal .control-label, .form-horizontal .radio, .form-horizontal .radio-inline {padding-top:0!important}
.grpChosen{width:100px !important;}
.input-group-chosen{width:100%;}
.chosen-container-single .chosen-single{height:35px;line-height:35px;}
<?php $this->headStyle()->captureEnd()   ?>
<form method="post" action="<?php echo $formSubmit;?>" id="editArticleForm" role="form" class="form-horizontal editArticleForm" enctype="multipart/form-data">
    <div class="panel panel-default" >
		<ul class="list-group">
		    <li class="list-group-item">
				<div class="form-group">            
					<label class="col-md-2  col-sm-2 control-label"> Catégorie*: </label> 
					<div   class="col-md-10 col-sm-10"> <?php echo $this->formSelect("catid",intval($data["catid"]), array("class"=>"form-control"), $this->categories); ?>   </div> 				
				    <p id="categorie-validation-message" class="validation-message"></p> 
				</div>					
			</li>			 
		    <li class="list-group-item">
				<div class="form-group">
				   <label class="col-md-2 col-sm-2  control-label" for="title"> Titre*: </label>
				   <div   class="col-md-10 col-sm-10"><input id="title" name="title" type="text" maxlength="220" class="form-control" title="Titre de l'article" placeholder="Titre de l'article" value="<?php echo $data["title"]; ?>"></div> 			   
				   <p id="title-validation-message" class="validation-message"></p> 
				</div>     
			</li>  
			<li class="list-group-item">
				<div class="form-group">
				   <label class="col-md-2 col-sm-2  control-label" for="keywords">Mots clés: </label>
				   <div   class="col-md-10 col-sm-10"><input id="keywords" name="keywords" type="text" maxlength="220" class="form-control" title="Mots clés de l'article" placeholder="Mots clés de l'article" value="<?php echo $data["keywords"]; ?>"></div> 			   
				   <p id="keywords-validation-message" class="validation-message"></p> 
				</div>     
			</li>	
            <li class="list-group-item">
				<div class="form-group">
				   <label class="col-md-2 col-sm-2  control-label" for="alias">Alias: </label>
				   <div   class="col-md-10 col-sm-10"><input id="alias" name="alias" type="text" maxlength="220" class="form-control" title="Mots clés de l'article" placeholder="Mots clés de l'article" value="<?php echo $data["alias"]; ?>"></div> 			   
				   <p id="alias-validation-message" class="validation-message"></p> 
				</div>     
			</li>  
            <li class="list-group-item">
			    <div class="form-group">              
					<label class="col-sm-2  col-md-2 control-label">Photo de garde: </label>
					<div   class="col-sm-10 col-md-10"> <input type="file" name="photogarde" id="photogarde"  /> </div>  
			    </div>
			</li>  
            <li class="list-group-item">
			    <div class="form-group">              
					<label class="col-sm-2  col-md-2 control-label"> Pièce Jointe: </label>
					<div   class="col-sm-10 col-md-10"> <input type="file" name="articledoc" id="articledoc"  /> </div>  
			    </div>
			</li>	
            <li class="list-group-item">
				<div class="form-group">
					<label class="col-md-2 col-sm-2 control-label"> Introduction: </label>
					<div   class="col-md-10 col-sm-10"><textarea rows="5" cols="75" name="introtext" id="introtext" class="form-control textarea-sm"> <?php echo $data["introtext"]; ?> </textarea></div>              
				</div>  
			</li>			
            <li class="list-group-item">
				<div class="form-group">
					<label class="col-md-2 col-sm-2 control-label"> Contenu*: </label>
					<div   class="col-md-10 col-sm-10"><textarea rows="5" cols="75" name="content" id="content" class="form-control textarea-sm"> <?php echo $data["content"]; ?> </textarea></div>              
				</div>  
			</li>				
		</ul>
		 
<?php     
   $buttonsbar = $this->Btnbar(array() , $this->jqueryHandler());
   $toolEdit   = $buttonsbar->button("Enregistrer","save")->setPriority("primary");
   $toolCancel = $buttonsbar->button("Annuler","chevron-left");
   
   $toolEdit->setAttributes(array("type"=> "submit"));
   $toolCancel->setAttributes(array("type"=> "submit"));
      
   $buttonsbar->add( $toolCancel , "cancelCreationButton");
   $buttonsbar->add( $toolEdit , "editButton");

   if(!$this->isAjax) {
   	   echo "<div class=\"panel-footer\"> ".$buttonsbar." </div>";
   } else {
   	   echo $this->jQuery();
	   echo $this->headStyle();
   }  
?>
</div> 
  <input type="hidden" name="articleid" id="articleid" value="<?php echo $this->articleid; ?>"  />
  <input type="hidden" name="id"        id="id"        value="<?php echo $this->articleid; ?>"  />
</form>