<?php 
$member      = $this->member;
$memberid    = $this->memberid;
$groupe      = $this->groupe;
$famille     = $this->famille;
$paiements   = $this->paiements;
$factures    = $this->factures;
$visites     = $this->visites;
$documents   = $this->documents;
$commandes   = $this->commandes;
$entreprise  = $this->entreprise;
$assureurs   = $this->assureurs;
$ville       = $this->ville;
$pays        = $this->pays;

$situations  = array("Célibataire" => "Célibataire","Marié(e)"=> "Marié(e)","Divorcé(e)"=> "Divorcé(e)","Veuf(ve)"=> "Veuf(ve)");
$civilites   = array("Mr" => "Monsieur", "Mme" => "Madame", "Mle" => "Mademoiselle", "Excellence"=>"Son excellence","Maître" => "Maître","Dr" => "Docteur","Pr" => "Professeur");

$situation   = (isset( $situations[$member->matrimonial])) ? $situations[$member->matrimonial]: "";
$civilite    = (isset( $civilites[$member->civilite]    )) ? $civilites[$member->civilite]: "";

$villeVal    = ( $ville ) ? $ville->libelle : "";
$paysVal     = ( $pays  ) ? $pays->libelle  : "";

$basePath    = VIEW_BASE_PATH;
$jq          = $this->jQuery();

$linkCancel  = $this->url(array("controller" => "members", "action"  => "list"  ) , "default");
$linkCreate  = $this->url(array("controller" => "members", "action"  => "create") , "default");
$linkEdit    = $this->url(array("controller" => "members", "action"  => "edit"   , "memberid" => $memberid) , "default");
$linkPhoto   = $this->url(array("controller" => "members", "action"  => "photo"  , "memberid" => $memberid) , "default");
$linkDelete  = $this->url(array("controller" => "members", "action"  => "delete" , "ids" => $memberid ), "default");

$jq->addStyleSheet( $basePath ."/assets-minified/widgets/tabs-ui/tabs.css");
$jq->addJavascriptFile( $basePath . "/assets-minified/widgets/tabs-ui/tabs.js" );
$jq->addOnload(" jQuery('.tabs').tabs();");

$buttonBar    = $this->Btnbar(array("class" => "button-pane"), $this->jqueryHandler());
$buttonCreate = $buttonBar->button("Enregistre un autre member", "plus");
$buttonEdit   = $buttonBar->button("Mettre à jour"         , "edit");
$buttonDelete = $buttonBar->button("Supprimer"             , "trash-o");
$buttonCancel = $buttonBar->button("Revenir sur la liste"  , "ban");

$buttonEdit->setAttributes(array("class" => "active glyph-icon icon-edit"));

$buttonBar->add( $buttonCreate , "createButton");
$buttonBar->add( $buttonEdit   , "editButton");
$buttonBar->add( $buttonDelete , "deleteButton");
$buttonBar->add( $buttonCancel , "cancelButton");

$buttonCreate->setAttributes(array("type" => "submit", "class" => "btn btn-success"));
$buttonEdit->setAttributes(  array("type" => "submit", "class" => "btn btn-primary"));
$buttonDelete->setAttributes(array("type" => "submit", "class" => "btn alert-danger"));
$buttonCancel->setAttributes(array("type" => "submit"));

$buttonCreate->onClick( sprintf("event.preventDefault(); document.location.href='%s';" , $linkCreate));
$buttonEdit->onClick(   sprintf("event.preventDefault(); document.location.href='%s';" , $linkEdit  ));
$buttonDelete->onClick( sprintf("event.preventDefault(); document.location.href='%s';" , $linkDelete));
$buttonCancel->onClick( sprintf("event.preventDefault(); document.location.href='%s';" , $linkCancel));

$creationDate         = $updateDate = "00/00/0000";
$creator              = Sirah_Fabric::getUser($member->creatorid);
$updatedUser          = Sirah_Fabric::getUser($member->updateduserid);
if( $member->creationdate ) {
	$zendCreationdate = new Zend_Date( $member->creationdate , Zend_Date::TIMESTAMP );
	$creationDate     = $zendCreationdate->toString("d MMM Y");
}
if( $member->updatedate ) {
	$zendUpdatedate   = new Zend_Date( $member->updatedate , Zend_Date::TIMESTAMP );
	$updateDate       = $zendUpdatedate->toString("d MMM Y");
}
$this->toolsbar       = $buttonBar;
?>
<div  class="container" style="text-align:left;">
 <div class="row">
  <div class="col-md-7">
   <div class="panel panel-default">
	 <div class="panel-heading"> <h4 class="panel-title"> <span class='glyph-icon icon-user'></span> Les informations personnelles du member </h4> </div>
	 <ul class="list-group">
	    <li class="list-group-item">
            <div class="row"> 
                <div class="col-md-4"> <b> Code member :</b></div> 
                <div class="col-md-8"><?php echo $member->code; ?></div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row"> 
                <div class="col-md-4"> <b> N° Passport:</b></div> 
                <div class="col-md-8"><?php echo $member->passport; ?></div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row"> 
                <div class="col-md-4"> <b> Nom & Prénom  :</b></div> 
                <div class="col-md-8"><?php printf("%s %s %s", $civilite, $member->lastname, $member->firstname ); ?></div>
            </div>
        </li>
        <?php if( $entreprise): ?>
		<?php
		     $linkEntreprise  = $this->url(array("controller"  => "entreprise", "action"  => "infos", "entrepriseid"  => $entreprise->entrepriseid ), "default");
		?>
        <li class="list-group-item">
            <div class="row"> 
                <div class="col-md-4"> <b> Entreprise :</b></div> 
                <div class="col-md-8"> <a href="<?php echo $linkEntreprise; ?>"> <?php echo $entreprise->libelle; ?> </a></div>
            </div>
        </li>
        <?php endif; ?>		
         <?php if( $famille): ?>
          <a class="list-group-item">
            <div class="row"> 
                <div class="col-md-4"> <b> Famille marraine :</b></div> 
                <div class="col-md-8"><?php echo $famille->libelle; ?></div>
            </div>
         </a>
        <?php endif; ?>
        <?php if( $groupe ): ?>
        <li class="list-group-item">
            <div class="row"> 
                <div class="col-md-4"> <b> Groupe :</b></div> 
                <div class="col-md-8"><?php echo $groupe->libelle; ?></div>
            </div>
        </li>
        <?php endif; ?>
        <?php if( $famille ): ?>
        <li class="list-group-item">
            <div class="row"> 
                <div class="col-md-4"> <b> Famille :</b></div> 
                <div class="col-md-8"><?php echo $famille->libelle; ?></div>
            </div>
        </li>
        <?php endif; ?>
        <li class="list-group-item">
            <div class="row"> 
                <div class="col-md-4"> <b> Sexe :</b></div> 
                <div class="col-md-8"><?php echo $member->sexe; ?></div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row"> 
                <div class="col-md-4"> <b> Situation matrimoniale:</b></div> 
                <div class="col-md-8"><?php echo $situation; ?></div>
            </div>
        </li>
         <?php if( $member->creatorid ): ?>
        <li class="list-group-item">
              <div class="row"> 
                  <div class="col-md-4"> <b> Créé le:</b></div> 
                  <div class="col-md-8"><?php printf("%s par %s %s", $creationDate , $creator->lastname, $creator->firstname ); ?></div>
             </div>
        </li>
        <?php endif; ?>
        <?php if( $member->updateduserid ): ?>
           <li class="list-group-item">
             <div class="row"> 
                       <div class="col-md-4"> <b> Mis à jour le:</b> </div> 
                       <div class="col-md-8"><?php printf("%s par %s %s", $updateDate, $updatedUser->lastname, $updatedUser->firstname ); ?></div>
             </div>
           </li>
       <?php endif; ?> 
	 </ul>
    </div>
   </div> 
   
   <div class="col-md-5">
       <div class="panel-group" id="accordion">
	    <div class="panel panel-default">
		    <div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#memberAddress"><span class='glyph-icon icon-user'></span> Les coordonnées </a></h4> </div>
			<div id="memberAddress" class="panel-collapse collapse in"> <?php echo $this->partial("members/profile/address.phtml", array("member"=> $member, "memberid" => $member->memberid)); ?> </div>			
		</div>
		<?php if($me->isAllowed("visites", "list")): ?> 
		<div class="panel panel-default">
		    <div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#memberVisites"><span class='glyph-icon icon-th-list'></span> Historique des visites </a></h4> </div>
			<div id="memberVisites" class="panel-collapse collapse"> 
			  <?php echo $this->partial("members/visites.phtml", array("member"=> $member, "visites"=>$visites, "memberid" => $member->memberid )); ?> 
			  <?php if($me->isAllowed("visites", "create")): ?>  
			    <div class="panel-footer">
                  <div class="controls"><button type="submit" class="btn btn-primary glyph-icon icon-plus-circle addVisite"> Enregistrer une visite </button></div>
                </div>
			  <?php endif; ?>
			</div>			
		</div>
		<?php endif; ?>
		<?php if($me->isAllowed("vcommandes", "list")): ?> 
		<div class="panel panel-default">
		    <div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#memberCommandes"><span class='glyph-icon icon-th-list'></span> Historique des commandes </a></h4> </div>
			<div id="memberCommandes" class="panel-collapse collapse"> 
			  <?php echo $this->partial("members/commandes.phtml", array("member"=> $member, "commandes"=>$commandes , "memberid" => $member->memberid)); ?> 
			  <?php if($me->isAllowed("vcommandes", "create")): ?>  
			    <div class="panel-footer">
                  <div class="controls"><button type="submit" class="btn btn-primary glyph-icon icon-plus-circle addCommande"> Enregistrer une commande </button></div>
                </div>
			  <?php endif; ?>
			</div>			
		</div>
		<?php endif; ?>
		<?php if($me->isAllowed("vfactures","list")): ?> 
		<div class="panel panel-default">
		  <div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#memberInvoices"><span class='glyph-icon icon-th-list'></span> Historique des factures</a></h4> </div>
		  <div id="memberInvoices" class="panel-collapse collapse"> 
		    <?php echo $this->partial("members/factures.phtml", array("member"=> $member, "factures"=> $factures, "memberid" => $member->memberid)); ?> 
			<?php if($me->isAllowed("vfactures", "create")): ?>  
			  <div class="panel-footer">
                <div class="controls"><button type="submit" class="btn btn-primary glyph-icon icon-plus-circle addInvoice"> Enregistrer une facture </button></div>
              </div>
			<?php endif; ?>
		  </div>			
		</div>
		<?php endif; ?>
		<?php if($me->isAllowed("vpaiements","list")): ?>
		<div class="panel panel-default">
		    <div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#memberPayments"><span class='glyph-icon icon-th-list'></span> Historique des commandes </a></h4> </div>
			<div id="memberPayments" class="panel-collapse collapse"> 
			   <?php echo $this->partial("members/paiements.phtml", array("member"=> $member, "paiements"=> $paiements, "memberid" => $member->memberid)); ?> 
			   <?php if($me->isAllowed("vpaiements", "create")): ?>  
				 <div class="panel-footer">
                    <div class="controls"><button type="submit" class="btn btn-primary glyph-icon icon-plus-circle addPaiement"> Enregistrer un paiement </button></div>
                 </div>
			   <?php endif; ?>
			</div>			
		</div>
		<?php endif; ?>
		<div class="panel panel-default">
		    <div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#commandeDocuments"><span class='glyph-icon icon-list-alt'></span> Historique des documents</a></h4> </div>
			<div id="commandeDocuments" class="panel-collapse collapse"> 
			    <?php echo $this->partial("members/documents.phtml",array("documents" => $documents,"member" => $member,"memberid" => $memberid)); ?>
                <?php if($me->isAllowed("vcommandes","upload")): ?> 
				<div class="panel-footer">
                    <div class="controls"><button type="submit" class="btn btn-primary glyph-icon icon-plus-circle uploadFile"> Ajouter un document</button></div>
                </div>
				<?php endif; ?>
			</div>			
		</div>		  
	   </div> 
   </div> 
  </div>  
</div>
<?php 
     if( $this->isAjax ) {
     	 echo $this->jQuery();
	     echo $this->headStyle();
     }
?>
 