<?php 
$front              = Zend_Controller_Front::getInstance();
$defaultController  = $front->getDefaultControllerName();
$defaultAction      = $front->getDefaultAction();
$captcha            = $this->captcha;
$messages           = $this->messages;
$data               = $this->data;
$formSubmit         = $this->url(array("module"=>"public","controller"=>"account"   ,"action"=>"login"   ),"default",true);
$forgotPasswordLink = $this->url(array("module"=>"public","controller"=>"recoverpwd","action"=>"init"    ),"default",true);
$registerLink       = $this->url(array("module"=>"public","controller"=>"members"   ,"action"=>"register"),"default",true);
$linkCancel         = $this->url(array("module"=>"public","controller"=>$defaultController,"action"=>$defaultAction ),"default",true);
$linkActivate       = $this->url(array("module"=>"public","controller"=>"account"   ,"action"=>"sendactivationtoken"),"default",true);
$basePath           = VIEW_BASE_PATH;
$register           = $this->register;
$headScript         = $this->headScript();
$headScript->appendFile("https://www.google.com/recaptcha/api.js","text/javascript");
?>
<?php $this->headStyle()->captureStart() ?>
 body{overflow:hidden;}
<?php $this->headStyle()->captureEnd()   ?>
<?php
$jq     = $this->jQuery();  
$onLoad = " 
jQuery('body').keydown(function(e) {if (e.keyCode===13) {jQuery('.btn-primary').trigger('click');}});
jQuery('.cancelLogin').click(function(e){e.preventDefault();document.location.href='".$linkCancel."';});
jQuery('.register,#createAccount').click(function(e){e.preventDefault();document.location.href='".$registerLink."';});  
jQuery('#recoverPwd').click(function( e){e.preventDefault();document.location.href='".$forgotPasswordLink."';});
jQuery('.checkCaptcha').click(function(e) { 
    e.preventDefault(); 
    var formSelector= jQuery('#accountLoginForm'); 
    var code        = jQuery('#captchainput').val();     
    if( SIRAH.util.isEmpty(code)){
        SIRAH.error.raise('accountLoginForm','Saisir une valeur valide');
        return;
    }
    formSelector .submit();
});
jQuery('#activateAccount').click(function(e){e.preventDefault();document.location.href='".$linkActivate."';});
jQuery('#connectBtn').click(function(e) {
    e.preventDefault();
    var formSelector= jQuery('#accountLoginForm');     
    var username    = jQuery.trim(jQuery('#username').val());
    var credential  = jQuery.trim(jQuery('#password').val());      
    if( SIRAH.util.isEmpty(username)){
        jQuery('#username').addClass('input-error');
        SIRAH.error.raise('accountLoginForm','Entrez un nom d\'utilisateur valide');
        return;
    }      
    if( SIRAH.util.isEmpty(credential) || (parseInt(credential.length) < 3)){
        jQuery('#password').addClass('input-error');
        SIRAH.error.raise('accountLoginForm','Entrez un mot de passe valide');
        return;
    }
    formSelector .submit();      
}); ";
$jq->addOnLoad($onLoad);
?>
<div class="container form-container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
            <div class="panel panel-default panel-more-shadow">
				<div class="panel-body">
					<div class="panel-desc"> <h1 class="section-hero"> Connexion </h1> </div> <hr>
					<form id="accountLoginForm" method="post" action="<?php echo $formSubmit; ?>" role="form">
						<?php if( ( null!= $captcha ) && $this->showcaptcha): ?>
							<div class="form-group"> <?php echo $this->errormessage(); ?></div>
							<div class="form-group"><div class="col-sm-12"> <img width="100%"  alt="Entrez le code qui apparait dans l'image" src="<?php  echo $captcha->getImgUrl(). $captcha->getId()  ?>.png" /><br/> </div> </div>
							<div style="margin-bottom: 25px;width:100%;" class="input-group">
							  <input type="text" name="captcha[input]" id="captchainput" class="form-control" autocomplete="off" placeholder="Entrez le code qui apparait dans l'image" >
							</div>
							<input type="hidden" name="captcha[id]"  value="<?php echo $captcha->getId();  ?>"  /><br/>
							<input type="hidden" name="captchatime"  id="captchatime" value="<?php echo time(); ?>"  /> 
						<?php endif; ?>
						<?php if((null==$captcha) || (false==$this->showcaptcha)): ?>
							<div class="form-group"> <?php echo $this->errormessage(); ?></div>
							<div style="margin-bottom:25px" class="input-group"><span class="input-group-addon"><i class="glyph-icon icon-user"></i></span><input name="username" type="email" class="form-control" id="username" placeholder="Votre adresse email" value="<?php echo $data["username"];  ?>" autocomplete="off" ></div>
							<div style="margin-bottom:25px" class="input-group"><span class="input-group-addon"><i class="glyph-icon icon-lock"></i></span><input type="password" class="form-control" id="password" placeholder="Votre mot de passe" name="password" autocomplete="off" ></div>
							<div style="margin-bottom:25px" class="input-group">
								<div class="col-md-12 g-recaptcha" data-sitekey="<?php echo API_GOOGLE_RECAPTCHA_SITE_KEY; ?>"></div>
							</div>  
						<?php endif; ?> 
						<?php if(( null!=$captcha) && $this->showcaptcha): ?>
						<button type="submit" class="btn btn-primary btn-lg btn-block checkCaptcha"><i class="glyph-icon icon-check"></i> VERIFIER </button> 
						<?php else: ?>						
						<div class="form-group">
							<div class="col-md-6"><div class="checkbox m-bot15"><label><input id="rememberme" name="rememberme" type="checkbox" <?php echo (isset($data['rememberme']))? intval($data['rememberme']) : 1; ?>>Se souvenir de moi.</label></div></div>
							<div class="col-md-6"><a id="activateAccount" class="activateAccount pull-left" href="<?php echo $linkActivate; ?>" title="Activer mon compte"> Activer mon compte </a></div> 
							<button type="submit" class="btn btn-primary btn-lg btn-block connect" id="connectBtn"><i class="glyph-icon icon-sign-in"></i> ME CONNECTER </button>   					   
						</div>
						
						<?php endif; ?>
						<div class="form-group m-top15"><a id="createAccount" class="register   pull-left"  href="#" title="Enregistrer un nouveau compte">  Je n'ai pas de compte</a></div> 				  
						<div class="form-group m-top15"><a id="recoverPwd"    class="recoverPwd pull-right" href="#" title="Réinitialiser mon mot de passe"> Mot de passe oublié ? </a></div>   
						   <input type="hidden" name="<?php echo $this->csrfTokenId; ?>"  id="<?php echo $this->csrfTokenId; ?>"  value="<?php echo $this->csrfTokenValue; ?>" />   
						   <input type="hidden" name="continue"   id="continue"   value="<?php echo $this->escape( $this->doneUri ); ?>" />
					       <input type="hidden" name="rememberme" id="rememberme" value="1" />
					</form>
				</div>
            </div>      
        </div>   
    </div>
</div>



 