<?php 
   $entreprise         = $this->entreprise;
   $countries          = $this->countries();
   $entrepriseCountry  = (isset($countries[$entreprise->country])) ? $countries[$entreprise->country] : $entreprise->country;
   
   $linkEdit           = $this->url(array("module" => "admin","controller"  => "entreprise" , "action" => "edit" , "id"  => $entreprise->id) , "default" ) ;
   
   $buttonbar          = $this->buttonbar(array() , $this->jqueryHandler());
    
   $buttonEdit         = $buttonbar->button(" Mettre à jour les informations","edit")->setPriority("primary");
   $buttonCancel       = $buttonbar->button("Annuler" , "ban-circle");
   
   $buttonbar->add($buttonEdit ,"saveButton");
   $buttonbar->add($buttonCancel ,"cancelButton");
   
   $buttonEdit->onClick("document.location.href= '".$linkEdit."' ;");
?>
  
 <div class="container pagecontainer col-md-12" style="text-align:left;">
    <ul class="list-group">
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-4"> <label class="label" for="libelle"> <b>  Désignation de l'entreprise:</b> </label></div> 
            <div class="col-md-8"><?php echo $this->escape($entreprise->libelle);  ?></div>
       </div>
     </li> 
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-4"> <label class="label" for="ifu"> <b> Numéro IFU :</b> </label></div> 
            <div class="col-md-8"><?php echo $this->escape($entreprise->ifu);  ?></div>
       </div>
     </li> 
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-4"> <label class="label" for="slogan"> <b> Slogan :</b> </label></div> 
            <div class="col-md-8"><?php echo $this->escape($entreprise->slogan);  ?></div>
       </div>
     </li> 
     <li class="list-group-item">    
       <div class="row col-md-12"> 
            <div class="col-md-4"> <label class="label" for="telephone"> <b> Téléphone : </b> </label></div> 
            <div class="col-md-8"><?php echo $this->escape($entreprise->telephone);  ?></div>
       </div>
    </li> 
    <li class="list-group-item">   
       <div class="row col-md-12"> 
            <div class="col-md-4"> <label class="label" for="email"> <b> Adresse e-mail : </b> </label> </div> 
            <div class="col-md-8"><?php echo $this->escape($entreprise->email);  ?></div>
       </div>
    </li> 
    <li class="list-group-item">    
         <div class="row col-md-12"> 
            <div class="col-md-4"> <label class="label" for="codepostal"> <b>  Code postal: </b> </label> </div> 
            <div class="col-md-8"><?php echo $this->escape($entreprise->codepostal);  ?></div>
       </div>
    </li> 
    <li class="list-group-item">     
         <div class="row col-md-12"> 
            <div class="col-md-4"> <label class="label" for="siteweb"> <b> Site Web: </b> </label> </div> 
            <div class="col-md-8"><?php echo $entreprise->siteweb;  ?></div>
       </div>
    </li> 
    <li class="list-group-item">     
         <div class="row col-md-12"> 
            <div class="col-md-4"> <label class="label" for="pays"> <b> Pays :  </b> </label> </div> 
            <div class="col-md-8"><?php echo $this->escape($entrepriseCountry);  ?></div>
       </div>
    </li> 
    <li class="list-group-item">     
        <div class="row col-md-12"> 
            <div class="col-md-4"> <label class="label" for="pays"> <b> Ville : </b> </label> </div> 
            <div class="col-md-8"><?php echo $this->escape($entreprise->ville);  ?></div>
       </div>
   </li> 
   <li class="list-group-item">  
        <div class="row col-md-12"> 
            <div class="col-md-4"><label class="label" for="fax"> <b> Fax  : </b> </label> </div> 
            <div class="col-md-8"><?php echo $this->escape($entreprise->fax);  ?></div>
       </div>
   </li> 
   <li class="list-group-item">     
          <div class="row col-md-12"> 
            <div class="col-md-4"> <label class="label" for="adresse"><b> Adresse : </b> </label> </div> 
            <div class="col-md-8"><?php echo $this->escape($entreprise->adresse);  ?></div>
       </div>
  </li> 
  <li class="list-group-item">  
        <div class="row col-md-12"> 
            <div class="col-md-4"> <label class="label" for="adresse"><b> Responsable : </b> </label> </div> 
            <div class="col-md-8"><?php echo $this->escape($entreprise->responsable);  ?></div>
       </div>
 </li>
  </ul>
  </div>
  
    <?php 
          if(!$this->isAjax) {
          	 echo $buttonbar;
          } else {
          	 echo $this->jQuery();
          }
      ?>
       