<?php
$demande           = $this->demande;
$demandeid         = $this->demandeid;
$entreprise        = $this->entreprise;
$demandeur         = $this->demandeur;
$params            = $this->params;
$content           = $this->contenu;

$formSubmit        = $this->url(array("module"=>"admin","controller"=>"demandes"     ,"action"=>"get"   ,"demandeid"=>$demandeid),"default");
$linkVerify        = $this->url(array("module"=>"admin","controller"=>"demandes"     ,"action"=>"verify","demandeid"=>$demandeid),"default");
$linkCancel        = $this->url(array("module"=>"admin","controller"=>"demandes"     ,"action"=>"infos" ,"demandeid"=>$demandeid),"default");
$linkUserdocuments = $this->url(array("module"=>"admin","controller"=>"userdocuments","action"=>"infos" ,"demandeid"=>$demandeid),"default"); 
 
$basePath          = VIEW_BASE_PATH;
     
$jq                = $this->jQuery();
     
$buttonbar         = $this->Btnbar(array() , $this->jqueryHandler());
$buttonCreate      = $buttonbar->button("Générer la fiche","save")->setPriority("primary");
$buttonVerify      = $buttonbar->button("Vérifier la disponibilité","check");
$buttonCancel      = $buttonbar->button("Revenir sur la demande","chevron-left");
$buttonList        = $buttonbar->button("Retourner sur la liste des demandes","arrow-left");

$buttonbar->add($buttonList  , "listButton"); 
$buttonbar->add($buttonCancel, "cancelButton");
$buttonbar->add($buttonVerify, "verifyButton");
$buttonbar->add($buttonCreate, "createButton");

$buttonList->setAttributes(  array("type" => "submit", "title" => "Retourner sur la liste des demandes de vérifications"));	
$buttonCreate->setAttributes(array("type" => "submit", "title" => "Générer et imprimer la fiche de cette demande"));
$buttonVerify->setAttributes(array("type" => "submit", "class" => "btn btn-warning","title"=>"Procéder à la vérification de la disponibilité de cette demande"));
$buttonCancel->setAttributes(array("type" => "submit", "class" => "btn alert-danger","title"=>"Revenir sur la page récapitulative de cette demande"));
     
$buttonCreate->onClick("event.preventDefault();
                        var formSelector   = jQuery('#createFicheForm');
						var documentOutput = formSelector.find('input[type=\'radio\'][name=\'document_output\']:checked').eq(0);
						if( documentOutput.val()=='print') {
							var formData   = formSelector.serialize();
							SIRAH.request.post( formSelector, '".$formSubmit."',
							                   { dataType:'json',cache:false,data:formData,beforeSend:function(){},
												 success:function(data) {
													SIRAH.loading.off();
													if(!SIRAH.util.isEmpty(data.error)){
                            		                    SIRAH.error.raise(formSelector,data.error,'error');
                            		                    return data;
                            	                    } else if((undefined !== data.success) && (undefined !== data.documentid) && (undefined !== data.numero)){
                            		                    SIRAH.loading.off(false);
														var documentid     = data.documentid;
														var numero         = data.numero;
														var dialogTitle    = encodeURIComponent('Fiche de la demande numero '+numero);
														var linkViewDoc    = '".$linkUserdocuments."?documentid='+documentid+'&dialogTitle='+dialogTitle;
										 
														var documentDialog = jQuery('<div></div>').attr('id','documentDialog'); 
														documentDialog.dialog2({title:'Création d\'une fiche de demande...',content:linkViewDoc,autoOpen:false,modalClass:'pdfDialog',removeOnClose:true,closeOnEscape:true,closeOnOverlayClick:true,showCloseHandle:true,initialLoadText:'Chargement des données de la fiche de demande, patientez...' });         		            		
														documentDialog.dialog2('addButton','<i class=\'glyph-icon icon-chevron-left\'></i> Fermer', {primary:false,click :function(event){event.preventDefault();jQuery(this).dialog2('close');}});
														documentDialog.dialog2('addButton','<i class=\'glyph-icon icon-check\'> </i> Vérifier la disponibilité',{primary:true,click :function(event){event.preventDefault();jQuery(this).dialog2('close');verifyFunction();}});
														documentDialog.dialog2('open');
                            	                    }	else if(undefined !== data.reload) {
                            		                    var reloadurl     = (SIRAH.util.isEmpty(data.newurl) || (SIRAH.util.isUndefined(data.newurl))) ? url : data.newurl;
                                                        document.location.href  =  reloadurl ;
                                                    } else {
                            		                    SIRAH.error.raise(formSelector,'Aucune reponse valide na été retournée par le serveur','error');
                            		                    return data;
                            	                    }
												 },
												 error: function(data){SIRAH.loading.off();SIRAH.error.raise(formSelector , data ,'error');return data;}
							 });
						} else {
							 formSelector.submit(); 
						}");
$buttonCancel->onClick( "event.preventDefault();document.location.href='".$linkCancel."' ;");
$buttonVerify->onClick( "event.preventDefault();document.location.href='".$linkVerify."' ;");
        
$onLoad ="
jQuery('input[type=\'checkbox\'].custom-checkbox').uniform();
jQuery('input[type=\'radio\'].custom-radio').uniform();
var verifyFunction = function(){document.location.href='".$linkVerify."';};
tinymce.init({selector:'textarea',language:'fr_FR',plugins:[
    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
    'searchreplace wordcount visualblocks visualchars code fullscreen',
    'insertdatetime media nonbreaking save table contextmenu directionality',
    'template paste textcolor colorpicker textpattern imagetools codesample toc help emoticons hr'
  ],
  toolbar1: 'formatselect | bold italic  strikethrough  forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
  image_advtab:true});
  
setTimeout(function(){jQuery('#createButton').trigger('click');},10); 
";
$basePath      = VIEW_BASE_PATH;      
$jq->addOnLoad( $onLoad );
 
$jq->addJavascriptFile( $basePath."/js/bootstrap/bootstrap-filestyle.js");
$jq->addJavascriptFile( $basePath."/js/editors/tinymce2/tinymce.min.js");
$jq->addJavascriptFile( $basePath."/assets-minified/widgets/uniform/uniform.js");
$jq->addStylesheet(     $basePath."/assets-minified/widgets/uniform/uniform.css" );
$jq->addJavascriptFile( $basePath."/assets-minified/widgets/input-switch/inputswitch.js");
$jq->addStylesheet(     $basePath."/assets-minified/widgets/input-switch/inputswitch.css" );
?>
<?php $this->headStyle()->captureStart() ?>
input.hidden{visibility:hidden!important;display:none !important;font-size:0pt !important;height:0!important;line-height:0;}
<?php $this->headStyle()->captureEnd()   ?>
<form method="post" action="<?php echo $formSubmit;?>" id="createFicheForm" role="form" class="form-horizontal">
    <div class="panel panel-default">
		<div class="panel-heading"> <h4 class="panel-title"> <span class="glyphicon glyphicon-cog"></span> Options d'édition la fiche de demande </h4></div>
		<ul class="list-group">
			<li class="list-group-item">
				<div class="form-group">
					<label class="col-md-2  col-sm-2  col-xs-hidden control-label">  <b> Mode de lecture:</b> </label> 
					<div   class="col-md-10 col-sm-10 col-xs-12">
						<label class="radio-inline"><input class="custom-radio" type="radio" name="document_output" id="document_output-download" value="download" <?php if($params["document_output"]=="download") echo "checked"; ?> /> Télécharger </label>          
						<label class="radio-inline"><input class="custom-radio" type="radio" name="document_output" id="document_output-iframe"   value="iframe"   <?php if($params["document_output"]=="iframe"  ) echo "checked"; ?> /> Afficher </label>
						<label class="radio-inline"><input class="custom-radio" type="radio" name="document_output" id="document_output-print"    value="print"    <?php if($params["document_output"]=="print"   ) echo "checked"; ?> /> Imprimer </label>
						<label class="radio-inline"><input class="custom-radio" type="radio" name="document_output" id="document_output-save"     value="save"     <?php if($params["document_output"]=="save"    ) echo "checked"; ?> /> Repartir sur le dossier </label>
					</div>		   
				</div>	   
			</li> 
			<li class="list-group-item">
				<div class="form-group">
					<label class="col-md-2  col-sm-2  col-xs-hidden control-label">  <b>Afficher l'entête:</b> </label> 
					<div   class="col-md-10 col-sm-10 col-xs-12">
						<label class="radio-inline"><input class="custom-radio" type="radio" name="show_header" id="show_header-no"  value="0" <?php if($params["show_header"]==0) echo "checked"; ?> /> Non, ne pas afficher</label>          
						<label class="radio-inline"><input class="custom-radio" type="radio" name="show_header" id="show_header-yes" value="1" <?php if($params["show_header"]==1) echo "checked"; ?> /> Oui, Afficher</label> 
					</div>		   
				</div>	   
			</li>
		</ul>
		<div class="panel-body">
		  <textarea name="contenu" id="contenu" class="form-control textarea col-xs-1 releveContenuTextarea" rows="20" cols="175"> <?php echo htmlentities($content , ENT_QUOTES , "UTF-8" ) ; ?></textarea>
		</div>
	<?php 
		if(!$this->isAjax) {
			echo "<div class=\"panel-footer\"> ".$buttonbar." </div>";
		} else {
			echo $this->jQuery();
			echo $this->headStyle();
		}
    ?>
    </div>  
</form>