<?php


?>

<div id="sirah-toolbar" class="sirah-toolbar sirah-toolbar-colored">
      <div class="sirah-toolbar-content"> 
           <ul  class="nav nav-list inline">
               <li><a href="#"><i class="icon-edit icon-white"></i>Mettre à jour</a></li>
               <li><a href="#"><i class="icon-trash icon-white"></i>Supprimer</a></li>
               <li><a href="#"><i class="icon-cancel icon-white"></i>Annuler</a></li>
           </ul>                                   
     </div>
</div> 