<?php
     $rows = $this->rows;
?>
<table id="nbreCourriersParCategorieTable" class="table table-bordered table-hover">
	<thead>
			<tr>
				<th width="75%"> Catégories </th>                                         
				<th width="25%"> Total      </th>
			</tr>         
	</thead>          
	<tbody>
	<?php 
		$output      = "";
		$total       = 0;
		if( count(   $rows )) {
			foreach( $rows as $row ) {
					 $rowBg    = $this->cycle(array("#FFFFFF","#F5F5F5"))->next();
					 $linkList = $this->url(array("module"=>"courriers","controller"=>"letters","action"=>"list","catid"=> $row['catid']), "default");  								 
					 $output.="<tr style=\"background-color:".$rowBg."\">";
							$output.="<td> <a title=\"Accéder à tous les dossiers de cette catégorie\" href=\"".$linkList."\"> ".$row['categorie']." </a> </td>";                   	 	                             	 	            
							$output.="<td> <a title=\"Accéder à tous les dossiers de cette catégorie\" href=\"".$linkList."\"> ".$row['nombre']   ." </a> </td>";
					 $output.="</tr>";  
					 $total += $row['nombre'];                    	 	
			 } 
			 $output.="<tr>";
					$output.="<td> TOTAL :    </td>";
					$output.="<td> ".number_format($total, 0, ' ', ' ')." </td>";
			 $output.="</tr>";
		} else {
			 $output.="<tr>";
					$output.="<td style=\"text-align:center;\" colspan=\"2\"> AUCUNE DONNEE DE CE TYPE N'A PU ETRE TROUVEE </td>";
			 $output.="</tr>";
		} 
		echo $output;
	?>          
	</tbody>         
</table>