<?php 
$data              = $this->data;
$saveAndCreateLink = $this->url(array("module"=>"admin","controller" =>"registrephysique", "action" => "create","new_creation"=>1), "default" );
$formSubmit        = $this->url(array("module"=>"admin","controller" =>"registrephysique", "action" => "create"), "default" );
$backList          = $this->url(array("module"=>"admin","controller" =>"registrephysique", "action" => "list")  , "default" );
$basePath          = VIEW_BASE_PATH;
$domaines          = $this->domaines;
$localites         = $this->localites;
$situations        = array("Célibataire"=>"Célibataire","Marié(e)"=> "Marié(e)","Divorcé(e)"=> "Divorcé(e)", "Veuf(ve)" => "Veuf(ve)");
$statuts           = array("Selectionnez un statut",1=>"Créé",2=>"Modifié",3 =>"Racheté",4=>"Radié");
$me                = Sirah_Fabric::getUser();
$searchUrl         = $this->url(array("module"=>"admin","controller"=>"ajaxres","action"=>"searchrc"), "default" );
$checkNumeroUrl    = $this->url(array("module"=>"admin","controller"=>"ajaxres","action"=>"checkrcnum","type"=>"physique"), "default" );
$checkLibUrl       = $this->url(array("module"=>"admin","controller"=>"ajaxres","action"=>"checkrclib"), "default" );
?>
<?php $this->headStyle()->captureStart() ?>
.input-document{width:250px;display:inline-block;}
.form-horizontal .checkbox, .form-horizontal .checkbox-inline, .form-horizontal .control-label, .form-horizontal .radio, .form-horizontal .radio-inline {padding-top:0!important}
.grpChosen{width:100px !important;}
<?php $this->headStyle()->captureEnd()   ?>
<?php
$jq     = $this->jQuery();  
$onLoad = "
jQuery('#libelle').change(function(){	
	var formSelector = jQuery('#createRegistreForm');
	var numero       = formSelector.find('#numero').val();
	var libelle      = jQuery(this).val();
    if( numero.length < 12) {
	    SIRAH.dialog.alert('Saisir d\'abord le numéro de registre','Erreur de saisie');
        return;
    }
	if( SIRAH.util.isEmpty(libelle)) {
	    SIRAH.dialog.alert('Veuillez saisir le nom commercial','Erreur de saisie');
        return;
    }
	jQuery('#libRcSearching').html('Vérification du nom commercial...');
	setTimeout(function(){
	    SIRAH.request.get(formSelector,'".$checkLibUrl."',{data:{'libelle':libelle},beforeSend : function() {},	
			success:function( data ) {
				jQuery('#libRcSearching').html('').removeClass('parsley-required');
				jQuery('#libelle').removeClass('danger').removeClass('parsley-error');
				if( data.error !== undefined   ) {
					SIRAH.dialog.alert(data.error,'Erreur de saisie');
					jQuery('#libRcSearching').html(data.error).addClass('parsley-required');
					jQuery('#libelle').addClass('danger').addClass('parsley-error');
					jQuery('#libRcSearching').html(data.error);
					return data;
				}
				if( data.success !== undefined  ) {
					jQuery('#libRcSearching').html('');
					return data;
				}
			}
	    });
	},500);
});	
var updateFormByNum = function(numero){
	var formSelector = jQuery('#createRegistreForm');
	SIRAH.request.get(formSelector,'".$searchUrl."', {data:{'numero':numero},beforeSend : function(){},			   
		    success : function( data ) {
				if( data.success !== undefined ) {
				    if((data.success !== undefined) && (data.libelle !== undefined ) ) {
					   jQuery('#libelle').val(data.libelle);
				    }
				    if((data.success !== undefined) && (data.lastname !== undefined ) ) {
					   jQuery('#nom').val(data.lastname);
				    }
				    if((data.success !== undefined) && (data.firstname !== undefined ) ) {
					   jQuery('#prenom').val(data.firstname);
				    }
				    if((data.success !== undefined) && (data.description !== undefined ) ) {
					   jQuery('#description').val(data.description);
				    }
				    if((data.success !== undefined) && (data.telephone !== undefined ) ) {
					   jQuery('#telephone').val(data.telephone);
				    }
				    if((data.success !== undefined) && (data.adresse !== undefined ) ) {
					   jQuery('#adresse').val(data.adresse);
				    }
				    if((data.success !== undefined) && (data.lieu_naissance !== undefined ) ) {
					   jQuery('#lieunaissance').val(data.lieu_naissance);
				    }
				    if((data.success !== undefined) && (data.passport !== undefined ) ) {
					   jQuery('#passport').val(data.passport);
				    }
				    if((data.success !== undefined) && (data.localiteid !== undefined ) ) {
					   jQuery('#localiteid').val(data.localiteid);
					   jQuery('#localiteid').trigger('chosen:updated');
				    }
				    if((data.success !== undefined) && (data.date_enregistrement_day !== undefined ) ) {
					   jQuery('#date_day').val(data.date_enregistrement_day);
					   jQuery('#date_day').trigger('chosen:updated');
				    }
				    if((data.success !== undefined) && (data.date_enregistrement_month !== undefined ) ) {
					   jQuery('#date_month').val(data.date_enregistrement_month);
					   jQuery('#date_month').trigger('chosen:updated');
				    }
				    if((data.success !== undefined) && (data.date_enregistrement_year !== undefined ) ) {
					   jQuery('#date_year').val(data.date_enregistrement_year);
					   jQuery('#date_year').trigger('chosen:updated');
				    }
				    if((data.success !== undefined) && (data.date_naissance_year !== undefined ) && parseInt(data.date_naissance_year)) {
					   jQuery('#date_naissance_year').val(data.date_naissance_year);
					   jQuery('#date_naissance_year').trigger('chosen:updated');
				    }
				    if((data.success !== undefined) && (data.date_naissance_month !== undefined ) && parseInt(data.date_naissance_month)) {
					    jQuery('#date_naissance_month').val(data.date_naissance_month);
					    jQuery('#date_naissance_month').trigger('chosen:updated');
				    }
				    if((data.success !== undefined) && (data.date_naissance_day !== undefined ) && parseInt(data.date_naissance_day) ) {
					    jQuery('#date_naissance_day').val(data.date_naissance_day);
					    jQuery('#date_naissance_day').trigger('chosen:updated');
				    }
				}
		    }
    });
};
jQuery('#numero').change(function(){
    var numero = jQuery(this).val();
    var formSelector = jQuery('#createRegistreForm');
	jQuery('#numRcSearching').html('Vérification du numéro RCCM...');
	setTimeout(function(){	
		SIRAH.request.get(formSelector,'".$checkNumeroUrl."', { data:{'numero':numero}, beforeSend : function(){},
			success: function( data ) {
				jQuery('#numRcSearching').html('').removeClass('parsley-required').removeClass('parsley-required');
				jQuery('#numero').removeClass('danger').removeClass('parsley-error');
				jQuery('#numero').removeClass('success').removeClass('parsley-success');
				if( data.error !== undefined   ) {
					jQuery('#validnumrc').val('0');
					jQuery('#numRcSearching').html(data.error).addClass('parsley-required');
					jQuery('#numero').addClass('danger').addClass('parsley-error');
					jQuery('#numero').removeClass('success').removeClass('parsley-success');
					SIRAH.dialog.alert(data.error,'Numéro RCCM Invalide');
					return data;
				}
				if( data.success !== undefined ) {
					jQuery('#numRcSearching').html('').removeClass('parsley-required');
					jQuery('#numRcSearching').html('').addClass('parsley-success');
					jQuery('#numero').removeClass('danger').removeClass('parsley-error');
					jQuery('#numero').addClass('success').addClass('parsley-success');
					jQuery('#validnumrc').val('1');
					updateFormByNum(jQuery('#numero').val());
				}
			}
		});		
	}, 500);
});
jQuery('input:checkbox').bootstrapSwitch();
jQuery('input:checkbox').on('switchChange.bootstrapSwitch', function(event, state) {
	if((state == true) && (this.name =='find_documents')) {
		jQuery('#findDocumentsOptions').removeClass('hide');
		jQuery('.manualFindDocuments').addClass('hide'); 
	} 
	if((state == false) && (this.name =='find_documents')){
		jQuery('#findDocumentsOptions').addClass('hide');
		jQuery('.manualFindDocuments').removeClass('hide');
	}
});
jQuery('input:checkbox, input:radio').uniform();
jQuery('.chosen').chosen({allow_single_deselect:true,no_results_text: 'Aucun element ne correspond à ', width:'100%'});
jQuery('input[name=\'find_documents\']').click(function( event ){
	if( jQuery(this).is(':checked')) {
		jQuery('#findDocumentsOptions').removeClass('hide');
		jQuery('.manualFindDocuments').addClass('hide');
	} else {
		jQuery('#findDocumentsOptions').addClass('hide');
		jQuery('.manualFindDocuments').removeClass('hide');
	} 
});
jQuery('#docmini').filestyle({buttonText:'Rechercher un document',classButton:'btn btn-primary',classInput:'input-inline form-control input-document',classIcon:'glyph-icon icon-folder-open',icon: true});
jQuery('#docoriginal').filestyle({buttonText:'Rechercher un document',classButton:'btn btn-primary',classInput:'input-inline form-control input-document',classIcon:'glyph-icon icon-folder-open',icon: true});
jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});  
jQuery('#saveButton').click(function(e){
    e.preventDefault();      
    var  formSelector = jQuery('#createRegistreForm');
    var  libelle      = jQuery.trim(formSelector.find('#libelle').val());
    var  numero       = jQuery.trim(formSelector.find('#numero').val());
    var  localiteid   = parseInt(formSelector.find('#localiteid').val());
	var  isValidNumRC = parseInt(formSelector.find('#validnumrc').val());
    
	if(!isValidNumRC) {
		jQuery('#numRcSearching').html(data.error).addClass('parsley-required');
		jQuery('#numero').addClass('danger').addClass('parsley-error');
		SIRAH.dialog.alert('Veuillez saisir un numéro RCCM Valide','Erreur de saisie');
        return;
	}
    if( SIRAH.util.isEmpty( libelle )){
		SIRAH.dialog.alert('Entrez un nom commercial valide','Erreur de saisie');
        return;
    }
    if( SIRAH.util.isEmpty( localiteid )){
		SIRAH.dialog.alert('Veuillez selectionner une localité valide','Erreur de saisie');
        return;
    }      
    formSelector.submit();
});

jQuery('#saveAndCreateButton').click(function(e){
    e.preventDefault();      
    var formSelector = jQuery('#createRegistreForm');
    var libelle      = jQuery.trim(formSelector.find('#libelle').val());
    var numero       = jQuery.trim(formSelector.find('#numero').val());
    var localiteid   = parseInt(formSelector.find('#localiteid').val());
	var isValidNumRC = parseInt(formSelector.find('#validnumrc').val());
    
	if(!isValidNumRC) {
		jQuery('#numRcSearching').html(data.error).addClass('parsley-required');
		jQuery('#numero').addClass('danger').addClass('parsley-error');
		SIRAH.dialog.alert('Veuillez saisir un numéro RCCM Valide','Erreur de saisie');
        return;
	}
    if( SIRAH.util.isEmpty( libelle )){
		SIRAH.dialog.alert('Entrez un nom commercial valide','Erreur de saisie');
        return;
    }
    if( SIRAH.util.isEmpty( localiteid )){
		SIRAH.dialog.alert('Veuillez selectionner une localité valide','Erreur de saisie');
        return;
    }   
    formSelector.attr('action',\"".$saveAndCreateLink."\");	
    formSelector.submit();
});";  
  $jq->addOnLoad($onLoad);
  $jq->addJavascriptFile( $basePath."/js/bootstrap/bootstrap-filestyle.js");
  $jq->addJavascriptFile( $basePath."/assets-minified/widgets/uniform/uniform.js");
  $jq->addStylesheet(     $basePath."/assets-minified/widgets/uniform/uniform.css" );
  $jq->addJavascriptFile( $basePath."/assets-minified/widgets/input-switch/inputswitch.js");
  $jq->addStylesheet(     $basePath."/assets-minified/widgets/input-switch/inputswitch.css" );
?>
<div  class="content-box">    
    <h3 class="content-box-header content-box-header-alt bg-default">ETAPE 1 <small> Les informations du RCCM </small></h3>
    <form method="post"  id="createRegistreForm" class="form-horizontal mrg15T row" role="form" enctype="multipart/form-data">  
        <div class="form-group"> 
            <label class="col-sm-12 col-md-3 control-label" title="Le numéro RC doit contenir au moins 12 caractères"> Numéro RCCM* : </label>
            <div   class="col-sm-12 col-md-6"> <input style="text-transform:uppercase" maxlength="25" type="text" name="numero" id="numero" class="form-control" placeholder="Numéro RC du registre (Exemples:BFOUA2016A00001 ou BFOUA012022A1000001)" value="<?php echo $data["numero"]; ?>" /></div>        
            <div   class="col-sm-12 col-md-3" id="numRcSearching"> </div>
			<input type="hidden" name="validnumrc" id="validnumrc" value="1" />
	    </div>       
        <div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Nom commercial* : </label>
			<div   class="col-sm-12 col-md-6"> <input type="text" name="libelle" id="libelle" class="form-control" placeholder="Nom commercial" value="<?php echo $data["libelle"]; ?>" /></div>        
			<div   class="col-sm-12 col-md-3" id="libRcSearching"> </div>
	    </div>
		<div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Numéro IFU* : </label>
           <div   class="col-sm-12  col-md-9"> <input type="text" name="numifu" id="numifu" class="form-control" placeholder="Numéro IFU" value="<?php echo $data["numifu"]; ?>" /></div>        
	    </div>
		<div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Numéro CNSS: </label>
           <div   class="col-sm-12  col-md-9"> <input type="text" name="numcnss" id="numcnss" class="form-control" placeholder="Numéro CNSS" value="<?php echo $data["numcnss"]; ?>" /></div>        
	    </div>
        <?php if(!$me->isGREFFIERS()): ?>
        <div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Localité* : </label>
           <div   class="col-sm-12 col-md-9"> <?php echo $this->formSelect("localiteid", intval( $data["localiteid"]  ), array("class"=>"form-control chosen"), $localites); ?> </div>   
        </div>
        <?php else: ?> 
        <input type="hidden" name="localiteid"  id="localiteid" value="<?php echo intval($data['localiteid']); ?>" />
        <?php endif; ?>          
        <div class="form-group">    
            <label class="col-sm-12 col-md-3 control-label"> Date du RCCM*: </label>
            <div   class="col-sm-12 col-md-9">
				<div class = "input-group">
					<?php echo $this->formSelect("date_day"  , $data["date_day"]  , array("class" => "form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?> 
					<span class="input-group-btn" style="width:0px;"></span>
					<?php echo $this->formSelect('date_month', $data["date_month"], array("class" => "form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?>
					<span class="input-group-btn" style="width:0px;"></span>
					<?php echo $this->formSelect('date_year' , $data["date_year"] , array("class" => "form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1960, intval(date("Y")) ) );?>             
				</div>
			</div>
	    </div>
	    <div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Secteur d'activité*: </label>
           <div   class="col-sm-12 col-md-9"> <?php echo $this->formSelect("domaineid", intval( $data["domaineid"]), array("class" => "form-control chosen"), $domaines ); ?> </div>       
        </div>
        <div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Décrire l'activité : </label>
           <div   class="col-sm-12 col-md-9"> <input type="text" name="description" id="description" class="form-control" value="<?php echo $data["description"]; ?>" placeholder="Décrivez en quelques mots l'activité menée" /></div>       
        </div>
        <div class="form-group"> 
            <label class="col-sm-12 col-md-3 control-label"> Adresse*: </label>
            <div   class="col-sm-12 col-md-9"> <input type="text" name="adresse2"   id="adresse2"   class="form-control" value="<?php echo $data["adresse"]; ?>" placeholder="Adresse" /></div>       
        </div>	  
        <div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Téléphone de la société: </label>
           <div   class="col-sm-12 col-md-9"> <input type="text" name="telephone2" id="telephone2" class="form-control" value="<?php echo $data["telephone"]; ?>" placeholder="Numéro de téléphone" /></div>       
        </div>	  
        <h3 style="display:none;" class="content-box-header content-box-header-alt bg-default mrg10R mrg10L mrg10B">ETAPE 2 <small> Les informations du promoteur </small></h3>
        <div class="form-group"> 
            <label class="col-sm-12 col-md-3 control-label"> Nom & Prénom*: </label>
            <div   class="col-sm-12 col-md-9"> 
				<div class="input-group">
				  <input type="text" name="nom"    id="nom"    class="form-control" value="<?php echo $data["nom"]; ?>" placeholder="Nom de famille" />
				  <span class="input-group-btn" style="width:0px;"></span>
				  <input type="text" name="prenom" id="prenom" class="form-control" value="<?php echo $data["prenom"]; ?>" placeholder="Prénom" />      
				</div>
		    </div>  
	    </div>	  
        <div class="form-group"> 
            <label class="col-sm-12 col-md-3 control-label"> Adresse*: </label>
            <div   class="col-sm-12 col-md-9"> <input type="text" name="adresse" id="adresse" class="form-control" value="<?php echo $data["adresse"]; ?>" placeholder="Adresse" /></div>       
        </div>	  
        <div class="form-group"> 
            <label class="col-sm-12 col-md-3 control-label"> Numéro de téléphone: </label>
            <div   class="col-sm-12 col-md-9"> <input type="text" name="telephone" id="telephone" class="form-control" value="<?php echo $data["telephone"]; ?>" placeholder="Numéro de téléphone" /></div>       
        </div>	  
        <div class="form-group">    
            <label   class="col-sm-12 col-md-3 control-label"> Date & lieu de naissance*: </label>
			<div     class="col-sm-12 col-md-9">
			    <div class="input-group">
			       <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect("date_naissance_day", $data["date_naissance_day"]  , array("class" => "form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?></span>
				   <span class="input-group-btn" style="width:0px;"></span>
				   <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect('date_naissance_month', $data["date_naissance_month"], array("class" => "form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?> </span>
			       <span class="input-group-btn" style="width:0px;"></span>
				   <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect('date_naissance_year' , $data["date_naissance_year"] , array("class" => "form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1900, intval(date("Y")) ) );?></span>
				   <span class="input-group-btn" style="width:0px;"></span>
				   <input style="height:40px;" type="text" name="lieunaissance" id="lieunaissance" class="form-control" value="<?php echo $data["lieunaissance"]; ?>" placeholder="Lieu de naissance" />
			    </div>
			</div>    
        </div>
	    <div class="form-group"> 
            <label class="col-sm-12 col-md-3 control-label"> Sexe*: </label>
            <div   class="col-sm-12 col-md-3 radio radio-primary"> 
		        <label class="radio-inline pull-left"><input type="radio" name="sexe" id="sexe-m" value="M" <?php if($data["sexe"] == "M") echo "checked"; ?>> Homme </label>          
                <label class="radio-inline pull-left"><input type="radio" name="sexe" id="sexe-f" value="F" <?php if($data["sexe"] == "F") echo "checked"; ?>> Femme </label>
		    </div>        
        </div>
	    <div class="form-group">          
            <label class="col-sm-12 col-md-3 control-label"> Nationalité* : </label>
            <div   class="col-sm-12 col-md-9"> <?php echo $this->formSelect("country", $data['country'], array("class" => "form-control chosen"), array(0=>"Sélectionnez un pays")+$this->countries());?> </div>
        </div>
	    <div class="form-group"> 
            <label class="col-sm-12 col-md-3 control-label"> Situation matrimoniale*: </label>
            <div   class="col-sm-12 col-md-9"> <?php echo $this->formSelect("marital_status", $data["marital_status"], array("class" => "form-control"), $situations); ?> </div>        
        </div>
	    <div class="form-group"> 
            <label class="col-sm-12 col-md-3 control-label"> N° passport ou CNIB*: </label>
            <div   class="col-sm-12 col-md-9"> <input type="text" name="passport" id="passport" class="form-control" value="<?php echo $data["passport"]; ?>" placeholder="Le numéro d'identité (CNIB ou PASSPORT)" /></div>        
        </div>
        <div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Profession: </label>
           <div   class="col-sm-12 col-md-9"> <input type="text" name="fonction" id="fonction" class="form-control"  placeholder="La profession du gérant" /></div>        
        </div>	  
        <div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Adresse email: </label>
           <div   class="col-sm-12 col-md-9"> <input type="text" name="email" id="email" class="form-control" value="<?php echo $data["email"]; ?>" placeholder="Adresse email" /></div>       
        </div>
        <div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Indexation automatique: </label>
           <div   class="col-sm-12 col-md-9" style="height:32px;"> <input type="checkbox" data-on-color="primary" name="find_documents" class="input-switch" data-size="medium" data-on-text="Oui" data-off-text="Non" <?php echo (intval($data["find_documents"]) == 1) ? 'checked' : ''; ?> value="1"></div>
        </div>
	    <div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Contrôle de la qualité: </label>
           <div   class="col-sm-12 col-md-9" style="height:32px;"> <input type="checkbox" data-on-color="primary" name="check_documents" class="input-switch" data-size="medium" data-on-text="Oui" data-off-text="Non" <?php echo (intval($data["check_documents"]) == 1) ? 'checked' : ''; ?> value="1"></div>
        </div>
	    <div id="findDocumentsOptions" class="form-group <?php echo (intval($data["find_documents"]) == 0) ? 'hide' :''; ?> "> 
	        <label class="col-sm-12 col-md-3 control-label"> Dossier source*: </label>
		    <div   class="col-sm-12 col-md-9"> <input type="text" name="find_documents_src" id="find_documents_src" class="form-control" placeholder="Dossier source de stockage des documents" value="<?php echo $data["find_documents_src"]; ?>" /></div> 
	    </div>
	    <div class="form-group manualFindDocuments <?php echo (intval($data["find_documents"]) == 1) ? 'hide' :''; ?> "> 
           <label class="col-sm-12 col-md-3 control-label"> Le formulaire * : </label>
           <div   class="col-sm-12 col-md-9"> <input type="file" name="docmini" id="docmini"    /></div>        
        </div>
        <div class="form-group manualFindDocuments <?php echo (intval($data["find_documents"]) == 1) ? 'hide' :''; ?>"> 
           <label class="col-sm-12 col-md-3 control-label"> Le fond de dossier* : </label>
           <div   class="col-sm-12 col-md-9"> <input type="file" name="docoriginal"  id="docoriginal"    /></div>        
        </div>	  
    </form>
<?php 
    $buttonsbar        = $this->Btnbar(array("class" => "button-pane") , $this->jqueryHandler());
    $toolSave          = $buttonsbar->button("Enregistrer","save")->setPriority("primary");
	$toolSaveAndCreate = $buttonsbar->button("Enregistrer & Nouveau","plus")->setPriority("primary");
    $toolCancel        = $buttonsbar->button("Annuler & revenir sur la liste","chevron-left");
     
    $toolSave->setAttributes(array("type" => "submit", "class" => "btn btn-success"));
    $toolCancel->setAttributes(array("type" => "submit"));
    
	$buttonsbar->add($toolCancel        , "cancelCreationButton");
    $buttonsbar->add($toolSave          , "saveButton");
	$buttonsbar->add($toolSaveAndCreate , "saveAndCreateButton");
       
    if( !$this->isAjax )
        echo $buttonsbar;
?>
</div>

<?php     
    if( $this->isAjax) {
   	   echo $this->jQuery();
    }  
?>