<?php 
$registres         = $this->registres;
$filters           = $this->filters;
$paginator         = $this->paginator;
$localites         = $this->localites;
$domaines          = $this->domaines;
$users             = $this->users;
$types             = $this->types;
$statuts           = $this->statuts;
$me                = Sirah_Fabric::getUser();

$basePath          = VIEW_BASE_PATH;
$jq                = $this->jQuery();

$linkSearch        = $this->url(array("module" => "admin","controller" => "registrephysique", "action" => "list")  , "default");
$linkCreate        = $this->url(array("module" => "admin","controller" => "registrephysique", "action" => "create"), "default");
$linkEdit          = $this->url(array("module" => "admin","controller" => "registrephysique", "action" => "edit")  , "default");
$linkDelete        = $this->url(array("module" => "admin","controller" => "registrephysique", "action" => "delete"));
$linkExport        = $this->url(array("module" => "admin","controller" => "registrephysique", "action" => "export"));
$linkImport        = $this->url(array("module" => "admin","controller" => "registrephysique", "action" => "import"));
$linkIndexation    = $this->url(array("module" => "admin","controller" => "registrephysique", "action"=> "updatedocs","category" => 7),"default");
$linkIndexationAll = $this->url(array("module" => "admin","controller" => "registrephysique", "action"=> "updatealldocs","category" => 7),"default");
$jq->addOnload("
jQuery('.chosen').chosen({allow_single_deselect:true,no_results_text: 'Aucun element ne correspond à ', width:'100%'});
jQuery('.resetPage').click(function(event){event.preventDefault();document.location.href = '".$linkSearch."'; });
jQuery('.viewInfos').css('cursor','pointer');
jQuery('.viewInfos').click(function(event){event.preventDefault();document.location.href = jQuery(this).attr('href');});		
jQuery('.resetPage').click(function(){event.preventDefault();document.location.href='".$linkSearch."'; });
jQuery('#advancedSearchBtn').click(function(event){event.preventDefault(); jQuery('.advancedSearchForm').eq(0).toggle();});
jQuery('.resetSearch').click(function(event){
	   event.preventDefault();
		if( jQuery(this).hasClass('disabled') ) {
		    return;
		}
		var formSelector    = jQuery('#globalFormSearch') ;
		var searchData      = {};			
        var maincontent	    = jQuery('#maincontent');				
		SIRAH.loading.on(maincontent, 'Chargement des données...' );
		SIRAH.request.post(formSelector, '".$linkSearch."' , 
		                   {  dataType   :'html' ,
		                      async      : true,
		                      data       : {},
		                      beforeSend : function() { },
		                      error      : function(data){maincontent.html(data);SIRAH.loading.off(false);},
	                          success    : function(data){maincontent.html(data);SIRAH.loading.off(false);},
		                      update     : function(data){maincontent.html(data);SIRAH.loading.off(false);}		
		                  });				
});	
jQuery('#searchRegistres').click(function(event){
		event.preventDefault();
		var formSelector               = jQuery('.advancedSearchForm').eq(0) ;
		var searchData                 = {};	
        searchData.searchQ             = jQuery.trim(jQuery('#globalFormSearch').find('#searchQ').val());		
		searchData.page                = parseInt(formSelector.find('#page').val());
		searchData.maxitems            = parseInt(formSelector.find('#maxitems').val());
        searchData.numero              = jQuery.trim(formSelector.find('#numero').val());
        searchData.libelle             = jQuery.trim(formSelector.find('#libelle').val());	
        searchData.name                = jQuery.trim(formSelector.find('#name').val());	
        searchData.passport            = jQuery.trim(formSelector.find('#passport').val());			
		searchData.creatorid           = parseInt(formSelector.find('#creatorid').val());
		searchData.localiteid          = parseInt(formSelector.find('#localiteid').val());
		searchData.domaineid           = parseInt(formSelector.find('#domaineid').val());
		searchData.statut              = parseInt(formSelector.find('#statut').val());
		searchData.annee               = parseInt(formSelector.find('#annee').val());
		searchData.date_year           = parseInt(formSelector.find('#date_year').val());
		searchData.date_month          = parseInt(formSelector.find('#date_month').val());
		searchData.date_day            = parseInt(formSelector.find('#date_day').val());
		searchData.periode_start_year  = parseInt(formSelector.find('#periode_start_year').val());
		searchData.periode_end_year    = parseInt(formSelector.find('#periode_end_year').val());
		searchData.periode_start_month = parseInt(formSelector.find('#periode_start_month').val());
		searchData.periode_end_month   = parseInt(formSelector.find('#periode_end_month').val());
		searchData.periode_start_day   = parseInt(formSelector.find('#periode_start_day').val());
		searchData.periode_end_day     = parseInt(formSelector.find('#periode_end_day').val());		
        var maincontent	               = jQuery('#maincontent');	
		/*SIRAH.loading.on( maincontent , 'Chargement des données...' );*/
		jQuery('#registresListWrapper').loadingOn();
		formSelector.attr('action', '".$linkSearch."');
		SIRAH.request.post(formSelector, '".$linkSearch."' , 
		                   {  dataType   :'html' ,
		                      async      : true,
		                      data       : searchData,
		                      beforeSend : function() { },
		                      error      : function(data){maincontent.html(data);SIRAH.loading.off(false);jQuery('#registresListWrapper').loadingOff();},
	                          success    : function(data){maincontent.html(data);SIRAH.loading.off(false);jQuery('#registresListWrapper').loadingOff();},
		                      update     : function(data){maincontent.html(data);SIRAH.loading.off(false);jQuery('#registresListWrapper').loadingOff();}		
		                  });
});
jQuery('#simpleSearch').click(function( event ){
		event.preventDefault();
		if( jQuery(this).hasClass('disabled') ) {
		    return;
		}
		var formSelector    = jQuery('#globalFormSearch') ;
		var searchData      = {};
		var pageNum         = parseInt(formSelector.find('#page').val());
		
		searchData.page     = pageNum;
		searchData.maxitems = parseInt(formSelector.find('#maxitems').val());	
		 
		searchData.searchQ  = jQuery.trim(jQuery('#globalFormSearch').find('#searchQ').val());
        var maincontent     = jQuery('#maincontent');		
		/*SIRAH.loading.on(maincontent, 'Chargement des données...' );*/
		jQuery('#maincontent').loadingOn();
		SIRAH.request.post(formSelector, '".$linkSearch."' , 
		                   {  dataType   :'html' ,
		                      async      : true,
		                      data       : searchData,
		                      beforeSend : function() { },
		                      error      : function(data){maincontent.html(data);jQuery('#maincontent').loadingOff();},
	                          success    : function(data){maincontent.html(data);jQuery('#maincontent').loadingOff();},
		                      update     : function(data){maincontent.html(data);jQuery('#maincontent').loadingOff();}		
		                  });						
});
jQuery('.sirahPaginationBtn').click(function(event){
		event.preventDefault();
		if(jQuery(this).is('.active') || jQuery(this).is('.disabled') || jQuery(this).is('.currentBtn')) {
		     return false;
		}
		var formSelector        = jQuery('.advancedSearchForm').eq(0) ;
		var pageNum             = parseInt(jQuery(this).attr('id').replace('paginationBtnPage-' , ''));
		var pageMaxitems        = formSelector.find('#maxitems').val();
	    if(jQuery(this).is('.nextPage')) {
		      var currentBtnNum = parseInt(jQuery('.currentBtn').first().attr('id').replace('paginationBtnPage-' , ''));
		      pageNum           = parseInt( currentBtnNum +1);
		}
		if( jQuery(this).is('.prevPage')) {
		    var currentBtnNum    = parseInt(jQuery('.currentBtn').first().attr('id').replace('paginationBtnPage-' , ''));
		    pageNum              = parseInt( currentBtnNum - 1);
		}
		var paginationData                 = {};
		paginationData.searchQ             = jQuery.trim(jQuery('#globalFormSearch').find('#searchQ').val());
		paginationData.page                = pageNum;
		paginationData.maxitems            = parseInt(formSelector.find('#maxitems').val());	
        paginationData.numero              = jQuery.trim(formSelector.find('#numero').val());
        paginationData.libelle             = jQuery.trim(formSelector.find('#libelle').val());
        paginationData.name                = jQuery.trim(formSelector.find('#name').val());	
        paginationData.passport            = jQuery.trim(formSelector.find('#passport').val());			
		paginationData.creatorid           = parseInt(formSelector.find('#creatorid').val());
		paginationData.localiteid          = parseInt(formSelector.find('#localiteid').val());
		paginationData.domaineid           = parseInt(formSelector.find('#domaineid').val());
		paginationData.statut              = parseInt(formSelector.find('#statut').val());
		paginationData.annee               = parseInt(formSelector.find('#annee').val());
		paginationData.date_year           = parseInt(formSelector.find('#date_year').val());
		paginationData.date_month          = parseInt(formSelector.find('#date_month').val());
		paginationData.date_day            = parseInt(formSelector.find('#date_day').val());
		paginationData.periode_start_year  = parseInt(formSelector.find('#periode_start_year').val());
		paginationData.periode_end_year    = parseInt(formSelector.find('#periode_end_year').val());
		paginationData.periode_start_month = parseInt(formSelector.find('#periode_start_month').val());
		paginationData.periode_end_month   = parseInt(formSelector.find('#periode_end_month').val());
		paginationData.periode_start_day   = parseInt(formSelector.find('#periode_start_day').val());
		paginationData.periode_end_day     = parseInt(formSelector.find('#periode_end_day').val());			
		 	
		var maincontent                    = jQuery('#maincontent');			
		/*SIRAH.loading.on(maincontent, 'Chargement des données...' );*/
		jQuery('#registresListWrapper').loadingOn();
		SIRAH.request.post(formSelector, '".$linkSearch."' , 
		                   {  dataType   :'html' ,
		                      async      : true,
		                      data       : paginationData,
		                      beforeSend : function() { },
		                      error      : function(data){maincontent.html(data);SIRAH.loading.off(false);jQuery('#registresListWrapper').loadingOff();},
	                          success    : function(data){maincontent.html(data);SIRAH.loading.off(false);jQuery('#registresListWrapper').loadingOff();},
		                      update     : function(data){maincontent.html(data);SIRAH.loading.off(false);jQuery('#registresListWrapper').loadingOff();}		
		                  });		
	});
jQuery('input:checkbox').uniform({checkboxClass:'checkbox-primary'});
var getCheckedRegistresId = function() {
		var checkedItems  = jQuery('#registresListTable').find('input[type=\'checkbox\'][name!=\'checkall\']:checked');
        var checkedIds    = []; 
		if(checkedItems) {
		   checkedItems.each(function() {
             	var registreid   = parseInt(jQuery(this).attr('id').replace('registreids',''));
             	checkedIds.push(registreid);
           });
		}
		return checkedIds;
  };
jQuery('#registresListTable').find('input[type=\'checkbox\']').click(function(e){
		 var checkedItems  = jQuery('#registresListTable').find('input[type=\'checkbox\'][name!=\'checkall\']:checked');
		 if(jQuery(this).attr('id') == 'checkAll') {
		    if(!jQuery(this).is(':checked')) {
		       checknone(jQuery('#registresListTable'));
		       if(checkedItems) {
		           disableButtons(['editButton','exportButton','deleteButton','updatealldocsButton']);
		       }
		    } else {
		      checkall(jQuery('#registresListTable'));
		      enableButtons(['editButton','exportButton','deleteButton','updatealldocsButton']);
		    }
		 } else {
		  if(jQuery(this).is(':checked')) {
		     enableButtons(['editButton','actionButton','exportButton','deleteButton','updatealldocsButton']);
		  } else {
		      if( SIRAH.util.isEmpty(checkedItems)) {
		          disableButtons(['editButton','deleteButton','exportButton','updatealldocsButton']);
		       }
		  }
		}
   });");
$toolbar     = $this->supinaToolsbar(array(), $this->jqueryHandler());
$toolCreate  = $toolbar->tool("Nouveau"   , "plus");
$toolEdit    = $toolbar->tool("Modifier"  , "edit");
$toolDelete  = $toolbar->tool("Supprimer" , "trash-o");
$toolExport  = $toolbar->tool("Exporter"  , "download");
$toolImport  = $toolbar->tool("Importer"  , "upload");
$toolIndexer = $toolbar->tool("Re-Indexer", "refresh");

if($me->isAllowed("registrephysique", "create"))
   $toolbar->add( $toolCreate, "createPhysiqueButton");
if($me->isAllowed("registrephysique", "export"))
   $toolbar->add( $toolExport, "exportButton");
if($me->isAllowed("registrephysique", "import"))
   $toolbar->add( $toolImport, "importButton");
if($me->isAllowed("registrephysique", "edit"))
   $toolbar->add( $toolEdit    , "editButton");
if($me->isAllowed("registrephysique", "updatealldocs"))
   $toolbar->add( $toolIndexer , "updatealldocsButton");
if($me->isAllowed("registrephysique", "delete"))
   $toolbar->add( $toolDelete  , "deleteButton");

$toolCreate->onClick(sprintf("event.preventDefault(); document.location.href='%s';" , $linkCreate ));
$toolExport->onClick(sprintf("event.preventDefault(); document.location.href='%s';" , $linkExport ));

$toolEdit->disable();
$toolEdit->onClick("event.preventDefault();
		            var isDisabled   = jQuery(this).is('.disabled') || jQuery(this).is('.btn-disabled');
		            var checkedItem  = jQuery('#registresListTable').find('input[type=\'checkbox\'][name=\'registreids[]\']:checked').eq(0);
		            if( isDisabled || !checkedItem) {
		                 SIRAH.dialog.alert('Vous devrez selectionner une ligne avant d\'effectuer cette opération','Selectionnez une ligne');
		                 return;
                    }
		            var registreid         = parseInt(checkedItem.attr('id').replace('registreids',''));
		            document.location.href = '".$linkEdit."/registreid/'+registreid;");
$toolIndexer->disable();
$toolIndexer->onClick("event.preventDefault();
					   var isDisabled       = jQuery(this).is('.disabled') || jQuery(this).is('.btn-disabled');
		               var checkedRegistres = getCheckedRegistresId();
					   var localizedButton  = jQuery.fn.dialog2.localization.localizedButton;
		               if( isDisabled || SIRAH.util.isEmpty( checkedRegistres )) {
		                   SIRAH.dialog.alert('Vous devrez selectionner au moins une ligne avant d\'effectuer cette opération','Selectionnez une ligne');
		                   return;
                       }
		               var dialogIndexation = jQuery('<div> Voulez-vous vraiment re-indexer les registres selectionnés ? Les documents rattachés à ces registres vont être remplacés </div>').attr('id','dialogIndexation');             		             		   
					   dialogIndexation.dialog2({title :'Attention, confirmer cette action !!',autoOpen:false,removeOnClose:true,closeOnEscape:false,closeOnOverlayClick: true,showCloseHandle:true,initialLoadText: 'Chargement...' });        		
             		   dialogIndexation.dialog2('addButton','<i class=\'glyph-icon icon-check\'> </i> Oui',{primary:true,click : 
             		                            function(){
												jQuery('.modal-footer:first').find('button.btn').remove();
												jQuery('#dialogIndexation').dialog2('addButton','Annuler',{click:function(){jQuery('#dialogIndexation').dialog2('close'); }});
												jQuery('.modal-header:first').find('h3').first().html('Re-Indexation en cours...');
												var progressBarContainer = jQuery('<div/>').addClass('progressbar').addClass('progress-striped').attr('data-value','0').attr('id','progressbar');	
												var progressBarValue     = jQuery('<div/>').addClass('progressbar-value').addClass('bg-red').addClass('tooltip-button').attr('data-original-title','Initialisation...').attr('id','progressBarValue')
												                           .append(jQuery('<div/>').addClass('progress-label').html('0%').attr('id', 'progressLabel'))
																		   .append(jQuery('<div/>').addClass('progress-overlay').attr('id','progressBarOverlay'));	
												progressBarContainer.append(progressBarValue);
												jQuery('#dialogIndexation').html(progressBarContainer);
												var progressBarTxt       = jQuery('<div/>').addClass('row').css('color','black').css('font-weight','bold').attr('id','progressBarTxt');
												jQuery('#dialogIndexation').append(progressBarTxt);
												var nbre                 = 0;
												var totalSuccess         = 0;
												var totalRegistres       = checkedRegistres.length;
												jQuery.each(checkedRegistres, function(key,registreid) {			    
													    var numeroRegistre  = jQuery('#numero-'+registreid).val();														
														setTimeout(function(){
															var xhr = jQuery.ajax({url:'".$linkIndexation."',async:true,dataType:'json',type:'GET',data:{'registreid':registreid}});
															xhr.done(function( data ){
																nbre++;
																if( data.error !== undefined ) {
																	SIRAH.error.raise(jQuery('#dialogIndexation'),data.error, 'error');																						
																} else if( data.success !== undefined ) {
																	totalSuccess++;
																}
																var percent           = nbre*(100/totalRegistres);
																var percentTxt        = percent+'%';
														        progressBarContainer.attr('data-value', percent );
																progressBarValue.css('width', percentTxt);
														        progressBarValue.attr('data-original-title','Indexation du registre n° '+numeroRegistre+'...');
														        jQuery('#progressLabel').html(percentTxt);
																progressBarTxt.html('(Copie du registre n° '+numeroRegistre+' en cours...)');																												
																
																if( nbre == totalRegistres ) {
																	progressBarValue.removeClass('bg-red').addClass('bg-green');
															        SIRAH.error.raise(jQuery('#dialogIndexation'),'L\'opération d\'indexation des documents s\'est effectuée avec succès, au total,'+totalSuccess+' ont été indexés', 'success');
															        setTimeout(function(){jQuery('#dialogIndexation').dialog2('close');return false;},4500);											        
														        }
															});	
															jQuery('.modal-footer:first').find('button.btn').first().click(function(event){ event.preventDefault();xhr.abort();});															
														}, 500);														
												});														   
                                                           }}); 
             		      dialogIndexation.dialog2('addButton','<i class=\'glyph-icon icon-ban\'></i>Annuler', {primary: false,click : function(){jQuery(this).dialog2('close');}});              		
             		      dialogIndexation.dialog2('open');");				
$toolDelete->disable();
$toolDelete->onClick(" event.preventDefault();
		               var isDisabled       = jQuery(this).is('.disabled') || jQuery(this).is('.btn-disabled');
		               var checkedRegistres = getCheckedRegistresId();
		               if( isDisabled || SIRAH.util.isEmpty( checkedRegistres )) {
		                   SIRAH.dialog.alert('Vous devrez selectionner au moins une ligne avant d\'effectuer cette opération','Selectionnez une ligne');
		                   return;
                       }
		               var dialogDelete = jQuery('<div> Voulez-vous vraiment supprimer les registres selectionnés ? Ces registres seront définitivement supprimés du système </div>').attr('id','dialogDelete');             		 
             		   dialogDelete.dialog2({title:'Attention, confirmer cette action !!',autoOpen:false,removeOnClose:true,closeOnEscape:false,closeOnOverlayClick:true,showCloseHandle:true,initialLoadText: 'Chargement...' });        		
             		   dialogDelete.dialog2('addButton','<i class=\'glyph-icon icon-check\'> </i> Oui',{primary:true,click : 
             		                            function(){
													         jQuery('#dialogDelete').loadingOn();
															 setTimeout(function(){
             		                                            jQuery.ajax({
             		                                             url      :'".$linkDelete."',
             		                                             async    : false,
			                                                     dataType :'json',
             		                                             data     : {'registreids[]': checkedRegistres},
             		                                             type     : 'GET' ,
             		                                             success  : function(data) {
																	jQuery('#dialogDelete').loadingOff();
             		                                                if(data.error !== undefined) {
             		                                                   SIRAH.error.raise(jQuery('#dialogDelete') , data.error);
             		                                                   return;
             		                                                } else if(data.success !== undefined) {
             		                                                   var checkedRegistres = getCheckedRegistresId();  	            		
             		                                                  SIRAH.error.raise(jQuery('#dialogDelete'), data.success , 'success');
             		                                                setTimeout(function(){
             		             		                              jQuery.each(checkedRegistres, function(key , registreid) {
             		                                                          jQuery('#registreRowId-'+registreid).remove();
             		                                                    });
             		                                                   jQuery('#dialogDelete').dialog2('close');
             		                                                  },2500);
             		                                               }
             		                                             }
             		                                            });
                                                             }, 1000);															   
                                                           }}); 
             		      dialogDelete.dialog2('addButton','<i class=\'glyph-icon icon-ban\'></i>Annuler', {primary: false,click : function(){jQuery(this).dialog2('close');}});              		
             		      dialogDelete.dialog2('open'); ");
$toolImport->onClick("
                   event.preventDefault();
                   var dialogUploadFile   = jQuery('<div></div>').attr('id','dialogUploadFile');             		 
                   dialogUploadFile.dialog2({title:'Importer un fichier Excel',content:'".$linkImport."',autoOpen: false,modalClass:'modal-wide',
             		                         removeOnClose: true,closeOnEscape:true,closeOnOverlayClick:false,showCloseHandle:true,initialLoadText: 'Chargement de la page, patientez...' });
                   dialogUploadFile.dialog2('addButton','<span class=\'glyph-icon icon-upload\'></span> Importer votre fichier Excel',{primary:true,click:function(){alert('Veuillez fournir un document valide');}}); 
                   dialogUploadFile.dialog2('addButton','Annuler' ,{primary: false,click : function(){jQuery(this).dialog2('close');}});        		            		
                   dialogUploadFile.dialog2('open');
");
$this->toolsbar = $toolbar;

$pagination     = $this->pagination(array() , "Elastic" , "#", array(), array("class" => "panel-footer paginationControl", "style" => "text-align:center;")); 

?>
<?php $this->headStyle()->captureStart() ?>
 .form-row,.row {-webkit-box-sizing: border-box;-moz-box-sizing: border-box;box-sizing: border-box;margin-right:-25px;margin-left: -25px;}
 p{margin-bottom:10px !important;}
 td .list-group-item {padding:10px 0px !important;}
 td .row{margin-left:0 !important;margin-right:0 !important;}
 .col-md-2,.col-sm-2,.col-sm-10,.col-md-10{padding-right:5px !important;padding-left:5px !important;}
<?php $this->headStyle()->captureEnd() ?>

<div  id="registresListWrapper" class="row">
     <div  class="panel panel-default listPanel">
	    <div  class="panel-heading bg-blue-alt">
		   <form  class="form-horizontal" id="globalFormSearch" method="post" action="<?php echo $linkSearch; ?>" >
		    <div class="input-group">
		     <input value="<?php echo $filters['searchQ']; ?>" id="searchQ" name="searchQ"  type="text" class="form-control" placeholder="Recherchez un registre, saisir le numéro RC ou le nom commercial...">
		     <span class="input-group-btn ">
               <button id="simpleSearch" class="btn btn-primary simpleSearch" type="button"><span class="glyph-icon icon-search"></span> Recherchez </button>
               <button id="advancedSearchBtn" class="btn btn-default advancedSearchBtn" type="button"> <span class="glyph-icon icon-chevron-down"></span> Recherche avancée</button>
			   <button class="btn btn-danger resetSearch" type="button"><span class="glyph-icon icon-remove"></span> Effacer </button>
			</span>
		   </div>
             <input type="hidden" name="page"      id="page"      value="<?php echo $this->pageNum;    ?>" /> 
             <input type="hidden" name="maxitems"  id="maxitems"  value="<?php echo $this->pageSize;   ?>" />			 
		  </form>
    	</div>	
		<form id="registresListSearchForm"  method="post" role="form" class="form-horizontal advancedSearchForm" action="<?php echo $linkSearch; ?>" style="display:none;">
		   <ul class="list-group">
		      <li class="list-group-item">
                 <div  class="row">
				    <label class="col-sm-2 control-label">  <b> Numéro RC:</b> </label> 
                    <div class="col-sm-3"><input type="text" name="numero" id="numero" value="<?php echo $filters['numero']; ?>" class="form-control" placeholder="Saisir un numéro RC"      /></div>
					<label class="col-sm-3 control-label">  <b> Nom Commercial:</b> </label> 
                    <div class="col-sm-3"><input type="text" name="numero" id="numero" value="<?php echo $filters['libelle'];?>" class="form-control" placeholder="Saisir un nom commercial" /></div>
                 </div>
             </li>
             <li class="list-group-item">
                 <div  class="row">
				    <label class="col-sm-2 control-label">  <b> Nom du promoteur:</b> </label> 
                    <div class="col-sm-3"><input type="text" name="name" id="name" value="<?php echo $filters['name']; ?>" class="form-control" placeholder="Saisir le nom de l'exploitant"      /></div>
					<label class="col-sm-3 control-label">  <b> CNIB/Passport:</b> </label> 
                    <div class="col-sm-3"><input type="text" name="passport" id="passport" value="<?php echo $filters['passport'];?>" class="form-control" placeholder="Rechercher un numéro passport ou CNIB" /></div>
                 </div>
             </li>
             		     
             <li class="list-group-item"> 
			   <div class="row">
			       <label class="col-sm-2 control-label">  <b> Statut:</b> </label> 
				   <div   class="col-sm-3"><?php echo $this->formSelect("statut", $filters["statut"]  , array("class" => "form-control"), $statuts);?> </div> 
			       <label class="col-sm-3 control-label">  <b> Année de création:</b> </label>
			       <div class="col-md-3"><?php echo $this->formSelect("annee" , $filters["annee"] , array("class" => "form-control chosen"),array("0000"=> "Année")+createYearsArray(DEFAULT_START_YEAR, (date("Y")+1) ));?></div>  
			   </div> 			   
			 </li>
			<?php if( $me->isAdmin()): ?>
             <li class="list-group-item"> 
			   <div class="row">
			       <label class="col-sm-2 control-label">  <b> Localité:</b> </label> 
				   <div   class="col-sm-3"><?php echo $this->formSelect("localiteid", intval($filters["localiteid"]),array("class" => "form-control chosen"), $localites); ?> </div> 
                   <label class="col-sm-3 control-label">  <b> Domaine d'activités:</b> </label> 
				   <div   class="col-sm-3"><?php echo $this->formSelect("domaineid" , intval($filters["domaineid"]) ,array("class" => "form-control chosen"), $domaines); ?> </div> 
			   </div> 			   
			 </li>	
            <?php else:  ?>	
                <input type="hidden" name="localiteid"  id="localiteid"  value="<?php echo intval($filters["localiteid"]);?>" /> 
                <input type="hidden" name="domaineid"   id="domaineid"   value="<?php echo intval($filters["domaineid"]);?>" /> 				
            <?php endif; ?>			
			 <li class="list-group-item"> 
			    <div class="form-group"> 
                  <label class="col-sm-2 control-label"> Date de création: </label>
                  <div class="col-md-3"><?php echo $this->formSelect("date_day"  , $filters["date_day"]  , array("class" => "form-control chosen"),array("00"  =>"Jour")+createDatesArray());?></div>
                  <div class="col-md-3"><?php echo $this->formSelect("date_month", $filters["date_month"], array("class" => "form-control chosen"),array("00"  =>"Mois")+$this->months()); ?></div>
                  <div class="col-md-3"><?php echo $this->formSelect("date_year" , $filters["date_year"] , array("class" => "form-control chosen"),array("0000"=> "Année")+createYearsArray(DEFAULT_START_YEAR, (date("Y")+1) ));?></div>                 
               </div>
			 </li>
			 <!--
			 <li class="list-group-item">
                 <div  class="row">
				      <label class="col-sm-3 control-label">  <b> Période initiale:</b> </label> 
                      <div class="col-sm-3"><?php echo $this->formSelect("periode_start_day"  , $filters["periode_start_day"]  , array("class" => "form-control"),array("00"  =>"Jour")+createDatesArray());?></div>
                      <div class="col-sm-3"><?php echo $this->formSelect("periode_start_month", $filters["periode_start_month"], array("class" => "form-control"),array("00"  =>"Mois")+$this->months()); ?></div>
                      <div class="col-sm-3"><?php echo $this->formSelect("periode_start_year" , $filters["periode_start_year"] , array("class" => "form-control"),array("0000"=> "Année")+createYearsArray(DEFAULT_START_YEAR, (date("Y")+1) ));?></div>
                 </div>
              </li>
              <li class="list-group-item">
                 <div  class="row">
				      <label class="col-sm-3 control-label">  <b> Période finale:</b> </label> 
                      <div class="col-sm-3"><?php echo $this->formSelect("periode_end_day"  , $filters["periode_end_day"]  , array("class" => "form-control"),array("00"  =>"Jour")+createDatesArray());?></div>
                      <div class="col-sm-3"><?php echo $this->formSelect("periode_end_month", $filters["periode_end_month"], array("class" => "form-control"),array("00"  =>"Mois")+$this->months()); ?></div>
                      <div class="col-sm-3"><?php echo $this->formSelect("periode_end_year" , $filters["periode_end_year"] , array("class" => "form-control"),array("0000"=> "Année")+createYearsArray(DEFAULT_START_YEAR, (date("Y")+1) ));?></div>
                 </div>
              </li> -->
			  <li class="list-group-item">
                 <div  class="row">
				    <?php if( $me->isAdmin()): ?>
				      <label class="col-sm-2 control-label">  <b> Opérateur de saisie:</b> </label>
					  <div class="col-sm-3"><?php echo $this->formSelect("creatorid", $filters["creatorid"]  , array("class" => "form-control"), $users);?></div>
				    <?php endif; ?>
					
					<label class="col-sm-3 control-label">  <b> Nbre d'élements par page:</b> </label> 
                    <div class="col-sm-3"> <?php echo $this->formSelect("maxitems", $this->maxitems , array("class" => "form-control") , array( "10"   => 10, "25" => 25, "50" => 50 , "100" => 100, "500" => 500, 
                                		                                                                                 "1000" => 1000, "2000" => 2000 , "5000" => 5000, "100000000" => "Tout")); ?> </div>
                 </div>
              </li>			  			  
		   </ul>
		   <div class="panel-footer"> 
		      <button id="searchRegistres" class="btn btn-primary searchRegistre advancedSearch" type="button"><span class="glyph-icon icon-search"></span> Rechercher</button>
              <button class="btn btn-danger  resetSearch"    type="button"><span class="glyph-icon icon-remove"></span> Réinitialiser</button>
		   </div>
		   <input type="hidden" name="page"     id="page"     value="<?php echo $this->pageNum; ?>"  />
		   <input type="hidden" name="maxitems" id="maxitems" value="<?php echo $this->pageSize;?>" />
		</form>
		<table id="registresListTable"  class="table table-hover table-bordered text-center">
                <thead>
                     <tr> 
                          <th width="1%"> <input type="checkbox" name="checkall" id="checkAll" class="checkAll" /></th>   
                          <th width="14%" >  N°  RC         </th>    
                          <th width="20%" > Années de création  </th>  
                          <th width="45%">  Nom commercial      </th> 						  
                          <th width="20%" > Localités           </th>                                        
                     </tr>
                </thead>                
                <tbody>
                       <?php 
                              $output   = "";
                              if( count(   $registres ) ) {
                              	  foreach( $registres as $registre ) {
                              	  	       $registreid  = intval($registre['registreid']);
                              	  	       $libelle     = $registre["libelle"] ;
                              	  	       $numero      = $registre["numero"] ;
                              	  	       $description = $registre["description"] ;
                              	  	       $domaine     = (!empty( $registre["domaine"] )) ? $registre["domaine"]  : "";
                              	  	       $localite    = (!empty( $registre["localite"])) ? $registre["localite"] : "";
                              	  	       $annee       = $registre["annee"]; 
                              	  	       $linkInfos   = $this->url(array("module" => "admin","controller"=> "registrephysique", "action"=> "infos","id"=> $registreid), "default");                             	  	      
                              	  	       $rowBg       = $this->cycle(array("#F0F0F0","#FFFFFF"))->next();
										   $output .= "<tr style=\"background-color:".$rowBg."\" id=\"registreRowId-".$registreid."\"> ";
                              	  	                $output .= "<td> <input type=\"checkbox\" name=\"registreids[]\" id=\"registreids".$registreid."\" class=\"registreids\" /> </td>";
                              	  	                $output .= "<td> <a href=\"".$linkInfos."\"> ".$numero   ." </a> </td>";
                              	  	                $output .= "<td> <a href=\"".$linkInfos."\"> ".$annee    ." </a> </td>";                             	  	                
                              	  	                $output .= "<td> <a href=\"".$linkInfos."\"> ".$libelle  ." </a> </td>"; 
													$output .= "<td> <a href=\"".$linkInfos."\"> ".$localite ." </a> </td>";
                              	  	       $output .= "</tr>";
										   $output .="<input type='hidden'  name='numero-".$registreid."' id='numero-".$registreid."' value='".$numero."'  />" ;
                              	  }                              	
                              }  else {
                              	           $output .= "<tr  id=\"registreRowId-0\"> <td colspan=\"8\"> AUCUN REGISTRE DE TYPE PERSONNE PHYSIQUE N'A ETE RETROUVE  </td> </tr>";
                              }                              
                              echo $output;                      
                       ?>
                
                
                </tbody>           
           </table>
		<?php echo $pagination->render(); ?>
	 </div>
</div>
<?php 
     if( $this->isAjax ) {
     	 echo $this->jQuery();
		 echo $this->headScript();
	     echo $this->headStyle();
     }
?>
   