<html lang="en" >
<?php 
    //On initialise les variables nécessaires
    $layout        = $this->layout();
    $baseUrl       = $this->baseUrl();
    $tplPath       = ROOT_PATH."/myTpl/rccm";       
?>
<head>
<title><?php echo $this->escape($this->title); ?></title>
<meta http-equiv="Content-type" content="text/html; charset=UTF-8"/> 
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
 <style>
     #loading {position: fixed;width: 100%;height: 100%;left: 0;top: 0;right: 0;bottom: 0;display: block;background: #fff;z-index: 10000;}
     #loading img {position: absolute;top: 50%;left: 50%;margin: -23px 0 0 -23px;}
 </style>
<?php echo $this->headMeta() ?>
 <?php
           echo $this->headLink() ;
           echo $this->headStyle(); 
           echo $this->headScript();
           echo "<script type=\"text/javascript\">
                     window.SIRAH ||(window.SIRAH={}); 
                     SIRAH.basePath = \"".$tplPath."/\";
                 </script>";
 ?>
</head>
<body>
<div id="loading"><img src="<?php echo $tplPath; ?>/assets-minified/images/spinner/loader-dark.gif" alt="Chargement..."></div>
<img src="<?php echo $tplPath; ?>/assets-minified/dummy-images/814165-free-wallpaper_v2xusa7.jpg" class="login-img wow fadeIn animated" alt="" style="visibility: visible; animation-name: fadeIn;">
  <!--  DEBUT DE LA PAGE DU THEME -->
    <div class="center-vertical">  
        <div class="center-content"> <?php echo $this->layout()->content ?> </div>
    </div>
  <!--  FIN DE LA PAGE DU THEME -->
</body>
<?php      
      echo $this->jQuery();
 ?>
</html>
