<?php 
$data       = $this->data;
$formSubmit = $this->url(array("controller" =>"domaines", "action" => "create"), "default" );
$backList   = $this->url(array("controller" =>"domaines", "action" => "list")  , "default" );
$basePath   = VIEW_BASE_PATH;

?>
<?php $this->headStyle()->captureStart() ?>

<?php $this->headStyle()->captureEnd()   ?>

<?php

$jq     = $this->jQuery();  
$onLoad = " 
  
  jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});  
  jQuery('#createButton').click(function(e){
      e.preventDefault();      
      var  formSelector = jQuery('#createdomaine-form');
      var  libelle      = jQuery.trim(formSelector.find('#libelle').val());
      
      if(  SIRAH.util.isEmpty( libelle )){
           jQuery('#libelle').addClass('input-error');
           jQuery('#libelle-validation-message').html('');
           SIRAH.error.raise('libelle-validation-message','Entrez une désignation valide du domaine d\'activités');
         return;
      } else {
           jQuery('#libelle').removeClass('input-error');
           jQuery('#libelle-validation-message').html('');
      }      
      jQuery('#libelle').val( libelle );
      formSelector.submit();
   }); ";
  
  $jq->addOnLoad($onLoad);

?>
<form method="post" action="<?php echo $formSubmit; ?>" align="center" id="createdomaine-form" role="form">
 <div class="container col-md-12" style="text-align:left;">
  <ul class="list-group">
   <li class="list-group-item">
     <div class="row">
         <div class="col-md-2"> <label class="label" for="libelle"> <b> Désignation*: </b> </label> </div>
         <div class="col-md-10">
               <input id="libelle" type="text" maxlength="96" autocomplete="off" autocapitalize="off" autocorrect="off" class="form-control"
                      title="Désignation du secteur d'activités" placeholder="Désignation du secteur d'activités"  name="libelle" value="<?php echo $data['libelle']; ?>">
         </div>                 
     </div> 
     <p id="libelle-validation-message" class="validation-message"></p>    
   </li>
   <li class="list-group-item">
     <div class="row">
         <div class="col-md-2"> <label class="label" for="description"> <b> Description du secteur d'activités: </b> </label> </div>
         <div class="col-md-10">
            <textarea   name="description" id="description" class="form-control textarea-sm"> <?php echo $data["description"]; ?> </textarea>
         </div>              
     </div>  
   </li>
  
 </ul>  
<?php     
   $buttonsbar      = $this->Btnbar(array() , $this->jqueryHandler());
   $toolCreate      = $buttonsbar->button("Enregistrer un secteur d'activités","save")->setPriority("primary");
   $toolCancel      = $buttonsbar->button("Annuler et revenir sur la liste","ban");
   
   $toolCreate->setAttributes(array("type" => "submit"));
   $toolCancel->setAttributes(array("type" => "submit"));
   
   $buttonsbar->add($toolCreate ,"createButton");
   $buttonsbar->add($toolCancel ,"cancelCreationButton");

   if(!$this->isAjax) {
   	   echo $buttonsbar;
   } else {
   	   echo $this->jQuery();
   }
   
   ?>
   </div> 
   
   <input type="hidden" name="parentid" id="parentid" value="<?php echo $data["parentid"]; ?>" />
</form>