<?php 
   $model       = new Model_Document();
   $documents   = $this->documents;  
   $linkDelete  = $this->url(array("controller" => "userdocuments", "action" => "delete"), "default") ;
   $output      = "";
   $output     .= "<ul class=\"list-group documentList\">";
   $totalSize   = 0;
    if(count(      $documents )) {
    	  foreach( $documents as $document) {
    	  	$documentid   = intval($document["documentid"]);
    	  	$filename     = $document["filename"];
    	  	$filextension = strtolower($document["filextension"]);
    	  	$filemetadata = $document["filemetadata"];
    	  	$libelle      = $model->filterIndex( $filename, $document["userid"] );
    	  	$icone        = "glyphicon glyphicon-file";
			$class        = "";
			$title        = "Accéder au document";
    	  	
			$filesize     = ( isset( $document["filepath"] ) && file_exists( $document["filepath"] ) ) ? filesize( $document["filepath"] ) : $document["filesize"] ;
			$sizeKo       = Sirah_Functions::toByteString( $filesize, "" , 3 );
    	  	$totalSize   += $filesize;
    	  	
    	  	switch( $filextension ) {
    	  		case "pdf":
    	  			$icone = "icon-file-pdf";
    	  			break;
    	  		case "doc":
    	  		case "docx":
    	  			$icone = "icon-file-word";
    	  			break;
    	  		case "xml":
    	  			$icone = "icon-file-xml";
    	  			break;
    	  		case "ppt":
    	  			$icone = "icon-file-powerpoint";
    	  			break;
    	  		case "xls":
    	  		case "xlxs":
    	  		case "csv":
    	  			$icone = "icon-file-excel";
    	  			break;
    	  		case "png":
    	  		case "gif":
    	  		case "jpg":
    	  		case "jpeg":
    	  		case "bmp":
    	  			$icone = "icon-image";
					$class = "dialogViewInfos";
    	  			break;    	  			
    	  	}    	  	    	  	
    	  	$urlLibelle   = Sirah_Functions_String::cleanUtf8( $libelle );
            $linkView     = $this->url(array( "documentid" => $documentid, "libelle" => $urlLibelle ), "documentheque");   	  	
    	  	$output   .= " <li id=\"documentId-".$documentid."\" class=\"list-group-item\">
                              <div class=\"row\">                                 
                                 <div class=\"col-md-9\">
                                       <span class=\"".$icone."\"></span>
                                       <a class='".$class."' title='".$title."' href='".$linkView."'>
                                          ". $libelle ." 
                                       </a>
                                 </div>
                                 <div class=\"col-md-3\"><p class=\"text-mute\"> ".$sizeKo."</p> </div>
                              </div>
                          </li> ";
    	  }
    }  else {
    	$output .= " <li class=\"list-group-item\" id=\"documentId-0\">    	
    	                <p  class=\"list-group-item-text\"> Aucun document n'a été rattaché à cette activité. </p>
    	           </li>";
    }
    $output     .= "</ul>";
    
    echo  $output ;
 
?>
             