<?php 
$activite        = $this->activite;
$localisation    = $this->localisation;
$partenaires     = $this->partenaires;
$beneficiaires   = $this->beneficiaires;
$resultats       = $this->resultats;
$documents       = $this->documents;
$categorie       = $this->categorie;
$produit         = $this->produit;
$gallerie        = $this->gallerie;
$photos          = $this->photos;
$parent          = $this->parent;

$basePath        = VIEW_BASE_PATH;
$defaultImage    = $basePath."/images/blank.png";
$jq              = $this->jQuery();

$jq->addOnload("
		        var myWind     = jQuery(window);
                var pageBody   = jQuery(document.body);
                var navHeight  = jQuery('#sirahPgHeaderMenu').outerHeight(true) + 10;                
                jQuery('body').scrollspy({target: '.activiteMenu', offset:navHeight});     
    // back to top
    setTimeout(function() {
                             var sideBar       = jQuery('.activiteMenu');
	                         var sideBarTop    = sideBar.offset().top;
                             var navOuterHeight= jQuery('#sirahPgHeaderMenu').height();

                             return (this.top = sideBarTop - navOuterHeight);
                   }, 100);
                   jQuery('#activiteMenu [href=#]').click(function (e) {e.preventDefault()});
		           jQuery('body').scrollspy('refresh');
		");
?>

<div  id="activiteContent"  class="row-fluid">
   <!--  SECTION GENERAL -->            
      <div  class="page-section">
          <div class="page-header"> <h1 id="general"> Informations Générales</h1> </div>
          <div class="panel panel-default">
            <?php echo $this->partial("activites/activite.phtml", array("activite" => $activite, "produit" => $produit, "parent" => $parent, "categorie" => $categorie, "localisation" => $localisation )); ?>
        </div>
     </div> 
   <!--  FIN SECTION GENERAL -->
   
   <!--  SECTION INTRO -->            
      <div  class="page-section">
          <div class="page-header"> <h1 id="intro"> Introduction </h1> </div>
          <div class="panel panel-default">
             <div class="panel-body"><?php echo html_entity_decode(  $activite->introtext , ENT_QUOTES, "UTF-8" );  ?> </div> 
        </div>
     </div> 
   <!--  FIN SECTION INTRO -->
   
  <!--  SECTION OBJECTIFS -->            
    <div class="page-section" >
        <div class="page-header"> <h1 id="objectif"> Objectifs visés </h1> </div>
        <div class="panel panel-default">
            <div class="panel-body" ><?php echo html_entity_decode(  $activite->objectifs , ENT_QUOTES, "UTF-8" );  ?> </div>
                     
         </div>
    </div> 
  <!--  FIN SECTION OBJECTIFS --> 
            
  <!--  SECTION PRESENTATION -->            
    <div class="page-section" >
                  <div class="page-header"> <h1 id="presentation"> Présentation de l'activité </h1> </div>
                  <div class="panel panel-default"><div class="panel-body"><?php echo html_entity_decode( $activite->contenu , ENT_QUOTES, "UTF-8" );  ?> </div></div>
    </div> 
  <!--  FIN SECTION PRESENTATION --> 
            
  <!--  SECTION EFFETS CONSTATES -->            
     <div class="page-section" >
         <div class="page-header"> <h1 id="effets"> Effets Constatés </h1> </div>
         <div class="panel panel-default"><div class="panel-body"><?php echo html_entity_decode(  $activite->effets , ENT_QUOTES, "UTF-8" );  ?> </div></div>
     </div> 
  <!--  FIN SECTION EFFETS CONSTATES--> 
  
  <!--  SECTION RESULTATS PRODUITS -->            
     <div class="page-section" >
         <div class="page-header"> <h1 id="resultats"> Résultats Produits </h1> </div>
         <div class="panel panel-default"><div class="panel-body"><?php echo $this->partial("activites/resultats.phtml", array("activite" => $activite, "resultats" => $resultats )); ?>  </div></div>
     </div> 
  <!--  FIN RESULTATS PRODUITS--> 
            
  <!--  SECTION GALLERIE -->            
     <div  class="page-section">
         <div class="page-header"> <h1 id="gallery"> Gallerie Photos </h1> </div>
         <div class="panel panel-default">
             <div class="panel-body" >
                <?php echo $this->partial("activites/gallerie.phtml", array("activite" => $activite, "gallerie" => $gallerie, "photos" => $photos )); ?> 
             </div>
         </div>
     </div> 
  <!--  FIN SECTION GALLERIE-->
            
  <!--  SECTION DOCUMENTS -->            
       <div class="page-section" >
            <div class="page-header"> <h1 id="documents"> Documents Rattachés </h1> </div>
            <div class="panel panel-default">
                    <?php echo $this->partial("activites/documents.phtml", array("activite" => $activite, "documents" => $documents )); ;  ?>
            </div>
      </div> 
   <!--  FIN SECTION DOCUMENTS-->           


</div>
