<?php 
$activites       = $this->activites;
$categories      = $this->categories;
$beneficiaires   = $this->beneficiaires;
$partenaires     = $this->partenaires;
$regions         = $this->regions;
$provinces       = $this->provinces;
$villes          = $this->villes;
$communes        = $this->communes;
$produits        = $this->produits;
$filters         = $this->filters;
$paginator       = $this->paginator;

$linkSearch      = $this->url(array("module" => "public", "controller" => "activites", "action" => "list"), "default");

$basePath        = VIEW_BASE_PATH;
$defaultImage    = $basePath."/images/blank.png";
$jq              = $this->jQuery();

$jq->addOnload("
 
jQuery('.reset').eq(0).click(function( event ){ event.preventDefault(); document.location.href = '".$linkSearch."'; });		
	
jQuery('.sirahPaginationBtn').click(function(event){
		  event.preventDefault();
		  if(jQuery(this).is('.active') || jQuery(this).is('.disabled') || jQuery(this).is('.currentBtn')) { return false;}
		   var formSelector     = jQuery('#advanced-searchform');
		   var pageNum          = parseInt(jQuery(this).attr('id').replace('paginationBtnPage-' , ''));
		   var pageMaxitems     = formSelector.find('#maxitems').val();
		   if( jQuery(this).is('.nextPage')) {
		      var currentBtnNum = parseInt(jQuery('.currentBtn').first().attr('id').replace('paginationBtnPage-' , ''));
		      pageNum           = parseInt( currentBtnNum +1);
		   }
		   if(jQuery(this).is('.prevPage')) {var currentBtnNum = parseInt(jQuery('.currentBtn').first().attr('id').replace('paginationBtnPage-', ''));pageNum =parseInt( currentBtnNum - 1);}
		var paginationData                = {};
		paginationData.maxitems           = pageMaxitems;
		paginationData.page               = pageNum;
		paginationData.libelle            = formSelector.find('#libelle').val();
		paginationData.datedebut          = formSelector.find('#datedebut').val();
		paginationData.datefin            = formSelector.find('#datefin').val();
		paginationData.statut             = parseInt(formSelector.find('#statut').val() );
		
        var maincontent	                  = jQuery('#maincontent');	
		SIRAH.loading.on( maincontent , 'Chargement des données...' );
		SIRAH.request.post('globalformsearch' , '".$linkSearch."' , 
		                   {
		                      dataType : 'html' ,
		                      data     : paginationData,
		                      beforeSend : function() {},
		                      error      : function(data){maincontent.html(data);SIRAH.loading.off(false);},
	                          success    : function(data){maincontent.html(data);SIRAH.loading.off(false);},
		                      update     : function(data){maincontent.html(data);SIRAH.loading.off(false);}		
		                     });
	  SIRAH.loading.off(false);		 
	});");
  $jq->addJavascriptFile( VIEW_BASE_PATH ."/js/jquery.dynamic-select.min.js");
  $this->partial("activites/dynamiczone.phtml", array("regions" => $regions, "provinces" => $provinces, "villes" => $villes, "jq" => $jq ));

?>
<form method="post" action="<?php echo $linkSearch; ?>" align="left"   id="advanced-searchform"   role="form"> 
  <div id="advanced-searchform-wrapper" class="panel panel-default col-md-12" style="padding:0 !important;">
      <div class="panel-heading"> <h4 class="panel-title"> <span class='glyphicon glyphicon-search'></span> Recherchez une activité </h4></div> 
     <ul  class="list-group">
        <li class="list-group-item"> 
            <div class="row"> 
                <div class="col-md-2"> <label for="libelle"> Mots clés : </label> </div>
                <div class="col-md-10"> <input id="libelle" type="text"  autocomplete="off" autocapitalize="off" autocorrect="off" 
                                       title="Titre de l'activité" placeholder="Saisir des mots clés"  name="libelle" value="<?php echo $filters['libelle']; ?>">  </div>
            </div>         
        </li>
        <li class="list-group-item"> 
            <div class="row"> 
                <div class="col-md-2"> <label for="catid"> Domaines d'activités: </label> </div>
                <div class="col-md-9">  <?php echo $this->formSelect("domaineids[]", $this->checkedDomaines, array("multiple" => "multiple", "style" => "height:100px !important;"), $this->categories );?>  </div>
            </div>         
        </li>       
        <li class="list-group-item"> 
            <div class="row"> 
                <div class="col-md-2"> <label  for="regionid"> Zone/Localité: </label> </div>
                <div class="col-md-5"> <?php echo $this->formSelect("regionids[]"  , $this->checkedRegions  , array("multiple"=> "multiple", "style"=> "height:100px !important;"), $this->regions  );?> </div>
                <div class="col-md-5"> <?php echo $this->formSelect("provinceids[]", $this->checkedProvinces, array("multiple"=> "multiple", "style"=> "height:100px !important;"), $this->provinces);?> </div>
            </div>         
        </li>
        <li class="list-group-item"> 
            <div class="row"> 
               <div class="col-md-2"> <label for="beneficiaireids">Au bénéfice de: </label> </div>
               <div class="col-md-9">  <?php echo $this->formSelect("benefciaireids[]", $this->checkedBenefciaires,array("multiple"=> "multiple", "style"=> "height:100px !important;"), $this->beneficiaires );?> </div>
            </div>         
        </li>
        <li class="list-group-item">                 
          <div class="row">    
            <div class="col-md-2"> <label  for="periode">Période du: </label> </div>
            <div class="col-md-2"><?php echo $this->formSelect('datedebut_month', $this->datedebut_month, array(),array(0 =>"Mois")+$this->months()); ?></div>
            <div class="col-md-2"><?php echo $this->formSelect('datedebut_year' , $this->datedebut_year , array(),array(0 =>"Année")+createYearsArray( ( intval(date("Y")) - 5 ), intval(date("Y")) ) );?></div>
            <div class="col-md-1"> au </div>
            <div class="col-md-2"><?php echo $this->formSelect('datefin_month'  , $this->datefin_month  , array(), array(0 =>"Mois")+$this->months()); ?></div>
            <div class="col-md-2"><?php echo $this->formSelect('datefin_year'   , $this->datefin_year   , array(), array(0 =>"Année")+createYearsArray(( intval(date("Y")) - 5 ), intval(date("Y")) ) );?></div>          
         </div>
        </li>
        <li class="list-group-item"> 
            <div class="row"> 
                <div class="col-md-3"> <label   for="maxitemid"> Limiter à: </label> </div>
                <div class="col-md-2"> <?php echo $this->formSelect("maxitems", $this->maxitems, array(), array("10" => 10, "25" => 25, "50" => 50, "100" => 100,"500"=> 500, "1000" => 1000, "2000" => 2000)); ?> </div>
                <div class="col-md-3"> élements par page </div>
            </div>         
        </li>
        <li class="list-group-item">
           <div class="btn-buttonbar sirah-ui-buttonbar"> 
                 <div class="btn-group"> <button type="submit" class="btn btn-primary search"><span class="glyphicon glyphicon-search"></span > Rechercher</button> </div>
                 <div class="btn-group"> <button type="submit" class="btn btn-danger  reset" ><span class="glyphicon glyphicon-remove"></span > Réinitialiser </button> </div>
           </div> 
        </li>
     </ul>
  </div>
  <input type="hidden" name="page"     id="page"     value="<?php echo $this->pageNum; ?>"  />
</form>                                                           
<?php
      $modelActivite   = new Model_Activite();
      $output          = " <div class=\"panel panel-default listActivites \">
                             <ul class=\"list-group \"> ";
            //On crée et affiche le tableau                
             if(count(   $activites ) ) {
             	foreach( $activites as $activite ) {             		
             	         $activityid       = intval($activite['activityid']);  
             	         $libelle          = strip_tags( $activite["libelle"]);           	         
             	         $introduction     = strip_tags( substr( $activite["introtext"] , 0 , 200 ) ) ;
             	         
             	         $beneficiaires    = $modelActivite->beneficiaires( $activityid );
             	         $periodeStart     = $periodeEnd = "00/00/0000";
             	         
             	         if( intval( $activite["datedebut"] ) ) {
             	         	$zendPeriodeStart = new Zend_Date( $activite["datedebut"] , Zend_Date::TIMESTAMP );
             	         	$periodeStart     = ucfirst( $zendPeriodeStart->toString("dd MMM Y") );
             	         }
             	         if(intval( $activite["datefin"] ) ) {
             	         	$zendPeriodeEnd   = new Zend_Date( $activite["datefin"] , Zend_Date::TIMESTAMP );
             	         	$periodeEnd       = ucfirst( $zendPeriodeEnd->toString("dd MMM Y") );
             	         }
             	         $periode             = sprintf("%s au %s", $periodeStart, $periodeEnd );
             	         $photoGarde          = "";
             	         $urlLibelle          = Sirah_Functions_String::cleanUtf8( $libelle );
             	         $linkInfos           = $this->url(array("controller"=> "activites", "action"=> "infos", "activityid"=> $activityid, "activitylib" =>$urlLibelle ), "publications");
             	         if( empty( $libelle ))
             	         	 continue;
 
             	         $beneficiairesOutput = "Au bénéfice de ".implode(" / ", $beneficiaires );
             	      if( !empty( $activite["photogarde"] ) ) {
             	   	     $photoGardePath   =  $activite["photogarde"];
             	   	     if( file_exists( $photoGardePath ) ) {
             	   	  	     $photoGardePathname = str_replace( APPLICATION_PATH , ROOT_PATH . DS ."myV1", $photoGardePath );
             	   	  	     $photoGarde         = str_replace( DS , "/", $photoGardePathname );
             	   	  	     //$photoGarde         = str_replace( "original", "mini", $photoGarde );
             	   	     }
             	       }
             	       if( !empty( $photoGarde ) ) { 
             	       	    $output         .="<li class=\"list-group-item\" id=\"activityId-".$activityId."\" >";
             	       	            $output .= " <div class=\"row\"> ";
             	       	                       $output .= " <div class=\"col-md-3\"> <img class=\"img-thumbnail img-rounded\" src=\"".$photoGarde."\" width=\"150px\" title=\"Une photo de l'activité\" /> </div> ";
             	       	                       $output .= " <div class=\"col-md-9\"> 
             	       	                                            <h4 class=\"list-group-item-heading\"><u> <a title=\"Visualiser le contenu de l'activité\" href=\"".$linkInfos."\">  ".$libelle." </a> </u> </h4>
    	  	                                                        <p  class=\"list-group-item-text\"> ".$introduction."<a title=\"En savoir plus\" href=\"".$linkInfos."\">[...]</a> </p> 
             	       	                                        ";
             	       	            if( count( $beneficiaires ) ){
             	       	                       	$output    .=" <p  class=\"list-group-item-text\">  <span class=\"text-muted small\"> ".$beneficiairesOutput." </span> </p> ";
             	       	            }
             	       	            if( intval( $activite["datedebut"] ) && intval( $activite["datefin"])) {
             	       	                       	$output    .=" <p  class=\"list-group-item-text\">  <span class=\"text-muted small\"> Dans la période du ".$periode." </span> </p> ";
             	       	             }
             	       	            $output .= " </div> <div> ";
             	       	    $output         .="</li>";
             	       	    
             	       } else {             	       	   
             	       	    $output        .="<li class=\"list-group-item\" id=\"activityId-".$activityId."\" >";            	        
             	       	    $output        .="   <h4 class=\"list-group-item-heading\"> <u> <a title=\"Visualiser le contenu de l'activité\" href=\"".$linkInfos."\">  ".$libelle." </a> </u> </h4>
             	       	                         <p class=\"list-group-item-text\">  ".$introduction." </p> ";
             	       	    if( count( $beneficiaires ) ){
             	       	    	$output    .=" <p  class=\"list-group-item-text\">  <span class=\"text-muted small\"> ".$beneficiairesOutput." </span> </p> ";
             	       	    }
             	       	    if( intval( $activite["datedebut"] ) && intval( $activite["datefin"])) {
             	       	    	$output    .=" <p  class=\"list-group-item-text\">  <span class=\"text-muted small\"> Dans la période de ".$periode." </span> </p> ";
             	       	    }
             	       	    $output        .="</li>";           	       	
             	       }  
             	}
             }  else {
             	       $output .=  " <li id=\"activityId-0\" class=\"list-group-item\"> <p class=\"text-muted\"> AUCUNE ACTIVITE NA ETE TROUVEE DANS LE SYSTEME </p> </li> ";
             }   
              $output  .= " </ul> </div> " ;           
              echo $output;
              
              //On crée et affiche la pagination
              $pagination  = $this->pagination(array() , "Elastic" , "#");              
              echo $pagination->render();
              
              if( $this->isAjax ) {
              	  echo $this->jQuery();
              	  echo $this->headStyle();
              }
                   
    ?>