<?php 
$member      = $this->member;
$memberid    = $this->memberid;
$groupe      = $this->groupe;
$paiements   = $this->paiements;
$factures    = $this->factures;
$demandes    = $this->demandes;
$documents   = $this->documents;
$commandes   = $this->commandes;
$entreprise  = $this->entreprise;
 
$me          = Sirah_Fabric::getUser();

$situations  = array("Célibataire" => "Célibataire","Marié(e)"=> "Marié(e)","Divorcé(e)"=> "Divorcé(e)","Veuf(ve)"=> "Veuf(ve)");
$civilites   = array("Mr" => "Monsieur", "Mme" => "Madame", "Mle" => "Mademoiselle", "Excellence"=>"Son excellence","Maître" => "Maître","Dr" => "Docteur","Pr" => "Professeur");

$situation   = (isset($situations[$member->matrimonial]))? $situations[$member->matrimonial]: "";
$civilite    = (isset($civilites[$member->civilite]    ))? $civilites[$member->civilite]: "";

$villeVal    = ( $ville ) ? $ville->libelle : "";
$paysVal     = ( $pays  ) ? $pays->libelle  : "";

$basePath    = VIEW_BASE_PATH;
$jq          = $this->jQuery();

$linkCancel  = $this->url(array("module"=>"admin","controller"=>"members", "action"=> "list"  ),"default",true);
$linkCreate  = $this->url(array("module"=>"admin","controller"=>"members", "action"=> "create"),"default",true);
$linkEdit    = $this->url(array("module"=>"admin","controller"=>"members", "action"=> "edit"   ,"memberid"=>$memberid), "default",true);
$linkPhoto   = $this->url(array("module"=>"admin","controller"=>"members", "action"=> "photo" , "memberid"=>$memberid), "default",true);
$linkDelete  = $this->url(array("module"=>"admin","controller"=>"members", "action"=> "delete", "ids"     =>$memberid), "default",true);
$linkUpload  = $this->url(array("module"=>"admin","controller"=>"members", "action"=> "upload", "memberid"=>$memberid , "category" => 3), "default");


$jq->addOnload("
    jQuery('.uploadFile').click(function( event ) {
        event.preventDefault();
        var dialogUploadFile   = jQuery('<div></div>').attr('id','dialogUploadFile');             		 
        dialogUploadFile.dialog2({title:'Enregistrer un document',content:'".$linkUpload."',autoOpen:false,modalClass:'modal-wide',removeOnClose:true,closeOnEscape:true,closeOnOverlayClick:false,showCloseHandle:true,initialLoadText:'Chargement de la page, patientez...' });
        dialogUploadFile.dialog2('addButton','<span class=\'glyph-icon icon-upload\'></span> Charger',{primary:true,click:function(){alert('Veuillez fournir un document valide');}}); 
        dialogUploadFile.dialog2('addButton','Annuler' ,   {primary: false,click : function(){jQuery(this).dialog2('close');}});        		            		
        dialogUploadFile.dialog2('open');          
    });
");

$buttonBar    = $this->Btnbar(array("class"=>"button-pane"), $this->jqueryHandler());
$buttonCreate = $buttonBar->button("Nouveau"      , "plus");
$buttonEdit   = $buttonBar->button("Mettre à jour", "edit");
$buttonDelete = $buttonBar->button("Supprimer"    , "trash-o");
$buttonCancel = $buttonBar->button("Revenir sur la liste", "chevron-left");

$buttonEdit->setAttributes(array("class" => "active glyph-icon icon-edit"));

$buttonBar->add($buttonCancel, "cancelButton");
$buttonBar->add($buttonCreate, "createButton");
$buttonBar->add($buttonEdit  , "editButton");
$buttonBar->add($buttonDelete, "deleteButton");

$buttonCreate->setAttributes(array("type"=>"submit", "class"=>"btn btn-success"));
$buttonEdit->setAttributes(  array("type"=>"submit", "class"=>"btn btn-primary"));
$buttonDelete->setAttributes(array("type"=>"submit", "class"=>"btn alert-danger"));
$buttonCancel->setAttributes(array("type"=>"submit"));

$buttonCreate->onClick( sprintf("event.preventDefault(); document.location.href='%s';", $linkCreate));
$buttonEdit->onClick(   sprintf("event.preventDefault(); document.location.href='%s';", $linkEdit  ));
$buttonDelete->onClick( sprintf("event.preventDefault(); document.location.href='%s';", $linkDelete));
$buttonCancel->onClick( sprintf("event.preventDefault(); document.location.href='%s';", $linkCancel));

$creationDate         = $updateDate = "00/00/0000";
$creator              = Sirah_Fabric::getUser($member->creatorid);
$updatedUser          = Sirah_Fabric::getUser($member->updateduserid);
if( $member->creationdate ) {
	$zendCreationdate = new Zend_Date( $member->creationdate , Zend_Date::TIMESTAMP );
	$creationDate     = $zendCreationdate->toString("d MMM Y");
}
if( $member->updatedate ) {
	$zendUpdatedate   = new Zend_Date( $member->updatedate , Zend_Date::TIMESTAMP );
	$updateDate       = $zendUpdatedate->toString("d MMM Y");
}
$this->toolsbar       = $buttonBar;
?>
<div  class="container" style="text-align:left;">
	<div class="row">
		<div class="col-md-6 col-sm-12">
		    <div class="panel panel-default">
				<div class="panel-heading"> <h4 class="panel-title"> <span class="glyph-icon icon-user"></span> Les informations personnelles du compte client</h4> </div>
				<?php echo $this->partial("members/profile.phtml", array("member"=>$member,"memberid"=>$memberid,"groupe"=>$groupe,"entreprise"=>$entreprise)); ?> 
			</div>
		</div> 	   
	    <div class="col-md-6 col-sm-12">
		    <div class="panel-group" id="accordion">
				<div class="panel panel-default">
					<div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#memberAddress"><span class='glyph-icon icon-user'></span> Les coordonnées </a></h4> </div>
					<div id="memberAddress" class="panel-collapse collapse in"> <?php echo $this->partial("members/profile/address.phtml", array("member"=> $member, "memberid" => $memberid)); ?> </div>			
				</div>
				<?php if($me->isAllowed("demandes","list") && count($demandes)): ?> 
				<div class="panel panel-default">
					<div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#memberDemandes"><span class='glyph-icon icon-th-list'></span> Historique des demandes </a></h4> </div>
					<div id="memberDemandes" class="panel-collapse collapse"> 
					  <?php echo $this->partial("members/demandes.phtml", array("member"=>$member,"demandes"=>$demandes,"memberid"=>$memberid )); ?> 
					  <?php if($me->isAllowed("demandes", "create")): ?>  
						<div class="panel-footer">
						  <div class="controls"><button type="submit" class="btn btn-primary glyph-icon icon-plus-circle addDemande"> Enregistrer une demande </button></div>
						</div>
					  <?php endif; ?>
					</div>			
				</div>
				<?php endif; ?>
				<?php if($me->isAllowed("commandes", "list")): ?> 
				<div class="panel panel-default">
					<div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#memberCommandes"><span class='glyph-icon icon-th-list'></span> Historique des commandes </a></h4> </div>
					<div id="memberCommandes" class="panel-collapse collapse"> 
					  <?php echo $this->partial("members/commandes.phtml", array("member"=>$member,"commandes"=>$commandes,"memberid"=>$memberid)); ?> 
					   
					</div>			
				</div>
				<?php endif; ?>
				 
				<?php if($me->isAllowed("paiements","list")): ?>
				<div class="panel panel-default">
					<div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#memberPayments"><span class='glyph-icon icon-th-list'></span> Historique des paiements</a></h4> </div>
					<div id="memberPayments" class="panel-collapse collapse"> 
					    <?php echo $this->partial("members/paiements.phtml", array("member"=>$member,"paiements"=>$paiements,"memberid"=>$memberid)); ?> 
					    
					</div>			
				</div>
				<?php endif; ?>
				 	  
		    </div> 
	    </div> 
	</div>  
</div>
<?php 
    if( $this->isAjax ) {
     	echo $this->jQuery();
	    echo $this->headStyle();
    }
?>
 