<?php 
   $member      = $this->member;
   $memberid    = $this->memberid;
   $me          = Sirah_Fabric::getUser();
   $paiements   = $this->paiements;
   $canRemove   = $me->isAllowed("paiements", "delete");
   $linkDelete  = $this->url(array("module"=>"admin","controller"=>"paiements","action"=>"delete"),"default",true) ;
   $linkCreate  = $this->url(array("module"=>"admin","controller"=>"paiements","action"=>"create" ,"memberid"=> $memberid),"default",true) ;
   $output      = " <table id=\"paiementsList\" class=\"table table-striped table-responsive paiementsList\">
                        <thead>
                            <tr>
                                <th width=\"width:3%\"> *           </th>
								<th width=\"width:28%\"> Références </th>
                                <th width=\"width:35%\"> Dates      </th>
                                <th width=\"width:35%\" style=\"text-align:right;\"> Montants </th>
                            </tr>
                        </thead>";
   
    if( count(  $paiements ) ) {
   	            $paiementTotal = 0;
   	            $soldeTotal    = 0;
   	            $lastSolde     = 0;
   	            $valCommande   = isset($paiements[0]["totalAPayer"] ) ? $paiements[0]["totalAPayer"] : 0;
   	    foreach($paiements as $paiement ) {
   	   	        $paiementid    = $paiement["paiementid"];
   	   	        $numero        = $paiement["numero"];
   	   	        $datePaiement  = $paiement["date_paiement"];
   	   	        $montant       = number_format( $paiement["montant"], 0, ","," ");
   	   	        $paiementTotal+= $paiement["montant"];
 
   	   	        $rowBg         = $this->cycle(array("#F0F0F0","#F5F5F5"))->next();
   	   	        $linkInfos     = $this->url(array("module"=>"admin","controller"=>"paiements","action"=>"infos","paiementid"=>$paiementid), "default",true);
   	   	        
   	   	        $output      .="  <tr id=\"paiementId-".$paiementid ."\" style=\"background-color:".$rowBg."\"> ";
   	   	            if( $canRemove )  
					  $output.="     <td> <span title=\"Supprimer ce paiement\" href=\"#\" id=\"delPaiementId-".$paiementid."\" class=\"glyph-icon icon-remove pull-left delPaiement \"></span> </td>";
   	   	            else
                      $output.="     <td></td>";
                      $output.="     <td style=\"text-align:right;\"><a title=\"Voir les informations du paiement\" href=\"".$linkInfos."\">".$numero." </a> </td>";				  
					  $output.="     <td style=\"text-align:right;\"><a title=\"Voir les informations du paiement\" href=\"".$linkInfos."\">".$datePaiement." </a> </td>";
   	   	              $output.="     <td style=\"text-align:right;\"><a title=\"Voir les informations du paiement\" href=\"".$linkInfos."\">".$montant." </a> </td>";
   	   	        $output      .=" </tr>";
   	    }
   	    $rowBg                = $this->cycle(array("#F0F0F0","#F5F5F5"))->next();
   	    $paiementTotalFormat  = number_format( $paiementTotal, 0 , ",", " " );
 
   	    $output              .= " <tr id=\"paiementId-Total\" style=\"background-color:".$rowBg."\"> 
								    <td colspan=\"2\"> TOTAL </td>
								    <td colspan=\"2\" style=\"text-align:right;\"> ".$paiementTotalFormat." </td>
   	                             </tr>";
   } else {
   	    $output     .=" <tr> <td style=\"text-align:center;\" colspan=\"6\"> Aucun paiement n'a été trouvé dans ce compte </td> </tr>";
   }
   $output.= " </tbody></table>";   
    
   echo  $output ;
        
$jq      =  $this->jQuery();
$onLoad  = "
jQuery('.addPaiement').click(function( event ){event.preventDefault();document.location.href = '".$linkCreate."';});
jQuery('.delPaiement').css('cursor','pointer');
jQuery('.delPaiement').click(function( event ){      
        var itemId           = parseInt(jQuery(this).attr('id').replace('delPaiementId-',''));
        var dialogDeleteItem = jQuery('<div> Etes-vous sur de supprimer ce paiement ? </div>').attr('id','dialogDeleteItem');
        dialogDeleteItem.dialog2({title:'Confirmer l\'action',autoOpen:false,removeOnClose:true,closeOnEscape: false,closeOnOverlayClick:true,showCloseHandle:true,initialLoadText: 'Chargement...'});   
        dialogDeleteItem.dialog2('addButton','Oui' , { primary : true , click : 
             		             function(){
             		             jQuery.ajax({url:'".$linkDelete."',async:false,dataType:'json',data:{'paiementid': itemId},type:'GET',
             		                              success  : function(data) 
             		                              {
             		                                   if( data.error !== undefined) {
                                                           SIRAH.error.raise(jQuery('#dialogDeleteItem') , data.error);
             		                                       return;
             		                                   } else {
             		                                       SIRAH.error.raise(jQuery('#dialogDeleteItem'), data.success , 'success');
             		                                       setTimeout(function(){jQuery('#paiementId-'+itemId).remove();jQuery('#dialogDeleteItem').dialog2('close');},2500);
             		                                   }
             		                                 }
             		                             });     		
                                         }}); 
        dialogDeleteItem.dialog2('addButton','Annuler' , {primary: false,click : function(){jQuery(this).dialog2('close');}});              		
        dialogDeleteItem.dialog2('open'); 
});";    
    $jq->addOnLoad($onLoad);
?>
             