<?php

echo  "<div id=\"sirah-page-message\" class=\"sirah-message text-error\">
           <div class=\"alert alert-block alert-error \">  
                  <a class=\"close\" data-dismiss=\"alert\">×</a>  
                     <strong> ERREUR ! </strong> ". $this->error_title ." 
           </div>
       </div>";

echo  "<div class=\"sirah-message error-content \">
                   ".$this->error_content."
       </div>";

