<?php

echo  "<div id=\"sirah-page-message\" class=\"sirah-message text-error\">
           <div class=\"alert alert-block alert-error \" style=\" font-size:16px;\">  
                  <a class=\"close\" data-dismiss=\"alert\"> × </a>  
                     <strong> <u> ERREUR ! : ".$this->title." </u>  <br/><br/><br/>  ". $this->error_content ." <br/> </strong>
           </div>
       </div>";

