<?php 
$myPwdResetToken= $this->myPwdResetToken;
$formtoken      = $this->formtoken;
$code           = $this->code;
$formSubmit     = $this->url(array("module"=>"public","controller"=>"recoverpwd","action"=>"checkcode", "module"=>"public"),"default",true);
$linkCancel     = $this->url(array("module"=>"public","controller"=>"account"   ,"action"=>"login"    , "module"=>"public"),"default",true);
$basePath       = VIEW_BASE_PATH;

$jq     = $this->jQuery();  
$onLoad = " 
jQuery('body').keydown(function(e) {if (e.keyCode===13) {jQuery('#checkCodeForm').find('#validateBtn').trigger('click');}});
jQuery('#cancelBtn').click(function(e){e.preventDefault(); document.location.href='".$linkCancel."';});
jQuery('#validateBtn').click(function(e){
    e.preventDefault();     
    var code    = jQuery('#code').val();     
    if( SIRAH.util.isEmpty(code)){
        SIRAH.error.raise('checkCodeForm','Entrez un code valide');
        return;
    }      
    jQuery('#checkCodeForm').submit();     
}); ";
  
  $jq->addOnLoad($onLoad);
?>

<div class="container form-container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
			<div class="panel panel-default panel-more-shadow">
				<div class="panel-body">
					<div class="panel-desc"> <?php echo $this->title; ?> </div> <hr>
					<form id="checkCodeForm" method="post" action="<?php echo $formSubmit; ?>" role="form">                      
					    <div style="margin-bottom:25px" class="input-group"><span class="input-group-addon"><i class="glyph-icon icon-lock"></i></span><input name="code" type="text" class="form-control" id="code" title="Celui-ci vous a été transmis sur votre adresse email" placeholder="Jeton de renouvellement du mot de passe" autocomplete="off" ></div>
					    <button type="submit" class="btn btn-primary btn-lg btn-block validate" id="validateBtn"> <i class="glyph-icon icon-log-in"></i> VALIDER</button>
						<button type="submit" class="btn btn-danger  btn-lg btn-block cancel"   id="cancelBtn">   <i class="glyph-icon icon-chevron-left"></i> ANNULER </button>   
						   <input id="formtoken" type="hidden" name="<?php echo $formtoken ; ?>" value="formtoken" />  
						   <input id="myPwdResetToken" type="hidden" name="myPwdResetToken"  value="<?php echo $myPwdResetToken ; ?>" /> 
						   <input id="uid" type="hidden" name="uid"  value="<?php echo $this->userid ; ?>" /> 
				    </form>
				</div>
			</div>      
        </div>   
    </div>
</div>
 