<?php 
$formtoken  = $this->formtoken;
$identity   = $this->identity;
$formSubmit = $this->url(array("module"=>"public","controller"=>"recoverpwd", "action"=>"init" ,"module"=>"public"),"default",true);
$linkCancel = $this->url(array("module"=>"public","controller"=> "account"  , "action"=>"login","module"=>"public"),"default",true);
$basePath   = VIEW_BASE_PATH;

$headScript = $this->headScript();
$headScript->appendFile("https://www.google.com/recaptcha/api.js","text/javascript");
$jq         = $this->jQuery();  
$onLoad = "   
    jQuery('.cancel').click(function(e){e.preventDefault(); document.location.href  = '".$linkCancel."';});  
    jQuery('.send').click(function(e){
		e.preventDefault();     
		var identity    = jQuery('#identity').val();     
		if( SIRAH.util.isEmpty(identity)){
			SIRAH.error.raise('resetPasswordForm','Entrez un identifiant valide');
			return;
		}      
		jQuery('#resetPasswordForm').submit();     
    }); ";
  
  $jq->addOnLoad($onLoad);
?>
<?php $this->headStyle()->captureStart() ?>
<?php $this->headStyle()->captureEnd()   ?>

<div class="container form-container">
   <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
            <div class="panel panel-default panel-more-shadow">
				<div class="panel-body">
					<div class="panel-desc"> <?php echo $this->title; ?> </div> <hr>
				    <form id="resetPasswordForm" method="post" action="<?php echo $formSubmit; ?>" role="form">                      
					    <div style="margin-bottom:25px" class="input-group"><span class="input-group-addon"><i class="glyph-icon icon-user"></i></span><input name="identity" type="email" class="form-control" id="identity" placeholder="Votre adresse email" autocomplete="off" ></div>                  
					    <div style="margin-bottom:25px" class="input-group"><div class="col-md-12 g-recaptcha" data-sitekey="<?php echo API_GOOGLE_RECAPTCHA_SITE_KEY; ?>"></div></div>
					    <button type="submit" class="btn btn-primary btn-lg btn-block send">   <i class="glyph-icon icon-send"></i> ENVOYER</button>
					    <button type="submit" class="btn btn-danger  btn-lg btn-block cancel"> <i class="glyph-icon icon-chevron-left"></i> ANNULER </button>
						   <input id="formtoken" type="hidden" name="<?php echo $formtoken ; ?>" value="formtoken" />    
						   <input id="myPwdResetToken" type="hidden" name="myPwdResetToken"  value="<?php echo $myPwdResetToken ; ?>" />
						   <input id="uid" type="hidden" name="uid"  value="<?php echo $this->userid ; ?>" /> 
					</form>
				</div>
            </div>      
        </div>   
    </div>
</div>
