<?php 
     $linkLogin  = $this->url(array("module"=>"public","controller" => "account"  ,"action" => "login")   , "login");
	 $basePath   = VIEW_BASE_PATH;
     $avatarFile = $basePath."/images/login_avatar.png";
?>

<div class="col-md-5 col-sm-5 col-xs-12"> <img class="pull-left"  src="<?php echo ROOT_PATH; ?>/myTpl/public/images/company.png" /></div>
<div class="col-md-7 col-sm-7 col-xs-12">
	<h1 class="section-hero"> ERCCM : CONSULTEZ DES RCCM EN LIGNE </h1>                              
	<div  class="section-body"> 
	   <p> Le ERCCM est une plateforme de services en ligne du <a title="A propos de cette structure" href="#"> Fichier National du Registre du Commerce et du Crédit Mobilier (FNRCCM) </a> créée dans le but d'archiver, de centraliser et de rendre accessibles au public les Registres du Commerce et du Crédit Mobilier (RCCM) immatriculés au Burkina Faso. </p>
	   <p> Cette plateforme permet la recherche et la consultation en ligne des <a title="Consulter les types de documents officiels" href="#"> documents officiels </a>  des entreprises immatriculées à la <a title="En ssavoir plus sur la maison de l'entreprise" href="#"> Maison de l'Entreprise du Burkina Faso </a>. </p>
	
	</div>                           
</div>                      

<?php 

 
?>