<?php
$rows             = $this->rows;
$sourceItems      = $this->sourceItems;
$foundItems       = $this->foundItems;
$notFoundItems    = $this->notFoundItems;
$annees           = $this->annees;
$localites        = $this->localites;
$checkedLocalites = $this->checkedLocalites;
$registres        = $this->registres;
$tableauDate      = date("d/m/Y");
$zendDate         = new Zend_Date(array("year" => date("Y"), "month" => date("m"), "day" => date("d")));
$type             = $this->type;
if( $type == "A" ) {
	$categoryLibelle = "PERSONNES PHYSIQUES";
} elseif( $type == "B") {
	$categoryLibelle = "PERSONNES MORALES";
} elseif( $type == "M") {
	$categoryLibelle = "MODIFICATIONS";
} elseif( $type == "M") {
	$categoryLibelle = "SURETES";
}
if( $zendDate )  {
	$tableauDate = $zendDate->toString("d MMM yyyy");
}
//print_r( $notFoundItems["files"] );print_r( $registres );die();
$output        = "";
$output       .=" <table cellspacing=\"2\" cellpadding=\"2\" width=\"100%\" border=\"1\" align=\"center\" style=\"text-align:center;\" >";
                    $output.="<tr><td width=\"100%\" style=\"font-size:13pt; text-align:center;background-color:#E5E5E5\" align=\"center\"><b> STATISTIQUES DES DOCUMENTS MANQUANTS OU INCOHERENTS DES RETRAITEMENTS </b></td></tr>";
$output       .=" </table>";
$ColWidth      = (count($checkedLocalites)) ? (90/(count($checkedLocalites))) : 0;
$firstColWidth = 5;
$lastColWidth  = 5;
$totalColspan  = count($checkedLocalites)+2;	
$output       .= "<table border=\"1\" cellpadding=\"2\" cellspacing=\"0\" width=\"100%\" align=\"center\"><thead><tr>";
               if( count(   $checkedLocalites )) {
				            $output .=" <th style=\"text-align:center;\"  width=\"".$firstColWidth."%\"> Années </th>";
				   foreach( $checkedLocalites as $localitecode) { 
                             $localiteLibelle           = (isset($localites[$localitecode])) ? $localites[$localitecode] : null;
							 if( null==$localiteLibelle){
								 $errorMessages[]       = "Localité Invalide";
								 continue;
							 }				   
      	  	                $output .=" <th style=\"text-align:center;\"  width=\"".$ColWidth."%\"> ".$localitecode." </th> ";      	  	                     	  	                   	  	       
      	           }
				            $output .=" <th style=\"text-align:center;\"  width=\"".$lastColWidth."%\"> Total année       </th> ";
			   } 		   
$output       .= "</tr> </thead><tbody>";

if( count(   $rows ) && count($localites) && count($annees)) {
      	  foreach( $annees as $annee ) {
      	  	       $output .=" <tr> "; 
                           $anneeTotal  = 0;
                           $output     .=" <td style=\"text-align:center;\" width=\"".$firstColWidth."%\"> ".$annee." </td> "; 						   
      	  	               if( count(   $checkedLocalites )) {
      	  	               	   foreach( $checkedLocalites as $localitecode ) {
								        $localiteLibelle            = (isset($localites[$localitecode])) ? $localites[$localitecode] : null;
							            if( null==$localiteLibelle) {
								            $errorMessages[]        = "Localité Invalide";
								            continue;
							            }
      	  	               	   	        $rowTotal  =(isset($rows[$localitecode][$annee]["files"])) ? count($rows[$localitecode][$annee]["files"]) : "N.R";
										$colVal    = sprintf("%s ", formatNumber($rowTotal));
      	  	               	   	        $output   .= "<td style=\"text-align:center;\" width=\"".$ColWidth."%\"> ".$colVal." </td>";
										
										$anneeTotal+= $rowTotal;
      	  	               	   }
      	  	               }
						   $colAnneeTotal = sprintf("%s",formatNumber($anneeTotal));
                           $output       .=" <td style=\"text-align:center;\" width=\"".$lastColWidth."%\"> ".$colAnneeTotal." </td> "; 						   
      	  	       $output .=" </tr> ";
      	  }
}  else {
	               $output .="<tr><td width=\"100%\" style=\"text-align:center;\" colspan=\"".$totalColspan."\"> AUCUN REGISTRE MANQUANT NA ETE TROUVE POUR CES CRITERES </td></tr> ";
}
$totalLocalite  = 0;
if( count(   $checkedLocalites )) {
	$output .=" <tr><td style=\"text-align:left;\" width=\"".$firstColWidth."%\"> Total / Localités </td>";
	foreach($checkedLocalites as $localitecode ) {
		    $localiteLibelle            = (isset($localites[$localitecode])) ? $localites[$localitecode] : null;
			if( null==$localiteLibelle) {
				$errorMessages[]        = "Localité Invalide";
				continue;
			}
            $totalRow       =(isset($rows[$localitecode]["files"])) ? count($rows[$localitecode]["files"]) : 0;
            $totalLocalite += $totalRow ;
            $colVal         = sprintf("%s",formatNumber($totalRow));			
      	  	$output        .=" <td style=\"text-align:center;\" width=\"".$ColWidth."%\"> ".$colVal." </td> "; 
 			
    }
	$output .="  <td style=\"text-align:center;\" width=\"".$lastColWidth."%\"> ".sprintf('%s',formatNumber($totalLocalite))." </td></tr>";
} 
$output     .=" </tbody></table><br/><br/>";
$output     .=" <table cellspacing=\"2\" cellpadding=\"2\" width=\"100%\" border=\"1\" align=\"center\" style=\"text-align:center;\" >";
               $output.="<tr><td width=\"100%\" style=\"font-size:13pt; text-align:center;background-color:#E5E5E5\" align=\"center\"><b> LISTE DES DOCUMENTS MANQUANTS/INCOHERENTS DES RETRAITEMENTS</b></td></tr>";
$output     .=" </table>";
$output     .= "<table border='1' width='100%' cellspacing='2' cellpadding='2'> 
		            <thead> <tr>
							    <th width='10%'> N° d'ordre </th>
							    <th width='10%'> Numéros RCCM </th> 
								<th width='80%'> Noms & Prénoms (ou nom commercial) </th>
							</tr> 
					</thead>
				 <tbody>";
	if(count( $notFoundItems["files"] )) {
		$i = 1;
		foreach( $notFoundItems["files"]  as $numRegistre ) {
			     if(isset( $registres[$numRegistre])) {
					 $registre  = $registres[$numRegistre];
			     $output         .=" <tr> ";
				 $output         .=" <td> ".$i." </td> 
					                 <td> ".$registre['numero']." </td>
					                 <td> ".$registre['name']  ." </td>";
				 $output         .=" </tr> ";
				 $i++;
				 }
		}
	} else {
		         $output         .=" <tr><td align=\"center\" colspan=\"3\"> AUCUN FICHIER INVALIDE OU INCOHERENT N'A ETE TROUVE </td></tr>";
	}

$output     .= " </tbody></table>";
echo $output ;