<?php 
$orderCart= new Zend_Session_Namespace("ordercart");
$articles = $orderCart->articles; 
$output   = "";
$output  .="<div class=\"table-responsive\">
				<table class=\"table table-bordered table-striped \" width=\"100%\" border=\"1\" >";                  
				$output.="  <tr><th style=\"text-align:left;\"  width=\"70%\"><b>ARTICLES</b></th>
								<th style=\"text-align:right;\" width=\"30%\"><b>TARIFS  </b></th>
							</tr>";
			if( count(   $articles ) ) {
				$montantTotal = $montantTotalTTC = 0;
				foreach( $articles as $article ) {
						 $productid          = $article["productid"];
						 $registreid         = $article["registreid"];
						 $documentid         = $article["documentid"];
						 $productLibelle     = $article["libelle"];
						 $productDescription = $article["description"];
						 $quantite           = $article["quantite"];
						 $designation        = sprintf("%d %s", $quantite, $productLibelle);
						 $montantHT          = (intval($quantite))? ($article["cout_ht"]*$quantite) : $article["cout_ht"];
						 $montantTTC         = (intval($quantite))? ($article["cout_ttc"]*$quantite): $article["cout_ttc"];
						 $montantTotal      += $montantHT;
						 $montantTotalTTC   += $montantTTC;
						 $bgColorClass       = $this->cycle(array("#FFFFFF","#F5F5F5"))->next();
						 $output .=" <tr id=\"cardProductId".$productid."\" style=\"background-color:".$bgColorClass."\">";
								$output     .=" <td style=\"text-align:left;background-color:".$bgColorClass."\">".$designation." </td>";
								$output     .=" <td style=\"text-align:right;background-color:".$bgColorClass."\">".number_format($montantTTC, 0,' ', ' ')." F CFA </td>";
						 $output .=" </tr>";
				}				 										 
				//$output .=" <tr><td style=\"text-align:right;background-color:".$bgColorClass."\"><b> MONTANT HT</b></td><td style=\"text-align:right;\">".number_format($montantTotal,0,' ', ' ')." F CFA</td>  </tr>";
				$output .=" <tr><td style=\"text-align:right;background-color:".$bgColorClass."\"><b> TOTAL HT</b></td><td style=\"text-align:right;\">".number_format($montantTotalTTC,0,' ', ' ')." F CFA </td>  </tr>";	 
			}	else {
				$output .=" <tr><td colspan=\"2\" style=\"text-align:center;background-color:".$bgColorClass."\"> AUCUN ARTICLE N'A ETE TROUVE DANS VOTRE PANIER </td> </tr>";
			}				
		 
$output       .=" </table>
				</div>";
echo $output;	 
 
 