<?php 
    $commande   = $this->commande;
    $commandeid = $this->commandeid;
	$products   = $this->products;
	
	$output     = "";
    $output    .= " <table id=\"commandeProducts\" class=\"table table-hover table-striped\" >
                        <thead><tr><th width=\"10%\">Codes</th><th width=\"50%\">Désignations</th><th style=\"text-align:left;\" width=\"10%\">Qté</th><th width=\"15%\">Valeur HT</th><th width=\"15%\">Valeur TTC</th></tr></thead>
						<tbody>";
    if( count(  $products)) {
    	foreach($products as $product) {
				$productid   = intval($product["productid"]);
                $produitCode = sprintf("%s",$product["produitCode"]);
				$produitLib  = sprintf("%s",$product["produit"]);
				$quantite    = (floatval($product["quantite"]  ))?sprintf("%s", number_format($product["quantite"]  ,0," ", " ")) : 0;
				$valeurHT    = (floatval($product["valeur_ht"] ))?sprintf("%s", number_format($product["valeur_ht"] ,0," ", " ")) : 0; 
				$valeurTTC   = (floatval($product["valeur_ttc"]))?sprintf("%s", number_format($product["valeur_ttc"],0," ", " ")) : 0;
				
				$output     .= "<tr id=\"productId-".$productid."\">";
				    $output .= "    <td style=\"text-align:left;\"> ".$produitCode."</td>
					                <td style=\"text-align:left;\"> ".$produitLib ."</td>
									<td style=\"text-align:left;\"> ".$quantite   ."</td>
									<td style=\"text-align:right;\">".$valeurHT   ."</td>
									<td style=\"text-align:right;\">".$valeurTTC  ."</td>";
				$output     .= "</tr>";
		} 
    }  else {
    	        $output .= "<tr id=\"productId-0\"><td colspan=\"5\" style=\"text-align:center !important;\"> AUCUN PRODUIT N'A ETE ASSOCIE A CETTE COMMANDE</td></tr>";
    }
    $output     .= "</tbody></table>";
    
    echo  $output ;     
?>
             