<?php
$messageSubject  = $this->subject;
$message         = $this->message;
$enteteImg       = $this->enteteImg;
$logoImg         = APPLICATION_STRUCTURE_LOGO;
$replyToEmail    = $this->replyToEmail;
$replyToName     = $this->replyToName;
$replyToTel      = $this->replyToTel;
$replyToSiteWeb  = $this->replyToSiteWeb;

$toName          = $this->toName;
$toEmail         = $this->toEmail;

$imagePathName   = SERVER_IMAGES_PATHNAME;

?>
<div style="background:#fff <?php echo 'url('.$imagePathName."body_bg.png".') '; ?> repeat-x; width: 100%; height: auto; font-size: 11px; font-family:Arial,Times,Tahoma,Geneva,Kalimati,sans-serif; text-align: center;"><br /> 
<table style="width:620px; margin: auto; text-align: center; height: auto;" border="0" cellspacing="2" cellpadding="2">
<tbody>
<tr>
<td style="background-color:#fff; border:1px solid #AAD3EE;-moz-border-radius:4px;-webkit-border-radius:4px;" colspan="2">
<table style="width: 100%; height: 100%;" border="0">
<!--Entete du contenu--> 
<tbody>
<tr>
<td style="text-align: left;" height="80"><img src="<?php echo $imagePathName."entete.png";  ?>" border="0"  /><br /></td>
<td></td>
</tr>
<tr>
<td style="height: auto; padding: 5px; text-align: left; color: #46260f;">       
        <div><h2 style="background:#00559E <?php echo 'url('.$imagePathName."entete_separator.png".') '; ?> repeat-x bottom;
                        color:#fff;font-size:12px;font-weight:bold;text-align:left;padding:5px;  width:98%;height:25px;">        
                        <?php echo $messageSubject;  ?><br />
             </h2>
       </div>
</td>
</tr>
<!--Fin Entete du contenu--> <!--Corps du contenu--> 
<tr>
<td style="color: black; font-size: 11px; text-align: justify; height: auto;" valign="top">
<?php echo stripslashes($message);  ?>
<p> </p>
</td>
</tr>
</tbody>
</table>
<br /></td>
</tr>
</tbody>
</table>
</div>



