<?php
   $csrfHelper    = Zend_Controller_Action_HelperBroker::getStaticHelper("Csrf");
   $tags          = $this->tags;
   $tokenId       = $csrfHelper->getTokenId();
   $tokenValue    = $csrfHelper->getToken();
   $linkDelete    = $this->url(array("module" => "admin", "controller" => "myprofile", "action" => "removetag", $tokenId => $tokenValue), "default") ;
   $linkInsertTags= $this->url(array("module" => "admin", "controller" => "myprofile", "action" => "tags") , "default");
   $linkDeleteTag = $this->url(array("module" => "admin", "controller" => "myprofile", "action" => "removetag", $tokenId => $tokenValue), "default");
   $output       = "";
   $output       = "<div class=\"controls\"> 
                         <ul id=\"tagList\" class=\"nav nav-pills list-inline pills-default-bg selectedList tagList\">";
    if( count(     $tags ) ) {
    	  foreach( $tags as $tag ) {
    	  	$tagId    = intval(  $tag["tagid"] );
    	  	$tagLib   = $tag["keyword"];    	  	
    	  	$output .= " <li  id=\"tagId-".$tagId."\"> <a href=\"#general\">".$tagLib." <i title=\"Supprimer cet element\" href=\"#\" id=\"closeId-".$tagId."\" class=\"glyphicon glyphicon-remove closeItemTag\"></i> </a> </li> ";
    	  }    	
    } else {
    	$output .= " <li id=\"tagId-0\"> <p class=\"text-muted\"> 
    	                                 Aucun tag n'est rattaché à votre profil. 
    	                                 Vous pouvez taguer votre profil par des mots clés à travers lesquels votre profil sera plus visible sur le web.</p></li> ";
    }
    $output     .= "</ul></div>";
    echo  $output ;    
$jq      =  $this->jQuery();
$onLoad  = "
jQuery('.insertTag').click(function( event ) {
         event.preventDefault();
        var dialogTagsInsert   = jQuery('<div></div>').attr('id','dialogTagsInsert').addClass('modal-medium');             		 
        dialogTagsInsert.dialog2({
             		               title : 'Enregistrer les tags de votre profil',
             		               content : '".$linkInsertTags."',
             		               autoOpen: false,
             		               modalClass:'modal-wide',
             		               removeOnClose: true,
             		               closeOnEscape: false, 
                                   closeOnOverlayClick: true,
             		               showCloseHandle:true,
             		               initialLoadText: 'Chargement...'            		                       
             		             });
        dialogTagsInsert.dialog2('addButton','<span class=\'glyphicon glyphicon-plus\'></span> Enregistrer',{ primary:true, 
             		              click:function( event ) {
             		                         event.preventDefault();
             		                         var modalBody = jQuery('.modal').find('.modal-body');
             		                         var insertBtn = jQuery('.modal').find('.modal-footer').find('.btn-primary').eq(0);
             		                         insertBtn.btnLoading({text:'Chargement...',icon:'icon-spinner4'});
             		                         SIRAH.loading.on( modalBody , 'Patientez...' ); 
             		                         var tagsForm = jQuery(this).find('form').eq(0);
             		                         SIRAH.request.post( tagsForm ,'".$linkInsertTags."',{
             		                                            success : function( data ) {
             		                                                 jQuery('#patientez').fadeOut('slow');
             		                                                 SIRAH.loading.off(false);            		                                                                                      
                            	                                     if( !SIRAH.util.isEmpty( data.error ) ) {
                            		                                      SIRAH.error.raise( dialogTagsInsert , data.error , 'error');
                            		                                      insertBtn.btnLoading({on:false});
                            		                                      return data;
                            	                                     } else if( !SIRAH.util.isEmpty( data.success ) ) {
                            		                                      SIRAH.error.raise( dialogTagsInsert , data.success , 'success');
                            		                                      setTimeout(function(){
                            		                                            insertBtn.btnLoading({on:false});
                            		                                            jQuery('#sirah-page-message').remove();
                            		                                            SIRAH.MYPROFILE.insertTags( data.tags, '".$linkDeleteTag."' );
                            		                                            dialogTagsInsert.dialog2('close');} , 2000);
                            	                                     }	else {
                            		                                      SIRAH.error.raise( dialogTagsInsert ,'Aucune reponse valide n\'a été retournée par le serveur','error');
                            		                                      insertBtn.btnLoading({on:false});
                            		                                      return data;
                            	                                    }		
             		                                            }
             		                         });
             		               }
             		             });
        dialogTagsInsert.dialog2('addButton','<span class=\'glyphicon glyphicon-ban-circle\'></span> Annuler',{primary: false,click:function(){jQuery(this).dialog2('close');}});              		
        dialogTagsInsert.dialog2('open');       	
  });
 jQuery('.closeItemTag').css('cursor','pointer');
 jQuery('.closeItemTag').click(function(){      
          var itemId           = parseInt(jQuery(this).attr('id').replace('closeId-',''));
          var dialogDeleteItem = jQuery('<div> Etes-vous sur de supprimer cet element ? </div>').attr('id','dialogDeleteItem');
          dialogDeleteItem.dialog2({
             		                title : 'Confirmer ',
             		                autoOpen: false,
             		                removeOnClose: true,
             		                closeOnEscape: false, 
                                    closeOnOverlayClick: true,
             		                showCloseHandle:true,
             		                initialLoadText: 'Chargement...'            		                       
             		              });   
          dialogDeleteItem.dialog2('addButton','Oui' , { primary : true , click : 
             		               function(){
             		                jQuery.ajax({
             		                              url      :'".$linkDeleteTag."',
             		                              async    : false,
			                                      dataType :'json',
             		                              data     : {'tags[]': itemId},
             		                              type     : 'GET' ,
             		                              success  : function(data) 
             		                              {
             		                                   if ( data.error !== undefined ) {
                                                           SIRAH.error.raise(jQuery('#dialogDeleteItem') , data.error);
             		                                       return;
             		                                   } else {
             		                                       SIRAH.error.raise(jQuery('#dialogDeleteItem'), data.success , 'success');
             		                                       jQuery('#tagId-'+itemId).remove();
             		                                        setTimeout(function(){
             		             		                               jQuery('#tagId-'+itemId).remove();
             		                                                   jQuery('#dialogDeleteItem').dialog2('close');
             		                                                  },2500);
             		                                   }
             		                                 }
             		                             });     		
                                         }}); 
         dialogDeleteItem.dialog2('addButton','Annuler',{primary:false,click:function(){jQuery(this).dialog2('close');}});              		
         dialogDeleteItem.dialog2('open');                   		             		            		       
       });";    
    $jq->addOnLoad($onLoad);
?>
             