<?php 
   $data               = $this->data;
   $formNames          = $this->formNames;
   $categories         = $this->categories;
   $formSubmit         = $this->url(array("module" => "admin", "controller" => "myprofile" , "action" => "upload") , "default" ) ; 
   $onLoad  = "
   jQuery('#mydocument').filestyle({
                                   buttonText  : ' Choisir un fichier',
                                   classButton : 'btn btn-default',
                                   classIcon   : 'glyphicon glyphicon-folder-open',
                                   icon        : true
                                });
   jQuery('#mydocumentform').fileupload({
                                      paramName:'mydocument',
                                      url      : '".$formSubmit."' ,
                                      type     : 'POST',
                                      dataType : 'json',
                                      add : function(e , data) {
                                                   var modalButton  = jQuery('.modal').first().find('.btn-primary:first');
                                                   modalButton.unbind('click');
                                                   modalButton.bind('click' , function( event ) {
                                                          event.preventDefault();
                                                          SIRAH.loading.on( jQuery('.modal-body').first(), 'Patientez , stockage du document...' );
                                                          var jqXhr    = data.submit();
                                                          jqXhr.success(function(result , textStatus , jqXHR){
                                                               if( result.success != undefined) {
                                                                   SIRAH.loading.off(false);
                                                                   SIRAH.error.raise(jQuery('#dialogUploadFile') , 'Opération terminée : '+result.success , 'success');
                                                                   var document  = result.document;
                                                                   if( document  != undefined ){
                                                                       SIRAH.loading.off(false);
                                                                       /*jQuery('#dialogUploadFile').dialog2('close')*/;                                                                      
                                                                      }
                                                                  } else if(result.error != undefined) {
                                                                      SIRAH.error.raise(jQuery('#dialogUploadFile') , 'Opération terminée : '+result.error , 'error');
                                                                      SIRAH.loading.off(false);
                                                                      return true;
                                                                 }
                                                              });
                                                           jqXhr.error(function( result , textStatus, errorThrown){
                                                                    SIRAH.error.raise(jQuery('#dialogUploadFile') , 'Opération terminée , aucune erreur valide n\'a été retournée : '+result , 'error');
                                                                    SIRAH.loading.off(false);
                                                                    return false;
                                                      });
                                         });  },
                                        messages: {uploadedBytes: 'Le fichier que vous voulez uploader est trop lourd'}
   });
   jQuery('#mydocumentform').bind('fileuploadprogress', function (e, data) {
          var progress = parseInt(data.loaded / data.total * 100, 10);
          jQuery('#progress').css('width', progress+'%');
          jQuery('#progress').html(progress+'%');
    });
   jQuery('#mydocumentform').bind('fileuploadformsubmit', function (e, data) {
                                  var inputs    = jQuery(this).find(':input');
                                  data.formData = inputs.serializeArray();
   });";
   $jq  = $this->jQuery();
   $jq->addOnLoad($onLoad);
   $basePath    = ROOT_PATH."/myTpl/default";
   $jq->addStyleSheet(     $basePath . "/js/fileupload/css/jquery.fileupload.css");
   $jq->addStyleSheet(     $basePath . "/js/fileupload/css/jquery.fileupload-ui.css");
   $jq->addStyleSheet(     $basePath . "/css/sirahfileupload.css");
   $jq->addJavascriptFile( $basePath . "/js/bootstrap/bootstrap-filestyle.js");
   $jq->addJavascriptFile( $basePath . "/js/fileupload/js/vendor/jquery.ui.widget.js");
   $jq->addJavascriptFile( $basePath . "/js/fileupload/js/jquery.iframe-transport.js");
   $jq->addJavascriptFile( $basePath . "/js/fileupload/js/jquery.fileupload.js");
   $jq->addJavascriptFile( $basePath . "/js/fileupload/js/jquery.fileupload-ui.js");
?>
<?php $this->headStyle()->captureStart() ?>
.bar {height: 18px;background: green;}
div.bootstrap-filestyle input[type="text"]{width:auto;margin-left:5px;margin-right:5px;margin-bottom:0;}
div.bootstrap-filestyle, div.fileUploadRow{margin-bottom:15px;}
<?php $this->headStyle()->captureEnd()   ?>  
 <form method="post" action="<?php echo $formSubmit; ?>" align="center"   id="mydocumentform" enctype="multipart/form-data"   role="form">
 <div class="row"> 
              <div class="col-lg-12 fileupload-progress fade">                
                  <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                     <div id="progress" class="progress-bar progress-bar-success" style="width:0%;"></div>
                  </div>
                  <div class="progress-extended">&nbsp;</div>              
              </div>
 </div> 
 <div class="row col-md-12" style="text-align:left;">
    <ul class="list-group">
      <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-4"> <label class="control-label" for="filepath"> Chercher le document : </label> </div>
            <div class="col-md-8"> <input name="mydocument" type="file" id="mydocument" /> </div>
       </div> 
     </li> 
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-4"> <label class="label" for="<?php echo $formNames['filename']; ?>"> <b> Désignation du fichier *:</b> </label></div> 
            <div class="col-md-8"> <input id="<?php echo $formNames['filename']; ?>" type="text" maxlength="96" autocomplete="off" autocapitalize="off" autocorrect="off" 
                                          title="La désignation du fichier" placeholder="La désignation du fichier" name="<?php echo $formNames['filename']; ?>" value="<?php echo $this->escape($data["filename"]); ?>"></div>
       </div>
       <p id="filename-validation-message" class="validation-message"></p>  
     </li> 
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-4"> <label class="label" for="<?php echo $formNames['category']; ?>"> <b> La catégorie du fichier* :</b> </label></div> 
            <div class="col-md-8"> <?php echo $this->formSelect($formNames["category"] , $data["category"] , array() , $categories ); ?></div>
       </div>
     </li> 
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-4"> <label class="label" for="<?php echo $formNames['filemetadata']; ?>"> <b>Les mots clés :</b> </label></div> 
            <div class="col-md-8"> <input id="<?php echo $formNames['filemetadata']; ?>" type="text" maxlength="96" autocomplete="off" autocapitalize="off" autocorrect="off" 
                                          title="Les clés d'indexation du fichier" placeholder="Les clés d'indexation du fichier"  name="<?php echo $formNames['filemetadata']; ?>" value="<?php echo $this->escape($data["filemetadata"]); ?>"> </div>
       </div>
     </li>     
     <li class="list-group-item">     
        <div class="row col-md-12"> 
            <div class="col-md-4"> <label class="label" for="filedescription"> <b> Description du fichier : </b> </label> </div> 
            <div class="col-md-8"> <textarea cols="3" rows="60" name="<?php echo $formNames['filedescription']; ?>"  id="<?php echo $formNames['filedescription']; ?>">
                                            <?php echo $this->escape($data["filedescription"]); ?>
                                   </textarea> 
           </div>
       </div>
   </li>   
  </ul>
  </div>  
   <?php if($this->isAjax) : ?>
   <?php echo $this->jQuery(); echo $this->headStyle(); ?>
   <?php endif; ?>   
   <input type="hidden" name="<?php echo $this->csrfTokenId; ?>"  id="<?php echo $this->csrfTokenId; ?>"  value="<?php echo $this->csrfTokenValue; ?>" />
  </form>     
  
  