<?php 
$captcha            = $this->captcha;
$messages           = $this->messages;
$token              = $this->token;
$data               = $this->data;
$defaultCountry     = (isset($data["country"]) && !empty($data["country"])) ? $data["country"] : "BF";
 
$formSubmit         = $this->url(array("controller"=>"shippers", "action"=> "account", "module"=> "public"),"default");
$linkCancel         = $this->url(array("controller"=>"index"   , "action"=> "index"        , "module"=> "public") , "default");
$linkCheckUsername  = $this->url(array("controller"=>"ajaxres" , "action"=> "checkusername", "module"=> "public"),"default");
$linkCheckEmail     = $this->url(array("controller"=>"ajaxres" , "action"=> "checkemail"   , "module"=> "public"),"default");
 
$basePath           = ROOT_PATH.'/myTpl/public';
$situations         = array("Célibataire" => "Célibataire","Marié(e)" => "Marié(e)","Divorcé(e)" => "Divorcé(e)","Veuf(ve)"=> "Veuf(ve)");
?>
<?php $this->headStyle()->captureStart() ?>
.panel > .list-group .list-group-item{border-width:1px !important;border-top:1px solid #ddd !important}
<?php $this->headStyle()->captureEnd()   ?>

<?php
$jq     = $this->jQuery();  
$onLoad = " 
var  formSelector= jQuery('#createAccountForm');
jQuery('.birthday,#birthday').pickadate({format:'dd/mm/yyyy',formatSubmit:'dd/mm/yyyy',hiddenName:true,hiddenSuffix:'__suffix',hiddenPrefix:'prefix__',selectYears:100,selectMonths:true,min:new Date(1950,1,1),max:new Date(),onStart:function(){this.set('select','".$data["birthday"]."');}});
jQuery('.createButton').click(function( event ){
      event.preventDefault();      
      var  formSelector= jQuery('#createAccountForm');
      var  firstname   = jQuery.trim(formSelector.find('#firstname').val());
      var  lastname    = jQuery.trim(formSelector.find('#lastname').val());
      var  email       = jQuery.trim(formSelector.find('#email').val());
      var  credential  = jQuery.trim(formSelector.find('#password').val());
      var  credential2 = jQuery.trim(formSelector.find('#confirmedpassword').val());
      var  phone1      = jQuery.trim(formSelector.find('#phone1').val());
      
      if(SIRAH.util.isEmpty(lastname)){
         formSelector.find('#lastname').addClass('input-error');
         formSelector.find('#name-validation-message').html('');
         SIRAH.error.raise('name-validation-message','Entrez un nom de famille valide');
         return;
      } else {
         formSelector.find('#lastname').removeClass('input-error');
         formSelector.find('#name-validation-message').html('');
      }
      if(SIRAH.util.isEmpty(firstname)){
        formSelector.find('#firstname').addClass('input-error');
        formSelector.find('#name-validation-message').html('');
         SIRAH.error.raise('name-validation-message','Entrez un prénom valide');
         return;
      }  else {
          formSelector.find('#firstname').removeClass('input-error');
          formSelector.find('#name-validation-message').html('');
      }    
       if(SIRAH.util.isEmpty(phone1)){
        formSelector.find('#phone1').addClass('input-error');
        formSelector.find('#phone-validation-message').html('');
         SIRAH.error.raise('phone-validation-message','Entrez un numéro de téléphone valide');
         return;
      }  else {
         formSelector.find('#phone1').removeClass('input-error');
         formSelector.find('#phone-validation-message').html('');
      }
      if(!SIRAH.validators.isEmailAddress(email)){
         formSelector.find('#email').addClass('input-error');
         formSelector.find('#email-validation-message').html('');
         SIRAH.error.raise('email-validation-message','Entrez un email valide');
         return;
      }  else {
         formSelector.find('#email').removeClass('input-error');
         formSelector.find('#email-validation-message').html('');
      }     
      if(SIRAH.util.isEmpty(credential) || (parseInt(credential.length) < 4)){
         formSelector.find('#password').addClass('input-error');
         formSelector.find('#password-validation-message').html('');
         SIRAH.error.raise('password-validation-message','Entrez un mot de passe valide, doit contenir au moins 4 caractères');
         return;
      } else {
         formSelector.find('#credential').removeClass('input-error');
         formSelector.find('#password-validation-message').html('');
      }      
      if(credential2 !== credential){
         formSelector.find('#confirmedpassword').addClass('input-error');
         formSelector.find('#confirmedpassword-validation-message').html('');
         SIRAH.error.raise('confirmedpassword-validation-message','Les mots de passe sont differents');
         return;
      } else {
         formSelector.find('#confirmedpassword').removeClass('input-error');
         formSelector.find('#confirmedpassword-validation-message').html('');
      }
      formSelector.find('#lastname').val(lastname);
      formSelector.find('#firstname').val(firstname);
      formSelector.find('#email').val(email);
      formSelector.find('#phone1').val(phone1);
      formSelector.find('#password').val(credential);
      formSelector.find('#confirmedpassword').val(credential2);
      formSelector.submit();
});
formSelector.find('#lastname').bind('blur change',function(e){
      e.preventDefault();
	  var  formSelector = jQuery('#createAccountForm');
      var lastname      = jQuery.trim(jQuery(this).val());
      if(!SIRAH.util.isEmpty(lastname)){
        formSelector.find('#lastname').removeClass('input-error');
        formSelector.find('#name-validation-message').html('');
      } else {
        formSelector.find('#lastname').addClass('input-error');
        return;
      }
  });  
formSelector.find('#firstname').bind('blur change',function(e){
      e.preventDefault();
	  var  formSelector = jQuery('#createAccountForm');
      var firstname     = jQuery.trim(jQuery(this).val());
      if(!SIRAH.util.isEmpty(firstname)){
        formSelector.find('#firstname').removeClass('input-error');
        formSelector.find('#name-validation-message').html('');
      }  else {
        formSelector.find('#firstname').addClass('input-error');
         return;
      }
});  
formSelector.find('#username').bind('blur change',function(e){
      e.preventDefault();
	  var  formSelector = jQuery('#createAccountForm');
      var username      = jQuery.trim(jQuery(this).val());
      if( username.length >= 3){
		  jQuery('#username-validation-message').html('Vérification du nom d\'utilisateur...');
		  SIRAH.request.get(formSelector,'".$linkCheckUsername."', {beforeSend : function(){},			   
							success : function( data ) {
										formSelector.find('#username-validation-message').html('');
										formSelector.find('#username').removeClass('input-error');
										if( data.error !== undefined   ) {
											formSelector.find('#username').addClass('input-error');
											formSelector.find('#username-validation-message').html('');
											SIRAH.error.raise('username-validation-message',data.error);
										}
								  }
		  });
	  }	else {
		 formSelector.find('#username').addClass('input-error');
		 formSelector.find('#username-validation-message').html('Votre nom d\'utilisateur doit comporter au moins 4 caractères...');
		 return;
	  }				  
}); 
formSelector.find('#email').bind('blur change',function(e){
      e.preventDefault();
	  var  formSelector = jQuery('#createAccountForm');
      var email         = jQuery.trim(jQuery(this).val());
	  if( SIRAH.validators.isEmailAddress(email)){	
          formSelector.find('#email-validation-message').html('Vérification de l\'adresse Email...');	  
		  SIRAH.request.get(formSelector,'".$linkCheckEmail."', {beforeSend : function(){},			   
							success : function( data ) {
								formSelector.find('#email-validation-message').html('');
								formSelector.find('#email').removeClass('input-error');
								if( data.error !== undefined   ) {
									formSelector.find('#email').addClass('input-error');
									formSelector.find('#email-validation-message').html('');
									SIRAH.error.raise('email-validation-message',data.error);
								}
							}
		  });
	  } else {
		  formSelector.find('#email').addClass('input-error');
		  formSelector.find('#email-validation-message').html('');
		  SIRAH.error.raise('email-validation-message','Entrez une adresse email valide');
		  return;
	  }         	  
});     
formSelector.find('#password').bind('blur change',function(e){
      e.preventDefault();
	  var  formSelector = jQuery('#createAccountForm');
      var credential    = jQuery.trim(jQuery(this).val());
      if(SIRAH.util.isEmpty(credential) || (parseInt(credential.length) < 4)){
         formSelector.find('#password').addClass('input-error');
         formSelector.find('#password-validation-message').html('');
         SIRAH.error.raise('password-validation-message','Entrez un mot de passe valide');
         return;
      }  else {
         formSelector.find('#password').removeClass('input-error');
         formSelector.find('#password-validation-message').html('');
      }    
});  
formSelector.find('#confirmedpassword').bind('blur change',function(e){
      e.preventDefault();
	  var formSelector = jQuery('#createAccountForm');
      var credential   = jQuery.trim(formSelector.find('#password').val());
      var credential2  = jQuery.trim(jQuery(this).val());
      if(credential2 !== credential){
         formSelector.find('#confirmedpassword').addClass('input-error');
         formSelector.find('#confirmedpassword-validation-message').html('');
         SIRAH.error.raise('confirmedpassword-validation-message','Les mots de passe sont differents ');
         return;
      } else {
        formSelector.find('#confirmedpassword').removeClass('input-error');
        formSelector.find('#confirmedpassword-validation-message').html('');
      }      
  });  
formSelector.find('#phone1').bind('blur change',function(e){
      e.preventDefault();
	  var  formSelector = jQuery('#createAccountForm');
      var phone1        = jQuery.trim(jQuery(this).val());
      if(!SIRAH.util.isEmpty(phone1)){
        formSelector.find('#phone1').removeClass('input-error');
        jQuery('#phone-validation-message').html('');
      }  else {      
        formSelector.find('#phone1').addClass('input-error');
         return;     
      }
});  
jQuery('#cancelButton').click(function(e){e.preventDefault();document.location.href='".$linkCancel."';}); ";
$jq->addOnLoad($onLoad);
$jq->addStyleSheet(    $basePath ."/scripts/widgets/pickadate/themes/default.css");
$jq->addStyleSheet(    $basePath ."/scripts/widgets/pickadate/themes/default.date.css");
$jq->addStyleSheet(    $basePath ."/scripts/widgets/pickadate/themes/default.time.css");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/picker.js");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/picker.date.js");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/picker.time.js");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/translations/fr_FR.js");	
?>
<form method="post" action="<?php echo $formSubmit; ?>" id="createAccountForm"  class="form-horizontal" role="form" enctype="multipart/form-data">
	<div class="panel panel-default">
		<ul class="list-group">
			<li class="list-group-item">
				<div class="form-group">            
					<label class="col-sm-2  col-md-2 control-label" for="name">Nom*: </label>
					<div   class="col-sm-10 col-md-10">
						<div class="input-group">
						   <input id="lastname"  type="text" maxlength="100" class="form-control" title="Nom de famille" placeholder="Nom de famille" name="lastname"  value="<?php echo $data['lastname'];?>">
						   <span class="input-group-btn" style="width:0px;"></span>
						   <input id="firstname" type="text" maxlength="240" class="form-control" title="Prénom"         placeholder="Prénom"         name="firstname" value="<?php echo $data['firstname'];?>">											  
						</div>					
					</div>
					<p id="name-validation-message" class="validation-message"></p> 
				</div>					
			</li>
			<li class="list-group-item">
				<div class="form-group">
					 <label class="col-sm-2  col-md-2 control-label" for="name"> Identifiant*: </label>
					 <div   class="col-sm-10 col-md-10"><input id="username" type="text" maxlength="200"class="form-control" title="Votre nom d'utilisateur" placeholder="Votre nom d'utilisateur" name="username" value="<?php echo $data['username']; ?>"></div>           
				</div>
				<p id="username-validation-message" class="validation-message"></p>       
		    </li>
		    <li class="list-group-item">
				<div class="form-group">
					<label class="col-sm-2  col-md-2 control-label" for="name"> Adresse Email*: </label>
					<div   class="col-sm-10 col-md-10"><input id="email" type="text" maxlength="200" class="form-control" title="Votre adresse email" placeholder="Votre adresse email"  name="email" value="<?php echo $data['email']; ?>"></div>              
				</div>  
				<p id="email-validation-message" class="validation-message"></p>   
		    </li>
		    <li class="list-group-item">
				<div class="form-group">
					<label class="col-sm-2 col-md-2 control-label" for="name"> Mot de passe*: </label>
					<div   class="col-sm-10 col-md-10">
						<div class="input-group">
							<input id="password"          type="password" placeholder="Saisissez votre mot de passe" maxlength="20" title="Votre mot de passe par défaut" name="password"          class="form-control" />
							<span class="input-group-btn" style="width:0px;"></span>
							<input id="confirmedpassword" type="password" placeholder="Confirmez le mot de passe"    maxlength="32" title="Confirmez le mot de passe"     name="confirmedpassword" class="form-control">
						</div>
					</div>                 
				</div>
			 <p id="password-validation-message"          class="validation-message"></p> 
			 <p id="confirmedpassword-validation-message" class="validation-message"></p>  
		    </li>
		    <li class="list-group-item">
				<div class="form-group">
				    <label class="col-sm-2 col-md-2 control-label" for="birthday"> Date de naissance : </label>
					<div   class="col-sm-10 col-md-10">
						<div class="input-group">
						    <input type="text" name="birthday" id="birthday" class="form-control birthday" readonly value="<?php echo $data["birthday"]; ?>" />
							<span class="input-group-addon">
							<i class="fa fa-calendar"></i></span> 
							<input type="text" name="birthaddress" id="birthaddress" class="form-control" placeholder="Lieu de naissance" value="<?php echo $data["birthaddress"]; ?>" />
							 
						</div>
					</div>
				</div>
			</li>
			<li class="list-group-item">
				<div class="form-group">            
					<label class="col-sm-2  col-md-2 control-label">  <b>Téléphone*:</b> </label> 
					<div   class="col-sm-10 col-md-10">
						<div class="input-group">
						   <input id="phone1" type="text" maxlength="24" class="form-control" title="Numéro de téléphone"  placeholder="Numéro de téléphone"  name="phone1" value="<?php echo $data['phone1']; ?>">
						   <span class="input-group-btn" style="width:0px;"></span>
						   <input id="phone2" type="text" maxlength="24" class="form-control" title="Votre second  mobile" placeholder="Votre second  mobile" name="phone2" value="<?php echo $data['phone2']; ?>">											  
						</div>					
					</div>
					<p id="phone-validation-message" class="validation-message"></p> 
				</div>					
			</li>		             
			<li class="list-group-item">
				<div class="form-group">  
					<label class="col-sm-2 col-md-2 control-label">  <b> Sexe* :</b> </label> 
					<div   class="col-sm-5 col-md-5"> 
						<label class="radio-inline"><input type="radio" name="sexe" id="sexe-m" value="M" <?php if($data["sexe"]== "M") echo "checked"; ?>>Homme</label>	  
						<label class="radio-inline"><input type="radio" name="sexe" id="sexe-f" value="F" <?php if($data["sexe"]== "F") echo "checked"; ?>>Femme</label>
					</div>
					 <div class="col-sm-5 col-md-5">&nbsp;</div>    
				</div>  
			</li>  
	    </ul>   
	   <input id="socialstate"     type="hidden" name="socialstate"  value="Célibataire" />
	   <input id="adress"          type="hidden" name="adress"       value="" />
	   <input id="nationalite"     type="hidden" name="nationalite"  value="BF" /> 
	   <input id="country"         type="hidden" name="country"      value="BF" />  
	   <input id="city"            type="hidden" name="city"         value="0" />     
	   <input id="registerDoneUri" type="hidden" name="doneUri"      value="" /> 
	   <input id="t"               type="hidden" name="t"            value="<?php echo $token; ?>" /> 

	   <div class="panel-footer">
			<div class="btn-group"> <button id="createButton" class="btn btn-primary createButton"><i class="glyph-icon icon-save"> </i> Créer mon compte </button> </div>
			<div class="btn-group"> <button id="cancelButton" class="btn btn-danger  cancelButton"><i class="glyph-icon icon-ban-circle"> </i> Annuler</button> </div>
	   </div>
    </div>
</form>