<?php 
$me             = Sirah_Fabric::getUser();
$client         = $this->client;
$expeditions    = $this->shipments;
$documents      = $this->documents;
$recipients     = $this->recipients;
$basePath       = VIEW_BASE_PATH;
$jq             = $this->jQuery();

$linkEditInfos  = $this->url(array("module"=>"public","controller"=>"shippers","action"=>"edit"   ),"default");
$linkCancel     = $this->url(array("module"=>"public","controller"=>"shipments","action"=>"list"  ),"default");
$linkCreate     = $this->url(array("module"=>"public","controller"=>"shipments","action"=>"create"),"default");

$buttonBar      = $buttonbar  = $this->buttonsbar(array()  , $this->jqueryHandler());
$buttonCreate   = $buttonBar->button("Nouvelle expédition" ,"plus");
$buttonCancel   = $buttonBar->button("Toutes mes expéditions","ban-circle");

$buttonBar->add($buttonCreate, "createButton");
$buttonBar->add($buttonCancel, "cancelButton");

$buttonCreate->setAttributes(array("type"=>"submit", "class"=>"btn btn-success"));
$buttonCancel->setAttributes(array("type"=>"submit"));

$buttonCreate->onClick(sprintf("event.preventDefault(); document.location.href='%s';" , $linkCreate));
$buttonCancel->onClick(sprintf("event.preventDefault(); document.location.href='%s';" , $linkCancel));

$jq->addOnload("jQuery('.editInfos').click(function(event){event.preventDefault();document.location.href='".$linkEditInfos."';});");

?>
<?php $this->headStyle()->captureStart() ?>
.statute-red a,.statute-yellow a{color:white;}
<?php $this->headStyle()->captureEnd()   ?>
<div class="row">
    <div class="col-md-6">
	    <div class="panel panel-default">
		    <div class="panel-heading"> <h4 class="panel-title"> <span class="glyph-icon icon-user"></span> Informations Personnelles </h4> </div>
		    <?php echo $this->partial("shippers/profile.phtml", array("client"=>$client,"clientid"=>$clientid)); ?>
	        <div class="panel-footer"><div class="controls"><button type="submit" class="btn btn-primary glyph-icon icon-pencil editInfos"> Mettre à jour mes informations</button></div></div> 
		</div>
	</div>
	<div class="col-md-6">
	    <div class="panel-group" id="accordion">
			<div class="panel panel-primary">
				<div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#shipmentsList"><span class='glyph-icon icon-list-alt'></span> Historique des expéditions </a></h4> </div>
				<div id="shipmentsList" class="panel-collapse collapse in"> <?php echo $this->partial("shippers/shipments.phtml", array("expeditions"=>$expeditions)); ?> </div>			
			    <div class="panel-footer"><?php echo $buttonBar; ?></div>
			</div>
			<div class="panel panel-primary">
				<div class="panel-heading"><h4 class="panel-title"><a data-parent="#accordion" data-toggle="collapse" href="#recipientsList"><span class='glyph-icon icon-users'></span> Bénéficiaires </a></h4> </div>
				<div id="recipientsList" class="panel-collapse collapse"> <?php echo $this->partial("shippers/recipients.phtml", array("recipients"=>$recipients)); ?></div>			
			</div>
	    </div>
	</div>
</div>
<?php 
     if( $this->isAjax ) {
     	 echo $this->jQuery();
	     echo $this->headStyle();
     }
?>
 