<?php 
    $modifications = $this->modifications;
	$orderCart     = new Zend_Session_Namespace("ordercart");
    $registre      = $this->registre;
    $registreid    = $this->registreid;
    $documents     = $this->documents; 
	$cartRegistres = (isset($orderCart->registres))?$orderCart->registres : array();
    $cartDocuments = (isset($orderCart->documents))?$orderCart->documents : array();	
    $linkDownload  = $this->url(array("controller"=>"registres","action"=> "download","module"=> "public"), "default") ;   
	$linkAddToCart = $this->url(array("module"=>"public","controller"=>"ordercart","action"=>"addregistre"),"default",true) ;
    $output        = "<ul class=\"list-group modificationsList\">";
    if( count( $modifications ) ){
     	$output   .="<li id=\"modificationId-0\" class=\"list-group-item\">
						<div class=\"row\">
							 <div class=\"col-md-4\"> Numéros                </div>
							 <div class=\"col-md-4\"> Types de modifications </div>
							 <div class=\"col-md-4\"> * </div>							 
						</div> 
				    </li>";
		$i      = 0;
     	foreach( $modifications as $modification ) {
     		     $modificationid   = $documentKey = $modification["registreid"];
     		     $modificationType = $modification["type"];
				 $modificationNum  = $modification["numero"];
                 $zendDate         = ( intval($modification["date"]))?new Zend_Date($modification["date"], Zend_Date::TIMESTAMP) : null;
                 $date             = ( $zendDate ) ? $zendDate->toString("dd/MM/Y") : null;			 
     		     $linkView         = $this->url(array("controller"=>"registremodifications","action"=>"infos","registreid" => $modificationid ));
     		     
     		     $output .="<li id=\"modificationId-".$i."\" class=\"list-group-item\">
				             <div class=\"row\">     		                    
     		                    <div class=\"col-md-4\">".$modificationNum ."</div>
								<div class=\"col-md-4\">".$modificationType."</div>";
				 if( isset($cartRegistres[$modificationid])) {
					 $output .=" <div id=\"btnGroup-".$documentKey."\" class=\"col-md-4\"><button type=\"button\" class=\"btn btn-success disabled pull-left\" id=\"delFromCartId-".$documentKey."\"><span class=\"glyph-icon icon-check\"></span> Ajouté au panier </button></div>";
				 } else {
					 $output .=" <div id=\"btnGroup-".$documentKey."\" class=\"col-md-4\"><button type=\"button\" class=\"btn btn-danger pull-left addToCartModification\" title=\"Ajouter au panier\" id=\"addToCartModificationId-".$documentKey."\"><span class=\"glyph-icon icon-shopping-cart\"> </span> Ajouter au panier</button></div>";
				 }					 
								 
     		     $output.="</div></li> ";  
                 $i++;							
     	}
    } else {
     	$output .= " <li id=\"nomodifications\" class=\"list-group-item\"> <div class=\"row \"> Aucune modification n'a été trouvée pour ce registre </div> </li>";     	
    }  
    $output     .= "</ul>";
    echo  $output ;
   
    $jq      =  $this->jQuery();
    $onLoad  = "
        jQuery('.addToCartModification').css('cursor','pointer');
        jQuery('.addToCartModification').click(function(){      
		    var documentBtn = jQuery(this);
			var documentKey = jQuery(this).attr('id');
            var registreid  = documentKey.replace('addToCartModificationId-','');
			 
			documentBtn.html('En cours...');documentBtn.addClass('disabled');
            jQuery.ajax({url:'".$linkAddToCart."',async:true,dataType:'json',data:{'registreid':registreid},type:'GET',
			            beforeSend:function(){documentBtn.html('En cours...');documentBtn.addClass('disabled');},
						success  : function(data) {
							if( data.error !== undefined) {
							    alert(data.error);
								documentBtn.addClass('addToCartModification');
								documentBtn.removeClass('disabled');
								documentBtn.html('<span class=\'glyph-icon icon-shopping-cart\'></span> Ajouter au panier');
							} else if(data.success !== undefined && data.counter !==undefined ) {
							    jQuery('#cardUpdateBtn').trigger('addProduct');   	
                                documentBtn.removeClass('addToCartModification');								
							    documentBtn.removeClass('btn-danger').addClass('btn-success').addClass('disabled');
								documentBtn.html('<span class=\'glyph-icon icon-check\'></span>Ajouté au panier');
							}
						}
			});                  		             		            		       
        });";    
    $jq->addOnLoad($onLoad);			
?>
             