<?php
	$registres          = $this->registres;
	$filters            = $this->filters;
	$params             = $this->params;
	$paginator          = $this->paginator;
	$searchAdvandced    = $this->advanced;
	$advancedSearchForm = $this->advancedSearchForm;
	$domaines           = $this->domaines;
	$localites          = $this->localites;
	$checkedLocalites   = $this->checkedLocalites;
	$checkedDomaines    = $this->checkedDomaines;
	$csrfTokenId        = $this->csrfTokenId;
	$csrfTokenValue     = $this->csrfTokenValue;
	$totalResults       = 0;
	$paginationForm     = ($advancedSearchForm)?"advancedSearchEntreprise" : "searchRegistres";
	$linkSearch         = $this->url(array("module"=>"public","controller"=>"registres","action"=>"search","reset"=>1,"advanced"=>0),"default",true);
	if( null != $paginator ) {
  	   //On crée et affiche la pagination
  	    $pagination     = $this->pagination(array() , "Elastic" , "#", array(), array("class"=> "panel-footer paginationControl", "style" => "text-align:center;")); 
        $totalResults   = $paginator->getTotalItemCount();	  
    }	
	$jq                 = $this->jQuery();
	$jq->addOnLoad("
	    var dropdownMenu;
		var advancedSearch   = parseInt('".intval($searchAdvandced)."');
	    jQuery('.dropdown-toggle').dropdown();
		jQuery('.dropdown-menu a').click(function(){
			var typeID       = jQuery(this).val();
			var formSelector = jQuery('form#searchRegistres');
			if( typeID=='searchPP') {
				formSelector.find('#type').val(1);
			} else if(typeID=='searchPM') {
				formSelector.find('#type').val(2);
			} else {
				formSelector.find('#type').val(0);
			}
			formSelector.submit();
		});
		jQuery('#searchPP').click(function(event){
			event.preventDefault();
			if( advancedSearch ) {
				var formSelector = jQuery('form#advancedSearchEntreprise');
			} else {
				var formSelector = jQuery('form#searchRegistres');							
			}
			formSelector.find('input[name=\'type\']').val('1');	
			formSelector.submit();
		});
		jQuery('#searchPM').click(function(event){
			event.preventDefault();
			if( advancedSearch ) {
				var formSelector = jQuery('form#advancedSearchEntreprise');
			} else {
				var formSelector = jQuery('form#searchRegistres');							
			}
			formSelector.find('input[name=\'type\']').val('2');	
			formSelector.submit();
		});
		jQuery('#searchSS').click(function(event){
			event.preventDefault();
			if( advancedSearch ) {
				var formSelector = jQuery('form#advancedSearchEntreprise');
			} else {
				var formSelector = jQuery('form#searchRegistres');							
			}
			formSelector.find('input[name=\'type\']').val('3');	
			formSelector.submit();
		});
		jQuery('#searchTypeAll').click(function(event){
			event.preventDefault();
			if( advancedSearch ) {
				var formSelector = jQuery('form#advancedSearchEntreprise');
			} else {
				var formSelector = jQuery('form#searchRegistres');							
			}
			formSelector.find('input[name=\'type\']').val('0');	
			formSelector.submit();
		});
		jQuery('.sirahPaginationBtn').click(function(event){
			event.preventDefault();
			if(jQuery(this).is('.active') || jQuery(this).is('.disabled') || jQuery(this).is('.currentBtn')) { return false;}
			var formSelector     = jQuery('#".$paginationForm."');
			var currentPage      = parseInt(formSelector.find('#page').val());
			var pageNum          = parseInt(jQuery(this).attr('id').replace('paginationBtnPage-' , ''));
			var pageMaxitems     = parseInt(formSelector.find('#maxitems').val());
			if( jQuery(this).is('.nextPage')) {
				var currentBtnNum= parseInt(jQuery('.currentBtn').first().attr('id').replace('paginationBtnPage-' , ''));
				pageNum          = parseInt( currentBtnNum +1);
			}
			if( pageNum ) {
				formSelector.find('#page').val(pageNum);
				formSelector.find('#maxitems').val(pageMaxitems);				
			}
			formSelector.find('#advancedsearch').val('1');
			formSelector.submit();
		});
		jQuery('#searchBtn').click(function(event){
			event.preventDefault();
			var formSelector   = jQuery('#searchRegistres');
			if( formSelector.find('#".$csrfTokenId."')===undefined ) {
				jQuery('<input>').attr({type:'hidden',id:'".$csrfTokenId."',name:'".$csrfTokenId."'}).val('".$csrfTokenValue."').appendTo('form#searchRegistres');
			}			
			formSelector.submit();
		});
		jQuery('.resetBtn,.resetButton').click(function(event){event.preventDefault();document.location.href='".$linkSearch."';}); 
		jQuery('#resetSearchBtn').click(function(event){event.preventDefault();jQuery('#searchQ').val('');jQuery('#localiteid').val('0');jQuery('#type').val('0');jQuery('#domaineid').val('0');});
		jQuery(window).on('show.bs.dropdown',function (e) {
            dropdownMenu= jQuery(e.target).find('.dropdown-menu');
            jQuery('body').append(dropdownMenu.detach());
            var eOffset = jQuery(e.target).offset();
            dropdownMenu.css({'display': 'block','top': eOffset.top + jQuery(e.target).outerHeight(),'left': eOffset.left});
        });
		jQuery(window).on('hide.bs.dropdown',function(e) {jQuery(e.target).append(dropdownMenu.detach());dropdownMenu.hide();});
	");
?>
<?php $this->headStyle()->captureStart() ?>
.search-results-section{background-color:#F7F8FA;position:relative;padding:115px 5px 15px 5px;}
.search-results-buttons{float: right;margin-right: 0;display:flex}
.btn-adavanced-search,.search-results-buttons-sort-group > .btn{color: #686F7A;background-color:#FFF;border: 1px solid #CACBCC;border-radius:0px}
input.searchQ,.searchBtn{border: 1px solid #CACBCC;border-radius:0px}
.search-data-list{background-color:#fff;}
.btn-outline-secondary {color:#6c757d;background-color: transparent;background-image: none;border-color:#CACBCC;}
.results-infos{border-bottom:1px solid #e1e4e8!important}
.results-infos > .panel-title{font-size:20px;font-weight:600}
#search-results-rows h5.list-group-item-heading{color:#0366d6; font-size:16px;}
.search-results-rows-item{padding:8px 10px;}
#AdvancedSearchSection{padding:5px 0 !important}
.hideAdvancedSearch{display:none  !important}
.showAdvancedSearch{display:block !important}
.panel-body,.container{ overflow: inherit !important;}
.search-results-searchbox{padding-top:10px;padding-bottom:10px;}
<?php $this->headStyle()->captureEnd();  ?>
<div id="search-results-section" class="topadding search-results-section section">
    <div class="container">
        <div class="row section-content search-results-header">
			<div class="search-results-count"></div>
			<div class="search-results-searchbox">
                <div class="col-md-12 text-center"> 
					<form id="searchRegistres" class="form-horizontal" action="<?php echo $linkSearch; ?>" method="post"> 
						<div class="input-group input-group-lg">
						     
							<input value="<?php echo $filters['searchQ'];?>"    type="text"   class="form-control searchQ" name="searchQ" id="searchQ"  placeholder="Veuillez saisir le numéro RCCM, le nom commercial ou le nom du promoteur d'une entreprise...." />
							<input value="<?php echo $filters['type']; ?>"      type="hidden" id="type"       name="type"       />
							<input value="<?php echo $filters['domaineid'];?>"  type="hidden" id="domaineid"  name="domaineid"  />
							<input value="<?php echo $filters['localiteid'];?>" type="hidden" id="localiteid" name="localiteid" />

							<input type="hidden" name="<?php echo $this->csrfTokenId; ?>" id="<?php echo $this->csrfTokenId; ?>"  value="<?php echo $this->csrfTokenValue; ?>" />   
						    
							<input value="<?php echo $this->maxitems;?>"        type="hidden" id="maxitems"   name="maxitems"   />
							<input value="<?php echo $this->page;?>"            type="hidden" id="page"       name="page"       />
							<input value="1"                                    type="hidden" id="search"     name="search"     />
							<div class="input-group-btn">							    
								<button id="searchBtn"         class="btn btn-primary searchBtn" title="Veuillez cliquer sur ce bouton pour rechercher" ><span class="glyph-icon icon-search"></span> Recherche </button>
								<button id="advancedSearchBtn" class="results-buttons-filter-advancedsearch btn btn-lg btn-adavanced-search" title="Veuillez cliquer sur ce bouton pour effectuer une recherche avancée"><i class="glyph-icon icon-align-justify"></i></button>
								<button id="resetSearchBtn"    class="btn btn-danger  resetSearchBtn" title="Veuillez cliquer sur ce bouton pour annuler votre recherche"> <span class="glyph-icon icon-times"></span></button>
							</div>
						</div>
					</form>
				</div>
 
			</div>
		</div>
	</div>
	<?php echo $this->partial("registres/advancedsearch.phtml", array("csrfTokenId"=>$csrfTokenId,"csrfTokenValue"=>$csrfTokenValue,"advanced"=>$searchAdvandced,"checkedDomaines"=>$checkedDomaines,"checkedLocalites"=>$checkedLocalites,"filters"=>$filters,"params"=>$params,"localites"=>$localites,"domaines"=>$domaines));?>
</div>
<?php if( count( $registres ) || !empty($params['searchQ'])): ?>
<div class="search-data-list section" id="search-data-list">
	<div class="container">
	    <div class="row section-content search-results-header">
		    <div class="col-md-3 hidden-sm hidden-xs pull-left">
			    <div class="panel panel-danger panel-more-shadow panel-search-results" id="panel-search-typeresults">
				    <div class="panel-heading results-infos"><h3 class="panel-title">Filtrer par type</h3></div>
					<div class="list-group no-top-border">
					    <a title="Cliquez sur ce bouton pour afficher tous les RCCM"                      id="searchTypeAll" href="#" class="list-group-item searchTypeAll"> Tous les RCCM </a>
						<a title="Cliquez sur ce bouton pour afficher les Personnes Physiques uniquement" id="searchPP" href="#" class="list-group-item searchPP"> Personnes Physiques </a>
						<a title="Cliquez sur ce bouton pour afficher les Personnes Morales uniquement"   id="searchPM" href="#" class="list-group-item searchPM"> Personnes Morales   </a>
						<a title="Cliquez sur ce bouton pour afficher les Sûrétés uniquement"             id="searchSS" href="#" class="list-group-item searchSS"> Sûrétés   </a>
                    </div>					
				</div>
			</div>
			<div class="col-md-9 col-sm-9">
				<div class="panel panel-plain panel-more-shadow panel-search-results" id="panel-search-results">
				    <div class="panel-heading results-infos">
					    <h3 class="panel-title"> <?php echo ($totalResults>1)?sprintf("%s entreprises trouvées", number_format($totalResults, 0, ' ', ' ')) : sprintf("%d entreprise trouvée", $totalResults); ?></h3>
						<div class="panel-tools pull-right"> </div>
					</div>
					<div class="list-group search-results-rows" id="search-results-rows">
					<?php 
						$output = ""; 
						foreach($registres as $registre ) {
								$registreid           = intval($registre['registreid']);
								$libelle              = $registre["libelle"] ;
								$numero               = $registre["numero"]  ;
								$numeroIFU            = $registre["numifu"]  ;
								$numeroCNSS           = $registre["numcnss"]  ;
								$annee                = $registre["annee"]   ;
								$description          = $registre["description"] ;
								$localite             = (!empty( $registre["localite"])) ? $registre["localite"] : "";
								$dateRegistre         = sprintf("Immatriculé le : %s", date("d/m/Y",$registre["date_registre"]) ); 
								$urlLibelle           = Sirah_Functions_String::cleanUtf8( $numero );
								$linkInfos            = $this->url(array("registreid"=> $registreid, "registrelib"=>$urlLibelle,"type"=>"physiques" ), "registre", true);   
 
								$registreCategory     = "Registre de Commerce";
								if( $registre["type"]==1) {
									$registreCategory = "Personne Physique";
								} elseif($registre["type"]==2) {
									$registreCategory = "Personne Morale";
								} elseif($registre["type"]==3) {
									$registreCategory = "RCCM de type Sûrété";
								} elseif($registre["type"]==4) {
									$registreCategory = "RCCM de type Modification";
								} 
								                     	  	      
								$output .= "<div title=\"Consulter les informations de ce RCCM\" href=\"".$linkInfos."\" class=\"list-group-item list-group-item-action flex-column align-items-start search-results-rows-item \" id=\"registreid-".$registreid."\"> "; 
									$output .= "<div class=\"d-flex w-100 justify-content-between\"><h5 class=\"list-group-item-heading mb-1\"><u> <a title=\"Visualiser le contenu de ce RCCM\" href=\"".$linkInfos."\">".$libelle." </a> </u></h5> <small class=\"text-muted\">".$dateRegistre."</small></div>";
									$output .= "<p class=\"mb-1\"> ".$description." </p>";
									$output .= "<span class=\"text-muted\"> Numéro RCCM : ".$numero    .", </span>";
									$output .= "<span class=\"text-muted\"> Type        : ".$registreCategory.", </span>";
									$output .= "<span class=\"text-muted\"> Juridiction : ".$localite.", </span>";	
									$output .= "<span class=\"text-muted\"> Année de création:".$annee   ." </span>";
									$output .= "<div class=\"d-flex flex-wrap panel-body btn-arrange item-buttons\"> ";
									$output .= "   <a href=\"".$linkInfos."\" class=\"button\"> <i class=\"glyph-icon icon-info\"></i> En savoir plus... </a>";
									//$output .= "   <a href=\"#\" class=\"button\"> <i class=\"glyph-icon icon-file-pdf-o\"></i> Documents officiels </a>";
									//$output .= "   <a href=\"#\" class=\"button\"> <i class=\"glyph-icon icon-heart\"></i> Favoris </a>";
									//$output .= "   <a href=\"#\" class=\"button\"> <i class=\"glyph-icon icon-share-alt\"></i> Partager </a>";											
									$output .= "</div>";											
								$output .= "</div>";      
								$output .="";										
						}                               
					echo $output;                      
					?>                              
					</div>
					<?php if($this->pageSize < $totalResults ): ?>
		              <?php  echo $pagination->render(); ?>
					<?php endif; ?>
		        </div>
			</div>
            
		</div> 
	</div>
</div>
<?php endif; ?>