<?php 
$data          = $this->data;
$registreid    = $this->registreid;
$formSubmit    = $this->url(array("module"=>"admin","controller"=>"registremoral","action"=>"edit" ,"registreid"=>$registreid), "default" );
$backList      = $this->url(array("module"=>"admin","controller"=>"registremoral","action"=>"infos","registreid"=>$registreid), "default" );
$searchUrl     = $this->url(array("module"=>"admin","controller"=>"ajaxres","action"=>"searchrc"), "default" );
$checkNumeroUrl= $this->url(array("module"=>"admin","controller"=>"ajaxres","action"=>"checkrcnum","type"=>"moral","registreid"=>$registreid), "default" );
$checkLibUrl   = $this->url(array("module"=>"admin","controller"=>"ajaxres","action"=>"checkrclib"), "default" );


$basePath      = VIEW_BASE_PATH;
$domaines      = $this->domaines;
$localites     = $this->localites;
$formes        = $this->formes;
$dirigeants    = $this->dirigeants;
$situations    = array("Célibataire" => "Célibataire", "Marié(e)"=> "Marié(e)","Divorcé(e)" => "Divorcé(e)", "Veuf(ve)" => "Veuf(ve)");
$statuts       = array("Selectionnez un statut", 1 => "Créé", 2 => "Modifié", 3 => "Racheté", 4 => "Radié");
$me            = Sirah_Fabric::getUser();
?>
<?php $this->headStyle()->captureStart() ?>
.input-document{width:250px;display:inline-block;}
.form-horizontal .checkbox, .form-horizontal .checkbox-inline, .form-horizontal .control-label, .form-horizontal .radio, .form-horizontal .radio-inline {padding-top:0!important}
.grpChosen{width:100px !important;}
<?php $this->headStyle()->captureEnd()   ?>
<?php
$jq     = $this->jQuery();  
$onLoad = "
jQuery('.removeLine').css('cursor','pointer').click(function(event){event.preventDefault();var hisLigneId = parseInt(jQuery(this).attr('id').replace('closeId-',''));jQuery('#dirigeantFormGroup-'+hisLigneId).remove();});
jQuery('input:checkbox').bootstrapSwitch();
jQuery('input:checkbox').on('switchChange.bootstrapSwitch', function(event, state) {
	if((state == true) && (this.name =='find_documents')) {
		jQuery('#findDocumentsOptions').removeClass('hide');
		jQuery('.manualFindDocuments').addClass('hide'); 
	} 
	if((state == false) && (this.name =='find_documents')){
		jQuery('#findDocumentsOptions').addClass('hide');
		jQuery('.manualFindDocuments').removeClass('hide');
	}
}); 
jQuery('.chosen').chosen({allow_single_deselect:true,no_results_text: 'Aucun element ne correspond à ', width:'100%'});
jQuery('input[name=\'find_documents\']').click(function( event ){
    if(jQuery(this).is(':checked')) {
       jQuery('#findDocumentsOptions').removeClass('hide');
	   jQuery('.manualFindDocuments').addClass('hide');
    } else {
       jQuery('#findDocumentsOptions').addClass('hide');
	   jQuery('.manualFindDocuments').removeClass('hide');
    } 
});
jQuery('#docmini').filestyle({buttonText:'Rechercher un document',classButton:'btn btn-primary',classInput:'input-inline form-control',classIcon:'glyph-icon icon-folder-open',icon: true});
jQuery('#docoriginal').filestyle({buttonText:'Rechercher un document',classButton:'btn btn-primary',classInput:'input-inline form-control',classIcon:'glyph-icon icon-folder-open',icon: true});
jQuery('#docstatut').filestyle({buttonText:'Rechercher un document',classButton:'btn btn-primary',classInput:'input-inline form-control',classIcon:'glyph-icon icon-folder-open',icon: true});

jQuery('#numero').change(function(){
    var numero       = jQuery(this).val();
    var formSelector = jQuery('#editRegistreForm');
	jQuery('#numRcSearching').html('Vérification du numéro RCCM...');
	setTimeout(function(){	
		SIRAH.request.get(formSelector,'".$checkNumeroUrl."', { data:{'numero':numero}, beforeSend : function(){},
			success: function( data ) {
				jQuery('#numRcSearching').html('').removeClass('parsley-required').removeClass('parsley-required');
				jQuery('#numero').removeClass('danger').removeClass('parsley-error');
				jQuery('#numero').removeClass('success').removeClass('parsley-success');
				if( data.error !== undefined   ) {
					jQuery('#validnumrc').val('0');
					jQuery('#numRcSearching').html(data.error).addClass('parsley-required');
					jQuery('#numero').addClass('danger').addClass('parsley-error');
					jQuery('#numero').removeClass('success').removeClass('parsley-success');
					SIRAH.dialog.alert(data.error,'Numéro RCCM Invalide');
					return data;
				}
				if( data.success !== undefined ) {
					jQuery('#numRcSearching').html('').removeClass('parsley-required');
					jQuery('#numRcSearching').html('').addClass('parsley-success');
					jQuery('#numero').removeClass('danger').removeClass('parsley-error');
					jQuery('#numero').addClass('success').addClass('parsley-success');
					jQuery('#validnumrc').val('1');
				}
			}
		});		
	}, 500);
});
jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});  
jQuery('#editButton').click(function(e){
    e.preventDefault();      
    var formSelector = jQuery('#editRegistreForm');
    var libelle      = jQuery.trim(formSelector.find('#libelle').val());
    var numero       = jQuery.trim(formSelector.find('#numero').val());
    var localiteid   = parseInt(formSelector.find('#localiteid').val());
	var isValidNumRC = parseInt(formSelector.find('#validnumrc').val());

    if(!isValidNumRC) {
		jQuery('#numRcSearching').html(data.error).addClass('parsley-required');
		jQuery('#numero').addClass('danger').addClass('parsley-error');
		SIRAH.dialog.alert('Veuillez saisir un numéro RCCM Valide','Erreur de saisie');
        return;
	}
    if( SIRAH.util.isEmpty(libelle )){
        SIRAH.error.raise('editRegistreForm','Entrez un nom commercial valide');
        return;
    } 
    if( SIRAH.util.isEmpty(localiteid )){
        SIRAH.error.raise('editRegistreForm','Veuillez selectionner une localité');
        return;
    }      
    formSelector.submit();
}); ";
  
  $jq->addOnLoad($onLoad);
  $jq->addJavascriptFile( $basePath . "/js/bootstrap/bootstrap-filestyle.js");
  $jq->addJavascriptFile( $basePath . "/assets-minified/widgets/uniform/uniform.js");
  $jq->addStylesheet(     $basePath . "/assets-minified/widgets/uniform/uniform.css" );
  $jq->addJavascriptFile( $basePath . "/assets-minified/widgets/input-switch/inputswitch.js");
  $jq->addStylesheet(     $basePath . "/assets-minified/widgets/input-switch/inputswitch.css" );

?>

<div     class="content-box">    
    <h3 class="content-box-header content-box-header-alt bg-default">ETAPE 1 <small> Les informations du registre </small></h3>
    <form method="post"  id="editRegistreForm" class="form-horizontal mrg15T row" role="form" enctype="multipart/form-data">        
		<div class="form-group"> 
            <label class="col-sm-12 col-md-3 control-label" title="Le numéro RC doit contenir au moins 12 caractères"> Numéro RCCM* : </label>
            <div   class="col-sm-12 col-md-6"> <input style="text-transform:uppercase" maxlength="25" type="text" name="numero" id="numero" class="form-control" placeholder="Numéro RC du registre (Exemples:BFOUA2016B00001 ou BFOUA012022B1000001)" value="<?php echo $data["numero"]; ?>" /></div>        
            <div   class="col-sm-12 col-md-3" id="numRcSearching"> </div>
			<input type="hidden" name="validnumrc" id="validnumrc" value="1" />
	    </div>       
        <div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Nom commercial* : </label>
			<div   class="col-sm-12 col-md-6"> <input type="text" name="libelle" id="libelle" class="form-control" placeholder="Nom commercial ou dénomination sociale" value="<?php echo $data["libelle"]; ?>" /></div>        
			<div   class="col-sm-12 col-md-3" id="libRcSearching"> </div>
	    </div>
		<div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Numéro IFU: </label>
           <div   class="col-sm-12  col-md-9"> <input type="text" name="numifu" id="numifu" class="form-control" placeholder="Numéro IFU" value="<?php echo $data["numifu"]; ?>" /></div>        
	    </div>
		<div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Numéro CNSS: </label>
           <div   class="col-sm-12  col-md-9"> <input type="text" name="numcnss" id="numcnss" class="form-control" placeholder="Numéro CNSS" value="<?php echo $data["numcnss"]; ?>" /></div>        
	    </div>
        <?php if(!$me->isGREFFIERS()): ?>
        <div class="form-group"> 
            <label class="col-sm-12 col-md-3 control-label"> Localité*: </label>
            <div   class="col-sm-12 col-md-9"> <?php echo $this->formSelect("localiteid", intval( $data["localiteid"]  ), array("class"=>"form-control chosen"), $localites); ?> </div>   
        </div>
        <?php else: ?> 
        <input type="hidden" name="localiteid"  id="localiteid" value="<?php echo intval($data['localiteid']); ?>" />
        <?php endif; ?>          
        <div class="form-group">    
            <label class="col-sm-12 col-md-3 control-label"> Date du RCCM*: </label>
            <div   class="col-sm-12 col-md-9">
				<div class = "input-group">
					<?php echo $this->formSelect("date_day"  , $data["date_day"]  , array("class" => "form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?> 
					<span class="input-group-btn" style="width:0px;"></span>
					<?php echo $this->formSelect('date_month', $data["date_month"], array("class" => "form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?>
					<span class="input-group-btn" style="width:0px;"></span>
					<?php echo $this->formSelect('date_year' , $data["date_year"] , array("class" => "form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1960, intval(date("Y")) ) );?>             
				</div>
			</div>
	    </div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Secteur d'activité : </label>
			<div   class="col-sm-12 col-md-9"> <?php echo $this->formSelect("domaineid", intval( $data["domaineid"]), array("class" => "form-control chosen"), $domaines ); ?> </div>       
		</div>
	    <div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Décrire l'activité : </label>
			<div   class="col-sm-12 col-md-9"> <input title="Décrire l'activité de la société en quelques mots (facultatif)" type="text" name="description" id="description" class="form-control" value="<?php echo $data["description"]; ?>" placeholder="Décrivez en quelques mots l'activité menée" /></div>       
		</div>
		 <!--<h3 class="content-box-header content-box-header-alt bg-default mrg10R mrg10L mrg10B">ETAPE 2 <small> Selection des documents indexés </small></h3>-->
		 
		<h3 class="content-box-header content-box-header-alt bg-default mrg10R mrg10L mrg10B">ETAPE 2 <small> Renseignements relatifs à la Personne Morale</small></h3>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Forme juridique* : </label>
			<div   class="col-sm-12 col-md-9"><?php echo $this->formSelect("formid", $data["formid"], array("class" => "form-control"), $this->formes); ?></div>        
		</div>
		<div class="form-group"> 
			 <label class="col-sm-12 col-md-3 control-label"> Raison sociale: </label>
			<div   class="col-sm-12 col-md-9"> <input title="Saisir la raison sociale de la société (facultatif)" type="text" name="libelle2" id="libelle2" class="form-control" placeholder="Raison sociale" value="<?php echo $data["libelle"]; ?>" /></div>        
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Capital social: </label>
			<div   class="col-sm-12 col-md-9"> 
				<div class = "input-group">
					<input title="Saisir le capital social de la société (facultatif)" type="text" name="capital" id="capital" class="form-control" placeholder="Capital" value="<?php echo $data["capital"]; ?>" /> 
					<span class="input-group-addon"> F CFA</span>
				</div> 
			</div>        
	    </div>
		<div class="form-group">         
		   <label class="col-sm-12 col-md-3 control-label"> Immatriculation CNSS: </label>
		   <div   class="col-sm-12 col-md-9"> <input title="Saisir le numéro CNSS de la société (facultatif)" type="text" name="num_securite_social" id="num_securite_social" class="form-control" placeholder="Numéro d'imatriculation CNSS" value="<?php echo $data["num_securite_social"]; ?>" /> </div>        
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Adresse du siège*: </label>
			<div   class="col-sm-12 col-md-9"> <input title="Saisir l'adresse du siège de la société" type="text" name="address" id="address" class="form-control" value="<?php echo $data["address"]; ?>" placeholder="Adresse" /></div>       
		</div>     
		<div class="form-group"> 
		   <label class="col-sm-12 col-md-3 control-label"> Téléphone: </label>
		   <div   class="col-sm-4"><input title="Saisir le numéro de téléphone  de la société" type="text" name="phone1" id="phone1" class="form-control" placeholder="Téléphone fixe"   value="<?php echo $data["phone1"]; ?>" /> </div> 
		   <div   class="col-sm-4"><input title="Saisir un deuxième numéro de téléphone de la société (facultatif)" type="text" name="phone2" id="phone2" class="form-control" placeholder="Téléphone mobile" value="<?php echo $data["phone2"]; ?>" /> </div>        
		</div>
		<div class="form-group"> 
		   <label class="col-sm-12 col-md-3 control-label"> Adresse email: </label>
		   <div   class="col-sm-12 col-md-9"><input title="Saisir l'adresse email de la société (facultatif)" type="text" name="email" id="email" class="form-control" placeholder="Adresse email" value="<?php echo $data["email"]; ?>" /> </div>        
		</div>
		<div class="form-group"> 
		   <label class="col-sm-12 col-md-3 control-label"> Site web: </label>
		   <div   class="col-sm-12 col-md-9"><input title="Saisir l'adresse du site web de la société (facultatif)" type="text" name="siteweb" id="siteweb" class="form-control" placeholder="http://" value="<?php echo $data["siteweb"]; ?>" /> </div>        
		</div>
		<div class="form-group"> 
		   <label class="col-sm-12 col-md-3 control-label"> Code postal / Fax: </label>
		   <div   class="col-sm-12 col-md-5"><input title="Saisir le code postal de la société (facultatif)" type="text" name="zip" id="zip" class="form-control" placeholder="Code postal" value="<?php echo $data["zip"]; ?>" /> </div> 
		   <div   class="col-sm-12 col-md-4"><input title="Saisir le numéro fax de la société (facultatif)" type="text" name="fax" id="fax" class="form-control" placeholder="Fax" value="<?php echo $data["fax"]; ?>" /> </div>        
		</div>                 
        <h3 class="content-box-header content-box-header-alt bg-default mrg10R mrg10L mrg10B">ETAPE 3 <small> Les gérants et ou associés </small></h3>
		<?php
			   $dirigeantsOutput =  "";
			   $i                = 1;
			   if( count(   $dirigeants )) {			   
				   foreach( $dirigeants as $dirigeant ) {
							if( empty($dirigeant["nom"]) && $dirigeant["prenom"]) {
								continue;
							}
							$representantid   = $dirigeant["representantid"];				
							$dirigeantsOutput.="<div id=\"dirigeantFormGroup-".$i."\" class=\"form-group\"> ";
											 $dirigeantsOutput.=" <label class=\"col-sm-1 control-label\"> <span title=\"Supprimer ce dirigeant\" id=\"closeId-".$i."\" class=\"glyph-icon icon-remove removeLine\">&nbsp;</span> ".sprintf("Gérant %d ", $i)." </label>";
											 $dirigeantsOutput.=" <div   class=\"col-sm-4\"> 
																	<div class =\"input-group\">";
											 $dirigeantsOutput.="      <input type=\"text\" name=\"dirigeants_nom{$i}\"           id=\"dirigeants_nom{$i}\"           class=\"form-control\" title=\"Saisir le nom du dirigeant\"    placeholder=\"Nom\"    value=\"".$dirigeant["nom"]."\"/> <span class=\"input-group-btn\"    style=\"width:0px;\"></span>";						
											 $dirigeantsOutput.="      <input type=\"text\" name=\"dirigeants_prenom{$i}\"        id=\"dirigeants_prenom{$i}\"        class=\"form-control\" title=\"Saisir le prénom du dirigeant\" placeholder=\"Prénom\" value=\"".$dirigeant["prenom"]."\"/> <span class=\"input-group-btn\" style=\"width:0px;\"></span>";	
											 $dirigeantsOutput.="      <input type=\"text\" name=\"dirigeants_profession{$i}\"    id=\"dirigeants_profession{$i}\"    class=\"form-control\" title=\"Saisir la profession ou la fonction du dirigeant\"    placeholder=\"Profession\" value=\"".$dirigeant["fonction"]."\"/> <span class=\"input-group-btn\" style=\"width:0px;\"></span>";	
											 $dirigeantsOutput.="      <input type=\"text\" name=\"dirigeants_lieunaissance{$i}\" id=\"dirigeants_lieunaissance{$i}\" class=\"form-control\" title=\"Saisir le lieu de naissance du dirigeant\" placeholder=\"Lieu de naissance\" value=\"".$dirigeant["lieunaissance"]."\"/> <span class=\"input-group-btn\" style=\"width:0px;\"></span>";	
											 $dirigeantsOutput.="   </div>
																  </div>";
											
											 $dirigeantsOutput.=" <div   class=\"col-sm-7\"> 
																	<div class =\"input-group\">";
											 $dirigeantsOutput.="      <span class=\"input-group-addon bg-primary\"> Sexe: </span>";	
											 $dirigeantsOutput.="      <span class=\"input-group-addon\"> <input ".(($dirigeant['sexe'] == 'M') ? 'checked=\'checked\'' : '')." type=\"radio\" name=\"dirigeants_sexe{$i}\" id=\"sexe-m{$i}\" value=\"M\"> M </span> ";										 
											 $dirigeantsOutput.="      <span class=\"input-group-addon\"> <input ".(($dirigeant['sexe'] == 'F') ? 'checked=\'checked\'' : '')." type=\"radio\" name=\"dirigeants_sexe{$i}\" id=\"sexe-f{$i}\" value=\"F\"> F </span> ";
											 $dirigeantsOutput.="      <span class=\"input-group-addon bg-primary\"> Date nais. </span> <span class=\"input-group-btn\" style=\"width:0px;\"></span>";	
											 $dirigeantsOutput.="     ".$this->formSelect("dirigeants_date_naissance_day".$i  , $dirigeant['date_naissance_day']  , array("class" => "form-control chosen"),array("00"=>"Jour")+createDatesArray())." <span class=\"input-group-btn\" style=\"width:0px;\"></span>";
											 $dirigeantsOutput.="     ".$this->formSelect("dirigeants_date_naissance_month".$i, $dirigeant['date_naissance_month'], array("class" => "form-control chosen"),array(0 =>"Mois")+$this->months())." <span class=\"input-group-btn\" style=\"width:0px;\"></span>";
											 $dirigeantsOutput.="     ".$this->formSelect("dirigeants_date_naissance_year".$i , $dirigeant['date_naissance_year']  , array("class" => "form-control chosen")  ,array(0 =>"Année")+createYearsArray(1900, intval(date("Y"))));
											 $dirigeantsOutput.="     <input type=\"hidden\" name=\"dirigeants[]\"    id=\"dirigeants_".$i."\"    value=\"".$i."\" />";
											 $dirigeantsOutput.="     <input type=\"hidden\" name=\"representants[]\" id=\"representants_".$i."\" value=\"".$representantid."\" />";
											 $dirigeantsOutput.="   </div>
																  </div>";
							$dirigeantsOutput.="</div>";
							$i++;
				   }
			   }
			   for( $j=1;$j<=2;$j++ ) {
					$key   = $i;
					$dirigeantsOutput.="<div id=\"dirigeantFormGroup-".$key."\" class=\"form-group\"> ";
											 $dirigeantsOutput.=" <label class=\"col-sm-1 control-label\"> <span title=\"Supprimer ce dirigeant\" id=\"closeId-".$key."\" class=\"glyph-icon icon-remove removeLine\">&nbsp;</span>".sprintf("Gérant %d ", $key)." </label>";
											 $dirigeantsOutput.=" <div   class=\"col-sm-4\"> 
																	<div class =\"input-group\">";
											 $dirigeantsOutput.="      <input type=\"text\" title=\"Saisir le nom de famille du dirigeant\" name=\"dirigeants_nom{$key}\"           id=\"dirigeants_nom{$key}\"           class=\"form-control\" placeholder=\"Nom\"        /> <span class=\"input-group-btn\"    style=\"width:0px;\"></span>";						
											 $dirigeantsOutput.="      <input type=\"text\" title=\"Saisir le prénom du dirigeant\" name=\"dirigeants_prenom{$key}\"        id=\"dirigeants_prenom{$key}\"        class=\"form-control\" placeholder=\"Prénom\"     /> <span class=\"input-group-btn\" style=\"width:0px;\"></span>";	
											 $dirigeantsOutput.="      <input type=\"text\" title=\"Saisir la profession ou la fonction du dirigeant\" name=\"dirigeants_profession{$key}\"    id=\"dirigeants_profession{$key}\"    class=\"form-control\" placeholder=\"Profession\" /> <span class=\"input-group-btn\" style=\"width:0px;\"></span>";	
											 $dirigeantsOutput.="      <input type=\"text\" title=\"Saisir le lieu de naissance du dirigeant\" name=\"dirigeants_lieunaissance{$key}\" id=\"dirigeants_lieunaissance{$key}\" class=\"form-control\" placeholder=\"Lieu de naissance\" /> <span class=\"input-group-btn\" style=\"width:0px;\"></span>";	
											 $dirigeantsOutput.="   </div>
																  </div>";										
											 $dirigeantsOutput.=" <div   class=\"col-sm-7\"> 
																	<div class =\"input-group\">";
											 $dirigeantsOutput.="      <span class=\"input-group-addon bg-primary\"> Sexe: </span>";	
											 $dirigeantsOutput.="      <span class=\"input-group-addon\"> <input  type=\"radio\" name=\"dirigeants_sexe{$key}\" id=\"sexe-m{$key}\" value=\"M\"> M </span> ";										 
											 $dirigeantsOutput.="      <span class=\"input-group-addon\"> <input  type=\"radio\" name=\"dirigeants_sexe{$key}\" id=\"sexe-f{$key}\" value=\"F\"> F </span> ";
											 $dirigeantsOutput.="      <span class=\"input-group-addon bg-primary\"> Date nais. </span> <span class=\"input-group-btn\" style=\"width:0px;\"></span>";	
											 $dirigeantsOutput.="     ".$this->formSelect("dirigeants_date_naissance_day".$key  , null, array("class" => "form-control chosen"),array("00"=>"Jour")+createDatesArray())." <span class=\"input-group-btn\" style=\"width:0px;\"></span>";
											 $dirigeantsOutput.="     ".$this->formSelect("dirigeants_date_naissance_month".$key, null, array("class" => "form-control chosen"),array(0 =>"Mois")+$this->months())." <span class=\"input-group-btn\" style=\"width:0px;\"></span>";
											 $dirigeantsOutput.="     ".$this->formSelect("dirigeants_date_naissance_year".$key , null, array("class" => "form-control chosen"),array(0 =>"Année")+createYearsArray(1900, intval(date("Y"))));
											 $dirigeantsOutput.="     <input type=\"hidden\" name=\"dirigeants[]\"    id=\"dirigeants_".$key."\"    value=\"".$key."\" />";
											 $dirigeantsOutput.="     <input type=\"hidden\" name=\"representants[]\" id=\"representants_".$key."\" value=\"0\" />";
											 $dirigeantsOutput.="   </div>
																  </div>";
					$dirigeantsOutput.="</div>";
					$i++;			    
			   }
			   
			   echo $dirigeantsOutput;
		?>
    <div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Indexation automatique: </label>
           <div   class="col-sm-12 col-md-9" style="height:32px;"> <input type="checkbox" data-on-color="primary" name="find_documents" class="input-switch" data-size="medium" data-on-text="Oui" data-off-text="Non" <?php echo (intval($data["find_documents"]) == 1) ? 'checked' : ''; ?> value="1"></div>
      </div>
	  <div class="form-group"> 
           <label class="col-sm-12 col-md-3 control-label"> Contrôle de la qualité: </label>
           <div   class="col-sm-12 col-md-9" style="height:32px;"> <input type="checkbox" data-on-color="primary" name="check_documents" class="input-switch" data-size="medium" data-on-text="Oui" data-off-text="Non" <?php echo (intval($data["check_documents"]) == 1) ? 'checked' : ''; ?> value="1"></div>
      </div>
	  <div id="findDocumentsOptions" class="form-group <?php echo (intval($data["find_documents"])==0) ? 'hide' :''; ?> "> 
	    <label class="col-sm-12 col-md-3 control-label"> Dossier source*: </label>
		<div   class="col-sm-12 col-md-9"> <input type="text" name="find_documents_src" id="find_documents_src" class="form-control" placeholder="Dossier source de stockage des documents" value="<?php echo $data["find_documents_src"]; ?>" /></div> 
	  </div>
	  <div class="form-group manualFindDocuments <?php echo (intval($data["find_documents"])==1) ? 'hide' :''; ?> "> 
           <label class="col-sm-12 col-md-3 control-label"> Le formulaire * : </label>
           <div   class="col-sm-12 col-md-9"> <input type="file" name="docmini" id="docmini"    /></div>        
     </div>	
     <div class="form-group manualFindDocuments <?php echo (intval($data["find_documents"])==1) ? 'hide' :''; ?>"> 
           <label class="col-sm-12 col-md-3 control-label"> Le fond de dossier* : </label>
           <div   class="col-sm-12 col-md-9"> <input type="file" name="docoriginal"  id="docoriginal"  /></div>        
     </div> 
     <div class="form-group manualFindDocuments <?php echo (intval($data["find_documents"])==1) ? 'hide' :''; ?>"> 
           <label class="col-sm-12 col-md-3 control-label"> Le statut* : </label>
           <div   class="col-sm-12 col-md-9"> <input type="file" name="docstatut"  id="docstatut"  /></div>        
     </div>		
    </form>
 
    <?php 
    $buttonsbar  = $this->Btnbar(array("class" => "button-pane") , $this->jqueryHandler());
    $toolCreate  = $buttonsbar->button("Mettre à jour","save")->setPriority("primary");
    $toolCancel  = $buttonsbar->button("Annuler","chevron-left");
     
    $toolCreate->setAttributes(array("type" => "submit", "class" => "btn btn-success"));
    $toolCancel->setAttributes(array("type" => "submit"));
    
	$buttonsbar->add($toolCancel ,"cancelCreationButton");
    $buttonsbar->add($toolCreate ,"editButton");
       
    if( !$this->isAjax )
        echo $buttonsbar;
    ?>
</div>

<?php     
  

   if( $this->isAjax) {
   	   echo $this->jQuery();
   }
   
   ?>