<?php
    $tplPath       = VIEW_BASE_PATH;
    $demandes      = $this->demandes;
    $filters       = $this->filters;
    $paginator     = $this->paginator;
    $linkSearch    = $this->url(array("controller"=>"requetes","action"=>"list","module"=>"public"), "default", true);
	$linkCreate    = $this->url(array("controller"=>"requetes","action"=>"verify","module"=>"public"),"default", true);
	$linkCancel    = $this->url(array("controller"=>"members","action"=>"dashboard","module"=>"public"),"default", true);

    $statuts       = $this->statuts;
    if( null != $paginator ) {
  	  //On crée et affiche la pagination
  	  $pagination  = $this->pagination(array(),"Elastic",$this->url(array("controller"=>"demandes","action"=>"list","module"=>"public"),"default"), array(), array("class" => "panel-footer paginationControl"));
  	  
    }
    $jq         = $this->jQuery();
    $onLoad     = "
        jQuery('.sirahPaginationBtn').click(function(event){
			event.preventDefault();
			if( jQuery(this).is('.active') || jQuery(this).is('.disabled') || jQuery(this).is('.currentBtn')) { return false;}
			var formSelector       = jQuery('#globalFormSearch');
			var pageNum            = parseInt(jQuery(this).attr('id').replace('paginationBtnPage-' , ''));
			var pageMaxitems       = formSelector.find('#maxitems').val();
			if( jQuery(this).is('.nextPage')) {
				var currentBtnNum  = parseInt(jQuery('.currentBtn').first().attr('id').replace('paginationBtnPage-' , ''));
				pageNum            = parseInt( currentBtnNum +1);
			}
			if( jQuery(this).is('.prevPage')) {var currentBtnNum = parseInt(jQuery('.currentBtn').first().attr('id').replace('paginationBtnPage-', ''));pageNum =parseInt( currentBtnNum - 1);}
			var paginationData     = {};
			paginationData.maxitems= pageMaxitems;
			paginationData.page    = pageNum;
			paginationData.searchQ = formSelector.find('#searchQ').val();
			paginationData.statutid= parseInt(formSelector.find('#statutid').val());   
			var maincontent	       = jQuery('#maincontent');
			SIRAH.loading.on( maincontent , 'Chargement des données...' );
			SIRAH.request.post('maincontent','".$linkSearch."', {dataType:'html',data:paginationData,beforeSend:function(){},
							   error  : function(data){maincontent.html(data).after(data);SIRAH.loading.off(false);},
							   success: function(data){maincontent.html(data);SIRAH.loading.off(false);},
							   update : function(data){maincontent.html(data);SIRAH.loading.off(false);}		
			});
			SIRAH.loading.off(false);
		});
        jQuery('.simpleSearch,#simpleSearch').click(function( event ){
		    event.preventDefault();		            
		    var formSelector    = jQuery('#globalFormSearch'); 
		    var searchData      = {};
		    searchData.searchQ  = formSelector.find('#searchQ').val();
		    searchData.statutid = parseInt(formSelector.find('#statutid').val());
		    var maincontent	    = jQuery('#maincontent');	
		    SIRAH.loading.on( maincontent , 'Chargement des données...' );
		    SIRAH.request.post('maincontent','".$linkSearch."', {dataType:'html',data:searchData,beforeSend:function(){},
							  error  : function(data){maincontent.html(data);SIRAH.loading.off(false);},
							  success: function(data){maincontent.html(data);SIRAH.loading.off(false);},
							  update : function(data){maincontent.html(data);SIRAH.loading.off(false);}		
		    });
		    SIRAH.loading.off(false);		                
		});
        jQuery('.resetSearchBtn,#resetSearchBtn').click(function( event ){ event.preventDefault(); document.location.href='".$linkSearch."'; });";
   
   $jq->addOnLoad( $onLoad );
   
   $buttonBar    = $buttonbar  = $this->buttonsbar(array()  , $this->jqueryHandler());
   $buttonCreate = $buttonBar->button("Nouvelle réservation","plus");
   $buttonCancel = $buttonBar->button("Revenir sur mon tableau de bord","chevron-left");
   
   $buttonBar->add($buttonCancel, "cancelButton");
   $buttonBar->add($buttonCreate, "createButton");
   
   $buttonCreate->setAttributes(array("type"=>"submit", "class"=>"btn btn-danger"));
   $buttonCancel->setAttributes(array("type"=>"submit"));
   
   $buttonCreate->onClick(sprintf("event.preventDefault(); document.location.href='%s';", $linkCreate));
   $buttonCancel->onClick(sprintf("event.preventDefault(); document.location.href='%s';", $linkCancel));
?>
<div class="row buttons mrg20B mrg5L"><?php echo $buttonBar; ?></div>
<div id="panelListWrapper" class="row">
    <div  class="panel panel-default listPanel">
	    <div  class="panel-heading bg-green">
		    <form class="form-horizontal globalFormSearch" id="globalFormSearch" method="post" action="<?php echo $linkSearch; ?>" >
		        <div class="input-group">
				    <span class="input-group-btn selectBtn"> <?php echo $this->formSelect("statutid", intval($filters["statutid"]),array("class" => "form-control input-lg"), $this->statuts); ?></span>
					<input value="<?php echo $filters['searchQ']; ?>" id="searchQ" name="searchQ" type="text" class="form-control input-lg" placeholder="Recherchez une demande, saisir des mots clés...">
					<span class="input-group-btn ">
					   <button id="simpleSearch"   class="btn btn-lg btn-primary simpleSearch"    type="button"><span class="glyph-icon icon-search"></span> </button>
					   <button id="resetSearchBtn" class="btn btn-lg btn-danger  resetSearchBtn"  type="button"><span class="glyph-icon icon-remove"></span> </button>
					</span>
				</div>
				<input type="hidden" name="page"     id="page"     value="<?php echo $this->pageNum; ?>" /> 
				<input type="hidden" name="maxitems" id="maxitems" value="<?php echo $this->pageSize;?>" />
			</form>
		</div>
        <table class="table table-hover table-striped sirah-ui-table scrollable demandesListTable" id="demandesListTable" style="width:100%">
			<thead>
				<th width="13%"> Dates        </th>
				<th width="15%"> Juridictions </th>
                <th width="32%"> Objets       </th> 								 										
				<th width="20%"> Promoteurs   </th>
                <th width="20%"> Statuts      </th>				
			</thead>
			<?php
				$output        = "";
				if( count(   $demandes ) ) {
					foreach( $demandes as $demande ) {
							 $demandeid        = $demande["demandeid"];
							 $demandeTypeId    = $demande["typeid"];
							 $demandeLibelle   = $demande["libelle"];
							 $demandeLocalite  = $demande["localite"];
                             $promoteurName    = (isset($demande["promoteur"]) && !empty($demande["promoteur"]))?$demande["promoteur"] : ((isset($demande["promoteurName"]))?$demande["promoteurName"] : "");
							 $demandeType      = $demande["type"];
							 $demandeStatut    = $demande["statut"];
							 $zendDate         = (intval($demande['date']))?new Zend_Date($demande['date'],Zend_Date::TIMESTAMP) : null;
							 $dateDemande      = ( $zendDate )? $zendDate->toString("dd MMMM yyyy") : null;
							 $badgeHTML        = "<span ".$statutColor." title=\"".$demandeStatut."\" class=\"bs-badge badge-absolute float-right badge-danger\"> <i class=\"fa fa-asterisk\"> </i> ".$demandeStatut." </span>";
                             $bgColor          = "";
							 
							 if( intval($demande["disponible"]) == 1) {
								 $bgColor      = "alert success validated";
								 $badgeHTML    = "<span title=\"".$demandeStatut."...\" class=\"bs-badge badge-absolute float-right badge-success\"><i class=\"fa fa-asterisk\"></i>".$demandeStatut."</span>";
							 } else {
								 $bgColor      = "alert danger unvalidated";
								 $badgeHTML    = "<span title=\"".$demandeStatut."...\" class=\"bs-badge badge-absolute float-right badge-danger\"> <i class=\"fa fa-asterisk\"></i>".$demandeStatut."</span>";
							 }
							 if( intval($demande["expired"]) == 1) {
								 $bgColor      = "alert danger expired";
								 $badgeHTML    = "<span title=\"Ce dossier a dépassé le délai de traitement requis\" class=\"bs-badge badge-absolute float-right badge-warning\"> <i class=\"fa fa-asterisk\"> </i>  Demande expirée</span>";
							 }
							 $linkInfos        = $this->url(array("module"=>"public","controller"=>"requetes","action"=>"infos","id"=>$demandeid,"demandeid"=>$demandeid), "default",true);
							 $output          .= "<tr class=\"".$bgColor."\" id=\"demandeRowId-".$demandeid."\">";
								    $output   .= "    <td class=\"".$bgColor."\" width=\"13%\"><a href=\"".$linkInfos."\" title=\"Consulter les informations de cette demande\"> ".$dateDemande    ." </a></td>";	
								    $output   .= "    <td class=\"".$bgColor."\" width=\"15%\"><a href=\"".$linkInfos."\" title=\"Consulter les informations de cette demande\"> ".$demandeLocalite." </a> </td>";											
								    $output   .= "    <td class=\"".$bgColor."\" width=\"32%\"><a href=\"".$linkInfos."\" title=\"Consulter les informations de cette demande\"> ".$demandeLibelle ." </a></td>";
								    $output   .= "    <td class=\"".$bgColor."\" width=\"15%\"><a href=\"".$linkInfos."\" title=\"Consulter les informations de cette demande\"> ".$promoteurName  ." </a></td>";											
								    $output   .= "    <td class=\"".$bgColor."\" width=\"20%\"><a href=\"".$linkInfos."\" title=\"Consulter les informations de cette demande\"> ".$demandeStatut  ." </a></td>";
							 $output          .=" </tr>";
					}
				} else {
							 $output .="<tr><td style=\"text-align:center !important;\" align=\"center\" colspan=\"5\"> AUCUNE DEMANDE N'A ETE TROUVEE </td></tr>";
				}
				echo $output;
			?>
		</table>
		<div align="center" style="text-align:center !important" class="panel-footer"><?php  echo $pagination->render(); ?></div>
    </div>
</div>
 

<?php 
if( $this->isAjax ) {
	echo $this->jQuery();
	echo $this->headStyle();
}

?>

