<?php 
$captcha                    = $this->captcha;
$messages                   = $this->messages;
$token                      = $this->token;
$tokenId                    = $this->csrfTokenId;
$tokenValue                 = $this->csrfTokenValue;
$data                       = $this->data;
$identityData               = $this->identitydata;
$demandeurid                = $this->demandeurid;
$formNames                  = $fn = $this->formNames;
$defaultCountry             = (isset($data["country"]) && !empty($data["country"])) ? $data["country"] : "BF";

$urlCreationDone            = Sirah_Functions::url($this->url(array("module"=>"public","controller"=>"members","action"=>"dashboard","module"=>"public"),"default",true),"" , 81 , APPLICATION_HOST);
$formSubmit                 = $this->url(array("module"=>"public","controller"=>"requetes","action"=>"reservation"),"default",true);
$linkCancel                 = $this->url(array("module"=>"public","controller"=>"index"   ,"action"=>"index") ,"default",true);
$linkCheckUsername          = $this->url(array("module"=>"public","controller"=>"ajaxres" ,"action"=>"checkusername",$tokenId=>$tokenValue),"default",true);
$linkCheckEmail             = $this->url(array("module"=>"public","controller"=>"ajaxres" ,"action"=>"checkemail",$tokenId=>$tokenValue),"default",true);
$linkFormes                 = $this->url(array("module"=>"public","controller"=>"ajaxres" ,"action"=>"entrepriseformes"),"default",true);
if( isset($identityData["date_etablissement"]) && Zend_Date::isDate($identityData["date_etablissement"],"YYYY-MM-dd")) {
	$dateEtablissementArr   = explode("-", $identityData["date_etablissement"]);
	$dateEtablissementYear  = (isset($dateEtablissementArr[0]))?$dateEtablissementArr[0] : 0;
    $dateEtablissementMonth = (isset($dateEtablissementArr[1]))?$dateEtablissementArr[1] : 0;
    $dateEtablissementDay   = (isset($dateEtablissementArr[2]))?$dateEtablissementArr[2] : 0;

}
$civilites                  = array("0"=>"Civilité","Mr"=>"Monsieur","Mme"=>"Madame","Mle"=>"Mademoiselle","Excellence"=>"Son excellence","Maître"=>"Maître","Dr"=>"Docteur","Pr"=>"Professeur");
$situations                 = array("Célibataire"=>"Célibataire","Marié(e)"=> "Marié(e)","Divorcé(e)"=>"Divorcé(e)","Veuf(ve)"=>"Veuf(ve)");
$registerDoneUri            = $this->registerDoneUri;
$basePath                   = ROOT_PATH ."/myTpl/public/";
?>
<?php $this->headStyle()->captureStart() ?>
<?php $this->headStyle()->captureEnd()   ?>
<?php
$jq     = $this->jQuery();  
$onLoad = " 
jQuery('.chosen').chosen({   allow_single_deselect:true,no_results_text:'Aucun élement ne correspond à ', width:'100%'});
jQuery('#formid').chosen({   allow_single_deselect:true,no_results_text:'Aucune forme juridique ne correspond à ', width:'100%'});
jQuery('#domaineid').chosen({allow_single_deselect:true,no_results_text:'Aucun secteur d\'activité ne correspond à ', width:'100%'});
jQuery('#personne_physique').click(function( event){
	jQuery.ajax({ data:{'typeid':1,'type':'EI'},async:false,url:'".$linkFormes."',type:'GET',dataType:'json',beforeSend:function(){},error:function(data){SIRAH.error.raise(formSelector, data, 'error');return data;},
		success:function(data){
			if(!SIRAH.util.isEmpty(data.error)){
				return data;
			} else {
				jQuery('#formid').each(function(){jQuery(this).dynamicSelect('update', data ).trigger('chosen:updated');});
			}
		}
	});
});
jQuery('#personne_morale').click(function( event){
	jQuery.ajax({ data:{'typeid':2,'type':'ES'},async:false,url:'".$linkFormes."',type:'GET',dataType:'json',beforeSend:function(){},error:function(data){SIRAH.error.raise(formSelector, data, 'error');return data;},
		success:function(data){
			if(!SIRAH.util.isEmpty(data.error)){
				return data;
			} else {
				jQuery('#formid').each(function(){jQuery(this).dynamicSelect('update', data ).trigger('chosen:updated');});
			}
		}
	});
});
jQuery('#createButton').click(function(e){
	e.preventDefault();
	var formSelector    = jQuery('#createReservationForm');
	var firstname       = jQuery.trim(formSelector.find('#firstname').val());
    var lastname        = jQuery.trim(formSelector.find('#lastname').val());
    var telephone       = jQuery.trim(formSelector.find('#telephone').val());
	var identiteNumero  = jQuery.trim(formSelector.find('#numidentite').val());
	var activiteLibelle = jQuery.trim(formSelector.find('#activite').val());
	var domaineid       = parseInt(formSelector.find('#domaineid').val());
	var formid          = parseInt(formSelector.find('#formid').val());
	var localiteid      = parseInt(formSelector.find('#localiteid').val());
	var organismePiece  = jQuery.trim(formSelector.find('#organisme_etablissement').val());
	var lieuPiece       = jQuery.trim(formSelector.find('#organisme_etablissement').val());
      
	if( SIRAH.util.isEmpty(identiteNumero)){
        formSelector.find('#numidentite').addClass('input-error');
        formSelector.find('#numero-validation-message').html('');
        SIRAH.error.raise('numero-validation-message','Entrez le numéro de la pièce d\'identite du promoteur');
        return;
    } else {
        formSelector.find('#numidentite').removeClass('input-error');
        formSelector.find('#numero-validation-message').html('');
    }
	if( SIRAH.util.isEmpty(organismePiece)){
        formSelector.find('#organisme_etablissement').addClass('input-error');
        formSelector.find('#organisme_etablissement-validation-message').html('');
        SIRAH.error.raise('organisme_etablissement-validation-message','Entrez l\'organisme d\'établissement de la pièce d\'identite du promoteur');
        return;
    } else {
        formSelector.find('#organisme_etablissement').removeClass('input-error');
        formSelector.find('#organisme_etablissement-validation-message').html('');
    }
	if( SIRAH.util.isEmpty(lieuPiece)){
        formSelector.find('#lieu_etablissement').addClass('input-error');
        formSelector.find('#lieu_etablissement-validation-message').html('');
        SIRAH.error.raise('lieu_etablissement-validation-message','Entrez le lieu d\'établissement de la pièce d\'identite du promoteur');
        return;
    } else {
        formSelector.find('#lieu_etablissement').removeClass('input-error');
        formSelector.find('#lieu_etablissement-validation-message').html('');
    }
    if( SIRAH.util.isEmpty(lastname)){
        formSelector.find('#lastname').addClass('input-error');
        formSelector.find('#name-validation-message').html('');
        SIRAH.error.raise('name-validation-message','Entrez un nom de famille valide du promoteur');
        return;
    } else {
        formSelector.find('#lastname').removeClass('input-error');
        formSelector.find('#name-validation-message').html('');
    }
    if( SIRAH.util.isEmpty(firstname)){
        formSelector.find('#firstname').addClass('input-error');
        formSelector.find('#name-validation-message').html('');
        SIRAH.error.raise('name-validation-message','Entrez un prénom valide du promoteur');
        return;
    }  else {
        formSelector.find('#firstname').removeClass('input-error');
        formSelector.find('#name-validation-message').html('');
    }    
    if( SIRAH.util.isEmpty(telephone)){
        formSelector.find('#telephone').addClass('input-error');
        formSelector.find('#phone-validation-message').html('');
        SIRAH.error.raise('phone-validation-message','Entrez un numéro de téléphone valide du promoteur');
        return;
    }  else {
        formSelector.find('#telephone').removeClass('input-error');
        formSelector.find('#phone-validation-message').html('');
    }
	if( SIRAH.util.isEmpty(activite)){
        formSelector.find('#activite').addClass('input-error');
        formSelector.find('#activite-validation-message').html('');
        SIRAH.error.raise('activite-validation-message','Saisissez une activité déclarée par le promoteur');
        return;
    } else {
        formSelector.find('#activite').removeClass('input-error');
        formSelector.find('#activite-validation-message').html('');
    }
    if(!localiteid){
        formSelector.find('#localiteid').addClass('input-error');
        formSelector.find('#localite-validation-message').html('');
        SIRAH.error.raise('localite-validation-message','Sélectionnez une localité/juridiction valide');
        return;
    }  else {
        formSelector.find('#localiteid').removeClass('input-error');
        formSelector.find('#localite-validation-message').html('');
    }     
    if(!domaineid){
        formSelector.find('#domaineid').addClass('input-error');
        formSelector.find('#domaine-validation-message').html('');
        SIRAH.error.raise('domaine-validation-message','Sélectionnez un secteur d\'activités.');
        return;
    }  else {
        formSelector.find('#domaineid').removeClass('input-error');
        formSelector.find('#domaine-validation-message').html('');
    }
	if(!formid){
        formSelector.find('#formid').addClass('input-error');
        formSelector.find('#forme-validation-message').html('');
        SIRAH.error.raise('forme-validation-message','Sélectionnez une forme juridique.');
        return;
    }  else {
        formSelector.find('#formid').removeClass('input-error');
        formSelector.find('#forme-validation-message').html('');
    }
    formSelector.find('#lastname').val(lastname);
    formSelector.find('#firstname').val(firstname);
    formSelector.find('#telephone').val(telephone);
    formSelector.find('#domaineid').val(domaineid);
    formSelector.submit();
});
 jQuery('#cancelButton').click(function(e){e.preventDefault();document.location.href='".$linkCancel."';}); ";
$jq->addOnLoad($onLoad);
$jq->addStyleSheet(    $basePath ."/scripts/widgets/pickadate/themes/default.css");
$jq->addStyleSheet(    $basePath ."/scripts/widgets/pickadate/themes/default.date.css");
$jq->addStyleSheet(    $basePath ."/scripts/widgets/pickadate/themes/default.time.css");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/picker.js");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/picker.date.js");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/picker.time.js");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/translations/fr_FR.js");
$step               = 1;
$headScript         = $this->headScript();
//$headScript->appendFile("https://www.google.com/recaptcha/api.js","text/javascript");
?>
<form method="post" action="<?php echo $formSubmit; ?>" id="createReservationForm"  class="form-horizontal" role="form" >
    <div class="panel panel-info">
	    <?php if(!intval($demandeurid)): ?>
		<div class="panel-heading"> <h4 class="panel-title"> <span class="glyph-icon icon-typicons-vcard"></span><?php printf("%d.Les renseignements de votre pièce d'identité",$step);$step++; ?></h4></div>
		<ul class="list-group">
		    <li class="list-group-item">      
				<div class="form-group">    
					<label class="col-md-2  col-sm-12  control-label">Type pièce*:</label>
					<div   class="col-md-10 col-sm-12">
						<label class="radio-inline pull-left"><input type="radio" name="demandeur_identitetype" id="demandeur_identitetype-1" value="1" <?php if($identityData["typeid"]=="1") echo "checked"; ?>> CNIB     </label>          
						<label class="radio-inline pull-left"><input type="radio" name="demandeur_identitetype" id="demandeur_identitetype-2" value="2" <?php if($identityData["typeid"]=="2") echo "checked"; ?>> PASSPORT </label>
					    <label class="radio-inline pull-left"><input type="radio" name="demandeur_identitetype" id="demandeur_identitetype-3" value="3" <?php if($identityData["typeid"]=="3") echo "checked"; ?>> CARTE CONSULAIRE </label>
					    <label class="radio-inline pull-left"><input type="radio" name="demandeur_identitetype" id="demandeur_identitetype-4" value="4" <?php if($identityData["typeid"]=="4") echo "checked"; ?>> CARTE PROFESSIONNELLE </label>
					</div>
				</div>
			</li>
			<li class="list-group-item">  
				<div class="form-group">            
					<label class="col-sm-2  col-md-2 control-label"><b> Numéro*:</b> </label> 
					<div   class="col-sm-10 col-md-10">
						<div class="input-group"><input type="text" maxlength="250" class="form-control" title="Numéro de votre pièce d'identité" placeholder="Numéro de votre pièce d'identité" id="demandeur_numidentite" name="demandeur_numidentite" value="<?php echo $identityData["numero"];?>"> </div> 
					</div>					    
				</div>
                <p id="numero-validation-message" class="validation-message"></p>				
			</li>
			<li class="list-group-item">  
				<div class="form-group">            
					<label class="col-sm-2  col-md-2 control-label"><b> Organisme d'étalissement*:</b> </label> 
					<div   class="col-sm-10 col-md-10">
						<div class="input-group"><input id="demandeur_organisme_etablissement" type="text" maxlength="250" class="form-control" title="Organisme d'étalissement de votre pièce d'identité" placeholder="Organisme d'étalissement de votre pièce d'identité" name="demandeur_organisme_etablissement" value="<?php echo $identityData["organisme_etablissement"];?>"> </div> 
					</div>					    
				</div> 
				<p id="organisme_etablissement-validation-message" class="validation-message"></p>
			</li>
            <li class="list-group-item"> 			
				<div class="form-group">    
					<label class="col-sm-12 col-md-2 control-label"><b> Date & lieu d'étalissement*:</b> </label>   
					<div   class="col-sm-12 col-md-2"><?php echo $this->formSelect("demandeur_date_etablissement_day"  ,$dateEtablissementDay  , array("style"=> "width:260px !important;","class"=>"form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?></div> 
					<div   class="col-sm-12 col-md-2"><?php echo $this->formSelect('demandeur_date_etablissement_month',$dateEtablissementMonth, array("style"=> "width:260px !important;","class"=>"form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?></div> 
					<div   class="col-sm-12 col-md-2"><?php echo $this->formSelect('demandeur_date_etablissement_year' ,$dateEtablissementYear , array("style"=> "width:260px !important;","class"=>"form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1990, intval(date("Y")) ) );?></div>
					<div   class="col-sm-12 col-md-4"><input type="text" name="demandeur_lieu_etablissement" id="demandeur_lieu_etablissement" class="form-control" value="<?php echo $identityData["lieu_etablissement"]; ?>" placeholder="Lieu d'établissement de votre pièce d'identité" title="Lieu d'établissement de votre pièce" /></div>
				</div>
			    <p id="demandeur_lieu_etablissement-validation-message" class="validation-message"></p> 		
			</li>
		</ul>
		<?php else: ?>
		<input id="demandeurid" name="demandeurid" type="hidden" value="<?php echo $demandeurid; ?>" />
		<?php endif; ?>
		<div class="panel-heading"> <h4 class="panel-title"> <span class="glyph-icon icon-user"></span> <?php printf("%d.L'identité du promoteur/bénéficiaire",$step);$step++; ?></h4></div>
        <ul class="list-group">                             
			<li class="list-group-item">  
				<div class="form-group">            
					<label class="col-sm-2  col-md-2 control-label"><b> Nom et prénom(s)*:</b> </label> 
					<div   class="col-sm-10 col-md-10">
						<div class="input-group">
						    <?php echo $this->formSelect("civilite", $data["civilite"], array("class" => "form-control") , $civilites); ?>
							<span  class="input-group-btn" style="width:0px;"></span>
							<input id="lastname"  type="text" maxlength="150" class="form-control" title="Saisissez le nom de famille du promoteur" placeholder="Nom de famille du promoteur" name="lastname"  value="<?php echo $data['lastname'];?>">
							<span class="input-group-btn" style="width:0px;"></span>
							<input id="firstname" type="text" maxlength="300" class="form-control" title="Saisissez le(s) prénom(s) du promoteur"   placeholder="Prénom(s) du promoteur"      name="firstname" value="<?php echo $data['firstname'];?>">                                             
						</div> 
					</div>
					<p id="name-validation-message" class="validation-message"></p>    
				</div> 
			</li>
			<li class="list-group-item">
				<div class="form-group">            
					<label class="col-md-2  col-sm-2 control-label"> Téléphone*:</label> 
					<div   class="col-md-10 col-sm-10">
						<div class="input-group"><input id="telephone" name="telephone" type="text" maxlength="40" class="form-control" title="Numéro de téléphone du promoteur" placeholder="Numéro de téléphone du promoteur"  value="<?php echo $data['telephone']; ?>">	</div>					
					</div>					
				</div>	
                <p id="telephone-validation-message" class="validation-message"></p> 				
			</li>			 
			<li class="list-group-item">       
				<div class="form-group">
					<label class="col-md-2  col-sm-2 control-label"> Adresse*:</label>
					<div   class="col-md-10 col-sm-10"><input id="adresse" name="adresse" type="text" maxlength="200" title="Adresse du promoteur" placeholder="Adresse du promoteur" class="form-control" value="<?php echo $data['adresse']; ?>"></div> 
					<p id="adresse-validation-message" class="validation-message"></p> 
				</div>  
			</li> 
			<li class="list-group-item">       
				<div class="form-group">
					<label class="col-md-2  col-sm-2 control-label"> Profession*: </label>
					<div   class="col-md-10 col-sm-10"><input id="profession" name="profession" type="text" maxlength="220" title="Profession du promoteur" placeholder="Profession du promoteur" class="form-control" value="<?php echo $data['profession']; ?>"></div> 					
				</div>
                <p id="profession-validation-message" class="validation-message"></p> 				
			</li>		
			<li class="list-group-item">      
				<div class="form-group">    
					<label class="col-md-2  col-sm-2  control-label"> Sexe*: </label>
					<div   class="col-md-10 col-sm-10">
						<label class="radio-inline pull-left"><input class="custom-radio" type="radio" name="sexe" id="sexe-m" value="M" <?php if($data["sexe"]=="M") echo "checked"; ?>> Homme </label>          
						<label class="radio-inline pull-left"><input class="custom-radio" type="radio" name="sexe" id="sexe-f" value="F" <?php if($data["sexe"]=="F") echo "checked"; ?>> Femme </label>
					</div>
				</div>
			</li>
        </ul>
		<div class="panel-heading"> <h4 class="panel-title"> <span class="glyph-icon icon-user"></span> <?php printf("%d Les informations de la carte d'identité du promoteur/bénéficiaire",$step);$step++; ?></h4></div>
		<ul class="list-group">
		    <li class="list-group-item">      
				<div class="form-group">    
					<label class="col-md-2  col-sm-12  control-label">Type de pièce*:</label>
					<div   class="col-md-10 col-sm-12">
						<label class="radio-inline pull-left"><input class="custom-radio" type="radio" name="identitetype" id="identitetype-1" value="1" <?php if($identityData["typeid"]=="1") echo "checked"; ?>> CNIB     </label>          
						<label class="radio-inline pull-left"><input class="custom-radio" type="radio" name="identitetype" id="identitetype-2" value="2" <?php if($identityData["typeid"]=="2") echo "checked"; ?>> PASSPORT </label>
					    <label class="radio-inline pull-left"><input class="custom-radio" type="radio" name="identitetype" id="identitetype-3" value="3" <?php if($identityData["typeid"]=="3") echo "checked"; ?>> CARTE CONSULAIRE </label>
					    <label class="radio-inline pull-left"><input class="custom-radio" type="radio" name="identitetype" id="identitetype-4" value="4" <?php if($identityData["typeid"]=="4") echo "checked"; ?>> CARTE PROFESSIONNELLE </label>
					</div>
				</div>
			</li>
			<li class="list-group-item">  
				<div class="form-group">            
					<label class="col-sm-2  col-md-2 control-label"><b> Numéro*:</b> </label> 
					<div   class="col-sm-10 col-md-10">
						<div class="input-group"><input type="text" maxlength="100" class="form-control" title="Numéro de la pièce d'identité du promoteur" placeholder="Numéro de la pièce d'identité du promoteur" id="numidentite" name="numidentite" value="<?php echo $identityData['numero'];?>"> </div> 
					</div>					    
				</div>
                <p id="numero-validation-message" class="validation-message"></p>				
			</li>
			<li class="list-group-item">  
				<div class="form-group">            
					<label class="col-sm-2  col-md-2 control-label"><b> Organisme d'étalissement*:</b> </label> 
					<div   class="col-sm-10 col-md-10">
						<div class="input-group"><input id="organisme_etablissement" type="text" maxlength="150" class="form-control" title="Organisme d'étalissement de la pièce d'identité du promoteur" placeholder="Organisme d'étalissement de la pièce d'identité du promoteur" name="organisme_etablissement" value="<?php echo $identityData['organisme_etablissement'];?>"> </div> 
					</div>					    
				</div> 
				<p id="organisme_etablissement-validation-message" class="validation-message"></p>
			</li>
            <li class="list-group-item"> 			
				<div class="form-group">    
					<label class="col-sm-12 col-md-2 control-label"><b> Date & lieu d'étalissement*:</b> </label>   
                    <div   class="col-sm-12 col-md-2"><?php echo $this->formSelect("date_etablissement_day"  ,$dateEtablissementDay  , array("style"=> "width:260px !important;","class"=>"form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?></div> 
					<div   class="col-sm-12 col-md-2"><?php echo $this->formSelect('date_etablissement_month',$dateEtablissementMonth, array("style"=> "width:260px !important;","class"=>"form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?></div> 
			        <div   class="col-sm-12 col-md-2"><?php echo $this->formSelect('date_etablissement_year' ,$dateEtablissementYear , array("style"=> "width:260px !important;","class"=>"form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1990, intval(date("Y")) ) );?></div>
				    <div   class="col-sm-12 col-md-4"><input type="text" name="lieu_etablissement" id="lieu_etablissement" class="form-control" value="<?php echo $identityData["lieu_etablissement"]; ?>" placeholder="Lieu d'établissement du promoteur" title="Lieu d'établissement du promoteur" /></div>
				</div>
				
				
			    <p id="lieu_etablissement-validation-message" class="validation-message"></p> 		
			</li>
		</ul>
        <div class="panel-heading"><h4 class="panel-title"> <span class="glyph-icon icon-institution"></span> <?php printf("%d.Les informations de l'entreprise que vous comptez créer après la réservation.",$step);$step++; ?></h4></div>
        <ul class="list-group">
		    <li class="list-group-item">      
				<div class="form-group">    
					<label class="col-md-2  col-sm-2  control-label"> Catégorie*:</label>
					<div   class="col-md-10 col-sm-10">
						<label class="radio-inline pull-left"><input class="custom-radio" type="radio" name="personne_morale" id="personne_physique" value="0" <?php if($data["personne_morale"]=="0") echo "checked"; ?>> Personne Physique </label>          
						<label class="radio-inline pull-left"><input class="custom-radio" type="radio" name="personne_morale" id="personne_morale"   value="1" <?php if($data["personne_morale"]=="1") echo "checked"; ?>> Personne Morale   </label>
					</div>
				</div>
			</li>
			<li class="list-group-item">
			    <div class="form-group"> 
				   <label class="col-md-2  col-sm-2 control-label" for="formid">Forme juridique*:</label>
				   <div   class="col-md-10 col-sm-10"><?php echo $this->formSelect("formid", intval($data["formid"]), array("style"=> "width:460px !important;","class"=>"form-control chosen"), $this->formes); ?></div>        
			    </div>
				<p id="forme-validation-message" class="validation-message"></p>  
			</li>
			<li class="list-group-item">
			    <div class="form-group"> 
				   <label class="col-md-2  col-sm-2 control-label" for="localiteid">Juridiction/Localité*:</label>
				   <div   class="col-md-10 col-sm-10"><?php echo $this->formSelect("localiteid", intval($data["localiteid"]), array("style"=> "width:460px !important;","class"=>"form-control chosen"), $this->localites); ?></div>        
			    </div>
				<p id="localite-validation-message" class="validation-message"></p>  
			</li>
            <li class="list-group-item">
				<div class="form-group">
				    <label class="col-md-2  col-sm-2 control-label" for="nomcommercial">Nom commercial*:</label>
				    <div   class="col-md-10 col-sm-10">
				        <div class="input-group">
				            <input id="nomcommercial2" name="nomcommercial2" type="text" disabled="disabled" class="form-control" title="Nom commercial de l'entreprise cible" placeholder="Nom commercial de l'entreprise cible" value="<?php echo $data["nomcommercial"]; ?>">
					        <input id="nomcommercial"  name="nomcommercial"  value="<?php echo $data["keywords"]; ?>" type="hidden" />
							<input id="keywords"       name="keywords"       value="<?php echo $data["keywords"]; ?>" type="hidden" />
							<span class="input-group-btn" style="width:0px;"></span>
						   <input type="text" name="sigle" id="sigle" class="form-control" value="<?php echo $data["sigle"]; ?>" placeholder="Le sigle de l'entreprise" title="Le sigle de l'entreprise" />
						</div>
					</div> 			   				   
				</div>     
				<p id="nomcommercial-validation-message" class="validation-message"></p> 
			</li>
			<li class="list-group-item">
			    <div class="form-group"> 
				   <label class="col-md-2  col-sm-2 control-label" for="denomination"> Dénomination: </label>
				   <div   class="col-md-10 col-sm-10"><input title="Saisir la dénomination sociale de l'entreprise cible (facultatif)" type="text" name="denomination" id="denomination" class="form-control" placeholder="Dénomination sociale" value="<?php echo $data["denomination"]; ?>" /></div>        
			    </div>
			</li>			
			<li class="list-group-item">
			    <div class="form-group"> 
				    <label class="col-md-2  col-sm-2 control-label" for="domaineid"> Secteur activité*: </label>
				    <div   class="col-md-10 col-sm-10"> <?php echo $this->formSelect("domaineid", intval( $data["domaineid"]), array("style"=> "width:460px !important;","class"=>"form-control chosen"), $this->domaines ); ?> </div>       
			    </div>
				<p id="domaine-validation-message" class="validation-message"></p>  
			</li>
			<li class="list-group-item">
			    <div class="form-group"> 
				   <label class="col-md-2  col-sm-2 control-label" for="activite"> Activité déclarée*: </label>
				   <div   class="col-md-10 col-sm-10"> <input type="text" title="Décrire l'activité de l'entreprise en quelques mots" name="activite" id="activite" class="form-control" value="<?php echo $data["activite"]; ?>" placeholder="Saisissez les informations de l'activité déclarée par le promoteur" /></div>       
			    </div>
				<p id="activite-validation-message" class="validation-message"></p>  
			</li>
			<!--
			<li class="list-group-item">			     
				<div class="form-group">
				    <label class="col-md-2  col-sm-2 control-label" for="captcha">Captcha: </label>
				    <div   class="col-sm-12 col-md-10">
					    <div class="col-md-12 g-recaptcha" data-sitekey="<?php //echo API_GOOGLE_RECAPTCHA_SITE_KEY; ?>"></div>
					</div>
				</div>
			</li> -->
        </ul>	
		<div class="panel-footer">
			<div class="btn-group"><button id="cancelButton" class="btn btn-danger  cancelButton"><i class="glyph-icon icon-chevron-left"> </i>  Annuler </button></div> 
			<div class="btn-group"><button id="createButton" class="btn btn-primary createButton"> Demander la réservation <i class="glyph-icon icon-chevron-right"> </i> </button></div>	
		</div>
	</div>	 
</form>
