<?php
$entreprise          = $this->entreprise;
$linkEdit            = $this->url(array("module" => "admin","controller" => "entreprises", "action" => "edit", "id" => $entreprise->id ), "default");
$logo                = $entreprise->logo;  
$logoFile            = VIEW_BASE_PATH."/images/blank.png";
if( !empty( $logo ) ) {	
	$logoPathname    = str_replace( APPLICATION_PATH , ROOT_PATH . DS ."myV1", $logo );
	if( Sirah_Filesystem::exists( $logo ) ) {
		$logoFile    = str_replace( DS , "/" , $logoPathname );
	}	
}
$jq             = $this->jQuery();
$jq->addJavascriptFile( VIEW_BASE_PATH .'/js/typeahead/dist/typeahead.bundle.min.js');
$jq->addStyleSheet( VIEW_BASE_PATH ."/css/typeahead.css");
$onLoad         = " ";
$jq->addOnLoad($onLoad);

$jq->addStyleSheet( VIEW_BASE_PATH ."/css/userprofile.css");

$dateCreation = null;
if( empty( $entreprise->datecreation ) ) {
	$zendDateCreation = new Zend_Date( $entreprise->datecreation , Zend_Date::TIMESTAMP);
	$dateCreation     = $zendDateCreation->toString("dd MMMM yyyy");
}
$jq->addOnLoad("jQuery('#presentation').shorten({showChars:300}); ");
?>
<?php $this->headStyle()->captureStart() ?>
body{padding-top:1px !important;}
.only-left div.three-columns .col1 #sirah-page-content{width:800px !important; padding:0 !important;}
div#sirah-page-mainblock-wrapper,#sirah-page-content,#maincontent{margin:0 !important; padding:0 !important;}
.panel-body {padding:15px 15px 5px 15px;}
.panel-footer {background-color: #f5f5f5;border-bottom-left-radius:3px;border-bottom-right-radius:3px;border-top:1px solid #ddd;padding:5px 10px;}
<?php $this->headStyle()->captureEnd()   ?>
<div class="nopaddings nomargins container" style="margin:0 !important;padding:0 !important;">
<!-- Première section : les informations générales de l'entreprise -->
 <div id="general" class="container nopaddings" style="padding-top:55px !important;">
  <div class="panel panel-default" >  
   <div class="panel-body">
       <div  class="col-md-4"> 
           <div id="avatarRow" class="row avatar-row">
               <img id="myavatarThumbnail" src="<?php echo $logoFile; ?>"; align="center" class="img-rounded img-thumbnail"  />
          </div>
       </div>
       <div  class="col-md-8">
          <div class="list-group carreerList">
              <li class="list-group-item">
                <h2 class="list-group-item-heading"> <u> <?php echo $this->escape( $entreprise->libelle ); ?> </u> </h2>
                <?php if( $dateCreation ): ?>
                 <p  class="list-group-item-text"> <small> <?php echo $dateCreation; ?> </small> </p>
                <?php endif; ?>
                <?php if( $entreprise->capital ): ?>
                 <p  class="list-group-item-text"> <small> Au capital de <?php echo number_format( $entreprise->capital ,0 , " ", " " ); ?> F CFA </small> </p>
                <?php endif; ?>
                <?php if( $entreprise->nbemployes_min || $entreprise->nbemployes_max  ): ?>
                 <p  class="list-group-item-text"> <small> Le personnel varie entre <?php echo number_format( $entreprise->nbemployes_min ,0 , " ", " " ); ?> et 
                                                            <?php echo number_format( $entreprise->nbemployes_max , 0 , " ", " " ); ?> employés
                                                   </small> </p>                                                   
                <?php endif; ?>
                 <?php if( !empty( $entreprise->presentation ) ): ?>
                 <p id="presentation"  class="list-group-item-text"> <?php echo $this->escape( $entreprise->presentation ); ?> </p>                                                   
                <?php endif; ?>  
              </li>
          </div>
       </div>
     </div>
     <div class="panel-footer">
          <div class="controls">
               <ul class="nav nav-pills">
                  <li><a class="followEntreprise active" href="#"><span class="glyphicon glyphicon-eye-open"></span>  Suivre  </a></li>
                  <li><a  title="Partager cette entreprise à vos proches" class="shareEntreprise" href="#"><span class="glyphicon glyphicon-share-alt"></span> Partager </a></li>
                  <li><a  title="Visualiser les details de l'entreprise"  class="about" href="#"> A propos </a></li>
               </ul>
          </div>
     </div>    
   </div>
  </div>
  
  <div id="section1" class="row profile-panel nopaddings" >
     <div class="col-md-7 nopaddings" >
         <div class="col-md-12 nopaddings-left" >
             <div class="panel panel-default">
               <div class="panel-heading"> <span class='glyphicon glyphicon-tasks'></span> Les annonces publiées par cette entreprise </h4></div>              
                  <div class="panel-body"> Composant temporairement indisponible </div>
             </div>           
         </div>
         <div class="col-md-12 nopaddings-left" >
             <div class="panel panel-default">
               <div class="panel-heading"> <span class='glyphicon glyphicon-flash'></span> Actualités</h4></div>              
                  <div class="panel-body"> Composant temporairement indisponible </div>
             </div>           
         </div>
      </div>
      
     <div class="col-md-5 col-md-pull-right nopaddings" >
         <div class="col-md-12 nopaddings-right" >       
            <div class="panel panel-default">
               <div class="panel-heading"><h4 class="panel-title"> <span class='glyphicon glyphicon-phone-alt'></span> Coordonnées </h4></div>
                   <?php echo $this->partial("entreprises/coordonnees.phtml" , array("row"  => $entreprise )); ?>
               </div>  
         </div>         
         <div class="col-md-12 nopaddings-left" >
             <div class="panel panel-default">
               <div class="panel-heading"> <span class='icon-briefcase2'></span> References / Projets réalisés </h4></div>              
                  <div class="panel-body"> Composant temporairement indisponible </div>
             </div>           
         </div>
      </div>  
          
   </div>
</div>