<?php 
  $user           = $this->user;
  $params         = $this->params;
  $formtoken      = $this->pwdtoken;
  $formSubmit     = $this->url(array("module" => "admin", "controller" => "recoverpwd", "action"  => "init") , "default" );
  $changePwdLink  = $this->url(array("module" => "admin", "controller" => "account" , "action"  => "changepwd") , "default" );
?>
 
 <?php  if( !$params["change_password_security"] ) : ?>
 <form method="post" action="<?php echo $changePwdLink;  ?>" accept-charset="UTF-8"  id="changepasswordform" class="sirah-ui-form form-horizontal">    
  <ul>
   <li class="list-group-item">
      <div class="row">
         <div class="col-md-4"> <label class="label" for="password"> <b> Ancien mot de passe : </b></label> </div>   
         <div class="col-md-4">
              <input id="password" type="password" autocomplete="off" autocapitalize="off" autocorrect="off" 
                     title=""      placeholder="Votre ancien mot de passe" name="password"  class="form-control" /> 
         </div> 
         <div class="col-md-4"> &nbsp; </div>                       
     </div>
   </li>    
   <li class="list-group-item">
      <div class="row">
         <div class="col-md-4"> <label class="label" for="newpwd"> <b> Nouveau mot de passe : </b></label> </div>   
         <div class="col-md-4">
              <input id="newpwd" type="password" autocomplete="off" autocapitalize="off" autocorrect="off" 
                      title=""   placeholder="Votre nouveau mot de passe" name="newpwd" class="form-control"  /> 
         </div> 
         <div class="col-md-4"> &nbsp; </div>                       
     </div>
   </li>   
   <li class="list-group-item">
      <div class="row">
         <div class="col-md-4"> <label class="label" for="newpwdconfirm"> <b> Confirmation: </b></label> </div>   
         <div class="col-md-4">
              <input id="newpwdconfirm" type="password" autocomplete="off" autocapitalize="off" autocorrect="off" 
                      title="" placeholder="Confirmez le nouveau mot de passe" name="newpwdconfirm" class="form-control"  /> 
         </div> 
         <div class="col-md-4"> &nbsp; </div>                       
     </div>
   </li>     
 </ul> <br/>
  <div class="control-group">
           <div class="controls">
               <button type="submit" class="btn btn-primary editPwdChange"> <i class="glyphicon glyphicon-floppy-disk  glyphicon glyphicon-white "></i> Réinitialiser le mot de passe </button> 
           </div>                                       
  </div>  
   <input id="formtoken" type="hidden" name="<?php echo $formtoken ; ?>" value="formtoken" /> 
</form>
 <?php  else : ?>
     <form method="post" action="<?php echo $formSubmit;  ?>" accept-charset="UTF-8"  id="resetpasswordform" class="sirah-ui-form form-horizontal">        
       <div class="control-group">
           <div class="controls"> <label for="username" class="controls"> Entrez votre adresse e-mail, un code de vérification vous sera transmis:  <br/> </label>   </div>  
           <div class="controls">
               <input style="width:50%" value="<?php echo $user->get("email");  ?>" class="input-lg" type="text" id="identity" placeholder="Entrez votre adresse email" name="identity" autocomplete="off" >
           </div>
       </div>      
       <div class="control-group">
           <div class="controls">
               <button type="submit" class="btn btn-primary sendPwdChange"> <i class="glyphicon glyphicon-envelope  glyphicon glyphicon-white "></i> Réinitialiser le mot de passe </button> 
           </div>                                       
      </div>  
      <input id="formtoken" type="hidden" name="<?php echo $formtoken ; ?>" value="formtoken" />    
    </form>
  <?php endif; ?>
  
  