<html lang="en" >
<?php 
    //On initialise les variables nécessaires
    $layout        = $this->layout();
    $baseUrl       = $this->baseUrl();
    $tplPath       = ROOT_PATH."/myTpl/frontend";       
?>
<head>
<title><?php echo $this->escape($this->title); ?></title>
<meta http-equiv="Content-type" content="text/html; charset=UTF-8"/> 
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
 <style>
.center {float: none;margin-left: auto;margin-right: auto;}
.center-block{width:450px;margin: 0 auto;text-align:center;}
 </style>
<?php echo $this->headMeta() ?>
 <?php
           echo $this->headLink() ;
           echo $this->headStyle(); 
           echo $this->headScript();
           echo "<script type=\"text/javascript\">
                     window.SIRAH ||(window.SIRAH={}); 
                     SIRAH.basePath = \"".$tplPath."/\";
                 </script>";
 ?>
</head>
<body>
  
 <!--  DEBUT DE LA PAGE DU THEME -->  
        <div class="center-block"> <?php echo $this->layout()->content ?> </div>
  <!--  FIN DE LA PAGE DU THEME -->
</body>
<?php      
      echo $this->jQuery();
 ?>
</html>
