<?php
$demande              = $this->demande;
$demandeid            = $this->demandeid;
$localite             = $this->localite;
$entreprise           = $this->entreprise;
$demandeur            = $this->demandeur;
$promoteur            = $this->promoteur;
$identite             = $this->demandeurIdentite;
$promoteurIdentite    = $this->promoteurIdentite;
$identiteTypeRow      = $this->identiteType;
$identiteTypes        = $this->identitetypes;
$addSignature         = $this->addSignature;
$profile              = $this->profile;
$profileid            = $this->profileid;
$creatorid            = $this->creatorid;
$signataire           = $this->signataire;
$data                 = $this->data;
$me                   = ($creatorid    )? Sirah_Fabric::getUser($creatorid) : Sirah_Fabric::getUser();
$zendDemandeDate      = ($demande->date)? new Zend_Date($demande->date, Zend_Date::TIMESTAMP) : Zend_Date::now();
if( $zendDemandeDate ) {
	$demandeDate      = $todayDate = $zendDemandeDate->toString("dd MMMM YYYY");
} else {
	$demandeDate      = $todayDate = ($demande->date )? date("d/m/Y", $demande->date) : date("d/m/Y");
}
$nationalites         = $this->countries();

$demandeNumero        = $demande->numero;
$demandeObjet         = $demande->objet;

$demandeurName        = (isset($demandeur->name      ))? $demandeur->name       : "";
$demandeurFirstname   = (isset($demandeur->firstname ))? $demandeur->firstname  : "";
$demandeurLastname    = (isset($demandeur->lastname  ))? $demandeur->lastname   : "";
$demandeurAdresse     = (isset($demandeur->adresse   ))? $demandeur->adresse    : "";
$demandeurEmail       = (isset($demandeur->email     ))? $demandeur->email      : "";
$demandeurTelephone   = (isset($demandeur->telephone ))? $demandeur->telephone  : "";
$demandeurCountry     = (isset($demandeur->country   ))? strtolower($demandeur->country) : "bf";
$demandeurNationalite = (isset($nationalites[$demandeurCountry]))? $nationalites[$demandeurCountry] : "";
$demandeurSexe        = (isset($demandeur->sexe      ))? $demandeur->sexe       : "";
$demandeurProfession  = (isset($demandeur->profession))? $demandeur->profession : "";
$demandeurAdresse     = sprintf(" %s, Tel : %s", $demandeurAdresse,$demandeurTelephone);

$promoteurName        = (isset($promoteur->name      ))? $promoteur->name       : "";
$promoteurTelephone   = (isset($promoteur->telephone ))? $promoteur->telephone  : "";
$promoteurAdresse     = (isset($promoteur->adresse   ))? $promoteur->adresse    : "";
$promoteurAdresse     = sprintf("%s, Tel: %s", $promoteurAdresse,  $promoteurTelephone);
$promoteurProfession  = (isset($promoteur->profession))? $promoteur->profession    : "";

if( $promoteurIdentite ) {
	$zendDateEtablissement      = (Zend_Date::isDate($promoteurIdentite->date_etablissement,"YYYY-MM-dd"))?new Zend_Date($promoteurIdentite->date_etablissement,"YYYY-MM-dd")  :  null; 
	$dateEtablissement          = ($zendDateEtablissement)?$zendDateEtablissement->toString('dd/MM/YYYY') : $promoteurIdentite->date_etablissement;
	
	$promoteurIdentiteType      = (isset($identiteTypes[$promoteurIdentite->typeid]))? ucfirst($identiteTypes[$promoteurIdentite->typeid]) : (($identiteTypeRow)?$identiteTypeRow->libelle : "CNIB");
	$promoteurIdentiteOrganisme = $promoteurIdentite->organisme_etablissement;
	$promoteurIdentite          = sprintf("%s numéro %s établi le %s à %s ",$promoteurIdentiteType, $promoteurIdentite->numero,$promoteurIdentite->date_etablissement,$promoteurIdentite->lieu_etablissement);
    
} else {
	$promoteurIdentite          = "";
	$promoteurIdentiteOrganisme = "";
}
$NomCommercial        = ($entreprise)? $entreprise->nomcommercial : "";
$Sigle                = ($entreprise)? $entreprise->sigle         : "";
$Denomination         = ($entreprise)? $entreprise->denomination  : "";
$localiteName         = ($localite  )? $localite->libelle         : "Ouagadougou";

$civilites            = array("Mr"=>"Monsieur","Mme"=>"Madame","Mle"=>"Mademoiselle","Excellence"=>"Son excellence","Maître"=>"Maître","Dr" => "Docteur","Pr" => "Professeur","Conseiller"=>"Le Conseiller");
$myCivilite           = (isset($me->civilite) && !empty($me->civilite) )?$civilites[$me->civilite] : "Maître";
$myLastName           = ($me)?$me->lastname  : "";
$myFirstName          = ($me)?$me->firstname : ""; 
$myRole               = ($me)?$me->getRole() : "GREFFIER/GREFFIER EN CHEF/ADMINISTRATEUR DU FICHIER NATIONAL DU REGISTRE DU COMMERCE ET DU CREDIT MOBILIER";
if( empty($myRole) ) {
	$myRole           = "GREFFIER/GREFFIER EN CHEF/ADMINISTRATEUR DU FICHIER NATIONAL DU REGISTRE DU COMMERCE ET DU CREDIT MOBILIER";
}
  
$output.= " <form method=\"post\" action=\"#\" enctype=\"multipart/form-data\">";
$output.= " <table width=\"100%\" style=\"line-height:11px;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">
                <tr>
                    <td style=\"line-height:11px;\" valign=\"top\" align=\"left\" width=\"75%\"> 
					    <p align=\"center\" style=\"vertical-align:top;text-align:center;line-height:10px;font-size:10pt;\">
					        <strong>MINISTERE EN CHARGE DE LA JUSTICE</strong><br/>
							-----------------------------------------
					    </p> 
						<p align=\"center\" style=\"vertical-align:top;text-align:center;line-height:10px;font-size:10pt;\">
					        <strong>SECRETARIAT GENERAL </strong><br/>
							-----------------------------------------
					    </p>
                        <p align=\"center\" style=\"vertical-align:top;text-align:center;line-height:10px;font-size:10pt;\">
					        <strong>DIRECTION GÉNÉRALE DE L'ADMINISTRATION JUDICIAIRE</strong><br/>
							-----------------------------------------
					    </p>						
                        <p align=\"center\" style=\"vertical-align:top;text-align:center;line-height:10px;font-size:10pt;\">
					        <strong>DIRECTION DES GREFFES </strong><br/>
							-----------------------------------------
					    </p>					
						<p align=\"center\" style=\"vertical-align:top;text-align:center;line-height:10px;font-size:10pt;\">
					        <strong>FICHIER NATIONAL RCCM</strong> <br/>
					    </p>					
					</td>
                    <td align=\"center\" valign=\"top\" style=\"vertical-align:top;\" width=\"30%\"> &nbsp;</td>
                </tr>
            </table>";           
$output.="  <table style=\"border-collapse:collapse;margin:0px;\" border=\"0\" cellpadding=\"1\" cellspacing=\"0\" width=\"100%\">
				<tr><td style=\"background-color:#0a5993;\" align=\"justify\" valign=\"middle\" bgcolor=\"#0a5993\" colspan=\"2\"> <span style=\"font-weight:bold;font-size:10pt;color:#FFF;\">ATTESTATION DE DISPONIBILITE ET DE RESERVATION N° {$demandeNumero} </span> </td></tr>
				<tr nobr=\"true\" style=\"line-height:13px;\">
				    <td colspan=\"2\" style=\"line-height:13px;\">
						<p style=\"line-height:13px;font-family:arial;font-size:11pt;text-align:justify\"><strong>Nous, soussigné {$myCivilite} {$myFirstName} {$myLastName}, {$myRole }</strong></p> 
						<p style=\"line-height:13px;font-family:arial;font-size:11pt;text-align:justify\">Attestons que, suivant la demande de recherche de disponibilité et de réservation N°<strong>{$numDemande}</strong> de Mr/Mme {$demandeurName}</p>
						<p style=\"line-height:13px;font-family:arial;font-size:11pt;text-align:justify\">
							<span style=\"font-family:arial;font-size:11pt;\">La Dénomination Sociale: </span> 
							<span style=\"font-family:arial;font-size:11pt;font-weight:bold;\">".$Denomination."</span>
						</p>
						<p style=\"line-height:13px;font-family:arial;font-size:11pt;text-align:justify\">
							<span style=\"font-family:arial;font-size:11pt;\">Le Nom Commercial : </span> 
							<span style=\"font-family:arial;font-size:11pt;font-weight:bold;\">".$NomCommercial."</span>
						</p>
						<p style=\"line-height:13px;font-family:arial;font-size:11pt;text-align:justify\">
							<span style=\"font-family:arial;font-size:11pt;\">Le Sigle : </span> 
							<span style=\"font-family:arial;font-size:11pt;font-weight:bold;\">".$Sigle."</span>
						</p>
						<p style=\"line-height:13px;font-family:arial;font-size:11pt;text-align:justify\">
							<span style=\"font-family:arial;font-size:11pt;\">Est/Sont Disponible(s) </span> 
						</p>
						<p style=\"line-height:13px;font-family:arial;font-size:11pt;text-align:justify\">Par conséquent, cette dénomination Sociale/Ce nom commercial/Ce sigle est réservé(e) pour un délai de trois (03) mois à compter du {$demandeDate} au profit du promoteur ci-après:</p>
					    <p style=\"line-height:11px;font-family:arial;font-size:11pt;text-align:justify\">
							<span style=\"font-family:arial;font-size:11pt;\">Nom et Prénom(s) : </span> 
							<span style=\"font-family:arial;font-size:11pt;font-weight:bold;\">".$promoteurName."</span> 
					    </p>
						<p style=\"line-height:11px;font-family:arial;font-size:11pt;text-align:justify\">
							<span style=\"font-family:arial;font-size:11pt;\">Adresse : </span> 
							<span style=\"font-family:arial;font-size:11pt;\">".$promoteurAdresse."</span> 
					    </p>
					</td>
				</tr>
				<tr><td style=\"background-color:#CCCCCC;\" align=\"center\" valign=\"middle\" bgcolor=\"#CCCCCC\" colspan=\"2\"><span style=\"font-weight:bold;font-size:10pt;padding:5px;\"> REFERENCES DE LA PIECE D'IDENTITE </span> </td></tr>
				<tr nobr=\"true\">
					<td colspan=\"2\"> 
						<span style=\"font-family:arial;font-size:11pt;\">".$promoteurIdentite."</span> 
					</td>
				</tr>
				<tr nobr=\"true\">
					<td colspan=\"2\"> 
						<span style=\"font-family:arial;font-size:11pt;\">Délivré(e) par : </span>
						<span style=\"font-family:arial;font-size:11pt;\">".$promoteurIdentiteOrganisme."</span> 
					</td>
				</tr>
				<tr nobr=\"true\">
					<td colspan=\"2\"> 
						<span style=\"font-family:arial;font-size:11pt;\">Profession : </span>
						<span style=\"font-family:arial;font-size:12pt;font-weight:bold;\">".$promoteurProfession."</span> 
					</td>
				</tr>
				<tr nobr=\"true\">
					<td colspan=\"2\"> 
						<p style=\"font-family:arial;font-size:11pt;text-align:right;\">En foi de quoi la présente attestation est délivrée pour servir et valoir ce que de Droit.</p>
					</td>
				</tr>
				<tr nobr=\"true\">
					<td align=\"left\" colspan=\"2\"> 
						<p style=\"font-family:arial;font-size:11pt;text-align:left;\"> NB : Cette réservation  est renouvelable une fois.</p>
					</td>
				</tr>
		    </table>";
	
    if(!$addSignature ) {
$myName = sprintf("%s %s", $me->firstname, $me->lastname);
$output.=<<<EOF
			<table width="100%" cellspacing="2" border=0 cellpadding="2">   
				 
				<tr>
					<td align="center" >
						<p align="center" style="font-family:arial;font-size:10pt;"> Fait à {$localiteName}, le  <b> {$todayDate} </b> </p>
						<p align="center"  style="font-family:arial;font-size:10pt;text-align:center;">
							<b><u> L'AGENT COMPÉTENT</u></b><br/>			 
						</p>
					</td>
				</tr>
			</table> 
EOF;
	} else {
$myName = sprintf("%s %s", $me->firstname, $me->lastname);
$output.=<<<EOF
			<table nobr="true" style="line-height:10px;border-collapse:collapse;margin:0px;" width="100%" cellspacing="0" border="0" cellpadding="1">   
				<tr nobr="true">    								
					<td style="line-height:10px;border-left:none;border-right:none;border-bottom:none" align="center" valign="middle" width="100%">
						<p style="font-size:11pt;"> Fait à {$localiteName}, le <b> {$todayDate} </b><br/></p>
						<p style="font-size:11pt;"><b> L'AGENT COMPÉTENT </b></p>
						<p style="font-size:10pt;"><b>[SIGNATURE]</b></p>
						<p style="font-size:10pt;"><b> {$myName} </b></p>
						
					</td>
				</tr>
			</table> 
EOF;
	}
$output.= "</form>";

echo $output;