<?php 
$data       = $this->data;
$formSubmit = $this->url(array("module"=>"admin","controller"=>"productcategories","action"=>"create"),"default",true );
$backList   = $this->url(array("module"=>"admin","controller"=>"productcategories","action"=>"list")  ,"default",true);
$basePath   = BASE_PATH.'/myTpl/sirahpro';
?>
<?php $this->headStyle()->captureStart() ?>

<?php $this->headStyle()->captureEnd()   ?>

<?php

$jq     = $this->jQuery();  
$onLoad = " 
    jQuery('#image').filestyle({buttonText:'Chercher une photo',classButton:'btn btn-primary',classInput:'input-inline form-control',classIcon:'glyph-icon icon-folder-open',icon: true});
    jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});  
    jQuery('#createButton').click(function(e){
		e.preventDefault();      
		var  formSelector = jQuery('#createProductcategoryForm');
		var  libelle      = jQuery.trim(formSelector.find('#libelle').val());
		  
		if( SIRAH.util.isEmpty( libelle )){
			jQuery('#libelle').addClass('input-error');
			jQuery('#libelle-validation-message').html('');
			SIRAH.error.raise('libelle-validation-message','Entrez une désignation valide de la catégorie');
			return;
		} else {
		    jQuery('#libelle').removeClass('input-error');
			jQuery('#libelle-validation-message').html('');
		}      
		jQuery('#libelle').val( libelle );
		formSelector.submit();
    }); ";  
$jq->addOnLoad($onLoad);
$jq->addJavascriptFile($basePath."/js/bootstrap/bootstrap-filestyle.js");
?>
<form method="post" action="<?php echo $formSubmit;?>" id="createProductcategoryForm" role="form" class="form-horizontal" enctype="multipart/form-data">
 <div class="panel panel-default" >
    <ul class="list-group">
	    <li class="list-group-item">
			<div class="form-group"> 
				<label class="col-md-2 col-sm-2 col-xs-hidden control-label" for="image">Image: </label>
				<div   class="col-md-10 col-sm-10 col-xs-12"><input type="file" name="image" id="image"    /></div>        
			</div>
		</li>
	    <li class="list-group-item">
			<div class="form-group">
				 <label class="col-md-2 col-sm-2 col-xs-hidden control-label" for="documentcatid">Type de document: </label>
				 <div   class="col-md-10 col-sm-10 col-xs-12"> <?php echo $this->formSelect("documentcatid", intval($data["documentcatid"]), array("class" => "form-control"), $this->documentypes); ?> </div>                
			</div> 
			<p id="documentype-validation-message" class="validation-message"></p>    
		</li>
	    <li class="list-group-item">
			<div class="form-group">
				<label class="col-md-2 col-sm-2 col-xs-hidden control-label" for="code">Code: </label>
				<div   class="col-md-10 col-sm-10 col-xs-12">
					<input id="code" type="text" maxlength="100" class="form-control" title="Le code de la catégorie" placeholder="Le code de la catégorie" name="code" value="<?php echo $data['code']; ?>">
				</div>                 
			</div>     
		</li>
		<li class="list-group-item">
			<div class="form-group">
				<label class="col-md-2 col-sm-2 col-xs-hidden control-label" for="libelle"> Désignation: </label>
				<div   class="col-md-10 col-sm-10 col-xs-12">
					   <input id="libelle" type="text" maxlength="200" class="form-control" title="Désignation de la catégorie" placeholder="Désignation de la catégorie"  name="libelle" value="<?php echo $data['libelle']; ?>">
				</div>                 
			</div> 
			<p id="libelle-validation-message" class="validation-message"></p>    
		</li>
		<li class="list-group-item">
			<div class="form-group">
			   <label class="col-md-2  col-sm-2 col-xs-hidden control-label" for="prix">Cout HT: </label>
			   <div   class="col-md-10 col-sm-10 col-xs-12"> <input type="text" name="cout_ht" id="cout_ht" class="form-control" title="Cout unitaire Hors Taxes" placeholder="Cout unitaire Hors Taxes"  value="<?php echo $data["cout_ht"]; ?>" /></div>   
			</div>
		</li>
		<li class="list-group-item">
			<div class="form-group">
			   <label class="col-md-2  col-sm-2 col-xs-hidden control-label" for="prix">Cout TTC: </label>
			   <div   class="col-md-10 col-sm-10 col-xs-12"> <input type="text" name="cout_ttc" id="cout_ttc" class="form-control" title="Cout unitaire TTC" placeholder="Cout unitaire TTC"  value="<?php echo $data["cout_ttc"]; ?>" /></div>   
			</div>
		</li>
		<li class="list-group-item">
			<div class="form-group">
				<label class="col-md-2 col-sm-2 col-xs-hidden control-label" for="description"> Description: </label>				
				<div   class="col-md-10 col-sm-10 col-xs-12"><textarea name="description" id="description" class="form-control textarea-sm"> <?php echo $data["description"]; ?> </textarea></div>              
			</div>  
		</li>  
    </ul>  
<?php     
   $buttonsbar = $this->Btnbar(array() , $this->jqueryHandler());
   $toolCreate = $buttonsbar->button("Enregistrer la catégorie","save")->setPriority("primary");
   $toolCancel = $buttonsbar->button("Annuler et revenir sur la liste","chevron-left");
   
   $toolCreate->setAttributes(array("type"=> "submit"));
   $toolCancel->setAttributes(array("type"=> "submit"));
   
   $buttonsbar->add($toolCancel,"cancelCreationButton");
   $buttonsbar->add($toolCreate,"createButton");
   

   if(!$this->isAjax) {
   	   echo "<div class=\"panel-footer\">".$buttonsbar."</div>";
   } else {
   	   echo $this->jQuery();
   }  
   ?>
   </div> 
</form>