<?php 
$documents   = $this->documents;
$categories  = $this->categories;
$filters     = $this->filters;
$paginator   = $this->paginator;

$basePath    = VIEW_BASE_PATH;
$jq          = $this->jQuery();

$linkSearch  = $this->url(array("module" => "admin","controller" => "userdocuments", "action" => "list")    , "default");
$linkCreate  = $this->url(array("module" => "admin","controller" => "userdocuments", "action" => "create")  , "default");
$linkEdit    = $this->url(array("module" => "admin","controller" => "userdocuments", "action" => "edit")    , "default");
$linkDelete  = $this->url(array("module" => "admin","controller" => "userdocuments", "action" => "delete")  , "default");
$linkDownload= $this->url(array("module" => "admin","controller" => "userdocuments", "action" => "download"), "default");

$jq->addOnload("
  var getCheckedDocumentId = function() {
		var checkedItems = jQuery('#documentsListTable').find('input[type=\'checkbox\'][name!=\'checkall\']:checked');
        var checkedIds   = []; 
		if(checkedItems) {
		   checkedItems.each(function() {
             	var documentid   = parseInt(jQuery(this).attr('id').replace('documentids',''));
             	checkedIds.push( documentid );
           });
		}
		return checkedIds;
  };
  jQuery('#documentsListTable').find('input[type=\'checkbox\']').click(function(e){
		 var checkedItems  = jQuery('#documentsListTable').find('input[type=\'checkbox\'][name!=\'checkall\']:checked');
		 if(jQuery(this).attr('id') == 'checkAll') {
		    if(!jQuery(this).is(':checked')) {
		       checknone(jQuery('#documentsListTable'));
		       if(checkedItems) {
		           disableButtons(['editButton','downloadButton','deleteButton']);
		       }
		    } else {
		      checkall(jQuery('#documentsListTable'));
		      enableButtons(['editButton','downloadButton','deleteButton']);
		    }
		 } else {
		  if(jQuery(this).is(':checked')) {
		     enableButtons(['editButton','downloadButton','deleteButton']);
		  } else {
		      if( SIRAH.util.isEmpty(checkedItems)) {
		          disableButtons(['editButton','deleteButton','downloadButton']);
		      }		      
		  }
		}
   });
  jQuery('.reset').eq(0).click(function( event ){ event.preventDefault(); document.location.href = '".$linkSearch."'; });		
  jQuery('#close-advanced-searchform').click(function(event){event.preventDefault();jQuery('#advanced-searchform-wrapper').hide();});
  jQuery('#show-advanced-searchform').click(function(event){event.preventDefault();jQuery('#advanced-searchform-wrapper').show();});
  jQuery('.default-search').eq(0).click(function( event ){jQuery('#globalformsearch').submit();});		
  jQuery('.sirahPaginationBtn').click(function(event){
		  event.preventDefault();
		  if(jQuery(this).is('.active') || jQuery(this).is('.disabled') || jQuery(this).is('.currentBtn')) {
		     return false;
		  }
		   var formSelector     = jQuery('#advanced-searchform');
		   var pageNum          = parseInt(jQuery(this).attr('id').replace('paginationBtnPage-' , ''));
		   var pageMaxitems     = formSelector.find('#maxitems').val();
		   if(jQuery(this).is('.nextPage')) {
		      var currentBtnNum = parseInt(jQuery('.currentBtn').first().attr('id').replace('paginationBtnPage-' , ''));
		      pageNum           = parseInt( currentBtnNum +1);
		   }
		   if(jQuery(this).is('.prevPage')) {
		      var currentBtnNum = parseInt(jQuery('.currentBtn').first().attr('id').replace('paginationBtnPage-' , ''));
		      pageNum           = parseInt( currentBtnNum - 1);
		   }
		var paginationData      = {};
		paginationData.maxitems = pageMaxitems;
		paginationData.page     = pageNum;
		paginationData.category = parseInt(jQuery('#category').val());
		paginationData.libelle  = formSelector.find('#libelle').val();
		paginationData.filetype = formSelector.find('#filetype').val();
		paginationData.username = formSelector.find('#username').val();
		paginationData.userid   = formSelector.find('#userid').val();
        var maincontent	        = jQuery('#maincontent');	
		SIRAH.loading.on( maincontent , 'Chargement des données...' );
		SIRAH.request.post('globalformsearch' , '".$linkSearch."' , 
		                   {
		                      dataType : 'html' ,
		                      data     : paginationData,
		                      beforeSend : function() {},
		                      error      : function(data){maincontent.html(data);basicLoadPage();SIRAH.loading.off(false);},
	                          success    : function(data){maincontent.html(data);basicLoadPage();SIRAH.loading.off(false);},
		                      update     : function(data){maincontent.html(data);basicLoadPage();SIRAH.loading.off(false);}		
		                     });
	  SIRAH.loading.off(false);		
	});
");

?>
    <div class="row pagerow">
    <?php
             $buttonbar     = $this->buttonbar(array() , $this->jqueryHandler());             
             $buttonCreate  = $buttonbar->button("Nouveau"  , "plus")->setPriority("primary");             
             $buttonDelete  = $buttonbar->button("Supprimer", "trash");
             
             $buttonbar->add( $buttonCreate, "createButton");
             $buttonbar->add( $buttonDelete, "deleteButton");
                       
             $buttonCreate->onClick(sprintf("event.preventDefault(); document.location.href='%s';" , $linkCreate));             
           
             $buttonDelete->disable();             
             $buttonDelete->onClick(" event.preventDefault();
             		                  var isDisabled       = jQuery(this).is('.disabled') || jQuery(this).is('.btn-disabled');
             		                  var checkedDocuments = getCheckedDocumentId();  		        
             		                  if(isDisabled || SIRAH.util.isEmpty(checkedDocuments)) {
             		                      SIRAH.dialog.alert('Vous devrez selectionner une ligne avant d\'effectuer cette opération','Selectionnez une ligne');
             		                      return;
             		                   } 
             		       var dialogDelete = jQuery('<div> Voulez-vous vraiment supprimer les documents selectionnés ? </div>').attr('id','dialogDelete');             		 
             		       dialogDelete.dialog2({
             		                              title : 'Confirmer cette action',
             		                              autoOpen: false,
             		                              removeOnClose: true,
             		                              closeOnEscape: false, 
                                                  closeOnOverlayClick: true,
             		                              showCloseHandle:true,
             		                              initialLoadText: 'Chargement...'            		                       
             		                           });        		
             		      dialogDelete.dialog2('addButton','Oui',{primary : true , click : 
             		                            function(){
             		                                         jQuery.ajax({
             		                                             url      :'".$linkDelete."',
             		                                             async    : false,
			                                                     dataType :'json',
             		                                             data     : {'documentids[]' : checkedDocuments},
             		                                             type     : 'GET' ,
             		                                             success  : function(data) {
             		                                                if(data.error !== undefined) {
             		                                                   SIRAH.error.raise(jQuery('#dialogDelete') , data.error);
             		                                                   return;
             		                                                } else if(data.success !== undefined) {
             		                                                   var checkedDocuments = getCheckedDocumentId();  	            		
             		                                                  SIRAH.error.raise(jQuery('#dialogDelete'), data.success , 'success');
             		                                                setTimeout(function(){
             		             		                              jQuery.each( checkedDocuments , function(key , documentid ) {
             		                                                          jQuery('#documentRowId-'+documentid).remove();
             		                                                    });
             		                                                   jQuery('#dialogDelete').dialog2('close');
             		                                                  },2500);
             		                                               }
             		                                             }
             		                                           });     		
                                                           }}); 
             		      dialogDelete.dialog2('addButton','Annuler' ,   {primary: false,click : function(){jQuery(this).dialog2('close');}});              		
             		      dialogDelete.dialog2('open');  ");  
              ?>           
                  <div class="row" >
                      <div class="col-md-8"><?php echo $buttonbar; ?></div>
                      <div class="col-md-4"> 
                          <form style="margin :10px 0 10px 0;" class="form-horizontal" id="globalformsearch" method="post" action="<?php echo $linkSearch; ?>" >
                             <div class="input-group pull-right">
                                <input value="<?php echo $filters['libelle']; ?>" id="generalfilter" name="generalfilter"  type="text" class="form-control input-medium" placeholder="Numéro de dossier">
                                <span class="input-group-btn ">
                                   <button class="btn btn-default default-search" type="button"><span class="glyphicon glyphicon-search"></span> Filtrer </button>
                                   <button id="show-advanced-searchform" class="btn btn-default" type="button">Avancée</button>
                                </span>
                            </div>
                          </form>
                      </div>
                  </div>                  
                  <div style="display:none;" id="advanced-searchform-wrapper"  class="row simplerow" >
                      <form method="post" action="<?php echo $linkSearch; ?>" align="left"   id="advanced-searchform"   role="form">
                         <div class="row simplerow-search-form-header">
                            <a id="close-advanced-searchform" class="close"> Fermer</a>
                            <h3> <span class="icon-search"></span> Les paramètres de recherche avancée :</h3>
                         </div>
                          <div class="row">
                            <div class="column col-md-2"> <label  for="libelle"> Titre du document:  </label> </div>
                            <div class="column col-md-4">                                
                                <input id="libelle" type="text" maxlength="96" autocomplete="off" autocapitalize="off" autocorrect="off" 
                                       title="Titre du document" placeholder="Titre du document"  name="libelle" value="<?php echo $filters['libelle']; ?>">
                            </div>
                            <div class="column col-md-2"> <label  for="category"> Catégorie :  </label> </div>
                            <div class="column col-md-4"><?php echo $this->formSelect("category", $filters["category"] , array() , $this->categories ); ?> </div>                                         
                        </div>
                       <div class="row"> 
                          <div class="column col-md-2"> <label  for="filetype"> Type de categorie:  </label> </div>
                          <div class="column col-md-4">
                              <?php echo $this->formSelect("filetype" , $filters["filetype"] , array() , array("png" => "IMAGE/PNG", "xls" => "MICROSOFT OFFICE EXCEL", "ppt" => "MICROSOFT OFFICE POWERPOINT",
                              		                                                                           "pdf" => "APPLICATION/PDF", "gif" => "IMAGE/GIF", "bmp"=> "IMAGE/BMP", "doc" => "MICROSOFT OFFICE WORD",
                              		                                                                           "jpe" => "IMAGE/JPEG", "jpeg" => "IMAGE/JPEG", "jpg" => "IMAGE/JPEG") ); ?>
                          </div>
                          <div class="column col-md-6"> &nbsp; </div>                              
                       </div> 
                      <div class="row"> 
                          <div class="column col-md-2"> <label  for="limit"> Limiter la liste à : </label> </div>                           
                          <div class="column col-md-4">
                                <?php echo $this->formSelect("maxitems" , $this->maxitems , array() , array( "10"   => 10, "25" => 25, "50" => 50 , "100" => 100, "500" => 500, 
                                		                                                                     "1000" => 1000, "2000" => 2000 , "5000" => 5000, "100000000" => "Tout")); ?>
                          </div>
                          <div class="column col-md-6"> &nbsp; </div>
                      </div>                                                                     
                      <div class="row">
                          <div class="column  col-md-4">
                           <div class="btn-buttonbar sirah-ui-buttonbar"> 
                               <div class="btn-group">  
                                 <button type="submit" class="btn btn-primary search"><span class="glyphicon glyphicon-search"></span > Rechercher </button> 
                               </div>
                               <div class="btn-group">   
                                 <button type="submit" class="btn btn-danger  reset"><span class="glyphicon glyphicon-remove"></span > Réinitialiser </button> 
                               </div>
                           </div> 
                         </div>                      
                          <div class="column  col-md-8"></div>     
                      </div> 
                      <input type="hidden" name="page"     id="page"     value="<?php echo $this->pageNum; ?>"  />
                  </form>
                </div>                                   
            <?php
            //On crée et affiche le tableau
            $output  = "<table id=\"documentsListTable\" class=\"table table-hover table-bordered table-stripped sirah-ui-table scrollable\" >
                           <thead><tr>"  ;
                                  $output .= "<th width=\"1%\"> <input type=\"checkbox\" name=\"checkall\" id=\"checkAll\" class=\"checkAll\" /> </th>";
                                  $output .= "<th width=\"19%\"> Dossiers       </th>";
                                  $output .= "<th width=\"50%\"> Titres         </th>";
                                  $output .= "<th width=\"10%\"> Tailles        </th>";
                                  $output .= "<th width=\"20%\"> Enregistré le        </th>";
            $output .= "</tr></thead>";
            $lastCategorie = null;  
            $modelDocument = new Model_Document();
             if(count(   $documents ) ) {
             	foreach( $documents as $document ) {             		
             	         $documentid   = intval($document['documentid']);
             	         $linkInfos    = $this->url(array("module" => "admin","controller" => "userdocuments", "action" => "download", "documentid" => $documentid  ), "default");
             	         $categorie    = ( $lastCategorie == $document["categorie"] ) ? "" : $document["categorie"];
             	         $filextension = strtolower($document["filextension"]);
             	         $libelle      = $modelDocument->filterIndex( $filename, $document["userid"] );
             	         $icone        = $modelDocument->getFileIcon( $filextension );
             	         
             	         $filesize     = ( isset( $document["filepath"] ) && file_exists( $document["filepath"] ) ) ? filesize( $document["filepath"] ) : $document["filesize"] ;
             	         $sizeKo       = Sirah_Functions::toByteString( $filesize, "" , 3 );
             	         $totalSize   += $filesize;
             	         $dateCreation = date("d/m/Y", $document["creationdate"]);

             	   $output .= "<tr id=\"documentRowId-".$documentid."\">";
             	            $output .= "<td> <input type=\"checkbox\" name=\"documentids[]\" id=\"documentids".$documentid."\" class=\"documentids\" /> </td>";
             	            $output .= "<td> <a href=\"".$linkInfos."\"> ".$categorie." </a> </td>";
             	            $output .= "<td> <span class=\"".$icone."\"></span> <a href=\"".$linkInfos."\"> ".$libelle." </a> </td>";
             	            $output .= "<td> <a href=\"".$linkInfos."\"> ".$sizeKo." </a> </td>";
             	            $output .= "<td id=\"dateDocumentId-".$documentid."\"> ".$dateCreation." </td>";
             	   $output .= "</tr>";
             	   
             	   $lastCategorie = $document["categorie"];
             	}
             }  else {
             	  $output .= "<tr>";
             	           $output .= "<td colspan=\"8\"> Aucune ligne valide n'a été retrouvée , réessayez avec d'autres critères de recherche </td>";
             	  $output .= "</tr>";
             }   
              $output .="</table>";
              // On affiche le tableau
              echo $output;
              
              //On crée et affiche la pagination
              $pagination  = $this->pagination(array() , "Elastic" , "#");              
              echo $pagination->render();
              
echo $this->headScript();echo $this->jQuery();
              	  echo $this->headStyle();
              }                   
    ?>
 </div>