<?php 
$captcha            = $this->captcha;
$messages           = $this->messages;
$token              = $this->token;
$data               = $this->data;
$registreid         = intval($this->registreid);
$registre           = $this->registre;
$numrc              = ( $registre )?$registre->numero:null;
$defaultCountry     = (isset($data["country"]) && !empty($data["country"])) ? $data["country"] : "BF";

$formSubmit         = $this->url(array("controller"=>"requetes", "action"=> "createaccount", "module" => "public"),"default");
$linkSearch         = $this->url(array("controller"=>"ajaxres" , "action"=> "registreslist", "parentform" => "requestCreationForm", "module" => "public") , "default");
$linkCancel         = $this->url(array("controller"=>"index"   , "action"=> "index", "module"=> "public") , "default");
if( $registre ) {
	$urlLibelle     = Sirah_Functions_String::cleanUtf8($numrc);
	if( $registre->type == 1 ) {
		$linkCancel = $this->url(array("registreid"=>$registreid,"registrelib"=> $urlLibelle,"type" => "physiques" ), "registre");   
	} else {
		$linkCancel = $this->url(array("registreid"=>$registreid,"registrelib"=> $urlLibelle,"type" => "morales"), "registre"); 
	}
}
$registerDoneUri    = $this->registerDoneUri;
$basePath           = VIEW_BASE_PATH;
$typesDocuments     = $this->typesdocuments;

$jq     = $this->jQuery();  
$onLoad = " 
jQuery('.searchItem,.numero,#numero').click(function(event){
	  event.preventDefault();
	  var filterListDialog  = jQuery('<div></div>').attr('id','filterListRegistres').addClass('modal-medium');             		 
      filterListDialog.dialog2({title:'Rechercher un registre de commerce',content:'".$linkSearch."',autoOpen:false,modalClass:'modal-wide',removeOnClose:true,closeOnEscape:true,closeOnOverlayClick:true,showCloseHandle:true,initialLoadText:'Chargement...'});        		            		
      filterListDialog.dialog2('open');   		
});
jQuery('.createButton').click(function( event ){
      event.preventDefault();      
      var  formSelector= jQuery('#requestCreationForm');
      var  firstname   = jQuery.trim(jQuery('#firstname').val());
      var  lastname    = jQuery.trim(jQuery('#lastname').val());
      var  email       = jQuery.trim(jQuery('#email').val());
      var  credential  = jQuery.trim(jQuery('#password').val());
      var  credential2 = jQuery.trim(jQuery('#confirmedpassword').val());
      var  phone1      = jQuery.trim(jQuery('#phone1').val());
      var  registreid  = parseInt(formSelector.find('#registreid').val());
      var  typedocument= jQuery.trim(jQuery('#typedocument').val());
      
      if( !registreid ) {
          jQuery('#numero').addClass('input-error');
          jQuery('#registre-validation-message').html('');
          SIRAH.error.raise('registre-validation-message','Selectionnez un numéro de registre valide');
          return;
      }else {
         jQuery('#numero').removeClass('input-error');
         jQuery('#registre-validation-message').html('');
      }
      
      if(SIRAH.util.isEmpty(lastname)){
         jQuery('#lastname').addClass('input-error');
         jQuery('#name-validation-message').html('');
         SIRAH.error.raise('name-validation-message','Entrez un nom de famille valide');
         return;
      } else {
         jQuery('#lastname').removeClass('input-error');
          jQuery('#name-validation-message').html('');
      }
      if(SIRAH.util.isEmpty(firstname)){
        jQuery('#firstname').addClass('input-error');
        jQuery('#name-validation-message').html('');
         SIRAH.error.raise('name-validation-message','Entrez un prénom valide');
         return;
      }  else {
         jQuery('#firstname').removeClass('input-error');
          jQuery('#name-validation-message').html('');
      }    
      if(SIRAH.util.isEmpty(phone1)){
        jQuery('#phone1').addClass('input-error');
        jQuery('#phone-validation-message').html('');
         SIRAH.error.raise('phone-validation-message','Entrez un numéro de téléphone valide');
         return;
      }  else {
         jQuery('#phone1').removeClass('input-error');
         jQuery('#phone-validation-message').html('');
      }
      if(!SIRAH.validators.isEmailAddress(email)){
        jQuery('#email').addClass('input-error');
        jQuery('#email-validation-message').html('');
         SIRAH.error.raise('email-validation-message','Entrez un email valide');
         return;
      }  else {
         jQuery('#email').removeClass('input-error');
         jQuery('#email-validation-message').html('');
      }     
      if(SIRAH.util.isEmpty(credential) || (parseInt(credential.length) < 4)){
         jQuery('#password').addClass('input-error');
         jQuery('#password-validation-message').html('');
         SIRAH.error.raise('password-validation-message','Entrez un mot de passe valide, doit contenir au moins 4 caractères');
         return;
      } else {
         jQuery('#credential').removeClass('input-error');
         jQuery('#password-validation-message').html('');
      }      
     if(credential2 !== credential){
         jQuery('#confirmedpassword').addClass('input-error');
         jQuery('#confirmedpassword-validation-message').html('');
         SIRAH.error.raise('confirmedpassword-validation-message','Les mots de passe sont differents');
         return;
      } else {
        jQuery('#confirmedpassword').removeClass('input-error');
        jQuery('#confirmedpassword-validation-message').html('');
      }
      if(SIRAH.util.isEmpty(typedocument)){
         jQuery('#typedocument-validation-message').html('');
         SIRAH.error.raise('typedocument-validation-message','Selectionnez un type de document valide');
         return;
      }  else {
          jQuery('#typedocument-validation-message-validation-message').html('');
      }

      jQuery('#lastname').val(lastname);
      jQuery('#firstname').val(firstname);
      jQuery('#email').val(email);
      jQuery('#phone1').val(phone1);
      jQuery('#password').val(credential);
      jQuery('#confirmedpassword').val(credential2);
      formSelector.submit();
});
jQuery('#lastname').bind('blur change',function(e){
      e.preventDefault();
      var lastname = jQuery.trim(jQuery(this).val());
      if(!SIRAH.util.isEmpty(lastname)){
        jQuery('#lastname').removeClass('input-error');
        jQuery('#name-validation-message').html('');
      } else {
        jQuery('#lastname').addClass('input-error');
        return;
      }
  });  
  jQuery('#firstname').bind('blur change',function(e){
      e.preventDefault();
      var firstname = jQuery.trim(jQuery(this).val());
      if(!SIRAH.util.isEmpty(firstname)){
        jQuery('#firstname').removeClass('input-error');
        jQuery('#name-validation-message').html('');
      }  else {
        jQuery('#firstname').addClass('input-error');
         return;
      }
  });  
 jQuery('#email').bind('blur change',function(e){
      e.preventDefault();
      var email = jQuery.trim(jQuery(this).val());
      if(!SIRAH.validators.isEmailAddress(email)){
        jQuery('#email').addClass('input-error');
        jQuery('#email-validation-message').html('');
         SIRAH.error.raise('email-validation-message','Entrez un email valide');
         return;
      }  else {
         jQuery('#email').removeClass('input-error');
         jQuery('#email-validation-message').html('');
      }    
  });     
  jQuery('#password').bind('blur change',function(e){
      e.preventDefault();
      var credential = jQuery.trim(jQuery(this).val());
      if(SIRAH.util.isEmpty(credential) || (parseInt(credential.length) < 4)){
         jQuery('#password').addClass('input-error');
         jQuery('#password-validation-message').html('');
         SIRAH.error.raise('password-validation-message','Entrez un mot de passe valide');
         return;
      }  else {
         jQuery('#password').removeClass('input-error');
         jQuery('#password-validation-message').html('');
      }    
  });  
  jQuery('#confirmedpassword').bind('blur change',function(e){
      e.preventDefault();
      var credential   = jQuery.trim(jQuery('#password').val());
      var credential2  = jQuery.trim(jQuery(this).val());
      if(credential2 !== credential){
         jQuery('#confirmedpassword').addClass('input-error');
         jQuery('#confirmedpassword-validation-message').html('');
         SIRAH.error.raise('confirmedpassword-validation-message','Les mots de passe sont differents');
         return;
      } else {
        jQuery('#confirmedpassword').removeClass('input-error');
        jQuery('#confirmedpassword-validation-message').html('');
      }      
  });  
  jQuery('#phone1').bind('blur change',function(e){
      e.preventDefault();
      var phone1 = jQuery.trim(jQuery(this).val());
      if(!SIRAH.util.isEmpty(phone1)){
        jQuery('#phone1').removeClass('input-error');
        jQuery('#phone-validation-message').html('');
      }  else {      
        jQuery('#phone1').addClass('input-error');
         return;     
      }
  });  
 jQuery('#cancelAccountCreationButton,.cancelAccountCreationButton').click(function(e){e.preventDefault();document.location.href='".$linkCancel."';}); ";
$jq->addOnLoad($onLoad);

?>
<form method="post" action="<?php echo $formSubmit; ?>" align="center" id="requestCreationForm"  class="form-horizontal" role="form" >
<ul class="list-group" style="margin-bottom:0 !important;">
   <li class="list-group-item">
     <div class="row">
         <div class="col-md-4"> <label class="label" for="lastname"> <b> Nom/Prénom: </b> </label> </div>
         <div class="col-md-4">
               <input id="lastname" type="text" maxlength="200" autocomplete="off" autocapitalize="off" autocorrect="off" 
                      title="Nom de famille" placeholder="Nom de famille"  name="lastname" value="<?php echo $data['lastname']; ?>">
         </div>
         <div class="col-md-4">
               <input id="firstname" type="text" maxlength="275" autocomplete="off" autocapitalize="off" autocorrect="off" title="Prénom" placeholder="Prénom"  name="firstname" value="<?php echo $data['firstname']; ?>">
         </div>
         <p id="name-validation-message" class="validation-message"></p>    
     </div>  
   </li>
   <li class="list-group-item">
     <div class="row">
         <div class="col-md-4"> <label class="label" for="email"> <b> Adresse email: </b> </label> </div>
         <div class="col-md-8">
               <input id="email" type="text" maxlength="220" autocomplete="off" autocapitalize="off" autocorrect="off" title="Adresse email" placeholder="Adresse email"  name="email" value="<?php echo $data['email']; ?>" />
         </div>  
         <p id="email-validation-message" class="validation-message"></p>      
     </div>  
   </li>  
   <li class="list-group-item">
     <div class="row">
         <div class="col-md-4"> <label class="label" for="password"> <b> Mot de passe : </b> </label> </div>
         <div class="col-md-8">
               <input id="password" type="password"  maxlength="32" autocomplete="off" autocapitalize="off" autocorrect="off" title="Mot de passe par défaut" placeholder="Mot de passe" name="password"  />
         </div>  
         <p id="password-validation-message" class="validation-message"></p>      
     </div>  
   </li>  
   <li class="list-group-item">
     <div class="row">
         <div class="col-md-4"> <label class="label" for="confirmedpassword"> <b> Confirmez le mot de passe : </b> </label> </div>
         <div class="col-md-8">
              <input id="confirmedpassword" type="password" maxlength="32" autocomplete="off" autocapitalize="off" autocorrect="off" 
                      title="Confirmez le mot de passe" placeholder="Confirmez le mot de passe" value="" name="confirmedpassword">
         </div>  
         <p id="confirmedpassword-validation-message" class="validation-message"></p>      
     </div>  
   </li>   
   <li class="list-group-item">
     <div class="row">
         <div class="col-md-4"> <label class="label" for="phone1"> <b> Téléphone mobile : </b> </label> </div>
         <div class="col-md-8">
              <input id="phone1" type="text"  maxlength="20" autocomplete="off" autocapitalize="off" autocorrect="off" title="Téléphone mobile" placeholder="Téléphone mobile" name="phone1" value="<?php echo $data['phone1']; ?>">
         </div>  
          <p id="phone-validation-message" class="validation-message"></p>   
     </div>  
   </li>
   <li class="list-group-item">      
      <div class="row">    
          <div class="col-md-4"> <label class="label" for="country"> <b> Pays * : </b> </label> </div>
          <div class="col-md-8"> <?php echo $this->formSelect("country" , $data['country'] , array() , $this->countries()); ?> </div>
      </div>
   </li>
   <li class="list-group-item">
     <div class="row">
         <div class="col-md-4"> <label class="label" for="sexe"> <b> Sexe: </b> </label> </div>
         <div class="col-md-4"> 
          <label class="radio-inline">
              <input type="radio" name="sexe" id="sexe-m" value="M" <?php if($data["sexe"] == "M") echo "checked"; ?>>
                Homme
          </label>
          
          <label class="radio-inline">
               <input type="radio" name="sexe" id="sexe-f" value="F" <?php if($data["sexe"] == "F") echo "checked"; ?>>
                  Femme
         </label>
         </div>
         <div class="col-md-4">
            &nbsp;
         </div>    
     </div>  
   </li>
</ul> 
<ul class="list-group" style="margin-bottom:0 !important;">
    <li class="list-group-item">  
        <div class="row">              
            <div class="col-md-4"> <label class="label" for="registre"> <b> Numéro RC*: </b> </label> </div>
            <div class="col-md-5">
                 <input id="numero" type="text" maxlength="16" autocomplete="off" autocapitalize="off" autocorrect="off" value="<?php echo $numrc; ?>"
                        title="Saisissez le numéro du registre de commerce" placeholder="Numéro de registre" name="numero" class="numero"  >
            </div>
            <div class="col-md-3">
               <div class="btn-group"><button title="Selectionnez un registre dans la liste des registres enregistrés" type="submit" class="btn btn-primary searchItem"><span class="glyphicon glyphicon-search"></span> Selectionnez </button></div>
            </div>
            <p id="registre-validation-message" class="validation-message"></p>    
        </div>
    </li>
    <li class="list-group-item">
     <div class="row">
         <div class="col-md-4"> <label class="label" for="typedocument"> <b> Type de document* : </b> </label> </div>
         <div class="col-md-8">  <?php echo $this->formSelect("typedocument", intval( $data['typedocument']) , array() , $typesDocuments); ?> </div>  
          <p id="typedocument-validation-message" class="validation-message"></p>   
     </div>  
   </li>
   <li class="list-group-item">
     <div class="row">
         <div class="col-md-3"> <label class="label" for="description"> <b> Nature de la demande: </b> </label> </div>
         <div class="col-md-8"> 
            <textarea name="description" id="description"><?php echo $data["description"]; ?> </textarea>
         </div>  
     </div>  
   </li>
 </ul> 

   <input id="t" type="hidden" name="t" value="<?php echo $token; ?>" /> 
   <input type="hidden" name="registreid"  id="registreid"  value="<?php echo $this->registreid; ?>"        />
   <input id="city" type="hidden" name="city"  value="" /> 
   <input type="hidden" name="selectRegistre"      id="selectRegistre"      />
</form>

<div class="panel-footer">
     <div class="btn-group"> <button class="btn btn-success createButton"> <i class="glyphicon glyphicon-floppy-disk"> </i> Enregistrer </button> </div>
     <div class="btn-group"> <button class="btn btn-danger  cancelAccountCreationButton"><i class="glyphicon glyphicon-ban-circle"> </i>  Annuler </button> </div>
</div>



