<?php 
    $promoteur     = $this->promoteur;
	$countries     = $this->countries();
	$identite      = $this->identite;
	$identiteTypes = $this->identiteTypes;
	$nationalite   = (isset($countries[$promoteur->nationalite]))?$countries[$promoteur->nationalite] : $promoteur->nationalite;
	$identiteType  = (isset($identiteTypes[$identite->typeid]  ))?$identiteTypes[$identite->typeid]   : "Pièce Identité";
	$identiteDate  = "00/00/0000";
	
	if( isset($identite->date_etablissement) && Zend_Date::isDate($identite->date_etablissement,"YYYY-MM-dd")) {
		$zendIdentiteDate = new Zend_Date($identite->date_etablissement,"YYYY-MM-dd");
		$identiteDate     = ($zendIdentiteDate)?$zendIdentiteDate->toString("dd MMM YYYY") : $identite->date_etablissement;
	}
?>
<ul class="list-group">
    <?php if($identite): ?>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"><b>Identité:</b></div> 
			<div class="col-md-8"><?php echo sprintf("%s n° %s du %s établi par %s %s",$identiteType,$identite->numero,$identiteDate,$identite->organisme_etablissement,$identite->lieu_etablissement); ?> </div>
		</div>
	</li>
	<?php endif; ?>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Nom & Prénom  :</b></div> 
			<div class="col-md-8"><?php echo $promoteur->name; ?></div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Sexe:</b></div> 
			<div class="col-md-8"> <?php echo ( $promoteur) ? (($promoteur->sexe == "M") ? "Homme": "Femme") : ""; ?> </div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Adresse:</b></div> 
			<div class="col-md-8"> <?php echo ( $promoteur) ? $promoteur->adresse : ""; ?> </div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Nationalité:</b></div> 
			<div class="col-md-8"> <?php echo $nationalite; ?> </div>
		</div>
	</li>		   
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Numéro de téléphone:</b></div> 
			<div class="col-md-8"> <?php echo ( $promoteur) ? $promoteur->telephone : ""; ?> </div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Adresse email:</b></div> 
			<div class="col-md-8"> <?php echo ( $promoteur) ? $promoteur->email : ""; ?> </div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Fonction/Profession:</b></div> 
			<div class="col-md-8"> <?php echo ( $promoteur) ? $promoteur->profession: ""; ?> </div>
		</div>
	</li>
</ul>