/* ******* On insère les roles propres à l'application ******** */
INSERT INTO `system_acl_roles` (`roleid` , `rolename` , `description` , `accesslevel` , `creatoruserid`)
VALUES (5 , 'Etudiant' , 'Le role associé aux étudiants de luniversité' ,  6  ,  1) , 
       (6 , 'Candidat'  ,  'Correspond aux candidats de luniversité'  ,  7  ,  1) , 
       (7 , 'Gestionnaire'  ,  'Correspond aux gestionnaires de luniversité'  ,  3  , 1) , 
       (8 , 'Comptables'  ,  'Correspond aux comptables de luniversité'  ,  4  , 1) , 
       (9 , 'Chefclasse'  ,  'Correspond aux chefs des classes de luniversité'  ,  5  , 1) ,
       (10, 'Commercial'  ,  'Correspond aux commerciaux de luniversité'  ,  4  , 1);
       
/* ******* On insère les roles parents par defaut de l'application ******** */
INSERT INTO `system_acl_parentroles` (`childroleid` , `parentroleid` , `creatoruserid`)
VALUES (5 , 6 , 1)  ,  (9 , 5 , 1) , (7 , 10 , 1) , (7 , 8 , 1) , (2 , 7 , 1);

/* ******* On insère les modules de la plateforme ******** */
INSERT INTO `system_acl_resource_modules` (`moduleid` , `modulename` , `description` , `creatoruserid`)
VALUES (2  ,  'crmanagement' , 'Gestion commerciale'  ,  1)  ,  
       (3  ,  'schoolfeesmanagement' , 'Gestion comptable'  ,  1)  , 
       (4  ,  'myspace' , 'Espace privé'  ,  1) , 
       (5  ,  'scolarship' , 'Gestion de la scolarité'  ,  1) , 
       (6  ,  'coursemanagement' , 'Gestion des cours'  ,  1)  ,  
       (7  ,  'resourcesmanagement' , 'Gestion des ressources'  ,  1) , 
       (8  ,  'examanagement' , 'Gestion des examens'  ,  1)  ,  
       (9  ,  'entreprisemangament' , 'Gestion de la structure'  ,  1);
       
/* ******* On insère les ressources de la plateforme ******** */
INSERT INTO `system_acl_resources` (`resourceid` , `resourcename` , `description` , `parentid` , `creatoruserid` , `moduleid` , `enabled`)
VALUES (11 , 'schoolcontacts' , 'Gestion des contacts de luniversité' , 0 , 1 , 2 , 1) , 
       (12 , 'candidats' , 'Gestion des candidats de luniversité' , 0 , 1 , 2 , 1) , 
       (13 , 'candidatinscription' , 'Gestion des roles des pré-inscriptions' , 0 , 1 , 2 , 1) , 
       (14 , 'schoolemailing' , 'Gestion du système demailing ' , 0 , 1 , 2 , 1) ,        
       /* ******* Module de gestion de la comptabilité ******** */
       (15 , 'schoolfees' , 'Suivi des paiements de frais de scolarité' , 0 , 1 , 3 , 1) , 
       (16 , 'schoolfeesinscription' , 'Gestion des frais dinscription' , 0 , 1 , 3 , 1) , 
       (17 , 'honorairefees' , 'Gestion des paiements honoraires' , 0 , 1 , 3 , 1) , 
       (18 , 'schoolorders' , 'Gestion des commandes' , 0 , 1 , 3 , 1) , 
       (19 , 'achats' , 'Gestion des achats' , 0 , 1 , 3 , 1) ,
       (20 , 'reglements' , 'Gestion des paiements de prestataires' , 0 , 1 , 3 , 1) , 
       (21 , 'prestataires' , 'Gestion des fournisseurs/prestataires' , 0 , 1 , 3 , 1),
       (22 , 'bilancomptable' , 'Bilan des paiements' , 0 , 1 , 3 , 1),
        /* ******* Module de gestion de la scolarité ******** */
       (23 , 'inscriptions' , 'Gestion des inscriptions' , 0 , 1 , 5 , 1) , 
       (24 , 'honoraires' , 'Gestion des honoraires' , 0 , 1 , 5 , 1) , 
       (25 , 'cohortes' , 'Gestion des cohortes' , 0 , 1 , 5 , 1) , 
       (26 , 'statistiques' , 'Statistiques des inscriptions' , 0 , 1 , 5 , 1) , 
        /* ******* Module de gestion des modules de cours ******** */
       (27 , 'coursemodule' , 'Gestion des modules de cours' , 0 , 1 , 6 , 1) , 
       (28 , 'courseinstance' , 'Gestion des instances des cours' , 0 , 1 , 6 , 1) , 
       (29 , 'courseschedule' , 'Programme des cours' , 0 , 1 , 6 , 1) , 
       (30 , 'coursesubscription' , 'Répartition des cours' , 0 , 1 , 6 , 1) ,
       (31 , 'coursecategories' , 'Gestion des catégories des cours' , 0 , 1 , 6 , 1) , 
       (32 , 'courseabsence' , 'Gestion des absences' , 0 , 1 , 6 , 1) ,
       (33 , 'coursedelays' , 'Gestion des retards' , 0 , 1 , 6 , 1) ,
       (34 , 'courselevels' , 'Les niveaux détudes' , 0 , 1 , 6 , 1) ,
       (35 , 'coursefilieres' , 'Les filières des cours' , 0 , 1 , 6 , 1) ,
       /* ******* Module de gestion des ressources pédagogiques ******** */
       (36 , 'classrooms' , 'Gestion des salles de cours' , 0 , 1 , 7 , 1) , 
       (37 , 'classtools' , 'Gestion du matériel de cours' , 0 , 1 , 7 , 1) , 
       (38 , 'classlibrary' , 'Bibliothèque numérique' , 0 , 1 , 7 , 1) , 
       (39 , 'classmemories' , 'Mémoires détudes' , 0 , 1 , 7 , 1) , 
       (40 , 'classdocuments' , 'Gestion des documents' , 0 , 1 , 7 , 1) , 
        /* ******* Module de gestion des examens ******** */
       (41 , 'classexams' , 'Gestion des examens' , 0 , 1 , 7 , 1) , 
       (42 , 'classprep' , 'Gestion des devoirs' , 0 , 1 , 7 , 1) , 
       (43 , 'classprepresult' , 'Gestion des notes' , 0 , 1 , 7 , 1) , 
       (44 , 'classexamresult' , 'Gestion des résultats' , 0 , 1 , 7 , 1) ,       
        /* ******* Module de gestion des examens ******** */
       (45 , 'entreprise' , 'Gestion de la structure' , 0 , 1 , 8 , 1) , 
       (46 , 'entreprisemembers' , 'Gestion du personnel' , 0 , 1 , 8 , 1) , 
       (47 , 'entrepriseservices' , 'Gestion des services' , 0 , 1 , 8 , 1) , 
       (48 , 'entreprisemissions' , 'Gestion des missions' , 0 , 1 , 8 , 1) ;
       
 /* ******* On insère les objets ACL par defaut de la plateforme *********/
INSERT INTO `system_acl_objects` (`objectid` , `objectname` , `description` , `creatoruserid` , `resourceid`)
VALUES (70 , 'list' , "lister tous les contacts de l'université" , 1 , 11) , 
       (71 , 'create' , "Créer des contacts pour l'université" , 1 , 11) , 
       (72 , 'edit' , "Mettre a jour les informations d'un contact de l'université" , 1 , 11) , 
       (73 , 'delete' , "Supprimer un contact de l'université" , 1 , 1) , 
       (74 , 'infos' , "Accéder aux informations d'un contact de l'université" , 1 , 11) , 
       (75 , 'candidateconvert' , " Convertir un contact en candidat " , 1 , 11) , 
       (76 , 'studentconvert' , "Convertir un contact en étudiant" , 1 , 11) , 
       (77 , 'export' , "Exporter les contacts de l'université" , 1 , 11) , 
       (78 , 'import' , "Importer des nouveaux contacts" , 1 , 11) , 
       (79 , 'sendmail' , "Envoyer un email à un contact" , 1 , 11) ,
       (80 , 'list' , "Lister les candidats qui ont postulé à des formations / cours" , 1 , 12) ,
       (81 , 'create' , "Enregistrer un nouveau candidat" , 1 , 12) ,
       (82 , 'edit' , "Mettre à jour les informations d'un candidat" , 1 , 12) ,
       (83 , 'delete' , "Supprimer des candidats" , 1 , 12) ,
       (84 , 'infos' , "Accéder aux informations d'un candidat" , 1 , 12) ,
       (85 , 'create' , "Créer / Enregistrer le dossier de candidature d'un candidat" , 1 , 13) ,
       (86 , 'delete' , " Supprimer le dossier de candidature d'un candidat" , 1 , 13) ,
       (87 , 'infos' , "Accéder aux informations de candidature d'un candidat" , 1 , 13) ,
       (88 , 'edit' , "Mettre à jour le dossier de candidature d'un candidat" , 1 , 13) ,
       (89 , 'export' , "Exporter le dossier de candidature d'un candidat" , 1 , 13),
       (90 , 'create' , "Créer une newsletter à transmettre par email" , 1 , 14) ,
       (91 , 'addcontact' , "Ajouter des contacts pour l'envoi de la newsletter" , 1 , 14) ,
       (92 , 'removecontact' , "Supprimer des contacts de la liste des contacts destinataires de l'email" , 1 , 14) ,
       (93 , 'edit' , "Mettre à jour les informations d'une newsletter" , 1 , 14) ,
       (94 , 'insertdocument' , "Ajouter une pièce jointe dans la newsletter" , 1 , 14) ,
       (95 , 'removedocument' , "Ajouter des contacts pour l'envoi de la newsletter" , 1 , 14) ,
       (96 , 'send' , "Permet d'envoyer la newsletter" , 1 , 14) ,
       (97 , 'delete' , "Supprimer une newsletter" , 1 , 14) ,
       (98 , 'list' , "Lister les paiements des frais de scolarité" , 1 , 15) ,
       (99 , 'delete' , "Supprimer une entrée de paiement de frais de scolarité" , 1 , 15) ,
       (100 ,'create' , "Enregistrer un paiement de frais de scolarité" , 1 , 15) ,
       (101 ,'export' , "Exporter la liste des paiements des frais de scolarité" , 1 , 15) ,
       (102 ,'infos' , "Accéder aux informations d'un paiement de frais de scolarité" , 1 , 15) ,
       (103 ,'print' , "Générer et imprimer une quittance de paiement de scolarité" , 1 , 15) ,
       (104 ,'create' , "Enregistrer un paiement de frais de d'inscription" , 1 , 16) ,
       (105 ,'infos' , "Accéder aux informations du paiement de frais de d'inscription" , 1 , 16) ,
       (106 ,'export' , "Exporter la liste des frais de d'inscription" , 1 , 16) ,
       (107 ,'delete' , "Supprimer un paiement de frais de d'inscription" , 1 , 16) ,
       (108 ,'print' , "Générér / Imprimer une quittance de paiement de frais de d'inscription" , 1 , 16) ,
       (109 ,'list' , "Lister les entrées des paiements des frais d'inscription" , 1 , 16) ,
       (110 ,'create' , "Enregistrer un paiement de frais d'honoraires" , 1 , 17) ,
       (111 ,'infos' , "Accéder aux informations du paiement de frais d'honoraires" , 1 , 17) ,
       (112 ,'export' , "Exporter la liste des paiements des frais de d'honoraires" , 1 , 17) ,
       (113 ,'delete' , "Supprimer un paiement de frais de d'honoraires" , 1 , 17) ,
       (114 ,'print' , "Générér / Imprimer une quittance de paiement de frais de d'honoraires" , 1 , 17) ,
       (115 ,'list' , "Lister les entrées des paiements des frais d'honoraires" , 1 , 17) ,
       (116 ,'create' , "Enregistrer une commande émise par l'université" , 1 , 18) ,
       (117 ,'infos' , "Accéder aux informations d'uns commande émise par l'université" , 1 , 18) ,
       (118 ,'list' , "Lister les commandes emises par l'université" , 1 , 18) ,
       (119 ,'delete' , "Supprimer une commande" , 1 , 18) ,
       (120 ,'addligne' , "Enregistrer une ligne de commande" , 1 , 18) ,
       (121 ,'removeligne' , "Supprimer une ligne de commande" , 1 , 18) ,
       (122 ,'edit' , "Mettre à jour les informations d'une commande émise par l'université" , 1 , 18) ,
       (123 ,'list' , "Lister les achats effectués par l'université" , 1 , 19) ,
       (124 ,'create' , "Enregistrer un achat de produit effectué par l'université" , 1 , 19) ,
       (125 ,'delete' , "Supprimer un achat de produit effectué par l'université" , 1 , 19) ,
       (126 ,'infos' , "Acceder aux informations d'un achat de produit effectué par l'université" , 1 , 19) ,
       (127 ,'list' , "Lister les paiements des prestataires de l'université" , 1 , 20) ,
       (128 ,'delete' , "Supprimer une entrée de paiement de prestataire" , 1 , 20) ,
       (129 ,'create' , "Enregistrer une entrée de paiement de prestataire" , 1 , 20) ,
       (130 ,'infos' , "Accéder aux informations d'une entrée de paiement de prestataire" , 1 , 20) ,
       (131 ,'print' , "Générer / Imprimer la quittance d'une entrée de paiement de prestataire" , 1 , 20) ,
       (132 ,'list' , "Lister les prestataires de l'université" , 1 , 21) ,
       (133 ,'create' , "Enregistrer un nouveau prestataire pour l'université" , 1 , 21) ,
       (134 ,'infos' , "Accéder aux informations d'un prestataire de l'université" , 1 , 21) ,
       (135 ,'edit' , "Mettre à jour les informations d'un prestataire de l'université" , 1 , 21) ,
       (136 ,'delete' , "Supprimer les informations d'un prestataire de l'université" , 1 , 21) ,
       (137 ,'infos' , "Visualiser les informations du bilan de la comptabilité" , 1 , 22) ,
       (138 ,'list' , "Lister les inscriptions des différents étudiants de l'université" , 1 , 23) ,
       (139 ,'create' , "Enregistrer une nouvelle inscription d'étudiants" , 1 , 23) ,
       (140 ,'infos' , "Accéder aux informations de l'inscription d'un étudiant" , 1 , 23) ,
       (141 ,'delete' , "Supprimer les informations d'une inscription d'étudiant" , 1 , 23) ,
       (142 ,'edit' , "Mettre à jour les informations de l'inscription d'étudiants" , 1 , 23) ,
       (143 ,'import' , "Importer les inscriptions des étudiants à partir d'un fichier excel" , 1 , 23) ,
       (144 ,'export' , "Exporter la liste des inscriptions des étudiants  en PDF" , 1 , 23) ,
       (145 ,'print' , "Générer / Imprimer la fiche d'inscription d'un étudiant" , 1 , 23) ,
       (146 ,'list' , "Lister les honoraires des professeurs de l'université" , 1 , 24) ,
       (147 ,'create' , "Enregistrer une nouvelle honoraire" , 1 , 24) ,
       (148 ,'infos' , "Accéder aux informations de l'honoraire d'un professeur" , 1 , 24) ,
       (149 ,'delete' , "Supprimer les informations d'une honoraire" , 1 , 24) ,
       (150 ,'edit' , "Mettre à jour les informations de l'honoraire d'un professeur" , 1 , 24) ,
       (151 ,'export' , "Exporter les honoraires des professeurs de l'université" , 1 , 24) ,
       (152 ,'list' , "Lister les cohortes / classes auxquelles sont inscrits les étudiants" , 1 , 25) ,
       (153 ,'create' , "Enregistrer une nouvelle cohorte" , 1 , 25) ,
       (154 ,'infos' , "Accéder aux informations d'une cohorte" , 1 , 25) ,
       (155 ,'delete' , "Supprimer les informations d'une cohorte" , 1 , 25) ,
       (156 ,'edit' , "Mettre à jour les informations d'une cohorte" , 1 , 25) ,
       (157 ,'export' , "Exporter la liste des cohortes" , 1 , 25) ,
       (158 ,'infos' , "Accéder aux informations statistiques des inscriptions des étudiants" , 1 , 26) ,
       (159 ,'list' , "Lister les modules des cours / formations de l'université" , 1 , 27) ,
       (160 ,'create' , "Enregistrer un nouveau module de cours" , 1 , 27) ,
       (161 ,'infos' , "Accéder aux informations d'un module de cours" , 1 , 27) ,
       (162 ,'delete' , "Supprimer un module de cours " , 1 , 27) ,
       (163 ,'edit' , "Mettre à jour les informations d'un module de cours" , 1 , 27) ,
       (164 ,'list' , "Lister les instances de cours constitutives de l'emploi du temps" , 1 , 28) ,
       (165 ,'create' , "Enregistrer une nouvelle instance de cours dans le programme" , 1 , 28) ,
       (166 ,'infos' , "Accéder aux informations d'une instance de cours" , 1 , 28) ,
       (167 ,'delete' , "Supprimer une instance de cours du programme " , 1 , 28) ,
       (168 ,'edit' , "Mettre à jour les informations d'une instance de cours" , 1 , 28) ,
       (169 ,'sharedocument' , "Partager des documents dans une instance de cours" , 1 , 28) ,
       (170 ,'removedocument' , "Supprimer un document d'une instance de cours" , 1 , 28) ,
       (171 ,'associateresource' , "Associer une ressource à une instance de cours" , 1 , 28) ,
       (172 ,'removeresource' , "Rétirer une ressource d'une instance de cours" , 1 , 28) ,
       (173 ,'list' , "Lister les différentes répartitions des cours par cohorte" , 1 , 30) ,
       (174 ,'create' , "Enregistrer une nouvelle liaison de cours-cohorte" , 1 , 30) ,
       (175 ,'infos' , "Accéder aux informations d'une laison de cours-cohortes" , 1 , 30) ,
       (176 ,'delete' , "Supprimer une liaison de cours-cohortes " , 1 , 30) ,
       (177 ,'edit' , "Mettre à jour les informations d'une laison de cours-cohortes" , 1 , 30) ,
       (178 ,'list' , "Lister les différentes catégories de modules de cours" , 1 , 31) ,
       (179 ,'create' , "Enregistrer une nouvelle catégorie de cours" , 1 , 31) ,
       (180 ,'infos' , "Accéder aux informations d'une catégorie de cours" , 1 , 31) ,
       (181 ,'delete' , "Supprimer une catégorie des cours" , 1 , 31) ,
       (182 ,'edit' , "Mettre à jour les informations d'une catégorie de cours" , 1 , 31) ,
       (183 ,'list' , "Lister les absences des différents utilisateur" , 1 , 32) ,
       (184 ,'create' , "Enregistrer une nouvelle absence d'utilisateur" , 1 , 32) ,
       (185 ,'infos' , "Accéder aux informations d'une absence d'utilisateur" , 1 , 32) ,
       (186 ,'delete' , "Supprimer une absence d'utilisateur" , 1 , 33) ,
       (187 ,'edit' , "Mettre à jour les informations d'une absence d'utilisateur" , 1 , 33) ,
       (188 ,'list' , "Lister les retards des différents utilisateur" , 1 , 33) ,
       (189 ,'create' , "Enregistrer un retard d'utilisateur" , 1 , 33) ,
       (190 ,'infos' , "Accéder aux informations d'un retard d'utilisateur" , 1 , 33) ,
       (191 ,'delete' , "Supprimer un retard d'utilisateur" , 1 , 33) ,
       (192 ,'edit' , "Mettre à jour les informations d'un retard d'utilisateur" , 1 , 33) ,
       (193 ,'list' , "Lister les filières associées aux cohortes" , 1 , 34) ,
       (194 ,'create' , "Enregistrer une nouvelle filière" , 1 , 34) ,
       (195 ,'infos' , "Accéder aux informations d'une filière" , 1 , 34) ,
       (196 ,'delete' , "Supprimer une filière" , 1 , 34) ,
       (197 ,'edit' , "Mettre à jour les informations d'une filière" , 1 , 34) ,
       (198 ,'list' , "Lister les niveaux d'études associés aux cohortes" , 1 , 35) ,
       (199 ,'create' , "Enregistrer un nouveau niveau d'études" , 1 , 35) ,
       (200 ,'infos' , "Accéder aux informations d'un niveau d'étude" , 1 , 35) ,
       (201 ,'delete' , "Supprimer un niveau d'études" , 1 , 35) ,
       (202 ,'edit' , "Mettre à jour les informations d'un niveau d'études" , 1 , 35) ,
       (203 ,'list' , "Lister les différentes salles de cours de l'université" , 1 , 36) ,
       (204 ,'create' , "Enregistrer une nouvelle salle de cours" , 1 , 36) ,
       (205 ,'infos' , "Accéder aux informations d'une salle de cours" , 1 , 36) ,
       (206 ,'delete' , "Supprimer une salle de cours" , 1 , 36) ,
       (207 ,'edit' , "Mettre à jour les informations d'une salle des cours" , 1 , 36) ,
       (208 ,'list' , "Lister les outils du matériel pédagogique de l'université" , 1 , 37) ,
       (209 ,'create' , "Enregistrer un nouvel outil pédagogique" , 1 , 37) ,
       (210 ,'infos' , "Accéder aux informations d'un outil pédagogique" , 1 , 37) ,
       (211 ,'delete' , "Supprimer un outil pédagogique" , 1 , 37) ,
       (212 ,'edit' , "Mettre à jour les informations d'un outil pédagogique" , 1 , 37) ,
       (213 ,'list' , "Lister les documents disponibles dans la bibliothèque numérique" , 1 , 38) ,
       (214 ,'create' , "Enregistrer un nouveau document dans la bibliothèque numérique" , 1 , 38) ,
       (215 ,'infos' , "Accéder aux informations d'un document de la bibliothèque numérique" , 1 , 38) ,
       (216 ,'delete' , "Supprimer un document de la bibliothèque numérique" , 1 , 38) ,
       (217 ,'edit' , "Mettre à jour les informations d'un document de la bibliothèque numérique" , 1 , 38) ,
       (218 ,'listcategories' , "Lister les catégories des documents de la bibliothèque numérique" , 1 , 38) ,
       (219 ,'createcategory' , "Enregistrer une catégorie de document de la bibliothèque numérique" , 1 , 38) ,
       (220 ,'deletecategory' , "Supprimer une catégorie de document de la bibliothèque numérique" , 1 , 38) ,
       (221 ,'editcategory' , "Mettre à jour les informations d'une catégorie de document de la bibliothèque numérique" , 1 , 38) ,
       (222 ,'infoscategory' , "Accéder aux informations d'une catégorie de document de la bibliothèque numérique" , 1 , 38) ,
       (223 ,'list' , "Lister les mémoires d'étude des étudiants de l'université" , 1 , 39) ,
       (224 ,'create' , "Enregistrer un mémoire d'études" , 1 , 39) ,
       (225 ,'delete' , "Supprimer un mémoire d'études" , 1 , 39) ,
       (226 ,'edit' , "Mettre à jour les informations d'un mémoire d'études" , 1 , 39) ,
       (227 ,'infos' , "Accéder aux informations d'un mémoire d'études" , 1 , 39) ,
       (228 ,'list' , "Lister les examens enregistrés dans le système" , 1 , 41) ,
       (229 ,'create' , "Enregistrer un nouvel examen" , 1 , 41) ,
       (230 ,'delete' , "Supprimer un examen du système" , 1 , 41) ,
       (231 ,'edit' , "Mettre à jour les informations d'un examen" , 1 , 41) ,
       (232 ,'infos' , "Accéder aux informations d'un examen" , 1 , 41) ,
       (233 ,'list' , "Lister les devoirs programmés pour les différentes classes" , 1 , 42) ,
       (234 ,'create' , "Enregistrer un nouveau devoir" , 1 , 42) ,
       (235 ,'delete' , "Supprimer un devoir" , 1 , 42) ,
       (236 ,'edit' , "Mettre à jour les informations d'un devoir" , 1 , 42) ,
       (237 ,'infos' , "Accéder aux informations d'un devoir" , 1 , 42) ,
       (238 ,'list' , "Afficher les résultats des différents devoirs des étudiants " , 1 , 43) ,
       (239 ,'create' , "Attribuer des notes aux devoirs des étudiants" , 1 , 43) ,
       (240 ,'delete' , "Supprimer une note de devoir" , 1 , 43) ,
       (241 ,'edit' , "Mettre à jour les informations d'une note de devoir" , 1 , 43) ,
       (242 ,'infos' , "Accéder aux informations d'une note de devoir" , 1 , 43) ,
       (243 ,'list' , "Afficher les résultats des examens des étudiants " , 1 , 44) ,
       (244 ,'create' , "Enregistrer les resultats d'examen d'un étudiant" , 1 , 44) ,
       (245 ,'edit' , "Mettre à jour les informations d'un résultat d'examen" , 1 , 44) ,
       (246 ,'infos' , "Accéder aux informations d'un résultat d'examen" , 1 , 44) ,
       (247 ,'list' , "Afficher les entreprises enregistrées dans le système " , 1 , 45) ,
       (248 ,'create' , "Enregistrer une entreprise dans le système" , 1 , 45) ,
       (249 ,'delete' , "Supprimer une entreprise" , 1 , 45) ,
       (250 ,'edit' , "Mettre à jour les informations d'une entreprise" , 1 , 45) ,
       (251 ,'infos' , "Accéder aux informations d'une entreprise" , 1 , 45) ,
       (252 ,'list' , "Lister les membres du personnel de l'entreprise " , 1 , 46) ,
       (253 ,'create' , "Enregistrer un nouveau membre du personnel de l'entreprise" , 1 , 46) ,
       (254 ,'delete' , "Supprimer un nouveau membre du personnel de l'entreprise" , 1 , 46) ,
       (255 ,'edit' , "Mettre à jour les informations d'un membre du personnel de l'entreprise" , 1 , 46) ,
       (256 ,'infos' , "Accéder aux informations d'un membre du personnel de l'entreprise" , 1 , 46) ,
       (257 ,'list' , "Lister les différents services / formations proposés par l'université " , 1 , 47) ,
       (258 ,'create' , "Enregistrer un nouveau service / formation proposé par l'université" , 1 , 47) ,
       (259 ,'delete' , "Supprimer un service / formation proposé par l'université" , 1 , 47) ,
       (260 ,'edit' , "Mettre à jour les informations d'un service / formation proposé" , 1 , 47) ,
       (261 ,'infos' , "Accéder aux informations d'un service / formation proposé par l'université" , 1 , 47) ,
       (262 ,'list' , "Lister les différents missions des membres du personnel " , 1 , 48) ,
       (263 ,'create' , "Enregistrer une mission du membre du personnel" , 1 , 48) ,
       (264 ,'delete' , "Supprimer une mission du membre du personnel" , 1 , 48) ,
       (265 ,'edit' , "Mettre à jour les informations d'une mission" , 1 , 48) ,
       (266 ,'infos' , "Accéder aux informations d'une mission" , 1 , 48) , 
       (267 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des contacts" , 1 , 11) ,
       (268 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des candidats" , 1 , 12) ,
       (269 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des candidatures" , 1 , 13) ,
       (270 ,'all' , "Accéder à toutes les fonctionnalités du système d'emailing" , 1 , 14) , 
       (271 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des frais de scolarité" , 1 , 15) ,
       (272 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des frais d'inscription" , 1 , 16) , 
       (273 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des frais d'honoraires" , 1 , 17) , 
       (274 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des commandes" , 1 , 18) , 
       (275 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des achats" , 1 , 19) ,
       (276 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des règlements de prestataires" , 1 , 20) ,
       (277 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des prestataires" , 1 , 21) ,
       (278 ,'all' , "Accéder à toutes les fonctionnalités du bilan de la comptabilité" , 1 , 22) ,
       (279 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des inscriptions" , 1 , 23) ,
       (280 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des honoraires" , 1 , 24) ,
       (281 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des cohortes" , 1 , 25) ,
       (282 ,'all' , "Accéder à toutes les fonctionnalités des statistiques" , 1 , 26) ,
       (283 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des modules de cours" , 1 , 27) ,
       (284 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des instances des cours" , 1 , 28) ,
       (285 ,'all' , "Accéder à toutes les fonctionnalités de la gestion de la programmation des cours" , 1 , 29) ,
       (286 ,'all' , "Accéder à toutes les fonctionnalités de l'inscription des cohortes aux cours" , 1 , 30) ,
       (287 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des catégories de cours" , 1 , 31) ,
       (288 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des absences" , 1 , 32) ,
       (289 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des retards" , 1 , 33) ,
       (290 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des niveaux d'études" , 1 , 34) ,
       (291 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des filières" , 1 , 35) ,
       (292 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des salles de cours" , 1 , 36) ,
       (293 ,'all' , "Accéder à toutes les fonctionnalités de la gestion du matériel pédagogique" , 1 , 37) ,
       (294 ,'all' , "Accéder à toutes les fonctionnalités de la gestion de la bibliothèque numérique" , 1 , 38) ,
       (295 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des mémoires d'étude" , 1 , 39) ,
       (296 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des documents des classes" , 1 , 40) ,
       (297 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des examens" , 1 , 41) ,
       (298 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des devoirs" , 1 , 42) , 
       (299 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des notes de devoirs" , 1 , 43) ,
       (300 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des résultats d'examens" , 1 , 44) ,
       (301 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des entreprises" , 1 , 45) ,
       (302 ,'all' , "Accéder à toutes les fonctionnalités de la gestion du personnel de l'entreprise" , 1 , 46) ,
       (303 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des services de formation de l'entreprise" , 1 , 47) ,
       (304 ,'all' , "Accéder à toutes les fonctionnalités de la gestion des missions" , 1 , 48) ,        
       (305 ,'list' , "Lister les dossiers de candidature des candidats" , 1 , 13) ,
       (306 ,'list' , "Lister les newsletters du système d'emailing" , 1 , 14),
       (307 ,'delete' , "Supprimer un résultat d'examen" , 1 , 44);
        
 /**** On définit les permissions par défaut attribuées à chaque role ****/  
       INSERT INTO `system_acl_rights` (`objectid` , `roleid` , `userid` , `allow` , `creatoruserid`)
	   VALUES (267 , 10 , 0 , 1 , 1), /** Les commerciaux accèdent à toutes les fonctionnalités de gestion des contacts **/
	          (268 , 10 , 0 , 1 , 1), /** Les commerciaux accèdent à toutes les fonctionnalités de gestion des candidats **/
			  (269 , 10 , 0 , 1 , 1), /** Les commerciaux accèdent à toutes les fonctionnalités de gestion des candidatures **/
			  (270 , 10 , 0 , 1 , 1), /** Les commerciaux accèdent à toutes les fonctionnalités de gestion du système d'emailing **/
			  (271 , 8 , 0 , 1 , 1), /** Les comptables accèdent à toutes les fonctionnalités de gestion des frais de scolarité **/
			  (272 , 8 , 0 , 1 , 1), /** Les comptables accèdent à toutes les fonctionnalités de gestion des frais d'inscriptions **/
			  (273 , 8 , 0 , 1 , 1), /** Les comptables accèdent à toutes les fonctionnalités de gestion des frais d'honoraires **/
			  (274 , 8 , 0 , 1 , 1), /** Les comptables accèdent à toutes les fonctionnalités de gestion des commandes initiées avec les fournisseurs **/
			  (275 , 8 , 0 , 1 , 1), /** Les comptables accèdent à toutes les fonctionnalités de gestion des achats **/
			  (276 , 8 , 0 , 1 , 1), /** Les comptables accèdent à toutes les fonctionnalités de gestion des règlements des prestataires **/
			  (277 , 8 , 0 , 1 , 1), /** Les comptables accèdent à toutes les fonctionnalités de gestion des commandes initiées avec les fournisseurs **/
			  (278 , 7 , 0 , 1 , 1), /** Les comptables accèdent à toutes les fonctionnalités du bilan comptable **/
			  (279 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des inscriptions **/
			  (280 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des honoraires **/
			  (281 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des cohortes **/
			  (282 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des statistiques **/
			  (283 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des modules de cours **/
			  (284 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des instances des cours **/
			  (285 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion de la programmation des cours **/
			  (286 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de l'inscription des cohortes aux cours **/
			  (287 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des catégories de cours **/
			  (288 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des absences aux cours **/
			  (289 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des retards **/
			  (290 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des niveaux d'études **/
			  (291 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des filières **/
			  (292 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des salles de cours **/
			  (293 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion du matériel pédagogique **/
			  (294 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion de la bibliothèque numérique **/
			  (295 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des mémoires d'études **/
			  (296 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des documents des cohortes **/
			  (297 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des examens **/
			  (298 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des devoirs **/
			  (299 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des notes de devoirs **/
			  (300 , 7 , 0 , 1 , 1), /** Les gestionnaires accèdent à toutes les fonctionnalités de gestion des résultats d'examens **/
			  (301 , 2 , 0 , 1 , 1), /** Les administrateurs accèdent à toutes les fonctionnalités de gestion des entreprises **/
			  (302 , 2 , 0 , 1 , 1), /** Les administrateurs accèdent à toutes les fonctionnalités de gestion du personnel de l'entreprise **/
			  (303 , 2 , 0 , 1 , 1), /** Les administrateurs accèdent à toutes les fonctionnalités de gestion des prestations de l'entreprise **/
			  (304 , 2 , 0 , 1 , 1), /** Les administrateurs accèdent à toutes les fonctionnalités de gestion des missions **/
			  (269 , 6 , 0 , 1 , 1) /** Les candidats accèdent à toutes les fonctionnalités de candidatures **/ ;
			  
INSERT INTO `system_layout_menu` (`menuid` , `menuname` , `description` , `position` , `creatoruserid` )
VALUES (3  ,  "Gestion de la scolarité"  ,  "Le module de la gestion "  ,  "left"  ,  1 ),
       (4  ,  "Gestion Commerciale"  ,  "Le module de gestion commerciale"  ,  "left"  ,  1 )  , 
       (5  ,  "Gestion Comptable"  ,  "Le module de gestion de la comptabilité"  ,  "left"  ,  1 ) , 
	   (6  ,  "Espace des cours"  ,  "Le module de gestion des cours"  ,  "left"  ,  1 ) , 
	   (7  ,  "Gestion des ressources"  ,  "Le module de gestion des ressources et documents de l'université"  ,  "right"  ,  1 ) ,
	   (8  ,  "Espace des examens"  ,  "Le module de gestion des examens et devoirs de l'université"  ,  "right"  ,  1 ) ;
	  
INSERT INTO `system_layout_menu_element` (`elementid` , `elementname`  ,  `elementlink` , `description` , `elementicon` , `aclobjectid` , `menuid`  ,  `elementorder`  , `creatoruserid` )
VALUES (10  ,  "Gestion des contacts"  , ""  ,  "Gérer les contacts de l'université"  , "glyphicon glyphicon-user"  ,   70  ,  4  ,  2  , 1)  , 
       (11  ,  "Gestion des candidats"  , ""  ,  "Gérer les candidats qui ont postulé à des ormations"  , "glyphicon glyphicon-user"  , 80  ,  4  ,  2 , 1)  , 
	   (12  ,  "Les candidatures"  , ""  ,  "Gérer les candidatures des étudiants"  , "glyphicon glyphicon-user"  ,  305  ,  4  ,  2 , 1 ) , 
	   (13  ,  "Campagnes e-mailing"  , ""  ,  "Gérer vos campagnes de communication"  , "glyphicon glyphicon-user"  ,  306  ,  4  ,  2 , 1 ) ,
	   (14  ,  "Frais de scolarité"  , ""  ,  "Gérer les frais de scolarité"  , "glyphicon glyphicon-user"  , 98  ,  5  ,  3  , 1) , 
	   (15  ,  "Frais d'inscription"  , ""  ,  "Gérer les frais d'inscription"  , "glyphicon glyphicon-user"  , 109 ,  5  ,  3  , 1) ,
	   (16  ,  "Frais d'honoraires"  , ""  ,  "Gérer les frais d'honoraires"  , "glyphicon glyphicon-user"  , 115  ,  5  ,  3  , 1) ,
	   (17  ,  "Gestion des commandes"  , ""  ,  "Gérer les commandes émises par l'université"  , "glyphicon glyphicon-user"  , 118  ,  5  ,  3  , 1) ,
	   (18  ,  "Gestion des achats"  , ""  ,  "Gérer les achats initiés par l'université"  , "glyphicon glyphicon-user"  , 123  ,  5  ,  3  , 1) ,
	   (19  ,  "Gestion des règlements"  , ""  ,  "Gérer les paiements des prestataires"  , "glyphicon glyphicon-user"  , 127  ,  5  ,  3  , 1) ,
	   (20  ,  "Gestion des prestataires"  , ""  ,  "Gérer les prestataires qui collaborent avec l'université"  , "glyphicon glyphicon-user"  , 132  ,  5  ,  3  , 1) ,
	   (21  ,  "Bilan comptable"  , ""  ,  "Accéder au bilan de la comptabilité de l'université"  , "glyphicon glyphicon-user"  , 137  ,  5  ,  3  , 1) ,
	   (22  ,  "Gestion des inscriptions"  , ""  ,  "Gérer les inscriptions des étudiants"  , "glyphicon glyphicon-user"  , 138  ,  3 ,  4  , 1) ,
	   (23  ,  "Gestion des honoraires"  , ""  ,  "Gérer les honoraires des professeurs"  , "glyphicon glyphicon-user"  , 146 ,  3 ,  4  , 1) ,
	   (24  ,  "Gestion des cohortes"  , ""  ,  "Gérer les cohortes de l'université"  , "glyphicon glyphicon-user"  ,  152  ,  3 ,  4  , 1) ,
	   (25  ,  "Statistiques"  , ""  ,  "Les statistiques des inscriptions des étudiants"  , "glyphicon glyphicon-user"  , 158  ,  3 ,  4  , 1) ,
	   (26  ,  "Gestion des modules"  , ""  ,  "Gérer les modules des cours"  , "glyphicon glyphicon-user"  , 159  ,  6 ,  5  , 1) ,
	   (27  ,  "Gestion des instances"  , ""  ,  "Gérer les instances des cours"  , "glyphicon glyphicon-user"  , 164  ,  6 ,  5  , 1) ,
	   (28  ,  "Programme"  , ""  ,  "Accéder aux programmes des cours"  , "glyphicon glyphicon-user"  , 0  ,  6 ,  5  , 1) ,
	   (29  ,  "Souscription"  , ""  ,  "Gérer les souscriptions aux cours"  , "glyphicon glyphicon-user"  , 173 ,  6 ,  5  , 1) ,
	   (30  ,  "Gestion des catégories"  , ""  ,  "Gérer les catégories des cours"  , "glyphicon glyphicon-user"  , 178  ,  6 ,  5  , 1) ,
	   (31  ,  "Gestion des absences"  , ""  ,  "Gérer les absences aux cours des étudiants"  , "glyphicon glyphicon-user"  , 183 ,  6 ,  5  , 1) ,
	   (32  ,  "Gestion des retards"  , ""  ,  "Gérer les retards"  , "glyphicon glyphicon-user"  , 188 ,  6 ,  5  , 1) ,
	   (33  ,  "Gestion des salles"  , ""  ,  "Gérer les salles des cours"  , "glyphicon glyphicon-user"  , 203,  7 ,  6  , 1) ,
	   (34  ,  "Gestion du matériel"  , ""  ,  "Gérer le matériel pédagogique de l'université"  , "glyphicon glyphicon-user"  , 208 ,  7 ,  6  , 1) ,
	   (35  ,  "Bibliothèque"  , ""  ,  "La bibliothèque numérique"  , "glyphicon glyphicon-user"  , 213 ,  7 ,  6  , 1) ,
	   (36  ,  "Gestion des mémoires"  , ""  ,  "Gérer les mémoires des étudiants"  , "glyphicon glyphicon-user"  , 223 ,  7 ,  6  , 1) ,
	   (37  ,  "Gestion des examens"  , ""  ,  "Gérer les examens des étudiants"  , "glyphicon glyphicon-user"  , 228 ,  8 ,  7  , 1) ,
	   (38  ,  "Gestion des devoirs"  , ""  ,  "Gérer les devoirs des étudiants"  , "glyphicon glyphicon-user"  , 233 ,  8 ,  7  , 1) ,
	   (39  ,  "Gestion des notes"  , ""  ,  "Gérer les notes des devoirs des étudiants"  , "glyphicon glyphicon-user"  , 238 ,  8 ,  7  , 1) ,
	   (40  ,  "Résultats d'examens"  , ""  ,  "Gérer les résultatst des étudiants"  , "glyphicon glyphicon-user"  , 243 ,  8 ,  7  , 1) ,
	   (41  ,  "Gérer la structure"  , ""  ,  "Gérer les informations de la structure"  , "glyphicon glyphicon-user"  , 251 ,  2,  8  , 1) ,
	   (42  ,  "Gestion du personnel"  , ""  ,  "Gérer le personnel de l'université"  , "glyphicon glyphicon-user"  , 252 ,  2 ,  8  , 1) ,
	   (43  ,  "Gérer les missions"  , ""  ,  "Gérer les missions de la structure"  , "glyphicon glyphicon-user"  , 262 , 2 ,  8  , 1);
	   
