<?php
    $tplPath = ROOT_PATH."/myTpl/public";
    $me      = Sirah_Fabric::getUser();
?>
<!--Pied de page du site-->
<div id="footer-copyright" class="footer-copyright clearfix">
	<div class="container clearfix"> 
		<div class="footer-logo col-sm-5 col-md-5">  © <?php echo date("Y"); ?> FNRCCM. Tous droits reservés.  </div>
		<div class="social-icons col-md-4 col-sm-4 pull-right"> 
			<ul class="social-icons-list">
				<li class="social-icons-list-item"> <a href="https://www.facebook.com" target="_blank" title="Suivez-nous sur FACEBOOK"><img src="<?php echo $tplPath ; ?>/assets/images/svg/facebook.svg"></a> </li>
				<li class="social-icons-list-item"> <a href="https://www.twitter.com"  target="_blank" title="Suivez-nous sur TWITTER" ><img src="<?php echo $tplPath ; ?>/assets/images/svg/twitter.svg"></a> </li>
				<li class="social-icons-list-item"> <a href="https://www.linkedin.com" target="_blank" title="Suivez-nous sur LINKEDIN"><img src="<?php echo $tplPath ; ?>/assets/images/svg/linkedin.svg"></a> </li>
			</ul>
		</div>
	</div>               
</div>
 <!--Fin pied de page du site-->     