<!DOCTYPE html> 
<html lang ="en">
<?php 
    //On initialise les variables nécessaires
    $layout                  = $this->layout();
    $baseUrl                 = $this->baseUrl();
    $tplPath                 = ROOT_PATH."/myTpl/public";     

    $columns                 = $this->columns;
	$layoutModules           = (!empty( $this->modules ))? $this->modules     : array();
    $bodyClasses             = ( $this->bodyClasses     )? $this->bodyClasses : array();
	$pageMainColumnClass     = "col-md-9 col-sm-9 col-xs-12";
    
    if(in_array("left",$columns) && in_array("right",$columns) && empty($bodyClasses)){
    	$bodyClasses         = array();
		$pageMainColumnClass = "col-md-6 col-sm-6 col-xs-12";
    } elseif(in_array("left",$columns)    && empty($bodyClasses)){
    	$bodyClasses[]       = "only-left";
		$pageMainColumnClass = "col-md-9 col-sm-9 col-xs-12";
    } elseif(in_array("right",$columns)   && empty($bodyClasses)){
    	$bodyClasses[]       = "only-right";
		$pageMainColumnClass = "col-md-9 col-sm-9 col-xs-12";
    } elseif(in_array("content",$columns) && empty($bodyClasses)){
    	$bodyClasses[]       = "only-content";
		$pageMainColumnClass = "col-md-12 col-sm-12 col-xs-12";
    }    
    $showLeftColumn          = in_array("left"          , $columns);
    $showRightColumn         = in_array("right"         , $columns);
    $view                    = $layout->getView();
    $message                 = $view->messages;
	$defaultErrorMessage     = $this->errormessage();
?>
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><?php echo $this->escape($this->title); ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Favicons -->
<style>
    .main-header ul.btn-nav {margin-bottom: 0;}
    .main-header .main-nav.nav-alt li>ul, .sf-mega{background: #f7f7f7 !important;padding:10px !important}
	.main-header .main-nav.nav-alt li>ul li{line-height:40px !important;height:40px !important;}
    .main-header .main-nav.nav-alt li>ul li a{color:#111 !important;line-height:40px !important;height:40px !important;}
    #loading {position:fixed;width:100%;height:100%;left:0;top:0;right:0;bottom:0;display:block;background:#fff;z-index:10000;}
    #loading img {position:absolute;top:50%;left:50%;margin: -23px 0 0 -23px;}
	.bootstrap-switch-info,.checkbox-info div[id^='uniform-'] span.checked,.radio-info div[id^='uniform-'] span.checked,.badge-info,.label-info,.btn-info,.hover-blue:hover,.hover-info:hover,.bg-blue{color:#fff;border-color:#0065ca;background:#0065ca;}
</style>
<?php echo $this->headMeta() ?>
<?php
	echo $this->headLink() ;
	echo $this->headStyle(); 
?>
</head>
<body class="<?php echo (!empty($bodyClasses)) ? " class=\"sr_page_body frontend-layout ".implode(' ',$bodyClasses)."\"" : "sr_page_body frontend-layout"; ?>">
    <div id="headerSection" class="headerSection featured-area bg-green-gradient">
        <!-- .main-header -->   
		<div id="mainheader" class="main-header bg-green-gradient header-fixed wow fadeInDown" data-0="padding:15px 0;">
			<div class="container clearfix"><?php echo $this->render("pagehead.phtml"); ?></div>
		</div>
	</div>
    <div id="mainContentWrapper" class="topadding mainContentWrapper gray-bg"><?php echo $layout->content ?> <br/></div>
	<!-- .footer --> 
    <div id="footersection" class="main-footer inverse section clearfix">
	    <?php echo $this->render("mainfooter.phtml");?>
		<?php echo $this->render("footer.phtml");?>	
	</div>
</body>
<?php  echo $this->headScript();echo $this->jQuery();?>

</html>
