<?php 
$data        = $this->data;
$formSubmit  = $this->url(array("module"=>"admin","controller"=>"articlecategories","action"=>"edit"),"default",true);
$backList    = $this->url(array("module"=>"admin","controller"=>"articlecategories","action"=>"list"),"default",true);
$basePath    = VIEW_BASE_PATH;

?>
<?php $this->headStyle()->captureStart() ?>
<?php $this->headStyle()->captureEnd()   ?>

<?php
$jq     = $this->jQuery();  
$onLoad = " 
  
  jQuery('#cancelEditButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});  
  jQuery('#editButton').click(function(e){
        e.preventDefault();      
        var  formSelector = jQuery('#editCategorieForm');
        var  libelle      = jQuery.trim(formSelector.find('#libelle').val());
		var code          = jQuery.trim(formSelector.find('#code').val());
		  
		if( SIRAH.util.isEmpty( libelle )){
			jQuery('#libelle').addClass('input-error');
			jQuery('#libelle-validation-message').html('');
			SIRAH.error.raise('libelle-validation-message','Entrez une désignation valide');
			return;
	    } else {
			jQuery('#libelle').removeClass('input-error');
			jQuery('#libelle-validation-message').html('');
		} 
 		
		jQuery('#libelle').val( libelle );
        formSelector.submit();
   }); ";
  
  $jq->addOnLoad($onLoad);

?>
<form method="post" action="<?php echo $formSubmit; ?>" id="editCategorieForm" role="form" class="form-horizontal">
 <div class="panel panel-default" >
    <ul class="list-group">
		<li class="list-group-item">
				<div class="form-group"> 
					<label class="col-md-2  col-sm-2 control-label"> Code* :</label> 
					<div   class="col-md-10 col-sm-10"><input id="code" name="code" type="text" maxlength="20" class="form-control" title="Le code du type d'activité" placeholder="Le code du type d'activité" value="<?php echo $data["code"]; ?>"></div>                 
					<p id="code-validation-message" class="validation-message"></p> 
				</div>   
			</li>
			<li class="list-group-item">
				<div class="form-group">
				   <label class="col-md-2  col-sm-2  control-label" for="code"> Désignation*: </label>
				   <div   class="col-md-10 col-sm-10"><input id="title" name="title" type="text" maxlength="250" class="form-control" title="Titre de la catégorie" placeholder="Titre de la catégorie" value="<?php echo $data["title"]; ?>"></div> 			   
				   <p id="title-validation-message" class="validation-message"></p> 
				</div>     
			</li>				 		
			<li class="list-group-item">
				<div class="form-group">
					<label class="col-md-2  col-sm-2 control-label"> Description: </label>
					<div   class="col-md-10 col-sm-10"><textarea name="description" id="description" class="form-control textarea-sm"> <?php echo $data["description"]; ?> </textarea></div>              
				</div>  
			</li>	
    </ul>
<?php     
    $buttonsbar = $this->Btnbar(array() , $this->jqueryHandler());
    $toolCreate = $buttonsbar->button("Sauvegarder","edit")->setPriority("primary");
    $toolCancel = $buttonsbar->button("Annuler et revenir sur la liste","chevron-left");
   
    $toolCreate->setAttributes(array("type" => "submit"));
    $toolCancel->setAttributes(array("type" => "submit"));
   
    $buttonsbar->add( $toolCancel, "cancelEditButton");
    $buttonsbar->add( $toolCreate, "editButton");  

    if(!$this->isAjax) {
   	   echo $buttonsbar;
    } else {
   	   echo $this->jQuery();
    }
   ?>
   </div> 
   <input type="hidden" name="catid" id="catid" value="<?php echo $data['catid']; ?>" />
</form>