<?php 
$categories        = $this->categories;
$filters           = $this->filters;
$paginator         = $this->paginator;


$basePath          = VIEW_BASE_PATH;
$avatarDefaultFile = $basePath."/images/login_avatar.png";
$jq                = $this->jQuery();

$linkSearch        = $this->url(array("module"=>"admin","controller"=> "articlecategories", "action"=> "list")  , "default");
$linkCreate        = $this->url(array("module"=>"admin","controller"=> "articlecategories", "action"=> "create"), "default");
$linkEdit          = $this->url(array("module"=>"admin","controller"=> "articlecategories", "action"=> "edit"  ), "default");
$linkDelete        = $this->url(array("module"=>"admin","controller"=> "articlecategories", "action"=> "delete"), "default");
 
$jq->addOnload("
jQuery('.resetPage').click(function(event){event.preventDefault();document.location.href='".$linkSearch."'; });
jQuery('#paginationBtnNext').click(function(  event ){
	event.preventDefault();
	if( jQuery(this).hasClass('disabled') ) {
		return;
	}
	var formSelector   = jQuery('#categorieSearchForm') ;
	var libelleText    = jQuery.trim(formSelector.find('#libelle').val());		
	var pageNum        = parseInt(   formSelector.find('#page').val());
	pageNum++;
	
	var searchData     = {};
	searchData.page    = pageNum;
	searchData.maxitems= parseInt(formSelector.find('#maxitems').val());						 
	searchData.libelle = libelleText;
	var maincontent	   = jQuery('#maincontent');	
	SIRAH.loading.on( maincontent , 'Chargement des données...' );
	SIRAH.request.post(formSelector, '".$linkSearch."' , 
					   {  dataType   :'html' ,
						  async      : true,
						  data       : searchData,
						  beforeSend : function() { },
						  error      : function(data){maincontent.html(data);SIRAH.loading.off(false);},
						  success    : function(data){maincontent.html(data);SIRAH.loading.off(false);},
						  update     : function(data){maincontent.html(data);SIRAH.loading.off(false);}		
					  });
});
jQuery('#paginationBtnPrev').click(function(  event ){
	event.preventDefault();
	if( jQuery(this).hasClass('disabled') ) {
		return;
	}
	var formSelector   = jQuery('#categorieSearchForm') ;
	var libelleText   = jQuery.trim(formSelector.find('#libelle').val());		
	var pageNum        = parseInt(   formSelector.find('#page').val());
	pageNum--;
	
	var searchData     = {};
	searchData.page    = pageNum;
	searchData.maxitems= parseInt(formSelector.find('#maxitems').val());						 
	searchData.libelle = libelleText;
	var maincontent	   = jQuery('#maincontent');	
	SIRAH.loading.on( maincontent , 'Chargement des données...' );
	SIRAH.request.post(formSelector, '".$linkSearch."' , 
					   {  dataType   :'html' ,
						  async      : true,
						  data       : searchData,
						  beforeSend : function() { },
						  error      : function(data){maincontent.html(data);SIRAH.loading.off(false);},
						  success    : function(data){maincontent.html(data);SIRAH.loading.off(false);},
						  update     : function(data){maincontent.html(data);SIRAH.loading.off(false);}		
					  });
});
jQuery('#searchCategorie').click(function( event ){
	event.preventDefault();
	var formSelector   = jQuery('#categorieSearchForm') ;
	var libelleText   = jQuery.trim(formSelector.find('#libelle').val());		
	
	var searchData     = {};
	searchData.maxitems= parseInt(formSelector.find('#maxitems').val());						 
	searchData.libelle = libelleText;

	var maincontent	   = jQuery('#maincontent');	
	SIRAH.loading.on( maincontent , 'Chargement des données...' );
	SIRAH.request.post(formSelector, '".$linkSearch."' , 
					   {  dataType   :'html' ,
						  async      : true,
						  data       : searchData,
						  beforeSend : function() { },
						  error      : function(data){maincontent.html(data);SIRAH.loading.off(false);},
						  success    : function(data){maincontent.html(data);SIRAH.loading.off(false);},
						  update     : function(data){maincontent.html(data);SIRAH.loading.off(false);}		
					  });						
});
jQuery('.paginationCountItem').click(function( event ){
	event.preventDefault();
	var paginationMaxitem  = parseInt(jQuery(this).attr('id').replace('paginationMaxitem-',''));	
	if( !paginationMaxitem ) {
		return;
	}	
	var formSelector      = jQuery('#categorieSearchForm') ;
	formSelector.find('#maxitems').val( paginationMaxitem );
	var searchData        = {};
	searchData.maxitems   = parseInt(formSelector.find('#maxitems').val());						 
	searchData.libelle    = libelleText;
	var maincontent	      = jQuery('#maincontent');	
	SIRAH.loading.on( maincontent , 'Chargement des données...' );
	SIRAH.request.post(formSelector, '".$linkSearch."' , 
					   {  
						  dataType   :'html' ,
						  async      : true,
						  data       : searchData,
						  beforeSend : function() { },
						  error      : function(data){maincontent.html(data);SIRAH.loading.off(false);},
						  success    : function(data){maincontent.html(data);SIRAH.loading.off(false);},
						  update     : function(data){maincontent.html(data);SIRAH.loading.off(false);}		
					  });
		
});
jQuery('input:checkbox').uniform({checkboxClass:'checkbox-primary'});
	var getCheckedCategoriesId = function() {
		var checkedItems = jQuery('#categoriesListTable').find('input[type=\'checkbox\'][name!=\'checkall\']:checked');
        var checkedIds   = []; 
		if( checkedItems) {
		    checkedItems.each(function() {
             	var catid   = parseInt(jQuery(this).attr('id').replace('catids',''));
             	checkedIds.push( catid );
            });
		}
		return checkedIds;
};
jQuery('#categoriesListTable').find('input[type=\'checkbox\']').click(function(e){
	var checkedItems  = jQuery('#categoriesListTable').find('input[type=\'checkbox\'][name!=\'checkall\']:checked');
	if( jQuery(this).attr('id') == 'checkAll') {
		if(!jQuery(this).is(':checked')) {
		   checknone(jQuery('#categoriesListTable'));
		   if( checkedItems ) {
			   disableButtons(['editButton','deleteButton']);
		   }
		} else {
		  checkall(jQuery('#categoriesListTable'));
		  enableButtons(['editButton','deleteButton']);
		}
	} else {
	    if( jQuery(this).is(':checked')) {
		    enableButtons(['editButton','deleteButton']);
	    } else {
		  if( SIRAH.util.isEmpty(checkedItems)) {
			  disableButtons(['editButton','deleteButton']);
		   }
	    }
	}
});");

$toolbar      = $this->supinaToolsbar(array() , $this->jqueryHandler());
$toolCreate   = $toolbar->tool("Nouvelle catégorie", "plus");
$toolEdit     = $toolbar->tool("Modifier" , "edit");
$toolDelete   = $toolbar->tool("Supprimer", "trash-o");

$toolbar->add( $toolCreate, "createButton");
$toolbar->add( $toolEdit  , "editButton");
$toolbar->add( $toolDelete, "deleteButton");

$toolCreate->onClick(sprintf("event.preventDefault(); document.location.href='%s';" , $linkCreate ));

$toolEdit->disable();
$toolEdit->onClick("
		            event.preventDefault();
		            var isDisabled   = jQuery(this).is('.disabled') || jQuery(this).is('.btn-disabled');
		            var checkedItem  = jQuery('#categoriesListTable').find('input[type=\'checkbox\'][name=\'catids[]\']:checked').eq(0);
		            if( isDisabled || !checkedItem) {
		                SIRAH.dialog.alert('Vous devrez selectionner une ligne avant d\'effectuer cette opération','Selectionnez une ligne');
		                return;
                    }
		            var catid         = parseInt(checkedItem.attr('id').replace('catids',''));
		            var categorieName = jQuery('#name-'+catid).val();
		            var dialogEdit    = jQuery('<div></div>').attr('id','dialogEdit').addClass('modal-medium');
		
		            dialogEdit.dialog2({title:'Mettre à jour les informations d\'une catégorie',content:'".$linkEdit."/catid/'+catid,autoOpen:false,modalClass:'modal-wide',removeOnClose:true,closeOnEscape:false,closeOnOverlayClick:true,showCloseHandle:true,initialLoadText:'Chargement...'});
		            dialogEdit.dialog2('addButton','<span class=\'glyph-icon icon-edit\'></span> Sauvegarder',{primary:true,click :function(){var editForm=jQuery('#dialogEdit').find('form').eq(0);SIRAH.request.post(editForm,'".$linkEdit."/catid/'+catid);}});
		            dialogEdit.dialog2('addButton','<i    class=\'glyph-icon icon-chevron-left\'> </i> Annuler', {primary:false,click:function(){jQuery(this).dialog2('close');}});
		            dialogEdit.dialog2('open');");
$toolDelete->disable();
$toolDelete->onClick(" 
		            var isDisabled        = jQuery(this).is('.disabled') || jQuery(this).is('.btn-disabled');
		            var checkedCategories = getCheckedCategoriesId();
		            if( isDisabled || SIRAH.util.isEmpty( checkedCategories )) {
		                SIRAH.dialog.alert('Vous devrez selectionner au moins une ligne avant d\'effectuer cette opération','Selectionnez une ligne');
		                return;
                    }
		            var dialogDelete = jQuery('<div> Voulez-vous vraiment supprimer les catégories selectionnées ? </div>').attr('id','dialogDelete');             		 
             		dialogDelete.dialog2({title:'Attention, confirmer cette action !!',autoOpen:false,removeOnClose:true,closeOnEscape:false,closeOnOverlayClick:true,showCloseHandle:true,initialLoadText: 'Chargement...' });        		
             		dialogDelete.dialog2('addButton','<i class=\'glyph-icon icon-check\'> </i> Oui',{primary:true,click : 
             		                     function(){
             		                                jQuery.ajax({url:'".$linkDelete."',async: false,dataType:'json',data : {'catids[]': checkedCategories},type :'GET' ,
             		                                             success  : function(data) {
             		                                                if(data.error !== undefined) {
             		                                                   SIRAH.error.raise(jQuery('#dialogDelete') , data.error);
             		                                                   return;
             		                                                } else if(data.success !== undefined) {
             		                                                   var checkedCategories = getCheckedCategoriesId();  	            		
             		                                                  SIRAH.error.raise(jQuery('#dialogDelete'), data.success , 'success');
             		                                                  setTimeout(function(){jQuery.each(checkedCategories,function(key,catid){jQuery('#categorieRowId-'+catid).remove();});jQuery('#dialogDelete').dialog2('close');},2500);
             		                                               }
             		                                             }
             		                                           });     		
                                                           }}); 
             		dialogDelete.dialog2('addButton','<i class=\'glyph-icon icon-chevron-left\'></i>Annuler', {primary: false,click : function(){jQuery(this).dialog2('close');}});              		
             		dialogDelete.dialog2('open');");

$this->toolsbar = $toolbar;

$pagination     = $this->supinaPagination(array(), "Jumping" , "#");

?>

<div id="categoriesListWrapper"  class="row">
  <form id="categorieSearchForm" method="post" role="form" class="form-horizontal">
    <div  class="col-md-12">
       <div class="content-box">
            <div class="mail-header clearfix">               
                <div class="float-right col-md-4 pad0A">
                    <div class="input-group">
                        <input type="text" class="form-control" value="<?php echo $filters['libelle']; ?>" name="libelle" id="libelle" placeholder="Saisir des mots clés">
                        <div class="input-group-btn">
                            <button id="searchCategorie" type="button" class="btn btn-default" tabindex="-1"><i class="glyph-icon icon-search"></i></button>
                            <button id="resetPage"       type="button" class="btn alert-danger resetPage" tabindex="-1"><i class="glyph-icon icon-remove"></i></button>
                        </div>
                    </div>
               </div>
            </div>                                                                  
            <div class="mail-toolbar clearfix"> 
                <div class="float-left"><a href="#" title="Actualiser la page" class="btn btn-default mrg5R resetPage"><i class="glyph-icon font-size-11 icon-refresh"></i></a></div>
                <div class="float-right"> <?php  echo $pagination->render(); ?> </div>
            </div>
            <table id="categoriesListTable" class="table table-hover table-bordered table-stripped table-responsive sirah-ui-table scrollable text-center">
                <thead>
                    <tr> 
                          <th width="5%"> <input type="checkbox" name="checkall" id="checkAll" class="checkAll" /></th>
                          <th width="15%"> Codes        </th> 
                          <th width="50%"> Désignations </th> 
                          <th width="25%"> Description  </th> 
                    </tr>
                </thead>                
                <tbody>
                <?php 
				$output   = "";
				if( count(   $categories ) ) {
					foreach( $categories as $categorie ) {
							 $catid               = intval($categorie['catid']);
							 $categorieCode       = $categorie["code"];
							 $categorieTitle      = $categorie["title"];
							 $categorieDescription= $categorie["description"];
							 $linkInfos           = $this->url(array("module"=>"admin","controller"=>"articlecategories","id"=>$catid,"action"=>"infos"), "default");

							 $output .= "<tr id=\"categorieRowId-".$catid."\">";
										$output .= "<td> <input type=\"checkbox\" name=\"catids[]\" id=\"catids".$catid."\" class=\"catids\" /> </td>";
										$output .= "<td><a title=\"Accéder aux informations de cette catégorie\" href=\"".$linkInfos."\">".$categorieCode       ." </a> </td>";
										$output .= "<td><a title=\"Accéder aux informations de cette catégorie\" href=\"".$linkInfos."\">".$categorieTitle      ." </a> </td>";
										$output .= "<td><a title=\"Accéder aux informations de cette catégorie\" href=\"".$linkInfos."\">".$categorieDescription." </a> </td>";
						     $output.= "</tr>";
								
							 $output.= "<input type=\"hidden\" name=\"name-".$catid."\" id=\"name-".$catid."\" value=\"".$categorieTitle."\"  />" ;
					  }                              	
				}  else {
					$output .= "<tr id=\"categorieRowId-0\"> <td style=\"text-align:center !important;\" colspan=\"5\"> Aucune catégorie n'a été retrouvée </td> </tr>";
				}                              
				  echo $output;                      
                ?>                            
                </tbody>           
           </table>
       </div>    
    </div>
    <input type="hidden" name="page"      id="page"     value="<?php echo $this->pageNum;  ?>"  /> 
    <input type="hidden" name="maxitems"  id="maxitems" value="<?php echo $this->pageSize; ?>"  />
  </form>
</div>
<?php 
    if( $this->isAjax ) {
     	echo $this->jQuery();
	    echo $this->headStyle();
    }
?>   