<?php 
$token             = $this->token;
$user              = $this->user;
$avatarPath        = USER_AVATAR_PATH .DS ."mini" .DS."";
$linkAvatarUpload  = $this->url(array("controller"  => "profile" , "action" => "changeavatar" , "username" => $user->username ) , "default");
$linkInfos         = $this->url(array("controller"  => "profile" , "action" => "infos" , "userid"  => $this->userid )   , "default" ) ;
$jq  = $this->jQuery();

$onLoad  = " 
   jQuery('#useravatar').filestyle({
   		                            buttonText  : ' Choisir un avatar',
   		                            classButton : 'btn btn-default',
   		                            classIcon   : 'glyphicon glyphicon-folder-open',
   		                            icon        : true
   		                         });
   jQuery('#fileupload').fileupload({
       paramName:'useravatar',
       url      : '".$linkAvatarUpload."' ,
       dropZone : jQuery('#dropzone'),
       type     : 'POST',
       dataType : 'json',
       add : function(e , data) {
           jQuery('#importAvatarBtn').on('click' , function( event ) {
   		            event.preventDefault();
   		            SIRAH.loading.on( jQuery('.modal-body').first() , 'Patientez , chargement de l\'avatar...' );
   		            var jqXhr    = data.submit();
   		            jqXhr.success(function(result , textStatus , jqXHR){
                    if( result.success != undefined) {
                        SIRAH.error.raise(jQuery('#dialogChangeAvatar') , 'Opération terminée : '+result.success , 'success');
                        var file  = result.files[0];
                        if(file  != undefined ){
                           var newfilename  = file.path + file.name; 
                           SIRAH.loading.off(false) ;                                      
                           jQuery('#dialogChangeAvatar').dialog2('close');
                           setTimeout(function(){jQuery('#useravatarThumbnail').attr('src' , newfilename);document.location.href = '".$linkInfos."';}, 500);                                                     
                         }
                    } else if(result.error != undefined) {
                       SIRAH.error.raise(jQuery('#dialogChangeAvatar') , 'Opération terminée : '+result.error , 'error');
                       SIRAH.loading.off(false) ;
                       return true;      
                    }
           });
           jqXhr.error(function( result , textStatus, errorThrown){
                 SIRAH.error.raise(jQuery('#dialogChangeAvatar') , 'Opération terminée , aucune erreur valide n\'a été retournée : '+result , 'error');
                 SIRAH.loading.off(false);
                 return false;        
           });
   		});  },    
        messages: {uploadedBytes: 'Le fichier que vous voulez uploader est trop lourd'}
     });     
   jQuery('#fileupload').bind('fileuploadsubmit', function (e, data) {
          var inputs    = jQuery(this).find(':input');
          data.formData = inputs.serializeArray();
    }); 
  jQuery('#fileupload').bind('fileuploaddrop', function (event , data) {
            event.preventDefault();
   		    SIRAH.loading.on( jQuery('.modal-body').first() , 'Patientez , chargement de l\'avatar...' );
   		     var jqXhr    = jQuery(this).fileupload('send', data );
   		     jqXhr.success(function(result , textStatus , jqXHR){
             if( result.success != undefined) {
                 SIRAH.error.raise(jQuery('#dialogChangeAvatar') , 'Opération terminée : '+result.success , 'success');
                 var file  = result.files[0];
                 if( file  != undefined ){
                     var newfilename  = file.path + file.name; 
                     SIRAH.loading.off(false);                                       
                     jQuery('#dialogChangeAvatar').dialog2('close');
                     setTimeout(function(){jQuery('#useravatarThumbnail').attr('src' , newfilename);document.location.href = '".$linkInfos."';}, 500);                                                     
                         }
                 } else if(result.error != undefined) {
                    SIRAH.error.raise(jQuery('#dialogChangeAvatar') , 'Opération terminée : '+result.error , 'error');
                    SIRAH.loading.off(false); 
                    return true;      
                 }
           });
           jqXhr.error(function( result , textStatus, errorThrown){
                 SIRAH.error.raise(jQuery('#dialogChangeAvatar') , 'Opération terminée , aucune erreur valide n\'a été retournée : '+result , 'error');
                 SIRAH.loading.off(false);
                 return false;        
           });
   });
   jQuery(document).bind('dragover', function (e) {
          var dropZone = jQuery('#dropzone'),
          timeout = window.dropZoneTimeout;
          if (!timeout) {
              dropZone.addClass('in');
           } else {
              clearTimeout(timeout);
           }
         var found = false,
      	         node = e.target;
          do {
               if (node === dropZone[0]) {
       		   found = true;
       		   break;
       	    }
       	     node = node.parentNode;
              } while (node != null);
              if (found) {
                 dropZone.addClass('hover');
               } else {
                  dropZone.removeClass('hover');
               }
           window.dropZoneTimeout = setTimeout(function () {
                 window.dropZoneTimeout = null;
                  dropZone.removeClass('in hover');
            }, 100);
    });   ";
$jq->addOnLoad($onLoad);
$basePath    = ROOT_PATH."/templates/sirah";
$jq->addStyleSheet($basePath     . "/js/fileupload/css/jquery.fileupload.css");
$jq->addStyleSheet($basePath     . "/js/fileupload/css/jquery.fileupload-ui.css");
$jq->addStyleSheet($basePath     . "/css/sirahfileupload.css");
$jq->addJavascriptFile($basePath . "/js/bootstrap/bootstrap-filestyle.js");
$jq->addJavascriptFile($basePath . "/js/fileupload/js/vendor/jquery.ui.widget.js");
$jq->addJavascriptFile($basePath . "/js/fileupload/js/jquery.iframe-transport.js");
$jq->addJavascriptFile($basePath . "/js/fileupload/js/jquery.fileupload.js");
$jq->addJavascriptFile($basePath . "/js/fileupload/js/jquery.fileupload-ui.js");

?>
<?php $this->headStyle()->captureStart() ?>
     .bar 
      {
          height: 15px;
          background: green;
        }
        div.bootstrap-filestyle input[type="text"]
        {
          width:auto;
          margin-left:5px;
          margin-right:5px;
          margin-bottom:0;
        }
        div.bootstrap-filestyle, div.fileUploadRow
        {
          margin-bottom:10px;
         }
<?php $this->headStyle()->captureEnd()   ?>  
<form style="margin-bottom:5px;" class="form-horizontal" id="fileupload"  action="<?php echo $linkAvatarUpload; ?>" enctype="multipart/form-data" method="post">
    <div class="row">           
       <div class="col-lg-12 fileupload-progress fade">                
         <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
              <div class="progress-bar progress-bar-success" style="width:0%;"></div>
         </div>
        <div class="progress-extended">&nbsp;</div>              
      </div>
    </div>
     <div class="row col-md-12 fileUploadRow">
        <div class="col-md-4"> <label class="control-label" for="inscriptions"> Chercher une photo (png ,gif,jpg ) 3MB : </label> </div>
        <div class="col-md-8"><input name="useravatar" type="file" id="useravatar" /> <button type="submit" class="btn btn-primary" id="importAvatarBtn"> Charger </button> </div>		 
	 </div>
	  <div id="dropzone" class="well fade">
           Vous pouvez aussi glisser-deposer votre image dans ce cadre puis cliquer sur le bouton charger
     </div>	 
   
    <input type="hidden"  name="token"  id="token"  value="<?php echo $token; ?>" />
    <input type="hidden"  name="userid" id="userid" value="<?php echo $this->userid; ?>" />
</form>    
<?php if($this->isAjax) : ?>
<?php echo $this->jQuery(); echo $this->headStyle();  echo "<div style=\"display:none;\" id=\"loadingBox\"> </div>"; ?>
<?php endif; ?>
    