<?php 
$me              = Sirah_Fabric::getUser();
$member          = $this->member;
$articles        = $this->articles;
$documents       = $this->documents;
$basePath        = VIEW_BASE_PATH;
$jq              = $this->jQuery();

$linkCreateOrder = $this->url(array("controller"=>"orders"   ,"action"=>"create","module"=>"public"),"default", true);
$linkDelete      = $this->url(array("controller"=>"ordercart","action"=>"delete","module"=>"public"),"default", true);
$linkReset       = $this->url(array("controller"=>"ordercart","action"=>"reset" ,"module"=>"public"),"default", true);
$linkReservation = $this->url(array("controller"=>"requetes" ,"action"=>"verify","module"=>"public"),"default", true);
$linkRegistres   = $this->url(array("controller"=>"registres","action"=>"search","module"=>"public"),"default", true);

$buttonBar       = $buttonbar = $this->buttonsbar(array(), $this->jqueryHandler());
$btnCreateOrder  = $buttonBar->button("Poursuivre la commande"  ,"chevron-right");
$btnDelete       = $buttonBar->button("Vider le panier"         ,"trash");
$btnCancel       = $buttonBar->button("Procéder à une autre réservation","chevron-left");

$buttonBar->add($btnCancel     , "cancelButton");
$buttonBar->add($btnDelete     , "deleteButton");
$buttonBar->add($btnCreateOrder, "createOrderButton");

$btnDelete->setAttributes(     array("type"=>"submit", "class"=>"btn btn-danger"));
$btnCreateOrder->setAttributes(array("type"=>"submit", "class"=>"btn btn-success"));
$btnCancel->setAttributes(     array("type"=>"submit"));

$btnCreateOrder->onClick(sprintf("event.preventDefault();document.location.href='%s';",$linkCreateOrder));
$btnDelete->onClick(     sprintf("event.preventDefault();document.location.href='%s';",$linkReset));
$btnCancel->onClick(     sprintf("event.preventDefault();document.location.href='%s';",$linkReservation));

$jq->addOnLoad("
    jQuery('.delProduct').click(function(event){
		event.preventDefault();
		var productid = parseInt(jQuery(this).attr('id').replace('delProductId-',''));
		jQuery('#dialogDeleteProduct').remove();
		var dialogDeleteProduct = jQuery('<div> Etes-vous sur de supprimer cet élement du panier ? </div>').attr('id','dialogDeleteProduct');
		dialogDeleteProduct.dialog2({title:'Confirmer cette action',autoOpen:false,removeOnClose:true,closeOnEscape:false,closeOnOverlayClick: true,showCloseHandle:true,initialLoadText: 'Chargement...'});
		dialogDeleteProduct.dialog2('addButton','<span class=\'glyph-icon icon-trash\'></span> Supprimer un product du panier',{primary : true , click :
								function(){
									jQuery.ajax({url:'".$linkDelete."',async:false,dataType:'json',type:'GET',data:{'productids[]':[productid],'organisationid':'".$organisationid."'},            		                                                               
												success:function(data) {
													if( data.error !== undefined) {
														SIRAH.error.raise(jQuery('#dialogDeleteProduct') , data.error);
														return;
													} else if(data.success !== undefined) {
														jQuery('#cardUpdateBtn').trigger('addProduct');
														SIRAH.error.raise(    jQuery('#dialogDeleteProduct'),data.success , 'success');
														setTimeout(function(){jQuery('#dialogDeleteProduct').dialog2('close');
														jQuery('#cardProductId-'+productid).remove();},1000);
													}
												}
									});
								}
		});
		dialogDeleteProduct.dialog2('addButton','Annuler',{primary: false,click:function(){jQuery(this).dialog2('close');jQuery(this).remove();}});
		dialogDeleteProduct.dialog2('open');
	});		
");
?>
<div id="information-section" class="information-section section">
    <div class="container">
		<div class="row section-content">
			<div class="panel panel-danger">
				<div  class="panel-heading"> <h4> Les détails du panier </h4> </div>
				<?php 	    
					$output = "";
					$output.= " <table class=\"table table-bordered table-striped \" width=\"100%\" border=\"1\" >";                  								
								if( count(   $articles ) ) {
									$output.="  <thead>
													<tr><th style=\"text-align:left;\"   width=\"5%\"><b>QTE</b></th>
														<th style=\"text-align:left;\"   width=\"30%\"><b>SERVICES/ARTICLES</b></th>
														<th style=\"text-align:left;\"   width=\"30%\"><b>DETAILS</b></th>
														<th style=\"text-align:right;\"  width=\"10%\"><b>TARIFS</b></th>
														<th style=\"text-align:center;\" width=\"5%\">*</th>
													</tr>
												</thead>";
									$output.="  <tbody>";			
									$montantTotal = $montantTotalTTC = 0;
									foreach( $articles as $article ) {
											 $productid          = $article["productid"];
											 $registreid         = $article["registreid"];
											 $documentid         = $article["documentid"];
											 $productLibelle     = $article["libelle"];
											 $productDescription = $article["description"];
											 $quantite           = $article["quantite"];
											 $montantHT          = (intval($quantite))?($article["cout_ht"]*$quantite)  : $article["cout_ht"];
											 $montantTTC         = (intval($quantite))?($article["cout_ttc"]*$quantite) : $article["cout_ttc"];
											 $montantTotal      += $montantHT;
											 $montantTotalTTC   += $montantTTC;
											 
											 $linkDeleteItem     = $this->url(array("controller"=>"ordercart","action"=>"delete","documentid"=>$documentid,"registreid"=>$registreid,"productid"=>$productid,"module"=>"public"),"default",true);
											 $bgColorClass       = $this->cycle(array("#FFFFFF","#F5F5F5"))->next();
											 $output .=" <tr id=\"cardProductId".$productid."\" style=\"background-color:".$bgColorClass."\">";
													$output .=" <td style=\"text-align:left;background-color:".$bgColorClass."\">".$quantite." </td>";
													$output .=" <td style=\"text-align:left;background-color:".$bgColorClass."\">".$productLibelle." </td>";
													$output .=" <td style=\"text-align:left;background-color:".$bgColorClass."\">".$productDescription." </td>";
													$output .=" <td style=\"text-align:right;background-color:".$bgColorClass."\">".number_format($montantTTC, 0,' ', ' ')." F CFA </td>";
													$output .="
																<td  style=\"text-align:left;background-color:".$bgColorClass."\"> 
																	<div class=\"btn-group\" role=\"group\">
																		<button type=\"button\" class=\"btn btn-danger pull-right delProduct\" title=\"Supprimer cet élément\" id=\"delProductId-".$productid."\"><span class=\"glyph-icon icon-trash-o\"></span> </button>										    
																	</div>
																</td>";
											 $output .=" </tr>";
									}				 										 
									//$output .="          <tr><td style=\"text-align:right;background-color:".$bgColorClass."\" colspan=\"3\"><b> TOTAL HT :</b></td><td colspan=\"2\" style=\"text-align:center;\"><small class=\"text-muted\">XOF </small> <span style=\"font-weight:bold;text-align:center\">".number_format($montantTotal,0,' ', ' ')." F CFA</span></td>  </tr>";
									$output .="          <tr><td style=\"text-align:right;background-color:".$bgColorClass."\" colspan=\"3\"><b> TOTAL A PAYER:</b></td><td colspan=\"2\" style=\"text-align:center;\"><small class=\"text-muted\">XOF </small> <span style=\"font-weight:bold;text-align:center\">".number_format($montantTotalTTC,0,' ', ' ')." F CFA</span></td>  </tr>";	 
								    $output.="  </tbody>";
								}  else {
									$output .="<tbody><tr><td style=\"text-align:center !important;background-color:".$bgColorClass."\" align=\"center\" colspan=\"5\"><b> AUCUN ARTICLE N'A ETE TROUVE DANS VOTRE PANIER. </b></td></tr></tbody>";
								}									
							    
					$output       .=" </table>";
					echo $output;	
				?>
				<?php if(count($articles)): ?>
				<div class="panel-footer"><?php echo $buttonBar; ?></div>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>
<?php 
    if( $this->isAjax ) {
     	echo $this->jQuery();
	    echo $this->headStyle();
    }
?>
 