<?php 
    $photos    = $this->rows;
    $gallerie  = $this->gallerie;  
    
    $basePath  = str_replace("default", "fao", VIEW_BASE_PATH);
    $jq        = $this->jQuery();
    //$jq->addOnLoad(" blueimp.Gallery(jQuery('#links a'), {container:'#blueimp-gallery'});");
    
    $jq->addJavascriptFile(  $basePath . '/gallerypack/js/bootstrap-image-gallery.js');
    $jq->addStyleSheet(      $basePath . "/gallerypack/css/bootstrap-image-gallery.css");
    $jq->addStyleSheet(      $basePath . "/css/main.css");
?>
<?php $this->headStyle()->captureStart() ?>
div.caption h4{font-size:14px;text-align:center;font-weight:bold;}
 div.row{margin-left:5px; margin-right:5px;}
.thumbnail .caption {height:120px;min-height:120px;}
.thumbnail{padding:5px;height:225px;}
.thumbnail img{margin-top:0;}
<?php $this->headStyle()->captureEnd()   ?> 
 
<?php if( count( $photos )) : ?>   
 <div id="links"  class="row">
    <?php 
         foreach( $photos as $row ) {
         	      $photoFilePath = $row["photo"];
         	      $imageSrc      = "";
         	      $photoLibelle  = strip_tags( substr( $row["libelle"], 0 , 30 ) );
         	      $itemActive    = ( $slideId == 0 ) ? " active " : "";
         	if( !empty( $photoFilePath ) ) {
         		$photoFilePathName = str_replace( APPLICATION_PATH , ROOT_PATH . DS ."myV1", $photoFilePath );
         		if( Sirah_Filesystem::exists( $photoFilePath ) ) {
         			$imageSrc = str_replace( DS, "/", $photoFilePathName );
         		} 
         	}
         	if( empty( $imageSrc ))
         		continue;
         	$outputPhoto .=" <div id=\"slideId-".$slideId."\" class=\"col-xs-18 col-sm-6 col-md-4\"> <div class=\"thumbnail\"> ";
         	$outputPhoto .= "<a href=\"".$imageSrc."\"  id=\"slide-".$slideId."\" title=\"".$row["libelle"]."\"  data-gallery>";
         	             $outputPhoto .= "<img src=\"".$imageSrc."\" alt=\"".$row["libelle"]."\" />";
         	             $outputPhoto  .=" <div class=\"caption\"> ";
         	             $outputPhoto  .="<h4>  ".$photoLibelle."   </h4>";
         	             $outputPhoto  .=" </div> ";
         	$outputPhoto .= "</a> </div> </div>";
         	$slideId++;
         }        
         echo $outputPhoto;
    
    ?>      
</div>
<?php else: ?> 
  <div class="row"> AUCUNE PHOTO N'A ETE CHARGEE DANS CETTE GALLERIE </div>
<?php endif; ?>

<?php 

if( $this->isAjax ) {
	echo $this->jQuery();
	echo $this->headStyle();
}
?>