<?php 
    $promoteur     = $this->promoteur;
	$countries     = $this->countries();
	$nationalite   = (isset($countries[$promoteur->nationalite]))?$countries[$promoteur->nationalite] : $promoteur->nationalite;
?>
<ul class="list-group">
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Nom & Prénom  :</b></div> 
			<div class="col-md-8"><?php echo $promoteur->name; ?></div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Sexe:</b></div> 
			<div class="col-md-8"> <?php echo ( $promoteur) ? (($promoteur->sexe == "M") ? "Homme": "Femme") : ""; ?> </div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Adresse:</b></div> 
			<div class="col-md-8"> <?php echo ( $promoteur) ? $promoteur->adresse : ""; ?> </div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Nationalité:</b></div> 
			<div class="col-md-8"> <?php echo $nationalite; ?> </div>
		</div>
	</li>		   
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Numéro de téléphone:</b></div> 
			<div class="col-md-8"> <?php echo ( $promoteur) ? $promoteur->telephone : ""; ?> </div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Adresse email:</b></div> 
			<div class="col-md-8"> <?php echo ( $promoteur) ? $promoteur->email : ""; ?> </div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Fonction/Profession:</b></div> 
			<div class="col-md-8"> <?php echo ( $promoteur) ? $promoteur->profession: ""; ?> </div>
		</div>
	</li>
</ul>