<?php 
$demande         = $this->demande;
$demandeid       = $demande->demandeid;
$entrepriseid    = $this->entrepriseid;
$entreprise      = $this->entreprise;
$forme           = $this->forme;
$demandeurid     = $demande->demandeurid;
$demandeur       = $this->demandeur;
$promoteurid     = $demande->promoteurid;
$promoteur       = $this->promoteur;
$similarites     = $this->similarites;
$similariteActivities = $this->similariteActivities;
$totalresults    = $this->totalresults;
$currentStep     = $this->currentStep;
$percent         = $this->successedPercent;
$query           = $this->query;
$localite        = $this->localite;
$statut          = $this->statut;
$domaineActivite = $this->domaineActivite;
$formeJuridique  = $this->formeJuridique;
$renderingView   = $this->renderingView;
$viewTitle       = $this->viewTitle;
$sourceid        = $this->sourceid;
$source          = $this->source;
$sourceCode      = $this->sourceCode;
$next            = $this->next;
$sources         = $this->sources;
$rejected        = $this->rejected;
$jq              = $this->jQuery();
$linkReject      = $this->url(array("module"=>"admin","controller"=>"demandes","action"=>"reject","demandeid"=>$demandeid,), "default");
$linkAccept      = $this->url(array("module"=>"admin","controller"=>"demandes","action"=>"accept","demandeid"=>$demandeid,), "default");
$linkComplete    = $this->url(array("module"=>"admin","controller"=>"demandes","action"=>"verify","demandeid"=>$demandeid,), "default");
$linkFetchItems  = $this->url(array("module"=>"admin","controller"=>"demandes","action"=>"verify","demandeid"=>$demandeid), "default");
$linkVerifyNext  = $this->url(array("module"=>"admin","controller"=>"demandes","action"=>"verify","source"=>$next,"demandeid"=>$demandeid), "default");

$onLoad          = "   
    var completeVerification = function(successed){		
	    if( successed >= 100) {
			var dialogComplete = jQuery('<div class=\'alert alert-success\'> <i class=\'glyph-icon icon-elusive-ok\'> </i> Les résultats de la recherche de disponibilité indiquent que le nom commercial est valide à '+successed+'%. Voulez-vous accepter la demande du promoteur ? </div>').attr('id','dialogComplete').addClass('modal-medium');             		 
			dialogComplete.dialog2({title:'Accepter la demande',autoOpen:false,removeOnClose:true,closeOnEscape:false,closeOnOverlayClick:true,showCloseHandle:true,initialLoadText: 'Chargement...'});
			dialogComplete.dialog2('addButton','<i class=\'glyph-icon icon-times\'> </i> Non, ne pas accepter',{primary:false,click:function(event){event.preventDefault();jQuery(this).dialog2('close');document.location.href=\"".$linkReject."\";}});
			dialogComplete.dialog2('addButton','<i class=\'glyph-icon icon-check\'> </i> Oui, accepter',{primary:true,click:function(event){event.preventDefault();jQuery(this).dialog2('close');document.location.href=\"".$linkAccept."\";}});	    
			dialogComplete.dialog2('open');
		} else {
			var dialogComplete = jQuery('<div class=\'alert alert-danger\'> <i class=\'glyph-icon icon-elusive-ok\'> </i> Les résultats de la recherche de disponibilité indiquent que le nom commercial est valide à '+successed+'%. Voulez-vous rejeter la demande du promoteur ? </div>').attr('id','dialogComplete').addClass('modal-medium');             		 
			dialogComplete.dialog2({title:'Rejeter la demande',autoOpen:false,removeOnClose:true,closeOnEscape:false,closeOnOverlayClick:true,showCloseHandle:true,initialLoadText: 'Chargement...'});
			dialogComplete.dialog2('addButton','<i class=\'glyph-icon icon-check\'> </i> Non, je veux accepter',{primary:false,click:function(event){event.preventDefault();jQuery(this).dialog2('close');document.location.href=\"".$linkAccept."\";}});	
			dialogComplete.dialog2('addButton','<i class=\'glyph-icon icon-times\'> </i> Oui, je veux rejeter' ,{primary:true,click:function(event){event.preventDefault(); jQuery(this).dialog2('close');document.location.href=\"".$linkReject."\";}});			    
			dialogComplete.dialog2('open');
		}		
	};
    var appendItems = function(source, sourceid){
		jQuery.ajax({url:'".$linkFetchItems."',async:false,dataType :'html',
					 data: {'source':''+source+''},type: 'GET' ,
					 success: function(data) {
						jQuery('#verificationSources').append(data);
                        jQuery('.collapse').collapse();
						var collapseContentId = jQuery('#accordionToggleId-'+sourceid).attr('data-target');
						var collapseContent   = jQuery('#'+collapseContentId);   
						if( collapseContent.attr('id') !== undefined ) {
							collapseContent.collapse();
						}
					 }
		});
	};";

$jq->addOnLoad($onLoad);

$basePath        = ROOT_PATH.'/myTpl/public';

$jq->addJavascriptFile($basePath ."/scripts/widgets/collapse/collapse.js");
?>

<div style="margin-bottom:10px;"  class="row">
    <h2 class="title-hero"> Taux de succès de la validation du nom commercial </h2>
    <div class="divider"> </div>
 
	<div id="verificationProgressBar" class="progressbar progress-striped" data-value="<?php echo $percent; ?>">
	    <div class="progressbar-value bg-green tooltip-button" data-original-title="<?php printf("Le nom commercial recherché <b> %s </b> est disponible à %d%% selon les différentes sources", $query, $percent ); ?>" style="width:100%;">
		    <div class="progress-label"> <?php printf(" %d%%", $percent ); ?></div> 
			<div class="progress-overlay"></div>
	     </div>
	</div>
</div>
<div class="row">
    <div  class="col-sm-12 col-md-4">
		<div class="panel panel-primary">
			<div class="panel-heading"> <h4 class="panel-title"> <span class='glyph-icon icon-folder'></span> Les informations de la demande </h4> </div>  
			<?php echo $this->partial("demandes/demande.phtml",array("demande"=>$demande,"demandeid"=>$demandeid,"jquery"=>&$jq)); ?>
			<?php echo $this->partial("demandes/entreprise.phtml",array("domaine"=>$domaineActivite,"forme"=>$formeJuridique,"entreprise"=>$entreprise,"entrepriseid"=>$entrepriseid,"demande"=>$demande,"demandeid"=>$demandeid,"jquery"=>&$jq)); ?>
	    </div>
	</div>
    <div  class="col-sm-12 col-md-8">
	    <div id="verificationSources" class="panel-group verificationSources">
	        <?php echo $this->partial("demandes/{$renderingView}.phtml",array("rejected"=>$rejected,"sources"=>$sources,"sourceCode"=>$sourceCode,"sourceid"=>$sourceid,"source"=>$source,"next"=>$next,"viewTitle"=>$viewTitle,"similarites"=>$similarites,"similariteActivities"=>$similariteActivities,"totalresults"=>$totalresults,"successedPercent"=>$percent,"currentStep"=>$currentStep,"demande"=>$demande,"demandeid"=>$demandeid,"jquery"=>&$jq)); ?>
	    </div>
	</div>
</div>