<?php 
$photoPath         = APPLICATION_DATA_PATH . DS . "produits" . DS . "photos". DS . "mini";
$linkPhotoUpload   = $this->url(array("controller" => "montures" , "action" => "photo", "produitid" => $this->produitid), "default");
$linkInfos         = $this->url(array("controller" => "montures" , "action" => "infos", "produitid" => $this->produitid), "default" ) ;
$linkProgress      = $this->url(array("controller" => "ajaxres"  , "action" => "fileprogress")   , "default" ) ;
$formNames         = $this->formNames;
$jq  = $this->jQuery();

$onLoad  = " 
   jQuery('#photoproduit').filestyle({buttonText:'Chercher une photo',classButton:'btn btn-default',classIcon:'glyph-icon icon-folder-open',icon: true});
   jQuery('#fileupload').fileupload({
                                      paramName:'photoproduit',
                                      url      : '".$linkPhotoUpload."' ,
                                      dropZone : jQuery('#dropzone'),
                                      type     : 'POST',
                                      dataType : 'json',
                                      add      : function(e , data) {
                                             jQuery('#importPhotoBtn').on('click' , function( event ) {
   		                                                event.preventDefault();
   		                                                SIRAH.loading.on(jQuery('#dialogChangePhoto') , 'Patientez , chargement de la photo...' );
   		                                                var jqXhr    = data.submit();
   		                                                jqXhr.success(function(result , textStatus , jqXHR){
                                                         if( result.success != undefined) {
                                                             SIRAH.error.raise(jQuery('#dialogChangePhoto') , 'Opération terminée : '+result.success , 'success');
                                                             var file  = result.files[0];
                                                             if( file  != undefined ){
                                                                 var newfilename  = file.path + file.name; 
                                                                  SIRAH.loading.off(false);                                                                  
                                                                  setTimeout(function(){
                                                                       jQuery('#photoBlockImg').attr('src', newfilename);
                                                                       jQuery('#dialogChangePhoto').dialog2('close');
                                                                       document.location.href = '".$linkInfos."';},
                                                                        1000);                                                     
                                                             }
                                                        } else if(result.error != undefined) {
                                                          SIRAH.error.raise(jQuery('#dialogChangePhoto') , 'Opération terminée : '+result.error , 'error');
                                                          SIRAH.loading.off(false); 
                                                          return true;      
                                                        }
                                         });
           jqXhr.error(function( result , textStatus, errorThrown){
                 SIRAH.error.raise(jQuery('#dialogChangePhoto') , 'Opération terminée , aucune erreur valide n\'a été retournée : '+result , 'error');
                 SIRAH.loading.off(false);
                 return false;        
           });
   		});  },    
        messages: {uploadedBytes: 'Le fichier que vous voulez uploader est trop lourd'}
     });
jQuery('#fileupload').bind('fileuploadsubmit',function (e, data) {var inputs = jQuery(this).find(':input');data.formData = inputs.serializeArray();});     
jQuery('#fileupload').bind('fileuploadprogress',function(e, data) {var progress = parseInt(data.loaded / data.total *100, 10);jQuery('#progress').css('width', progress+'%');jQuery('#progress').html(progress+'%');});
jQuery('#fileupload').bind('fileuploaddrop',function (event , data) {
            event.preventDefault();
   		    SIRAH.loading.on( jQuery('#dialogChangePhoto') , 'Patientez , chargement de la photo...' );
   		     var jqXhr    = jQuery(this).fileupload('send', data );
   		     jqXhr.success(function(result , textStatus , jqXHR){
             if( result.success != undefined) {
                 SIRAH.error.raise(jQuery('#dialogChangePhoto') , 'Opération terminée : '+result.success , 'success');
                 var file  = result.files[0];
                 if( file  != undefined ){
                     var newfilename  = file.path + file.name; 
                     SIRAH.loading.off(false);                                       
                     jQuery('#dialogChangePhoto').dialog2('close');
                     setTimeout(function(){jQuery('#photoBlockImg').attr('src',newfilename);document.location.href = '".$linkInfos."';}, 500);                                                     
                         }
                 } else if(result.error != undefined) {
                    SIRAH.error.raise(jQuery('#dialogChangePhoto') , 'Opération terminée : '+result.error , 'error');
                    SIRAH.loading.off(false); 
                    return true;      
                 }
           });
           jqXhr.error(function( result , textStatus, errorThrown){
                 SIRAH.error.raise(jQuery('#dialogChangePhoto') , 'Opération terminée , aucune erreur valide n\'a été retournée : '+result , 'error');
                 SIRAH.loading.off(false);
                 return false;        
           });
   });
   jQuery(document).bind('dragover', function (e) {
          var dropZone = jQuery('#dropzone'),
          timeout = window.dropZoneTimeout;
          if (!timeout) {
              dropZone.addClass('in');
           } else {
              clearTimeout(timeout);
           }
         var found = false,
      	         node = e.target;
          do {
               if (node === dropZone[0]) {
       		   found = true;
       		   break;
       	    }
       	     node = node.parentNode;
              } while (node != null);
              if (found) {
                 dropZone.addClass('hover');
               } else {
                 dropZone.removeClass('hover');
               }
           window.dropZoneTimeout = setTimeout(function () {
                 window.dropZoneTimeout = null;
                  dropZone.removeClass('in hover');
            }, 100);
    }); ";
$jq->addOnLoad($onLoad);
$basePath    = VIEW_BASE_PATH;
$jq->addStyleSheet(     $basePath . "/js/fileupload/css/jquery.fileupload.css");
$jq->addStyleSheet(     $basePath . "/js/fileupload/css/jquery.fileupload-ui.css");
$jq->addStyleSheet(     $basePath . "/css/sirahfileupload.css");
$jq->addJavascriptFile( $basePath . "/js/bootstrap/bootstrap-filestyle.js");
$jq->addJavascriptFile( $basePath . "/js/fileupload/js/vendor/jquery.ui.widget.js");
$jq->addJavascriptFile( $basePath . "/js/fileupload/js/jquery.iframe-transport.js");
$jq->addJavascriptFile( $basePath . "/js/fileupload/js/jquery.fileupload.js");
$jq->addJavascriptFile( $basePath . "/js/fileupload/js/jquery.fileupload-ui.js");

?>
<?php $this->headStyle()->captureStart() ?>
.bar{height: 18px;background: green;}
div.bootstrap-filestyle input[type="text"]{width:auto;margin-left:5px;margin-right:5px;margin-bottom:0;}
div.bootstrap-filestyle, div.fileUploadRow{margin-bottom:15px;}
<?php $this->headStyle()->captureEnd()   ?>  
<form style="margin-bottom:10px;" class="form-horizontal" id="fileupload"  action="<?php echo $linkPhotoUpload; ?>" enctype="multipart/form-data" method="post">
    <div class="row">           
       <div class="col-lg-12 fileupload-progress fade">                
         <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
              <div id="progress" class="progress-bar progress-bar-success" style="width:0%;"></div>
         </div>
         <div class="progress-extended">&nbsp;</div>              
       </div>
    </div>
     <div class="row col-md-12 fileUploadRow">
        <div class="col-md-4"> <label class="control-label" for="photo"> Chercher une photo (png ,gif,jpg ) 3MB : </label> </div>
        <div class="col-md-8"><input name="photoproduit" type="file" id="photoproduit" /> 
        <button type="submit" class="btn btn-success btn-primary" id="importPhotoBtn"> 
        <span class="glyphicon glyphicon-upload"></span> Changer </button> </div>		 
	 </div>
	 <div id="dropzone" class="well fade">
           Vous pouvez glisser-deposer votre photo dans ce cadre ou cliquez dans le champ ci-dessous.
     </div>	   
    <input type="hidden" name="<?php echo $this->csrfTokenId; ?>"       id="<?php echo $this->csrfTokenId; ?>"       value="<?php echo $this->csrfTokenValue; ?>" />
    <input type="hidden" name="<?php echo $formNames['produitid']; ?>"  id="<?php echo $formNames['produitid']; ?>"  value="<?php echo $this->produitid; ?>"    />
</form>    
<?php if($this->isAjax) : ?>
<?php echo $this->jQuery(); echo $this->headStyle(); ?>
<?php endif; ?>
    