<?php 
$data             = $this->data;

$saveAndCreateLink= $this->url(array("module"=> "admin","controller"=>"registremodifications", "action" => "create","new_creation"=>1), "default" );
$formSubmit       = $this->url(array("module"=> "admin","controller"=>"registremodifications", "action" => "create"), "default" );
$backList         = $this->url(array("module"=> "admin","controller"=>"registremodifications", "action" => "list")  , "default" );
$basePath         = VIEW_BASE_PATH;
$domaines         = $this->domaines;
$localites        = $this->localites;
$situations       = array("Célibataire" => "Célibataire", "Marié(e)" => "Marié(e)", "Divorcé(e)" => "Divorcé(e)", "Veuf(ve)" => "Veuf(ve)");
$me               = Sirah_Fabric::getUser();
$searchUrl        = $this->url(array("module"=>"admin","controller"=>"ajaxres", "action"=>"searchrc"  ), "default" );
$checkLibUrl      = $this->url(array("module"=>"admin","controller"=>"ajaxres", "action"=>"checkrclib"), "default" );
$checkNumeroUrl   = $this->url(array("module"=>"admin","controller"=>"ajaxres", "action"=>"checkrcnum","type"=>"modification"), "default" );
$linkSearchParent = $this->url(array("module"=>"admin","controller"=>"ajaxres", "action"=>"registreslist","parentform" =>"createRegistreForm", "selectCmdKey"=> "selectRegistre","selectedKey"=>"parentid","selectedVal"=>"parentnum"), "default");
$parentid         = $this->parentid;
$parentNumRc      = $this->parentNum;
$representantid   = $this->representantid;
?>
<?php $this->headStyle()->captureStart() ?>
.input-document{width:250px;display:inline-block;}
.form-horizontal .checkbox, .form-horizontal .checkbox-inline,.form-horizontal .control-label,.form-horizontal .radio, .form-horizontal .radio-inline {padding-top:0!important}
.grpChosen{width:100px !important;}
<?php $this->headStyle()->captureEnd()   ?>
<?php
$jq     = $this->jQuery();  
$onLoad = "
jQuery('#parentnum').click(function(event){event.preventDefault();jQuery('.searchRegistre').trigger('click'); });
jQuery('.searchRegistre').click(function(event){
	event.preventDefault();
	var filterListDialog  = jQuery('<div></div>').attr('id','filterListRegistres').addClass('modal-medium');             		 
	filterListDialog.dialog2({title:'Rechercher un registre de commerce',content:'".$linkSearchParent."',autoOpen:false,modalClass:'modal-wide',removeOnClose:true,closeOnEscape: true, closeOnOverlayClick: true,showCloseHandle:true,initialLoadText:'Chargement...'});        		            		
	filterListDialog.dialog2('open'); 
});
jQuery('#selectRegistre').bind('selectThis' , function(event, param1 ) {
    event.preventDefault();
	var parentid = parseInt(jQuery('#createRegistreForm').find('#paiementid').val() );
	if(!parentid && param1 ) {
		parentid =  param1;
	    jQuery('#createRegistreForm').find('#parentid').val(param1)
	}
	jQuery('#filterListRegistres').dialog2('close');
    document.location.href = '".$formSubmit."/parentid/'+parentid;	   
});
var updateFormByNum = function(numero){
	var formSelector = jQuery('#createRegistreForm');
	SIRAH.request.get(formSelector,'".$searchUrl."', {data:{'numero':numero},beforeSend : function(){},			   
		success:function( data ) {
			if( data.success !== undefined ) {
			    if(data.numero !== undefined) {
				   jQuery('#numero').val(data.numero);
			    }			   
			    if((data.success !== undefined) && (data.date_enregistrement_day !== undefined ) ) {
				   jQuery('#date_day').val(data.date_enregistrement_day);
				   jQuery('#date_day').trigger('chosen:updated');
			    }
			    if((data.success !== undefined) && (data.date_enregistrement_month !== undefined ) ) {
				   jQuery('#date_month').val(data.date_enregistrement_month);
				   jQuery('#date_month').trigger('chosen:updated');
			    }
			    if((data.success !== undefined) && (data.date_enregistrement_year !== undefined ) ) {
				   jQuery('#date_year').val(data.date_enregistrement_year);
				   jQuery('#date_year').trigger('chosen:updated');
			    }
			}	
		}
    });
};
jQuery('#numero').change(function(){
    var numero       = jQuery(this).val();
    var formSelector = jQuery('#createRegistreForm');
	jQuery('#numRcSearching').html('Vérification du numéro RCCM...');
	setTimeout(function(){	
		SIRAH.request.get(formSelector,'".$checkNumeroUrl."', { data:{'numero':numero}, beforeSend : function(){},
			success: function( data ) {
				jQuery('#numRcSearching').html('').removeClass('parsley-required').removeClass('parsley-required');
				jQuery('#numero').removeClass('danger').removeClass('parsley-error');
				jQuery('#numero').removeClass('success').removeClass('parsley-success');
				if( data.error !== undefined   ) {
					jQuery('#validnumrc').val('0');
					jQuery('#numRcSearching').html(data.error).addClass('parsley-required');
					jQuery('#numero').addClass('danger').addClass('parsley-error');
					jQuery('#numero').removeClass('success').removeClass('parsley-success');
					SIRAH.dialog.alert(data.error,'Numéro RCCM Invalide');
					return data;
				}
				if( data.success !== undefined ) {
					jQuery('#numRcSearching').html('').removeClass('parsley-required');
					jQuery('#numRcSearching').html('').addClass('parsley-success');
					jQuery('#numero').removeClass('danger').removeClass('parsley-error');
					jQuery('#numero').addClass('success').addClass('parsley-success');
					jQuery('#validnumrc').val('1');
					updateFormByNum(data.numero);
				}
			}
		});		
	}, 500);
});
jQuery('input:checkbox').bootstrapSwitch();
jQuery('input:checkbox').on('switchChange.bootstrapSwitch', function(event, state) {
	if((state == true) && (this.name =='find_documents')) {
		jQuery('#findDocumentsOptions').removeClass('hide');
		jQuery('.manualFindDocuments').addClass('hide'); 
	} 
	if((state == false) && (this.name =='find_documents')){
		jQuery('#findDocumentsOptions').addClass('hide');
		jQuery('.manualFindDocuments').removeClass('hide');
	}
});
jQuery('input:checkbox, input:radio').uniform();
jQuery('.chosen').chosen({allow_single_deselect:true,no_results_text: 'Aucun element ne correspond à ', width:'100%'});
jQuery('input[name=\'find_documents\']').click(function( event ){
	if( jQuery(this).is(':checked')) {
		jQuery('#findDocumentsOptions').removeClass('hide');
		jQuery('.manualFindDocuments').addClass('hide');
	} else {
		jQuery('#findDocumentsOptions').addClass('hide');
		jQuery('.manualFindDocuments').removeClass('hide');
	} 
});
jQuery('#docmini').filestyle({buttonText:'Rechercher un document',classButton:'btn btn-primary',classInput:'input-inline form-control input-document',classIcon:'glyph-icon icon-folder-open',icon: true});
jQuery('#docoriginal').filestyle({buttonText:'Rechercher un document',classButton:'btn btn-primary',classInput:'input-inline form-control input-document',classIcon:'glyph-icon icon-folder-open',icon: true});
jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});  
jQuery('#saveButton').click(function(e){
    e.preventDefault();      
    var formSelector = jQuery('#createRegistreForm');
    var libelle      = jQuery.trim(formSelector.find('#libelle').val());
    var numero       = jQuery.trim(formSelector.find('#numero').val());
	var parentnum    = jQuery.trim(formSelector.find('#parentnum').val());
    var localiteid   = parseInt(formSelector.find('#localiteid').val());
    var isValidNumRC = parseInt(formSelector.find('#validnumrc').val());
    
	if(!isValidNumRC) {
		jQuery('#numRcSearching').html(data.error).addClass('parsley-required');
		jQuery('#numero').addClass('danger').addClass('parsley-error');
		SIRAH.dialog.alert('Veuillez saisir un numéro RCCM Valide','Erreur de saisie');
        return;
	}
    if( SIRAH.util.isEmpty( libelle )){
		SIRAH.dialog.alert('Entrez un nom commercial valide','Erreur de saisie');
        return;
    }
	if( SIRAH.util.isEmpty( parentnum )){
		SIRAH.dialog.alert('Sélectionnez un numéro RCCM Valide','Erreur de saisie');
        return;
    }
    if( SIRAH.util.isEmpty( localiteid )){
		SIRAH.dialog.alert('Veuillez selectionner une localité valide','Erreur de saisie');
        return;
    }      
    formSelector.submit();
}); 

jQuery('#saveAndCreateButton').click(function(e){
	e.preventDefault();      
    var formSelector = jQuery('#createRegistreForm');
    var libelle      = jQuery.trim(formSelector.find('#libelle').val());
    var numero       = jQuery.trim(formSelector.find('#numero').val());
	var parentnum    = jQuery.trim(formSelector.find('#parentnum').val());
    var localiteid   = parseInt(formSelector.find('#localiteid').val());
	var isValidNumRC = parseInt(formSelector.find('#validnumrc').val());
    
	if(!isValidNumRC) {
		jQuery('#numRcSearching').html(data.error).addClass('parsley-required');
		jQuery('#numero').addClass('danger').addClass('parsley-error');
		SIRAH.dialog.alert('Veuillez saisir un numéro RCCM Valide','Erreur de saisie');
        return;
	}  	  
    if( SIRAH.util.isEmpty( libelle )){
		SIRAH.dialog.alert('Entrez un nom commercial valide','Erreur de saisie');
        return;
    }
	if( SIRAH.util.isEmpty( parentnum )){
		SIRAH.dialog.alert('Sélectionnez un numéro RCCM Valide','Erreur de saisie');
        return;
    }
    if( SIRAH.util.isEmpty( localiteid )){
		SIRAH.dialog.alert('Veuillez selectionner une localité valide','Erreur de saisie');
        return;
    } 
    formSelector.attr('action',\"".$saveAndCreateLink."\");	  
    formSelector.submit();
});";  
  $jq->addOnLoad($onLoad);
  $jq->addJavascriptFile($basePath."/js/bootstrap/bootstrap-filestyle.js");
  $jq->addJavascriptFile($basePath."/assets-minified/widgets/uniform/uniform.js");
  $jq->addStylesheet(    $basePath."/assets-minified/widgets/uniform/uniform.css" );
  $jq->addJavascriptFile($basePath."/assets-minified/widgets/input-switch/inputswitch.js");
  $jq->addStylesheet(    $basePath."/assets-minified/widgets/input-switch/inputswitch.css" ); 
?>

<div    class="content-box">    
    <h3 class="content-box-header content-box-header-alt bg-default">ETAPE 1 <small> Les informations de la modification </small></h3>
    <form action="<?php echo $formSubmit; ?>" method="post" id="createRegistreForm" class="form-horizontal mrg15T row" role="form" enctype="multipart/form-data">      
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label" title="Le numéro RC doit contenir 14 ou 18 caractères"> N° RCCM* : </label>
			<div   class="col-sm-12 col-md-9"> 
				<div class="input-group">
					<input disabled="disabled" style="text-transform:uppercase" maxlength="24" type="text" name="parentnum" id="parentnum" class="form-control" placeholder="Numéro du RCCM Modifié" value="<?php echo $parentNumRc; ?>" />
					<div class="input-group-btn">
						<button id="searchRegistre" title="Selectionnez un registre de commerce" type="submit" class="btn btn-primary searchRegistre"><span class="glyph-icon icon-search"></span> Selectionner un RCCM</button>
					</div>
				</div>
				<input type="hidden" name="selectRegistre" id="selectRegistre"  /> 
				<input type="hidden" name="parentid"       id="parentid" value="<?php echo intval($data['parentid']); ?>" />
			</div>        
		</div>	  
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label" title="Le numéro d'inscription doit contenir 14 ou 18 caractères"> Numéro de la Modification* : </label>
			<div   class="col-sm-12 col-md-6"><input style="text-transform:uppercase" maxlength="24" type="text" name="numero" id="numero" class="form-control" placeholder="Numéro d'enregistrement de la modification" value="<?php echo $this->escape($data["numero"]); ?>" /></div>
			<div   class="col-sm-12 col-md-3" id="numRcSearching"> </div>	
            <input type="hidden" name="validnumrc" id="validnumrc" value="1" />			
		</div> 
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Type modification*:</label>
			<div   class="col-sm-12 col-md-9"> <?php echo $this->formSelect("type", intval($data["type"]), array("class"=>"form-control chosen"), $this->types); ?> </div>   
		</div>      
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Nom commercial*: </label>
			<div   class="col-sm-12 col-md-9"> <input type="text" name="libelle" id="libelle" class="form-control" placeholder="Nouveau nom commercial" value="<?php echo $this->escape($data["libelle"]); ?>" /></div>        
		</div>
		<div class="form-group">    
		    <label class="col-sm-12 col-md-3 control-label"> Date d'enregistrement*: </label>
			<div   class="col-sm-12 col-md-9">
				<div class = "input-group">
					<?php echo $this->formSelect("date_day"  , $data["date_day"]  , array("class" => "form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?> 
					<span class="input-group-btn" style="width:0px;"></span>
					<?php echo $this->formSelect('date_month', $data["date_month"], array("class" => "form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?>
					<span class="input-group-btn" style="width:0px;"></span>
					<?php echo $this->formSelect('date_year' , $data["date_year"] , array("class" => "form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1960, intval(date("Y")) ) );?>             
				</div>
			</div>
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Secteur d'activités*: </label>
			<div   class="col-sm-12 col-md-9"> <?php echo $this->formSelect("domaineid", intval( $data["domaineid"]), array("class" => "form-control chosen"), $domaines ); ?> </div>       
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Activité actuelle : </label>
			<div   class="col-sm-12 col-md-9"> <input type="text" name="article_actuel" id="article_actuel" class="form-control" value="<?php echo $this->escape($data["article_actuel"]); ?>" placeholder="Indiquez l'activité actuelle" /></div>       
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Activité supprimée: </label>
			<div   class="col-sm-12 col-md-9"><input type="text" name="article_suppr" id="article_suppr"    class="form-control" value="<?php echo $this->escape($data["article_suppr"]); ?>" placeholder="Indiquez l'activité qui a été supprimée" /></div>       
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Activité ajoutée : </label>
			<div   class="col-sm-12 col-md-9"><input type="text" name="article_ajout" id="article_ajout"    class="form-control" value="<?php echo $this->escape($data["article_ajout"]); ?>" placeholder="Décrivez l'activité qui a été ajoutée" /></div>       
		</div>	  
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Nouvelle adresse*: </label>
			<div   class="col-sm-12 col-md-9"> <input type="text" name="adresse" id="adresse" class="form-control" value="<?php echo $this->escape($data["adresse"]); ?>" placeholder="Nouvelle Adresse de la société" /></div>       
		</div>	  
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Numéro de téléphone: </label>
			<div   class="col-sm-12 col-md-9"> <input type="text" name="telephone" id="telephone" class="form-control" value="<?php echo $this->escape($data["telephone"]); ?>" placeholder="Nouveau numéro de téléphone" /></div>       
		</div>
		<?php if(($me->isAdmin() || $me->isOPS()) && !intval($data["localiteid"])): ?>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Localité* : </label>
			<div   class="col-sm-12 col-md-9"> <?php echo $this->formSelect("localiteid", intval($data["localiteid"]  ), array("class"=>"form-control chosen"), $localites); ?> </div>   
		</div>
		<?php else: ?> 
		  <input type="hidden" name="localiteid"  id="localiteid" value="<?php echo intval($data['localiteid']); ?>" />
		<?php endif; ?>          
			  
		<h3 class="content-box-header content-box-header-alt bg-default mrg10R mrg10L mrg10B">ETAPE 2 <small> Nouveau dirigeant ? </small></h3>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Nom & Prénom*: </label>
			<div   class="col-sm-12 col-md-9"> 
				<div class="input-group">
				  <input type="text" name="nom"    id="nom"    class="form-control" value="<?php echo $this->escape($data["nom"]);   ?>" placeholder="Nom de famille" />
				  <span class="input-group-btn" style="width:0px;"></span>
				  <input type="text" name="prenom" id="prenom" class="form-control" value="<?php echo $this->escape($data["prenom"]);?>" placeholder="Prénom" />      
				</div>
			</div>  
		</div>	  
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Adresse*: </label>
			<div   class="col-sm-12 col-md-9"> <input type="text" name="adresse" id="adresse" class="form-control" value="<?php echo $this->escape($data["adresse"]); ?>" placeholder="Adresse" /></div>       
		</div>	  
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Numéro de téléphone: </label>
			<div   class="col-sm-12 col-md-9"> <input type="text" name="telephone" id="telephone" class="form-control" value="<?php echo $this->escape($data["telephone"]); ?>" placeholder="Numéro de téléphone" /></div>       
		</div>	  
		<div class="form-group">    
		    <label class="col-sm-12 col-md-3 control-label"> Date & lieu de naissance*: </label>
			<div   class="col-sm-12 col-md-9">
			    <div class="input-group">
				   <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect("date_naissance_day", $data["date_naissance_day"]  , array("class" => "form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?></span>
				   <span class="input-group-btn" style="width:0px;"></span>
				   <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect('date_naissance_month', $data["date_naissance_month"], array("class" => "form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?> </span>
				   <span class="input-group-btn" style="width:0px;"></span>
				   <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect('date_naissance_year' , $data["date_naissance_year"] , array("class" => "form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1900, intval(date("Y")) ) );?></span>
				   <span class="input-group-btn" style="width:0px;"></span>
				   <input style="height:40px;" type="text" name="lieunaissance" id="lieunaissance" class="form-control" value="<?php echo $data["lieunaissance"]; ?>" placeholder="Lieu de naissance" />
			    </div>
			</div>    
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Sexe*: </label>
			<div   class="col-sm-12 col-md-3 radio radio-primary"> 
				<label class="radio-inline pull-left"><input type="radio" name="sexe" id="sexe-m" value="M" <?php if($data["sexe"] == "M") echo "checked"; ?>> Homme </label>          
				<label class="radio-inline pull-left"><input type="radio" name="sexe" id="sexe-f" value="F" <?php if($data["sexe"] == "F") echo "checked"; ?>> Femme </label>
			</div>        
		</div>
		<div class="form-group">          
			<label class="col-sm-12 col-md-3 control-label"> Nationalité* : </label>
			<div   class="col-sm-12 col-md-9"> <?php echo $this->formSelect("country", $data['country'], array("class" => "form-control chosen") , $this->countries());?> </div>
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Situation matrimoniale*: </label>
			<div   class="col-sm-12 col-md-9"> <?php echo $this->formSelect("marital_status", $data["marital_status"], array("class" => "form-control"), $situations); ?> </div>        
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> N° passport ou N°CNIB*: </label>
			<div   class="col-sm-12 col-md-9"> <input type="text" name="passport" id="passport" class="form-control" value="<?php echo $this->escape($data["passport"]); ?>" placeholder="Le numéro d'identité (CNIB ou PASSPORT)" /></div>        
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Profession: </label>
			<div   class="col-sm-12 col-md-9"> <input type="text" name="fonction" id="fonction" class="form-control"  placeholder="La profession du gérant" /></div>        
		</div>	  
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Adresse email: </label>
			<div   class="col-sm-12 col-md-9"> <input type="text" name="email" id="email" class="form-control" value="<?php echo $data["email"]; ?>" placeholder="Adresse email" /></div>       
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Indexation automatique: </label>
			<div   class="col-sm-12 col-md-9" style="height:32px;"> <input type="checkbox" data-on-color="primary" name="find_documents" class="input-switch" data-size="medium" data-on-text="Oui" data-off-text="Non" <?php echo (intval($data["find_documents"]) == 1) ? 'checked' : ''; ?> value="1"></div>
		</div>
		<div class="form-group"> 
			<label class="col-sm-12 col-md-3 control-label"> Contrôle de la qualité: </label>
			<div   class="col-sm-12 col-md-9" style="height:32px;"> <input type="checkbox" data-on-color="primary" name="check_documents" class="input-switch" data-size="medium" data-on-text="Oui" data-off-text="Non" <?php echo (intval($data["check_documents"]) == 1) ? 'checked' : ''; ?> value="1"></div>
		</div>
		<div id="findDocumentsOptions" class="form-group <?php echo (intval($data["find_documents"]) == 0) ? 'hide' :''; ?> "> 
			<label class="col-sm-12 col-md-3 control-label"> Dossier source*: </label>
			<div   class="col-sm-12 col-md-9"> <input type="text" name="find_documents_src" id="find_documents_src" class="form-control" placeholder="Dossier source de stockage des documents" value="<?php echo $data["find_documents_src"]; ?>" /></div> 
		</div>
		<div class="form-group manualFindDocuments <?php echo (intval($data["find_documents"]) == 1) ? 'hide' :''; ?> "> 
			<label class="col-sm-12 col-md-3 control-label"> Le formulaire * : </label>
			<div   class="col-sm-12 col-md-9"> <input type="file" name="docmini" id="docmini"    /></div>        
		</div>
		<div class="form-group manualFindDocuments <?php echo (intval($data["find_documents"]) == 1) ? 'hide' :''; ?>"> 
			<label class="col-sm-12 col-md-3 control-label"> Le fond de dossier* : </label>
			<div   class="col-sm-12 col-md-9"> <input type="file" name="docoriginal"  id="docoriginal"    /></div>        
		</div>	  
    </form>
 
<?php 
    $buttonsbar        = $this->Btnbar(array("class" => "button-pane") , $this->jqueryHandler());
    $toolSave          = $buttonsbar->button("Enregistrer","save")->setPriority("primary");
	$toolSaveAndCreate = $buttonsbar->button("Enregistrer & Nouveau","plus")->setPriority("primary");
    $toolCancel        = $buttonsbar->button("Annuler","chevron-left");
     
    $toolSave->setAttributes(  array("type"=> "submit", "class" => "btn btn-success"));
    $toolCancel->setAttributes(array("type"=> "submit"));
     
    $buttonsbar->add($toolSave          , "saveButton");
	$buttonsbar->add($toolSaveAndCreate , "saveAndCreateButton");
    $buttonsbar->add($toolCancel        , "cancelCreationButton");
    
    if( !$this->isAjax )
        echo $buttonsbar;
?>
</div>

<?php     
    if( $this->isAjax) {
   	    echo $this->jQuery();
    }
?>