<?php 
$roles              = $this->roles;
$token              = $this->token;
$data               = $this->data;
$priorities         = array("Selectionnez une priorité", "Très Elevée", "Elevée", "Normale", "Basse", "La plus basse");

$formSubmit         = $this->url(array("module"=>"admin","controller" =>"useroles","action"=>"create") , "default");
$backList           = $this->url(array("module"=>"admin","controller" =>"useroles","action"=>"list") , "default");
$basePath           = VIEW_BASE_PATH;


$jq     = $this->jQuery();  
$onLoad = " 
 
jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});
jQuery('#createRoleButton').click(function(e){
      e.preventDefault();            
      var rolename  = jQuery('#rolename').val();      
      if( SIRAH.util.isEmpty(rolename)) {
          SIRAH.error.raise('createRoleForm' , 'Vous devrez entrer une désignation valide');
           return;
      } 
      jQuery('#createRoleForm').submit();
   }); ";
  
$jq->addOnLoad($onLoad);
$buttonsBar  = $this->Btnbar(array() , $this->jqueryHandler());
$buttonSave  = $buttonsBar->button("Enregistrer un rôle","save")->setPriority("primary");
$buttonCancel= $buttonsBar->button("Annuler","ban");

$buttonSave->setAttributes(  array("type" => "submit"));
$buttonCancel->setAttributes(array("type" => "submit"));

$buttonsBar->add( $buttonSave  , "createRoleButton");
$buttonsBar->add( $buttonCancel, "cancelCreationButton");
?>
<form method="post" action="<?php echo $formSubmit; ?>" align="center" id="createRoleForm" role="form" class="form-horizontal">  
    <div class="panel panel-default">
        <ul class="list-group">
		    <li class="list-group-item">
			    <div class="form-group">  
				    <label class="col-md-2  col-sm-2 control-label"> Désignation*:</label>
				    <div   class="col-md-10 col-sm-10 col-xs-12">
					    <input id="rolename" type="text" maxlength="196" class="form-control" title="La désignation du rôle" placeholder="La désignation du rôle"  name="rolename" value="<?php echo $data['rolename']; ?>">
				    </div> 
			 
			    </div>
		    </li>
		    <li class="list-group-item">
				<div class="form-group">  
					<label class="col-md-2  col-sm-2 control-label"> Priorité*:</label>
					<div   class="col-md-10 col-sm-10 col-xs-12"><?php echo $this->formSelect("accesslevel", $data["accesslevel"], array("class" => "form-control") , $priorities); ?></div>      
				</div>
		    </li>
		    <li class="list-group-item">     
				<div class="form-group"> 
					<label class="col-md-2 col-md-2 col-sm-2 col-xs-hidden control-label"> Description* : </label>
					<div   class="col-md-10 col-sm-10"> <textarea class="textarea-sm" name="description"  id="description"><?php echo $this->escape($data["description"]); ?></textarea> 
				   </div>
			   </div>
			</li> 
        </ul>	
        <?php 
            $table  = $this->table(array("id" => "rolesListTable","class"  => array("table sirah-ui-table scrollable")));
            $table->isBordered(true)->isStripped(true)->isCondensed(true)->isHover(true);
            $rowHeader  = $table->row();
            $rowHeader->add("<input type=\"checkbox\" name=\"checkall\" id=\"checkAll\" class=\"checkAll\" />")
                      ->add("ID")
                      ->add("Désignations")
                      ->add("Hérite du/des role(s)")
                      ->add("Priorités");
            $table->setHeader($rowHeader);
            
            if(!empty(  $roles)) {
               foreach( $roles as $roleid => $rolename) {
                 		$roleRow         = $table->row(array("id" => "rowRole-".$roleid));
                 		$accessLevel     = Sirah_User_Acl_Table::getAccesslevel($roleid);
                 		$parents         = Sirah_User_Acl_Table::getRoleParents($roleid);                		                		
                 		$roleRow->add("<input value=\"".$roleid."\" type=\"checkbox\" name=\"parents[]\" id=\"parentids-".$roleid."\" class=\"checkbox\"  />" , array("id" => "checkboxCell-".$roleid));
                 		$roleRow->add("id#".$roleid);
                 		$roleRow->add($rolename);
                 		if(empty($parents )){
                 			$roleRow->add("Aucun");
                 		} else {
                 			$roleRow->add(implode(", " , $parents));
                 		}
                 		if(!empty($accessLevel) && isset($priorities[$accessLevel[0]])) {
                 			$roleRow->add($priorities[$accessLevel[0]]);
                 		}  else {
                 			$roleRow->add($priorities[5]);
                 		}
                 		$table->add($roleRow);                		
                 	}                 	
                 } else {
                 	$unfoundRow  = $table->row(array("style"  => 'text-align:center;'));
                 	$unfoundRow->add("Aucun role n' a été retrouvé dans le système", array("colspan"  => 7));
                 	$table->add($unfoundRow);
                 }  
                 echo $table;

                if(!$this->isAjax) {
          	        echo "<div class=\"panel-footer\"> ".$buttonsBar." </div>" ;
				} else {
					echo $this->jQuery();
					echo $this->headStyle();
				}				 
            ?>		
    </div>
</form>     
