<?php
   
   $defaultImgPath = APPLICATION_TEMPLATES."public/assets/images/product.png";
   $basePath       = ROOT_PATH ."/myTpl/public/";
   $items          = $this->items;
   $paginator      = $this->paginator;
   if( null != $paginator ) {
  	  $pagination  = $this->pagination(array(),"Elastic", "#", array(), array("class" => "panel-footer paginationControl", "style" => "text-align:center;")); 	  
  }
?>
<?php $this->headStyle()->captureStart() ?>
.section-content{padding:5px;}
.section-content .panel-desc a{color:#333333;font-size:18px;font-weight:bold}
.panel .panel-heading {padding-top:14px;padding-bottom:14px;}
.panel-more-shadow{word-wrap: break-word;background-color:#fff;background-clip: border-box;border:1px solid rgba(0,0,0,.125);box-shadow: 0 4px 8px 0 rgb(0 0 0 / 20%);}
body{background-color:#f1f1f1;background-image:url(<?php echo $basePath; ?>images/body-bg.png);}
.item-img{border-radius:0.20rem;padding:4px;border:1px solid rgba(0,0,0,.125) !important;background:#ffffff;box-shadow:0 2px 4px #d8e1e8}
<?php $this->headStyle()->captureEnd()   ?>

<div class="container section-content">
    <div id="contentItems" class="col-xs-12 col-sm-12 col-md-8 equal-height-panels items-content margin-center">
	    <div class="panel panel-white panel-more-shadow"> 
			<?php if( count($items) ): ?>
			    <?php foreach( $items as $item ): ?>
				    <?php
					    $itemId             = intval($item["articleid"]);
					    $introtext          = strip_tags($item["introtext"]);
					    $itemTitle          = strip_tags($item["title"]);
						$updateDate         = intval($item["updatedate"]);
						$updatedDateStr     = "";
						if( intval($updateDate)) {
							$zendUpdateDate = new Zend_Date(intval($updateDate), Zend_Date::TIMESTAMP );
							$updatedDateStr = ($zendUpdateDate)?$zendUpdateDate->toString("dd MMM Y à H:m") : "";
						}
					    $linkInfos          = $this->url(array("controller"=>"articles","action"=>"infos","module"=>"public","title"=>$itemTitle,"itemid"=>$itemId),"default",true);
					?>
				    <div class="panel-body panel-body-lg">
					    <div class="panel-desc">
						    <h5 class="list-group-item-heading mb-1"><u><a title="Cliquer pour en savoir plus" href="<?php echo $linkInfos; ?>" title="En savoir plus"> <?php echo $itemTitle; ?></a></u></h5>
							<?php if( $updateDate ) : ?>
							  <small style="font-size:12px !important;" class="text-muted"><i><?php echo sprintf("Mis à jour pour la dernière fois le %s",$updatedDateStr); ?></i></small>
							<?php endif; ?>
						</div>
						<div class="panel-card item-card flex-column align-items-start">
						<?php
						    
						    $output            = "";
							$imagePath         = (!empty($item["photogarde"]))? APPLICATION_DATA_PATH.DS."articles".DS."photogarde".DS."mini".DS.$item["photogarde"] : "";
							$imageFile         = null;
							if((null !== $imagePath) && file_exists($imagePath)) {
								$imagePathname = str_replace( APPLICATION_PATH , ROOT_PATH . DS ."myV1", $imagePath);
								$imageFile     = str_replace( DS , "/" , $imagePathname);
							}
							if(!empty($imageFile)) {
								$output       .= "<div class=\"flex-shrink-0 col-md-4\" > <img alt=\"".$itemTitle."\" class=\"img-responsive item-img\" width=\"100%\" height=\"150px\" src=\"".$imageFile."\" /></div>";
							    $output       .= "<div class=\"flex-grow-1 col-md-8 ms-auto\">
								                        <p style=\"text-align:justify !important\" class=\"item-card-text\"> ".$introtext."</p>
														<div class=\"d-flex flex-wrap btn-arrange\">
														    <a href=\"".$linkInfos."\" class=\"button\"> <i class=\"glyph-icon icon-info\"></i> En savoir plus... </a>
														</div>
												  </div>";
							} else {
								$output       .= "<div class=\"flex-grow-1 col-md-12 ms-auto\">
								                        <p  style=\"text-align:justify !important\"> ".$introtext."</p>
														<div class=\"d-flex flex-wrap btn-arrange\">
														    <a href=\"".$linkInfos."\" class=\"button\"><i class=\"glyph-icon icon-info\"></i> En savoir plus... </a>
														</div>
												  </div>";
							}
							echo $output; 
                        ?>
						</div>
					</div>
					<hr class="small">
				<?php endforeach; ?>
				<?php  echo $pagination->render(); ?>
			<?php endif; ?>
		</div>
	</div>
	<div class="col-xs-12 col-sm-4 col-md-4">
	    <div class="panel panel-danger">
	        <div class="panel-heading"><h4 class="panel-title"> <span class="glyph-icon icon-credit-card"></span> Mon Panier </h4> </div>
		    <?php echo $this->partial("orders/articles.phtml", array()); ?>
		</div>
	</div>
</div> 

