<?php
   
   $defaultImgPath    = APPLICATION_TEMPLATES."public/assets/images/product.png";
   $basePath          = ROOT_PATH ."/myTpl/public/";
   
   $linkHome          = $this->url(array("controller"=>"index","action"=>"index","module"=>"public"),"default",true);  
   $linkSearch        = $this->url(array("controller"=>"registres","action"=>"search","module"=>"public","advanced"=> 1), "default",true);
   $jq                = $this->jQuery();
   $onLoad            = "  
	    jQuery('.searchButton').click(function(event){event.preventDefault();document.location.href='".$linkSearch."';});
	    jQuery('.cancelButton').click(function(event){event.preventDefault();document.location.href='".$linkHome."';});
	";
$jq->addOnLoad($onLoad);
?>
<?php $this->headStyle()->captureStart() ?>
.panel .panel-heading {padding-top: 14px;padding-bottom: 14px;}
.panel-more-shadow{box-shadow:0 1px 6px rgb(31 31 31 / 12%), 0 1px 4px rgb(31 31 31 / 12%)}
body{background-color:#f1f1f1 !important}
<?php $this->headStyle()->captureEnd()   ?>

<div class="container section-content">
    <div id="about-us" class="col-xs-12 col-sm-12 col-md-8 equal-height-panels about-us-content margin-center">
	    <div class="panel panel-white panel-more-shadow"> 
			<div class="panel-body panel-body-lg"> 
			    <div class="panel-desc"> <?php echo $this->libelle; ?></div>
			    <p> <?php echo $this->description; ?></p> 
			</div>
			<div class="panel-footer">
				<div class="btn-group"><button id="cancelButton" class="btn btn-default cancelButton"><i class="glyph-icon icon-home"> </i> Page d'accueil</button></div> 
				<div class="btn-group"><button id="searchButton" class="btn btn-primary searchButton"> Commander <i class="glyph-icon icon-chevron-right"> </i> </button></div>	
			</div> 
		</div>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-4">
	    <div class="panel panel-danger">
	        <div class="panel-heading"><h4 class="panel-title"> <span class="glyph-icon icon-credit-card"></span> Mon Panier </h4> </div>
		    <?php echo $this->partial("orders/articles.phtml", array()); ?>
		</div>
	</div>
</div>

