<?php 
$data         = $this->data;
$formSubmit   = $this->url(array("controller" =>"registres", "action" => "extractmorales", "module" => "admin"), "default" );
$backList     = $this->url(array("controller" =>"registrephysique", "action" => "list"  , "module" => "admin"), "default" );
$localites    = $this->localites;
$annees       = $this->annees;
?>
<?php $this->headStyle()->captureStart() ?>

<?php $this->headStyle()->captureEnd()   ?>

<?php

$jq     = $this->jQuery();  
$onLoad = " 
jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});  
jQuery('#importButton').click(function(e){
      e.preventDefault();      
      var  formSelector = jQuery('#importForm');
      var  annee        = parseInt(jQuery.trim(formSelector.find('#annee').val()));
      var  localiteid   = parseInt(formSelector.find('#localiteid').val());

      if( SIRAH.util.isEmpty( annee )){
          SIRAH.error.raise('importForm','Entrez une année valide');
          return;
      } 
      if( SIRAH.util.isEmpty( localiteid )){
          SIRAH.error.raise('importForm','Veuillez selectionner une localité');
          return;
      }      
      formSelector.submit();
   }); ";
  
  $jq->addOnLoad($onLoad);

?>

<div     class="content-box">    
    <h3 class="content-box-header content-box-header-alt bg-default">ETAPE 1 <small> Paramèters des données source</small></h3>
    <form method="post"  id="importForm" class="form-horizontal mrg15T row" role="form" enctype="multipart/form-data">  
     <div class="form-group"> 
           <label class="col-sm-3 control-label"> Dossier source racine* : </label>
           <div   class="col-sm-6"> <input type="text" name="rootpath" id="rootpath" class="form-control" placeholder="Dossier source racine" value="<?php echo $data["rootpath"]; ?>" /></div>        
     </div>
     <div class="form-group"> 
           <label class="col-sm-3 control-label"> Dossier source enfant* : </label>
           <div   class="col-sm-6"> <input type="text" name="srcfolder" id="srcfolder" class="form-control" placeholder="Dossier source enfant" value="<?php echo $data["srcfolder"]; ?>" /></div>        
     </div>
     <div class="form-group"> 
           <label class="col-sm-3 control-label"> Dossier destination des documents* : </label>
           <div   class="col-sm-6"> <input type="text" name="destpath" id="destpath" class="form-control" placeholder="Dossier destination des documents" value="<?php echo $data["destpath"]; ?>" /></div>        
     </div>
      
      <h3 class="content-box-header content-box-header-alt bg-default mrg10R mrg10L mrg10B">ETAPE 2 <small> Les paramètres des registres à extraire </small></h3>
       <div class="form-group"> 
          <label class="col-sm-3 control-label"> Localité concernée* : </label>
           <div  class="col-sm-6"> <?php echo $this->formSelect("localitekey", $data["localitekey"] , array("class"=>"form-control"), $localites); ?> </div>   
       </div> 
       
       <div class="form-group"> 
           <label class="col-sm-3 control-label"> L'année concernée* : </label>
           <div   class="col-sm-6"> <?php echo $this->formSelect("annee", $data["annee"] , array("class"=>"form-control"), $annees); ?> </div>        
     </div> 
     <div class="form-group"> 
           <label class="col-sm-3 control-label"> Les pages à extraire: </label>
           <div   class="col-sm-6"> <input type="text" name="extract_pages" id="extract_pages" class="form-control" placeholder="Pages à extraire pour le formulaire. Exemple:1,2,3" value="<?php echo $data["extract_pages"]; ?>" /></div>        
     </div>                
    </form>
 
    <?php 
    $buttonsbar  = $this->Btnbar(array("class" => "button-pane") , $this->jqueryHandler());
    $toolCreate  = $buttonsbar->button("Copier/Extraire les données","download")->setPriority("primary");
    $toolCancel  = $buttonsbar->button("Annuler","chevron-left");
     
    $toolCreate->setAttributes(array("type" => "submit", "class" => "btn btn-success"));
    $toolCancel->setAttributes(array("type" => "submit"));
     
    $buttonsbar->add($toolCreate ,"importButton");
    $buttonsbar->add($toolCancel ,"cancelCreationButton");
    
    if( !$this->isAjax )
        echo $buttonsbar;
    ?>
</div>

<?php     
  

   if( $this->isAjax) {
   	   echo $this->jQuery();
   }
   
   ?>