<?php 
$data        = $this->data;
$formSubmit  = $this->url(array("controller" =>"registres", "action" => "missingnere", "module" => "admin"), "default" );
$backList    = $this->url(array("controller" =>"registres", "action" => "list", "module" => "admin"), "default" );
$localites   = $this->localites;
$annees      = $this->annees;
$basePath    = VIEW_BASE_PATH;
?>
<?php $this->headStyle()->captureStart() ?>

<?php $this->headStyle()->captureEnd()   ?>

<?php

$jq     = $this->jQuery();  
$onLoad = " 
jQuery('.chosen').chosen({allow_single_deselect:true,no_results_text: 'Aucun element ne correspond à ', width:'100%'});
jQuery('input:checkbox, input:radio').uniform();
jQuery('input[name=\'check_documents\']').bootstrapSwitch();
jQuery('input[name=\'extract_components\']').bootstrapSwitch();
jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});  
jQuery('#validationButton').click(function(e){e.preventDefault();var formSelector = jQuery('#sigueImportForm');formSelector.submit();}); ";

$jq->addOnLoad($onLoad);
$jq->addJavascriptFile( $basePath . "/js/bootstrap/bootstrap-filestyle.js");
$jq->addJavascriptFile( $basePath . "/assets-minified/widgets/uniform/uniform.js");
$jq->addStylesheet(     $basePath . "/assets-minified/widgets/uniform/uniform.css" );
$jq->addJavascriptFile( $basePath . "/assets-minified/widgets/input-switch/inputswitch.js");
$jq->addStylesheet(     $basePath . "/assets-minified/widgets/input-switch/inputswitch.css" );
?>
<div    class="content-box">        
    <form action="<?php echo $formSubmit; ?>" method="post"  id="sigueImportForm" class="form-horizontal mrg15T row" role="form" enctype="multipart/form-data">   	       
		<h3 class="content-box-header content-box-header-alt bg-default">ETAPE 1 <small> DONNEES NERE </small></h3>
		<div class="form-group"> 
			   <label class="col-sm-3 control-label"> Hôte* : </label>
			   <div   class="col-sm-6"> <input type="text" name="dbparams_host" id="dbparams_host" class="form-control" placeholder="Le nom d'hôte" value="<?php echo $data["dbparams_host"]; ?>" /></div>        
		</div>
		<div class="form-group"> 
			   <label class="col-sm-3 control-label"> Identifiant* : </label>
			   <div   class="col-sm-6"> <input type="text" name="dbparams_username" id="dbparams_username" class="form-control" placeholder="Le nom d'utilisateur du compte" value="<?php echo $data["dbparams_username"]; ?>" /></div>        
		</div>
		<div class="form-group"> 
			   <label class="col-sm-3 control-label"> Mot de passe* : </label>
			   <div   class="col-sm-6"> <input type="password" name="dbparams_password" id="dbparams_password" value="<?php echo $data["dbparams_password"]; ?>" class="form-control" /></div>        
		</div>
		<div class="form-group"> 
			   <label class="col-sm-3 control-label"> Année* : </label>
			   <div   class="col-sm-9"> <?php echo $this->formSelect("annee", $data["annee"], array("class"=>"form-control chosen"), $this->annees); ?> </div>           
		</div>
		<div class="form-group"> 
			<label class="col-sm-3 control-label"> Localité concernée* : </label>
			<div  class="col-sm-9"> <?php echo $this->formSelect("localite", $data["localite"] , array("class"=>"form-control"), $this->localites); ?> </div>   
		</div>
</form>
 
    <?php 
    $buttonsbar  = $this->Btnbar(array("class" => "button-pane") , $this->jqueryHandler());
    $toolCreate  = $buttonsbar->button("Importer les documents","check")->setPriority("primary");
    $toolCancel  = $buttonsbar->button("Annuler","chevron-left");
     
    $toolCreate->setAttributes(array("type" => "submit", "class" => "btn btn-success"));
    $toolCancel->setAttributes(array("type" => "submit"));
     
    $buttonsbar->add($toolCreate ,"validationButton");
    $buttonsbar->add($toolCancel ,"cancelCreationButton");
    
    if( !$this->isAjax )
        echo $buttonsbar;
    ?>
</div>

<?php     
   if( $this->isAjax) {
   	   echo $this->jQuery();
   }
   
   ?>