<?php 
$data        = $this->data;
$formSubmit  = $this->url(array("controller" =>"registres", "action" => "saveusersdata", "module" => "admin"), "default" );
$backList    = $this->url(array("controller" =>"registres", "action" => "list", "module" => "admin"), "default" );
$localites   = $this->localites;
$annees      = $this->annees;	
?>
<?php $this->headStyle()->captureStart() ?>

<?php $this->headStyle()->captureEnd()   ?>

<?php

$jq     = $this->jQuery();  
$onLoad = " 
jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});  
jQuery('#saveButton').click(function(e){e.preventDefault();var formSelector = jQuery('#checkingForm');formSelector.submit();}); ";
  
$jq->addOnLoad($onLoad);

?>

<div     class="content-box">    
    <h3 class="content-box-header content-box-header-alt bg-default"> ETAPE 1 <small> Paramètres de sélection des RCCM </small></h3>
    <form action="<?php echo $formSubmit; ?>" method="post"  id="checkingForm" class="form-horizontal mrg15T row" role="form">   	      
	<div class="form-group"> 
        <label class="col-sm-3 control-label"> OPS* : </label>
        <div   class="col-sm-6"><?php echo $this->formSelect("ops_username", $data["ops_username"], array("class"=>"form-control"),  $this->users ); ?> </div>        
    </div>
	<div class="form-group"> 
        <label class="col-sm-3 control-label"> Dossier à sauvegarder* : </label>
        <div   class="col-sm-6"> <input type="text" name="srcpath"  id="srcpath" class="form-control" placeholder="Dossier source de stockage des documents" value="<?php echo $data["srcpath"]; ?>" /></div>        
    </div>
	<div class="form-group"> 
        <label class="col-sm-3 control-label"> Dossier de destination* : </label>
        <div   class="col-sm-6"> <input type="text" name="destpath" id="destpath" class="form-control" placeholder="Dossier de sauvegarde des documents retraités" value="<?php echo $data["destpath"]; ?>" /></div>        
    </div>
	<div class="form-group"> 
        <label class="col-sm-3 control-label"> Dossier de destination* : </label>
        <div   class="col-sm-6"> <input type="text" name="finalpath" id="finalpath" class="form-control" placeholder="Dossier final des retraitements du ERCCM" value="<?php echo $data["finalpath"]; ?>" /></div>        
    </div>
	<div class="form-group"> 
        <label class="col-sm-3 control-label"> Dossier des doublons* : </label>
        <div   class="col-sm-6"> <input type="text" name="doublonspath" id="doublonspath" class="form-control" placeholder="Dossier ou ranger les doublons" value="<?php echo $data["doublonspath"]; ?>" /></div>        
    </div>
	<div class="form-group"> 
           <label class="col-sm-3 control-label"> Que faire si le dossier existe* : </label>
           <div   class="col-sm-6"> <?php echo $this->formSelect("overwrite", $data["overwrite"], array("class"=>"form-control chosen"), array("SKIP"=>"Ignorer","erase"=>"Ecraser","combine"=>"Combiner","duplicate"=>"Dupliquer")); ?> </div> 	   
     </div>
	<div class="form-group"> 
        <label class="col-sm-3 control-label"> Localité* : </label>
        <div   class="col-sm-6"> <?php echo $this->formSelect("localite", $data["localite"], array("class"=>"form-control"), $localites); ?> </div> 		   
    </div>
	<div class="form-group"> 
        <label class="col-sm-3 control-label"> Année* : </label>
        <div   class="col-sm-6"> <?php echo $this->formSelect("annee", $data["annee"], array("class"=>"form-control"), $annees); ?> </div> 		   
    </div>     
     
    </form>
 
    <?php 
    $buttonsbar  = $this->Btnbar(array("class" => "button-pane") , $this->jqueryHandler());
    $toolCreate  = $buttonsbar->button("Sauvegarder les dossiers","floppy-disk")->setPriority("primary");
    $toolCancel  = $buttonsbar->button("Annuler","chevron-left");
     
    $toolCreate->setAttributes(array("type" => "submit", "class" => "btn btn-success"));
    $toolCancel->setAttributes(array("type" => "submit"));
     
    $buttonsbar->add($toolCreate ,"saveButton");
    $buttonsbar->add($toolCancel ,"cancelCreationButton");
    
    if( !$this->isAjax )
        echo $buttonsbar;
    ?>
</div>

<?php     
  

   if( $this->isAjax) {
   	   echo $this->jQuery();
   }
   
   ?>