<?php 
$data         = $this->data;
$formSubmit   = $this->url(array("controller"=>"registres","action"=>"findsigardmissings","module"=>"admin"), "default" );
$backList     = $this->url(array("controller"=>"registres","action"=>"list"  , "module" => "admin"), "default" );
$localites    = $this->localites;
$annees       = $this->annees;
?>
<?php $this->headStyle()->captureStart() ?>

<?php $this->headStyle()->captureEnd()   ?>

<?php

$jq     = $this->jQuery();  
$onLoad = " 
jQuery('#cancelCreationButton').click(function(e){e.preventDefault();document.location.href='".$backList."';});  
jQuery('#importButton').click(function(e){
      e.preventDefault();      
      var  formSelector = jQuery('#importForm');
      var  annee        = parseInt(jQuery.trim(formSelector.find('#annee').val()));
      var  localiteid   = parseInt(formSelector.find('#localiteid').val());

      if( SIRAH.util.isEmpty( annee )){
          SIRAH.error.raise('importForm','Entrez une année valide');
          return;
      } 
      if( SIRAH.util.isEmpty( localiteid )){
          SIRAH.error.raise('importForm','Veuillez selectionner une localité');
          return;
      }      
      formSelector.submit();
   }); ";
  
  $jq->addOnLoad($onLoad);
?>

<div    class="content-box">    
    <h3 class="content-box-header content-box-header-alt bg-default">ETAPE 1 <small> Paramèters du serveur</small></h3>
    <form method="post" action="<?php echo $formSubmit; ?>" id="importForm" class="form-horizontal mrg15T row" role="form" enctype="multipart/form-data">
        <div class="form-group"> 
           <label class="col-sm-3 control-label"> Nom d'hôte* : </label>
           <div   class="col-sm-6 col-md-6"> <input type="text" name="dbsource_host" id="dbsource_host" class="form-control" placeholder="Nom d'hôte" value="<?php echo $data["dbsource_host"]; ?>" /></div>        
        </div>
        <div class="form-group"> 
           <label class="col-sm-3 control-label"> Nom base* : </label>
           <div   class="col-sm-6 col-md-6"> <input type="text" name="dbsource_name" id="dbsource_name" class="form-control" placeholder="Nom de la base de données" value="<?php echo $data["dbsource_name"]; ?>" /></div>        
        </div>		
        <div class="form-group"> 
           <label class="col-sm-3 control-label"> Nom d'utilisateur* : </label>
           <div   class="col-sm-6 col-md-6"> <input type="text" name="dbsource_username" id="dbsource_username" class="form-control" placeholder="Nom d'utilisateur" value="<?php echo $data["dbsource_username"]; ?>" /></div>        
        </div>
        <div class="form-group"> 
           <label class="col-sm-3 control-label"> Mot de passe* : </label>
           <div   class="col-sm-6 col-md-6"> <input type="password" name="dbsource_password" id="dbsource_password" class="form-control"  /></div>        
        </div>	    
        <h3 class="content-box-header content-box-header-alt bg-default mrg10R mrg10L mrg10B">ETAPE 2 <small> Les paramètres des registres à vérifier </small></h3>
		<div class="form-group"> 
           <label class="col-sm-3 control-label"> Type* : </label>
           <div   class="col-sm-6 col-md-6"> <?php echo $this->formSelect("category",$data["category"], array("class"=>"form-control"),array("A"=>"Personnes Physiques","B"=>"Personnes Morales","M"=>"Modifications","S"=>"Sûrétés")); ?> </div>        
        </div>
        <div class="form-group"> 
           <label class="col-sm-3 control-label"> Dossier source* : </label>
           <div   class="col-sm-6 col-md-6"> <input type="text" name="srcpath" id="srcpath" class="form-control" placeholder="Dossier source enfant" value="<?php echo $data["srcpath"]; ?>" /></div>        
        </div>
        <div class="form-group"> 
           <label class="col-sm-3 control-label"> Dossier destination des documents* : </label>
           <div   class="col-sm-6 col-md-6"> <input type="text" name="destpath" id="destpath" class="form-control" placeholder="Dossier destination des documents" value="<?php echo $data["destpath"]; ?>" /></div>        
        </div>
		<div class="form-group"> 
           <label class="col-sm-3 control-label"> Dossier source* : </label>
           <div   class="col-sm-6 col-md-6"> <input type="text" name="storepath" id="storepath" class="form-control" placeholder="Dossier de stockage des documents" value="<?php echo $data["storepath"]; ?>" /></div>        
        </div>
	    <div class="form-group"> 
          <label class="col-sm-3 control-label"> Localité concernée* : </label>
           <div  class="col-sm-6 col-md-6"> <?php echo $this->formSelect("localiteid", $data["localiteid"] , array("class"=>"form-control"), $localites); ?> </div>   
        </div>       
        <div class="form-group"> 
           <label class="col-sm-3 control-label"> L'année concernée* : </label>
           <div   class="col-sm-6 col-md-6"> <?php echo $this->formSelect("annee", $data["annee"] , array("class"=>"form-control"), $annees); ?> </div>        
        </div>               
    </form>
 
    <?php 
    $buttonsbar  = $this->Btnbar(array("class" => "button-pane") , $this->jqueryHandler());
    $toolCreate  = $buttonsbar->button("Retrouver les dossiers manquants","download")->setPriority("primary");
    $toolCancel  = $buttonsbar->button("Annuler","chevron-left");
     
    $toolCreate->setAttributes(array("type" => "submit", "class" => "btn btn-success"));
    $toolCancel->setAttributes(array("type" => "submit"));
     
    $buttonsbar->add($toolCreate ,"importButton");
    $buttonsbar->add($toolCancel ,"cancelCreationButton");
    
    if( !$this->isAjax )
        echo $buttonsbar;
    ?>
</div>

<?php     
   if( $this->isAjax) {
   	   echo $this->jQuery();
   } 
?>