<?php 
   $data          = $this->data;
   
   $formSubmit    = $this->url(array("controller" => "project", "action" => "edit" , "id" => $data["projectid"]) , "default" ) ;
   $linkCancel    = $this->url(array("controller" => "project", "action" => "list") , "default" ) ;
     
   $buttonbar     = $this->btnbar(array() , $this->jqueryHandler());   
   $buttonEdit    = $buttonbar->button(" Mettre à jour ","save")->setPriority("primary");
   $buttonCancel  = $buttonbar->button(" Annuler","ban-circle");
   
   $basePath      = VIEW_BASE_PATH;
   
   $buttonEdit->setAttributes(  array("type" => "submit"));
   $buttonCancel->setAttributes(array("type" => "submit"));
   
   $buttonbar->add($buttonEdit   , "editButton");
   $buttonbar->add($buttonCancel , "cancelButton");
   
   $buttonCancel->onClick("event.preventDefault() ; document.location.href= '".$linkCancel."' ;");   
   $buttonEdit->onClick("
   	event.preventDefault();	
   	var  formSelector = jQuery('#editproject-form');
    var  libelle      = jQuery.trim(jQuery('#libelle').val());
    var  code         = jQuery.trim(jQuery('#code').val());

   	if(SIRAH.util.isEmpty(code)){
         jQuery('#code').addClass('input-error');
         jQuery('#code-validation-message').html('');
         SIRAH.error.raise('code-validation-message','Veuillez entrer un code valide du projet ');
         return;
    } else {
         jQuery('#code').removeClass('input-error');
         jQuery('#code-validation-message').html('');
    } 	   		
    if(SIRAH.util.isEmpty(libelle)){
         jQuery('#libelle').addClass('input-error');
         jQuery('#libelle-validation-message').html('');
         SIRAH.error.raise('libelle-validation-message',' Entrez une désignation valide pour le projet ');
         return;
      } else {
         jQuery('#libelle').removeClass('input-error');
         jQuery('#libelle-validation-message').html('');
      }     
      jQuery('#libelle').val(libelle);
   	  formSelector.find('#objectifs').val( tinyMCE.get('objectifs').getContent()); 
   	  formSelector.find('#introduction').val( tinyMCE.get('context').getContent()); 
	  formSelector.find('#context').val( tinyMCE.get('context').getContent()); 
	  formSelector.find('#presentation').val(   tinyMCE.get('presentation').getContent()); 
	  formSelector.find('#presentation_structure').val(    tinyMCE.get('presentation_structure').getContent());    
      formSelector.submit();  ");

$jq  = $this->jQuery();
$jq->addOnLoad(" tinymce.init({ selector: 'textarea',
                                height: 200,
		                        language:'fr_FR',
                                plugins: [],
		                        menubar: false, 
                                toolbar: 'styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent'
                              });
		");

$jq->addJavascriptFile( $basePath.'/js/editors/tinymce/tinymce.min.js');
?>
 <form method="post" action="<?php echo $formSubmit; ?>" align="center" id="editproject-form" role="form" enctype="multipart/form-data" > 
 <div class="col-md-12" style="text-align:left;">
    <ul class="list-group">
      <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="code"> <b>  Code du projet *:</b> </label></div> 
            <div class="col-md-9"> <input id="code" type="text" maxlength="200" autocomplete="off" autocapitalize="off" autocorrect="off"  class="form-control"
                                          title="Le code du projet" placeholder="Code du projet" name="code" value="<?php echo $this->escape($data["code"]); ?>"></div>
       </div>
       <p id="code-validation-message" class="validation-message"></p>  
      </li>
      <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="libelle"> <b>  Titre du projet *:</b> </label></div> 
            <div class="col-md-9"> <input id="libelle" type="text" maxlength="200" autocomplete="off" autocapitalize="off" autocorrect="off" class="form-control"
                                          title="La désignation du project" placeholder="Désignation"  name="libelle" value="<?php echo $this->escape($data["libelle"]); ?>"></div>
       </div>
       <p id="libelle-validation-message" class="validation-message"></p>  
     </li> 
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="objectif_global"> <b>  Objectif global:</b> </label></div> 
            <div class="col-md-9"> <input id="objectif_global"  name="objectif_global" type="text" maxlength="200" autocomplete="off" autocapitalize="off" autocorrect="off" class="form-control"
                                          title="L'objectif global du projet" placeholder="L'objectif global du projet" value="<?php echo $this->escape($data["objectif_global"]); ?>"></div>
       </div>  
    </li> 
    <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="objectif_strategique"> <b>  Objectif stratégique:</b> </label></div> 
            <div class="col-md-9"> <input id="objectif_strategique"  name="objectif_strategique" type="text" maxlength="255" autocomplete="off" autocapitalize="off" autocorrect="off"  class="form-control"
                                          title="L'objectif stratégique du projet" placeholder="L'objectif stratégique du projet" value="<?php echo $this->escape($data["objectif_strategique"]); ?>"></div>
       </div>  
    </li>
    <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="responsable"> <b>  Responsable:</b> </label></div> 
            <div class="col-md-9"> <input id="responsable"  name="responsable" type="text" maxlength="255" autocomplete="off" autocapitalize="off" autocorrect="off"  class="form-control"
                                          title="Le responsable du projet" placeholder="Le responsable du projet" value="<?php echo $this->escape($data["responsable"]); ?>"></div>
       </div>  
    </li> 
   
     <li class="list-group-item">     
        <div class="row"> 
            <div class="col-md-3"> <label class="label" for="objectifs"> <b> Objectifs visés: </b> </label> </div> 
            <div class="col-md-9"> <textarea name="objectifs" id="objectifs" class="objectifs" rows="15" cols="40"> 
                                      <?php echo $this->escape($data["objectifs"]); ?> 
                                   </textarea>  
           </div>
       </div>
    </li>
    <li class="list-group-item">     
        <div class="row"> 
            <div class="col-md-3"> <label class="label" for="introduction"> <b> Introduction: </b> </label> </div> 
            <div class="col-md-9"> <textarea name="introduction" id="introduction" class="textarea introduction"> 
                                     <?php echo htmlentities( $data["introduction"] , ENT_QUOTES , "UTF-8" ); ?> 
                                   </textarea>  
           </div>
       </div>
    </li>                       
    <li class="list-group-item">     
        <div class="row"> 
            <div class="col-md-3"> <label class="label" for="context"> <b> Contexte: </b> </label> </div> 
            <div class="col-md-9"> <textarea name="context" id="context" class="textarea context"> 
                                     <?php echo htmlentities( $data["context"] , ENT_QUOTES , "UTF-8" ); ?> 
                                   </textarea>  
           </div>
       </div>
    </li>    
    <li class="list-group-item">     
        <div class="row"> 
            <div class="col-md-3"> <label class="label" for="presentation"> <b> Présentation du projet: </b> </label> </div> 
            <div class="col-md-9"> <textarea name="presentation" id="presentation" class="textarea presentation"  rows="5" cols="50"> 
                                      <?php echo htmlentities( $data["presentation"] , ENT_QUOTES , "UTF-8" ); ?> 
                                   </textarea>  
           </div>
       </div>
    </li>
    <li class="list-group-item">     
        <div class="row"> 
            <div class="col-md-3"> <label class="label" for="presentation_structure"> <b> Présentation de la structure: </b> </label> </div> 
            <div class="col-md-9"> <textarea name="presentation_structure" id="presentation_structure" class="textarea presentation_structure"> 
                                      <?php echo htmlentities( $data["presentation_structure"] , ENT_QUOTES , "UTF-8" ); ?> 
                                   </textarea>  
           </div>
       </div>
    </li>
    <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="statut"> <b>Statut:</b> </label></div> 
            <div class="col-md-9"> </div>
       </div>  
    </li>   
    </ul>
  </div>
    <?php 
          if(!$this->isAjax) {
          	  echo $buttonbar;
          } else {
              echo $this->jQuery();
          	  echo $this->headScript();
          	  echo $this->headStyle();
          }
      ?>
        <input type="hidden"  name="projectid"  id="projectid"  value="<?php echo intval($data["projectid"]); ?>"  />
  </form>  
     