<?php 
   $data          = $this->data;
   
   $linkEdit      = $this->url(array("controller"  => "project", "action" => "edit", "id"  => $this->projectid ) , "default" ) ;
     
   $buttonbar     = $this->btnbar(array() , $this->jqueryHandler());   
   $buttonEdit    = $buttonbar->button(" Mettre à jour les informations","edit")->setPriority("primary");
   
   $buttonbar->add( $buttonEdit, "editButton");
   
   $buttonEdit->onClick("  event.preventDefault(); document.location.href= '".$linkEdit."' ;");
?>
  
 <div class="container pagecontainer col-md-12" style="text-align:left;">
    <ul class="list-group">
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="code"> <b>  Code du projet : </b> </label></div> 
            <div class="col-md-9"> <?php echo $this->escape($data["code"]);  ?></div>
       </div>
     </li>
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="libelle"> <b>  Intitulé du projet: </b> </label></div> 
            <div class="col-md-9"> <?php echo $this->escape($data["libelle"]);  ?></div>
       </div>
     </li>     
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="objectifs"> <b> Objectifs Visés: </b> </label></div> 
            <div class="col-md-9"> <?php echo  html_entity_decode( $data["objectifs"] , ENT_QUOTES, "UTF-8" );  ?></div>
       </div>
     </li> 
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="introduction"> <b> Introduction :</b> </label></div> 
            <div class="col-md-9"> <?php echo html_entity_decode( $data["introduction"] , ENT_QUOTES, "UTF-8" );  ?> </div>
       </div>
     </li>        
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="context"> <b> Contexte du projet :</b> </label></div> 
            <div class="col-md-9"> <?php echo html_entity_decode( $data["context"] , ENT_QUOTES, "UTF-8" );  ?> </div>
       </div>
     </li>
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="presentation"> <b>Présentation du projet :</b> </label></div> 
            <div class="col-md-9"> <?php echo html_entity_decode( $data["presentation"] , ENT_QUOTES, "UTF-8" );  ?> </div>
       </div>
     </li>
     <li class="list-group-item">
       <div class="row"> 
            <div class="col-md-3"> <label class="label" for="presentation_structure"> <b> Présentation de la structure:</b> </label></div> 
            <div class="col-md-9"> <?php echo html_entity_decode( $data["presentation_structure"] , ENT_QUOTES, "UTF-8" );  ?> </div>
       </div>
     </li>     
  </ul>
  </div>
    <?php 
          if(!$this->isAjax) {
          	 echo $buttonbar;
          } else {
          	 echo $this->jQuery();
          }
      ?>   