<?php 
$roles            = $this->roles;
$priorities       = array("Inconnue","Très Elevée", "Elevée", "Normale", "Basse", "La plus basse");
$basePath         = VIEW_BASE_PATH;
$jq               = $this->jQuery();

$linkSearch       = $this->url(array("controller" => "useroles" , "action" => "list") , "default");
$linkCreate       = $this->url(array("controller" => "useroles" , "action" => "create") , "default");
$linkEdit         = $this->url(array("controller" => "useroles" , "action" => "edit") , "default");
$linkDelete       = $this->url(array("controller" => "useroles" , "action" => "delete") , "default");
$linkRights       = $this->url(array("controller" => "useroles" , "action" => "rights") , "default");
$linkDefineRights = $this->url(array("controller" => "useroles" , "action" => "updaterights") , "default");

$jq->addOnload("
jQuery('.resetPage').click(function(){event.preventDefault(); document.location.href = '".$linkSearch."'; });
jQuery('#filterListFromName').click(function( event ){
		event.preventDefault();
		var formSelector    = jQuery('#usersRoleSearchForm') ;
		var rolenameText    = jQuery.trim(jQuery('#usersRoleSearchForm').find('#searchRolename').val());
		 
		var searchData      = {};
		searchData.rolename = rolenameText;
        var maincontent	    = jQuery('#maincontent');	
		SIRAH.loading.on( maincontent , 'Chargement des données...' );
		SIRAH.request.post(formSelector, '".$linkSearch."' , 
		                   {
		                    dataType   :'html', async: true, data: searchData,
		                    beforeSend : function() { },
		                    error      : function(data){maincontent.html(data);SIRAH.loading.off(false);},
	                        success    : function(data){maincontent.html(data);SIRAH.loading.off(false);},
		                    update     : function(data){maincontent.html(data);SIRAH.loading.off(false);}		
		                  });						
});
		
var getCheckedRoleIds= function() {
		var checkedItems = jQuery('#rolesListTable').find('input[type=\'checkbox\'][name!=\'checkall\']:checked');
        var checkedIds   = []; 
		if(checkedItems) {
		   checkedItems.each(function(){var roleid = parseInt(jQuery(this).attr('id').replace('roleids-',''));checkedIds.push(roleid);});
		}
		return checkedIds;
};
jQuery('#rolesListTable').find('input[type=\'checkbox\']').click(function(e){
		 var checkedItems  = jQuery('#rolesListTable').find('input[type=\'checkbox\'][name!=\'checkall\']:checked');
		 if(jQuery(this).attr('id') == 'checkAll') {
		    if(!jQuery(this).is(':checked')) {
		       checknone();
		       if( checkedItems ) {
		           disableButtons(['editButton', 'rightsButtonDefine', 'deleteButton','rightsButton']);
		       }
		    } else {
		           checkall();
		           enableButtons(['editButton', 'rightsButtonDefine','deleteButton','rightsButton']);
		    }
		 } else {
		  if(jQuery(this).is(':checked')) {
		     enableButtons(['editButton', 'rightsButtonDefine', 'deleteButton','rightsButton']);
		  } else {
		      if( SIRAH.util.isEmpty(checkedItems)) {
		          disableButtons(['editButton', 'rightsButtonDefine', 'deleteButton','rightsButton']);
		       }
		       jQuery(this).attr('checked','checked');
		  }
		}
   });
");

$supinaToolsbar = $this->supinaToolsbar(array() , $this->jqueryHandler());
$toolCreate     = $supinaToolsbar->tool("Enregistrer un role" , "plus");
$toolEdit       = $supinaToolsbar->tool("Modifier"            , "edit");
$toolDelete     = $supinaToolsbar->tool("Supprimer"           , "trash-o");
$toolRights     = $supinaToolsbar->tool("Afficher permissions", "lock");
$toolRights2    = $supinaToolsbar->tool("Définir  permissions", "pencil");
 
$supinaToolsbar->add($toolCreate,"createButton")->add($toolEdit,"editButton")->add($toolDelete,"deleteButton")->add($toolRights,"rightsButton")->add($toolRights2,"rightsButtonDefine");

$toolCreate->onClick(sprintf("event.preventDefault;document.location.href='%s';" , $linkCreate ));
$toolEdit->disable();
$toolEdit->onClick("
		var isDisabled   = jQuery(this).is('.disabled') || jQuery(this).is('.btn-disabled');
		var checkedItem  = jQuery('#rolesListTable').find('input[type=\'checkbox\'][name=\'roleids[]\']:checked').eq(0);
		if( isDisabled || !checkedItem ) {
		    SIRAH.dialog.alert('Vous devrez selectionner une ligne avant d\'effectuer cette opération','Selectionnez une ligne');
		    return;
        }
		var roleid       = parseInt(checkedItem.attr('id').replace('roleids-',''));
		var rolename     = jQuery('#rolename-'+roleid).val();
		var dialogEdit   = jQuery('<div></div>').attr('id','dialogEdit');
		dialogEdit.dialog2({
		                     title : 'Mettre à jour les informations du role '+rolename,
		                     content : '".$linkEdit."/roleid/'+roleid,
		                     modalClass:'modal-wide',
		                     autoOpen: false,
		                     removeOnClose: true,
		                     closeOnEscape: false,
		                     closeOnOverlayClick: true,
		                     showCloseHandle:true,
		                     initialLoadText: 'Chargement...'});
		dialogEdit.dialog2('addButton','<i class=\'glyph-icon icon-save\'></i> Sauvegarder',{primary:true,click:function(){var editForm=jQuery('#dialogEdit').find('form').eq(0);SIRAH.request.post(editForm,'".$linkEdit."/roleid/'+roleid);}});
		dialogEdit.dialog2('addButton','<i class=\'glyph-icon icon-ban\'></i>  Annuler',{primary:false,click:function(){jQuery(this).dialog2('close');}});
		dialogEdit.dialog2('open');");
$toolDelete->disable();
$toolDelete->onClick("
		var isDisabled   = jQuery(this).is('.disabled') || jQuery(this).is('.btn-disabled');
		var checkedRoles = getCheckedRoleIds();
		if( isDisabled || SIRAH.util.isEmpty(checkedRoles)) {
		    SIRAH.dialog.alert('Vous devrez selectionner au moins une ligne avant d\'effectuer cette opération','Selectionnez une ligne');
		    return;
        }
		var dialogDelete = jQuery('<div> Voulez-vous vraiment supprimer les roles selectionnés ? Ces roles et leurs données dépendantes seront définitivement supprimés du système </div>').attr('id','dialogDelete');
		dialogDelete.dialog2({
		                      title : 'Attention , confirmer cette action !!',
		                      autoOpen: false,
		                      removeOnClose: true,
		                      closeOnEscape: false,
		                      closeOnOverlayClick: true,
		                      showCloseHandle:true,
		                      initialLoadText: 'Chargement...'});
		dialogDelete.dialog2('addButton','<i class=\'glyph-icon icon-check\'></i> Oui',{primary:true,click:
		                     function(){
		                      jQuery.ajax({url:'".$linkDelete."',dataType:'json',type:'GET',
		                                  async  :false,data:{'roleids[]' : checkedRoles} ,
		                                  success:function(data){
		                                     if(data.error !== undefined) {
		                                        SIRAH.error.raise(jQuery('#dialogDelete') , data.error);
		                                        return;
                                              } else if(data.success !== undefined) {
		                                        var checkedRoles = getCheckedRoleIds();
		                                        SIRAH.error.raise(jQuery('#dialogDelete'), data.success , 'success');
		                                        setTimeout(function(){jQuery.each(checkedRoles,function(key,roleid){jQuery('#rowRole-'+roleid).remove();});jQuery('#dialogDelete').dialog2('close');},2500);
                                              }
                                           }
                                 });
         }});
		dialogDelete.dialog2('addButton','<i class=\'glyph-icon icon-ban\'></i>Annuler',{primary:false,click:function(){jQuery(this).dialog2('close');}});
		dialogDelete.dialog2('open');");
$toolRights->disable();
$toolRights->onClick("
		              var isDisabled  = jQuery(this).is('.disabled') || jQuery(this).is('.btn-disabled');
		              var checkedItem = jQuery('#rolesListTable').find('input[type=\'checkbox\'][name=\'roleids[]\']:checked').eq(0);
		              if( isDisabled || !checkedItem) {
		                  SIRAH.dialog.alert('Vous devrez selectionner au moins une ligne avant d\'effectuer cette opération','Selectionnez une ligne');
		                  return;
                      }
		              var roleid       = parseInt(checkedItem.attr('id').replace('roleids-',''));
		              var rolename     = jQuery('#rolename-'+roleid).val();
		              var dialogRights = jQuery('<div></div>').attr('id','dialogRights').addClass('scrollable');
		              dialogRights.dialog2({
		                                     title : 'Visualiser les permissions du role '+rolename+' sur la plateforme',
		                                     content : '".$linkRights."/roleid/'+roleid,
		                                     autoOpen: false,
		                                     modalClass : 'modal-wide',
		                                     removeOnClose: true,
		                                     closeOnEscape: false,
		                                     closeOnOverlayClick: false,
		                                     showCloseHandle:true,
		                                     initialLoadText: 'Patientez , chargement...'});
		dialogRights.dialog2('addButton','<i class=\'glyph-icon icon-check\'></i> Ok', {primary: true,click : function(){jQuery(this).dialog2('close');}});
		dialogRights.dialog2('open');"); 
$toolRights2->disable();
$toolRights2->onClick("
		                var isDisabled   = jQuery(this).is('.disabled') || jQuery(this).is('.btn-disabled');
		                var checkedItem  = jQuery('#rolesListTable').find('input[type=\'checkbox\'][name=\'roleids[]\']:checked').eq(0);
		                if( isDisabled || !checkedItem ) {
		                    SIRAH.dialog.alert('Vous devrez selectionner une ligne avant d\'effectuer cette opération','Selectionnez une ligne');
		                    return;
                        }
		                var roleid       = parseInt(checkedItem.attr('id').replace('roleids-',''));
		                var rolename     = jQuery('#rolename-'+roleid).val();
		                var dialogDefineRights = jQuery('<div></div>').attr('id','dialogDefineRights').addClass('scrollable');
		                dialogDefineRights.dialog2({ title : 'Définir des permissions du role '+rolename+' sur la plateforme',
		                                             content : '".$linkDefineRights."/roleid/'+roleid,
		                                             autoOpen: false,
		                                             modalClass : 'modal-wide',
		                                             removeOnClose: true,
		                                             closeOnEscape: false,
		                                             closeOnOverlayClick: true,
		                                             showCloseHandle:true,
		                                             initialLoadText: 'Patientez , chargement...'});
		dialogDefineRights.dialog2('addButton','<i class=\'glyph-icon icon-save\'></i>Définir des permissions',
		                           {primary:true,click:function(e){e.preventDefault();var rightsForm=jQuery(this).find('form');SIRAH.request.post(rightsForm,'".$linkDefineRights."/roleid/'+roleid);}});
		dialogDefineRights.dialog2('addButton','<i class=\'glyph-icon icon-ban\'></i>Annuler',{primary:false,click:function(){jQuery(this).dialog2('close');}});
		dialogDefineRights.dialog2('open');   ");

$this->toolsbar = $supinaToolsbar;

?>
<div id="usersRoleListWrapper"  class="row">
  <form id="usersRoleSearchForm" class="" method="post" role="form">
     <div  class="col-md-12">
         <div class="content-box">
            <div class="mail-header clearfix">
                <div class="float-right col-md-4 pad0A">
                    <div class="input-group">
                        <input type="text" class="form-control" value="<?php printf("%s", $this->searchRolename ); ?>" name="searchRolename" id="searchRolename" placeholder="Saisir le nom du role">
                        <div class="input-group-btn">
                           <button id="filterListFromName" type="button" class="btn btn-primary" tabindex="-1"><i class="glyph-icon icon-search"></i></button>
                           <button  type="button" class="btn alert-danger resetPage" tabindex="-1"><i class="glyph-icon icon-remove"></i></button>
                        </div>
                    </div>
               </div>
           </div>
           <div class="mail-toolbar clearfix"> 
              <div class="float-left"><a href="#" title="Actualiser la page" class="btn btn-default mrg5R resetPage"><i class="glyph-icon font-size-11 icon-refresh"></i></a></div>
           </div>            
           <table id="rolesListTable" class="table table-hover table-bordered table-stripped table-responsive sirah-ui-table scrollable text-center">
                <thead>
                     <tr> 
                          <th width="1%"> <input type="checkbox" name="checkall" id="checkAll" class="checkAll" /></th>
                          <th width="40%"> Désignations            </th> 
                          <th width="35%"> Hérite du/des role(s)   </th> 
                          <th width="24%"> Priorités               </th> 
                     </tr>
                </thead>
                <tbody>
                    <?php 
                          $output   = "";
                          if( count( $roles )) {
                          	foreach( $roles as $roleid => $rolename ) {
                          		     $accessLevel = Sirah_User_Acl_Table::getAccesslevel( $roleid);
                          		     $parents     = Sirah_User_Acl_Table::getRoleParents( $roleid);                        		     
                          		     $linkInfos   = $this->url(array("controller" => "useroles", "action" => "infos", "roleid" => $roleid));
                          		                               		     
                          		     $output .="<tr class=\"".$bgClass."\" id=\"rowRole-".$roleid."\">";
                          		             $output .= "<td id=\"checkboxCell-".$roleid."\"><input type=\"checkbox\" name=\"roleids[]\" id=\"roleids-".$roleid."\" class=\"roleids\" /> </td>";
                          		             $output .= "<td id=\"roleName-".$roleid."\">  <a href=\"".$linkInfos."\"> ".$rolename." </a> </td>";
                          		             if(empty($parents )){
                          		             	$output .= "<td id=\"parents-".$roleid."\"><a href=\"".$linkInfos."\"> Aucun </a> </td>";
                          		             } else {
                          		             	$output .= "<td id=\"parents-".$roleid."\"><a href=\"".$linkInfos."\"> ".implode(', ', $parents)." </a> </td>";
                          		             }
                          		             if(!empty($accessLevel) && isset( $priorities[$accessLevel[0]] )) {
                          		             	$output .= "<td id=\"priorities-".$roleid."\"> <a href=\"".$linkInfos."\"> ".$priorities[$accessLevel[0]]." </a> </td>";
                          		             }  else {
                          		             	$output .= "<td id=\"priorities-".$roleid."\"> <a href=\"".$linkInfos."\"> ".$priorities[5]." </a> </td>";
                          		             }
                          		     $output .="<input type=\"hidden\" id=\"rolename-".$roleid."\" name=\"rolename-".$roleid."\" value=\"".$rolename."\"  />"  ;
                          		     $output .="</tr>";
                          	}                          	
                          } else {
                          	         $output .="<tr style=\"text-align:center;\"><td colspan=\"5\"> Aucun role n' a été retrouvé dans le système </td> </tr>";
                          }
                                     echo $output;
                    ?>
                </tbody>
           </table>         
         </div>
     </div>
  </form>
</div>
