<?php 
$captcha            = $this->captcha;
$messages           = $this->messages;
$token              = $this->token;
$tokenId            = $this->csrfTokenId;
$tokenValue         = $this->csrfTokenValue;
$data               = $this->data;
$formNames          = $fn = $this->formNames;
$defaultCountry     = (isset($data["country"]) && !empty($data["country"])) ? $data["country"] : "BF";

$urlCreationDone    = Sirah_Functions::url($this->url(array("module"=>"public","controller"=>"account","action"=>"dashboard","module"=> "public"),"default",true),"" , 81 , APPLICATION_HOST);
$formSubmit         = $this->url(array("module"=>"public","controller"=>"members","action"=>"create"),"default",true);
$linkCancel         = $this->url(array("module"=>"public","controller"=>"index"  ,"action"=>"index") , "default",true);
$linkCheckUsername  = $this->url(array("module"=>"public","controller"=>"ajaxres","action"=>"checkusername",$tokenId=>$tokenValue),"default",true);
$linkCheckEmail     = $this->url(array("module"=>"public","controller"=>"ajaxres","action"=>"checkemail",$tokenId=>$tokenValue),"default",true);

$civilites          = array("Mr"=>"Monsieur","Mme"=>"Madame","Mle"=>"Mademoiselle","Excellence"=>"Son excellence","Maître"=>"Maître","Dr"=>"Docteur","Pr"=>"Professeur");
$situations         = array("Célibataire" => "Célibataire","Marié(e)" => "Marié(e)","Divorcé(e)" => "Divorcé(e)","Veuf(ve)"=> "Veuf(ve)");
$registerDoneUri    = $this->registerDoneUri;
$basePath           = ROOT_PATH ."/myTpl/public/";
?>
<?php $this->headStyle()->captureStart() ?>
<?php $this->headStyle()->captureEnd()   ?>
<?php
$jq     = $this->jQuery();  
$onLoad = " 
var  formSelector= jQuery('#createAccountForm');
jQuery('.birthday,#".$fn['birthday']."').pickadate({format:'dd/mm/yyyy',formatSubmit:'dd/mm/yyyy',hiddenName:true,hiddenSuffix:'__suffix',hiddenPrefix:'prefix__',selectYears:100,selectMonths:true,min:new Date(1950,1,1),max:new Date(),onStart:function(){this.set('select','".$data["birthday"]."');}});
jQuery('.createButton').click(function( event ){
    event.preventDefault();      
    var formSelector= jQuery('#createAccountForm');
    var prenom      = jQuery.trim(formSelector.find('#".$fn['firstname']."').val());
    var nom         = jQuery.trim(formSelector.find('#".$fn['lastname']."').val());
    var addressMail = jQuery.trim(formSelector.find('#".$fn['email']."').val());
    var credential  = jQuery.trim(formSelector.find('#".$fn['password']."').val());
    var credential2 = jQuery.trim(formSelector.find('#".$fn['confirmedpassword']."').val());
    var telephone   = jQuery.trim(formSelector.find('#".$fn['phone1']."').val());
	var numIdentity = jQuery.trim(formSelector.find('#".$fn['numidentite']."').val()); 
	var organismeP  = jQuery.trim(formSelector.find('#".$fn['organisme_etablissement']."').val());
      
	if( SIRAH.util.isEmpty(numIdentity)){
        formSelector.find('#".$fn['numidentite']."').addClass('input-error');
        formSelector.find('#numero_identite-validation-message').html('');
        SIRAH.error.raise('numero_identite-validation-message','Entrez le numéro de votre pièce d\'identité.');
        return;
    } else {
        formSelector.find('#".$fn['numidentite']."').removeClass('input-error');
        formSelector.find('#numero_identite-validation-message').html('');
    }
	if( SIRAH.util.isEmpty(organismeP)){
        formSelector.find('#".$fn['organisme_etablissement']."').addClass('input-error');
        formSelector.find('#organisme_identite-validation-message').html('');
        SIRAH.error.raise('organisme_identite-validation-message','Veuillez entrer l\'organisme d\'établissement de votre pièce.');
        return;
    } else {
        formSelector.find('#".$fn['organisme_etablissement']."').removeClass('input-error');
        formSelector.find('#organisme_identite-validation-message').html('');
    }
    if( SIRAH.util.isEmpty(nom)){
        formSelector.find('#".$fn['lastname']."').addClass('input-error');
        formSelector.find('#name-validation-message').html('');
        SIRAH.error.raise('name-validation-message','Entrez un nom de famille valide');
        return;
    } else {
        formSelector.find('#".$fn['lastname']."').removeClass('input-error');
        formSelector.find('#name-validation-message').html('');
    }
    if( SIRAH.util.isEmpty(prenom)){
        formSelector.find('#".$fn['firstname']."').addClass('input-error');
        formSelector.find('#name-validation-message').html('');
        SIRAH.error.raise('name-validation-message','Entrez un prénom valide');
        return;
    }  else {
        formSelector.find('#".$fn['firstname']."').removeClass('input-error');
        formSelector.find('#name-validation-message').html('');
    }    
    if( SIRAH.util.isEmpty(phone1)){
        formSelector.find('#".$fn['phone1']."').addClass('input-error');
        formSelector.find('#telephone-validation-message').html('');
        SIRAH.error.raise('telephone-validation-message','Entrez un numéro de téléphone valide');
        return;
    }  else {
        formSelector.find('#".$fn['phone1']."').removeClass('input-error');
        formSelector.find('#telephone-validation-message').html('');
    }
    if(!SIRAH.validators.isEmailAddress(addressMail)){
        formSelector.find('#".$fn['email']."').addClass('input-error');
        formSelector.find('#mail-validation-message').html('');
        SIRAH.error.raise('mail-validation-message','Entrez un email valide');
        return;
    }  else {
        formSelector.find('#".$fn['email']."').removeClass('input-error');
        formSelector.find('#mail-validation-message').html('');
    }     
    if( SIRAH.util.isEmpty(credential) || (parseInt(credential.length) < 4)){
        formSelector.find('#".$fn['password']."').addClass('input-error');
        formSelector.find('#pwd-validation-message').html('');
        SIRAH.error.raise('pwd-validation-message','Entrez un mot de passe valide, doit contenir au moins 4 caractères');
        return;
    } else {
        formSelector.find('#credential').removeClass('input-error');
        formSelector.find('#pwd-validation-message').html('');
    }      
    if( credential2 !== credential){
        formSelector.find('#".$fn['confirmedpassword']."').addClass('input-error');
        formSelector.find('#confirmedpwd-validation-message').html('');
        SIRAH.error.raise('confirmedpwd-validation-message','Les mots de passe sont differents');
        return;
    } else {
        formSelector.find('#".$fn['confirmedpassword']."').removeClass('input-error');
        formSelector.find('#confirmedpwd-validation-message').html('');
    }
    formSelector.find('#".$fn['lastname']."').val(nom);
    formSelector.find('#".$fn['firstname']."').val(prenom);
    formSelector.find('#".$fn['email']."').val(addressMail);
    formSelector.find('#".$fn['phone1']."').val(telephone);
    formSelector.find('#".$fn['password']."').val(credential);
    formSelector.find('#".$fn['confirmedpassword']."').val(credential2);
    formSelector.submit();
});
jQuery('#".$fn['lastname']."').bind('blur change',function(e){
    e.preventDefault();
    var lastname = jQuery.trim(jQuery(this).val());
    if(!SIRAH.util.isEmpty(lastname)){
        jQuery('#".$fn['lastname']."').removeClass('input-error');
        jQuery('#name-validation-message').html('');
    } else {
        jQuery('#".$fn['lastname']."').addClass('input-error');
        return;
    }
});  
jQuery('#".$fn['firstname']."').bind('blur change',function(e){
    e.preventDefault();
    var firstname = jQuery.trim(jQuery(this).val());
    if(!SIRAH.util.isEmpty(firstname)){
        jQuery('#".$fn['firstname']."').removeClass('input-error');
        jQuery('#name-validation-message').html('');
    }  else {
        jQuery('#".$fn['firstname']."').addClass('input-error');
        return;
    }
});  
formSelector.find('#".$fn['username']."').bind('blur change',function(e){
    e.preventDefault();
	var formSelector = jQuery('#createAccountForm');
    var username     = jQuery.trim(jQuery(this).val());
    if( username.length >= 3){
		jQuery('#userkey-validation-message').html('Vérification du nom d\'utilisateur...');
		SIRAH.request.get(  formSelector,'".$linkCheckUsername."', {data:{code:username},beforeSend : function(){},			   
							success : function( data ) {
									formSelector.find('#userkey-validation-message').html('');
									formSelector.find('#".$fn['username']."').removeClass('input-error');
									if( data.error !== undefined   ) {
										formSelector.find('#".$fn['username']."').addClass('input-error');
										formSelector.find('#userkey-validation-message').html('');
										SIRAH.error.raise('userkey-validation-message',data.error);
									}  
							}
		  });
	}	else {
		formSelector.find('#".$fn['username']."').addClass('input-error');
		formSelector.find('#userkey-validation-message').html('Votre nom d\'utilisateur doit comporter au moins 4 caractères...');
		return;
	}				  
}); 
formSelector.find('#".$fn['email']."').bind('blur change',function(e){
    e.preventDefault();
	var  formSelector = jQuery('#createAccountForm');
    var email         = jQuery.trim(jQuery(this).val());
	if( SIRAH.validators.isEmailAddress(email)){	
        formSelector.find('#mail-validation-message').html('Vérification de l\'adresse Email...');	  
		SIRAH.request.get(formSelector,'".$linkCheckEmail."', {data:{code:email},beforeSend: function(){},			   
							success : function( data ) {
								formSelector.find('#mail-validation-message').html('');
								formSelector.find('#".$fn['email']."').removeClass('input-error');
								if( data.error !== undefined   ) {
									formSelector.find('#".$fn['email']."').addClass('input-error');
									formSelector.find('#mail-validation-message').html('');
									SIRAH.error.raise('mail-validation-message',data.error);
								}
							}
		  });
	} else {
		formSelector.find('#".$fn['email']."').addClass('input-error');
		formSelector.find('#mail-validation-message').html('');
		SIRAH.error.raise('mail-validation-message','Entrez une adresse email valide');
		return;
	}         	  
});    
jQuery('#".$fn['password']."').bind('blur change',function(e){
    e.preventDefault();
    var credential = jQuery.trim(jQuery(this).val());
    if( SIRAH.util.isEmpty(credential) || (parseInt(credential.length) < 4)){
        jQuery('#".$fn['password']."').addClass('input-error');
        jQuery('#pwd-validation-message').html('');
        SIRAH.error.raise('pwd-validation-message','Entrez un mot de passe valide');
        return;
    }  else {
        jQuery('#".$fn['password']."').removeClass('input-error');
        jQuery('#pwd-validation-message').html('');
    }    
});  
jQuery('#".$fn['confirmedpassword']."').bind('blur change',function(e){
    e.preventDefault();
    var credential   = jQuery.trim(jQuery('#".$fn['password']."').val());
    var credential2  = jQuery.trim(jQuery(this).val());
    if( credential2 !== credential){
        jQuery('#".$fn['confirmedpassword']."').addClass('input-error');
        jQuery('#confirmedpwd-validation-message').html('');
        SIRAH.error.raise('confirmedpwd-validation-message','Les mots de passe sont differents');
        return;
    } else {
        jQuery('#".$fn['confirmedpassword']."').removeClass('input-error');
        jQuery('#confirmedpwd-validation-message').html('');
    }      
});  
jQuery('#".$fn['phone1']."').bind('blur change',function(e){
    e.preventDefault();
    var phone1 = jQuery.trim(jQuery(this).val());
    if(!SIRAH.util.isEmpty(phone1)){
        jQuery('#".$fn['phone1']."').removeClass('input-error');
        jQuery('#telephone-validation-message').html('');
    }  else {      
        jQuery('#".$fn['phone1']."').addClass('input-error');
         return;     
    }
});  
 jQuery('#cancelButton').click(function(e){e.preventDefault();document.location.href='".$linkCancel."';}); ";
$jq->addOnLoad($onLoad);
$jq->addStyleSheet(    $basePath ."/scripts/widgets/pickadate/themes/default.css");
$jq->addStyleSheet(    $basePath ."/scripts/widgets/pickadate/themes/default.date.css");
$jq->addStyleSheet(    $basePath ."/scripts/widgets/pickadate/themes/default.time.css");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/picker.js");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/picker.date.js");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/picker.time.js");
$jq->addJavascriptFile($basePath ."/scripts/widgets/pickadate/translations/fr_FR.js");
?>
<form method="post" action="<?php echo $formSubmit; ?>" id="createAccountForm"  class="form-horizontal" role="form" >
    <div class="panel panel-default">
		<ul class="list-group">
		    <div class="panel-heading"> <h4 class="panel-title"> <span class="glyph-icon icon-user"></span>1.Vos Informations Personnelles </h4></div>
		    <li class="list-group-item">
				<div class="form-group">            
					<label class="col-sm-hidden col-xs-hidden col-md-2 control-label" for="name">Nom & Prénoms*: </label>
					<div   class="col-sm-12     col-md-10">
						<div class="input-group">
						   <?php echo $this->formSelect($fn['civilite'], $data["civilite"], array("class" => "form-control") , $civilites); ?>
						   <span  class="input-group-btn" style="width:0px;"></span>
						   <input id="<?php echo $fn['lastname']; ?>" type="text" maxlength="150" class="form-control" title="Nom de famille" placeholder="Nom de famille" name="<?php echo $fn['lastname']; ?>"  value="<?php echo $data['lastname'];?>">
						   <span class="input-group-btn" style="width:0px;"></span>
						   <input id="<?php echo $fn['firstname'];?>" type="text" maxlength="600" class="form-control" title="Prénom"         placeholder="Prénom"         name="<?php echo $fn['firstname'];?>" value="<?php echo $data['firstname'];?>">											  
						</div>						
					</div>
					<p id="name-validation-message" class="validation-message"></p> 
				</div>					
			</li>
			<li class="list-group-item">
				<div class="form-group">
					<label class="col-sm-hidden col-xs-hidden col-md-2 control-label" for="userkey"> Identifiant*: </label>
					<div   class="col-sm-12 col-md-10"><input id="<?php echo $fn['username']; ?>" type="text" maxlength="200"class="form-control" title="Votre nom d'utilisateur" placeholder="Votre nom d'utilisateur" name="<?php echo $fn['username']; ?>" value="<?php echo $data['username']; ?>"></div>           
				</div>
				<p id="userkey-validation-message" class="validation-message"></p>       
		    </li>
		    <li class="list-group-item">
				<div class="form-group">
					<label class="col-sm-hidden col-xs-hidden col-md-2 control-label" for="mail"> Email*: </label>
					<div   class="col-sm-12 col-md-10"><input id="<?php echo $fn['email']; ?>" type="text" maxlength="200" class="form-control" title="Votre adresse email" placeholder="Votre adresse email"  name="<?php echo $fn['email']; ?>" value="<?php echo $data['email']; ?>"></div>              
				</div>  
				<p id="mail-validation-message" class="validation-message"></p>   
		    </li>
		    <li class="list-group-item">
				<div class="form-group">
					<label class="col-sm-hidden col-xs-hidden col-md-2 control-label" for="pwd"> Mot de passe*:</label>
					<div   class="col-sm-12 col-md-10">
						<div class="input-group">
							<input name="<?php echo $fn['password']; ?>"          id="<?php echo $fn['password']; ?>"          type="password" placeholder="Saisissez votre mot de passe" maxlength="20" title="Votre mot de passe" class="form-control" />
							<span class="input-group-btn" style="width:0px;"></span>
							<input name="<?php echo $fn['confirmedpassword']; ?>" id="<?php echo $fn['confirmedpassword']; ?>" type="password" placeholder="Confirmez le mot de passe"    maxlength="32" title="Confirmez le mot de passe" class="form-control">
						</div>
					</div>                 
				</div>
			    <p id="pwd-validation-message"          class="validation-message"></p> 
			    <p id="confirmedpwd-validation-message" class="validation-message"></p>  
		    </li>
			<li class="list-group-item">
				<div class="form-group">            
					<label class="col-sm-2  col-md-2 control-label">  <b>Téléphone*:</b> </label> 
					<div   class="col-sm-12 col-md-10">
						<div class="input-group">
						   <input name="<?php echo $fn['phone1']; ?>" id="<?php echo $fn['phone1']; ?>" type="text" maxlength="26" class="form-control" title="Numéro de téléphone"  placeholder="Numéro de téléphone"  value="<?php echo $data['phone1']; ?>">
						   <span class="input-group-btn" style="width:0px;"></span>
						   <input name="<?php echo $fn['phone2']; ?>" id="<?php echo $fn['phone2']; ?>" type="text" maxlength="26" class="form-control" title="Votre second numéro de téléphone (Facultatif)" placeholder="Votre second numéro de téléphone (Facultatif)" value="<?php echo $data['phone2']; ?>">											  
						</div>					
					</div>
					<p id="telephone-validation-message" class="validation-message"></p> 
				</div>					
			</li>		             
			<li class="list-group-item">
				<div class="form-group">  
					<label class="col-sm-hidden col-xs-hidden col-md-2 control-label">  <b> Sexe*:</b> </label> 
					<div   class="col-sm-12 col-md-4"> 
						<label class="radio-inline pull-left"><input type="radio" name="<?php echo $fn['sexe'];?>" id="sexe-m" value="M" <?php if($data["sexe"]== "M") echo "checked"; ?>>Homme</label>	  
						<label class="radio-inline pull-left"><input type="radio" name="<?php echo $fn['sexe'];?>" id="sexe-f" value="F" <?php if($data["sexe"]== "F") echo "checked"; ?>>Femme</label>
					</div>
					<div class="col-sm-hidden col-md-6">&nbsp;</div>    
				</div>  
			</li>
		    <li class="list-group-item">
				<div class="form-group">
				    <label class="col-sm-hidden col-xs-hidden col-md-2 control-label" for="birthday"> Date de naissance : </label>
					<div   class="col-sm-12 col-md-10">
						<div class="input-group">
						    <input type="text" name="<?php echo $fn['birthday']; ?>" id="<?php echo $fn['birthday']; ?>" class="form-control birthday" readonly value="<?php echo $data["birthday"]; ?>" />
							<span class="input-group-addon">
							<i class="fa fa-calendar"></i></span> 
							<input type="text" name="<?php echo $fn['birthaddress']; ?>" id="<?php echo $fn['birthaddress']; ?>" class="form-control" placeholder="Lieu de naissance" value="<?php echo $data["birthaddress"]; ?>" />
							 
						</div>
					</div>
				</div>
			</li>
			<li class="list-group-item">       
				<div class="form-group">
				    <label class="col-sm-hidden col-xs-hidden col-md-2 control-label">Nationalité:</label>
					<div   class="col-sm-12 col-md-10"><?php echo $this->formSelect($fn['nationalite'], $data["nationalite"] , array("class" => "form-control") , $this->countries()); ?> </div>					
				</div>  
		    </li>
			<li class="list-group-item">       
				<div class="form-group">
				    <label class="col-sm-hidden col-xs-hidden col-md-2 control-label"> Adresse*: </label>
					<div   class="col-sm-12 col-md-10">
					    <div class="input-group">
				            <?php echo $this->formSelect($fn['country'], $data["country"], array("class"=>"form-control countries"), $this->countries()); ?>  			   
					        <span  class="input-group-btn" style="width:0px;"></span>
							<input id="<?php echo $fn['address']; ?>" name="<?php echo $fn['address']; ?>" type="text" maxlength="220" title="Votre adresse" placeholder="Votre adresse" class="form-control">
				        </div>
					</div> 
				</div>  
		    </li>			 
            <li class="list-group-item">      
				<div class="form-group">    
					<label class="col-md-2 col-sm-2 col-xs-hidden control-label">Situation matrimoniale: </label>
					<div   class="col-sm-12 col-md-10"> <?php echo $this->formSelect($fn["matrimonial"], $data["matrimonial"] , array("class" => "form-control") , $situations); ?></div>
				</div>
			</li>		
		</ul>
		<div class="panel-heading"> <h4 class="panel-title"> <span class="glyph-icon icon-user"></span> 2.Les informations de la pièce d'identité</h4></div>
		<ul class="list-group">	
		    <li class="list-group-item">      
				<div class="form-group">    
					<label class="col-md-2  col-sm-2  control-label">Type de pièce*:</label>
					<div   class="col-md-10 col-sm-10">
						<label class="radio-inline pull-left"><input type="radio" name="<?php echo $fn['identitetype'];?>" id="<?php echo $fn['identitetype'];?>-1" value="1" <?php if($data["identitetype"]=="1") echo "checked"; ?>> CNIB     </label>          
						<label class="radio-inline pull-left"><input type="radio" name="<?php echo $fn['identitetype'];?>" id="<?php echo $fn['identitetype'];?>-2" value="2" <?php if($data["identitetype"]=="2") echo "checked"; ?>> PASSPORT </label>
					    <label class="radio-inline pull-left"><input type="radio" name="<?php echo $fn['identitetype'];?>" id="<?php echo $fn['identitetype'];?>-3" value="3" <?php if($data["identitetype"]=="3") echo "checked"; ?>> CARTE CONSULAIRE </label>
					    <label class="radio-inline pull-left"><input type="radio" name="<?php echo $fn['identitetype'];?>" id="<?php echo $fn['identitetype'];?>-4" value="4" <?php if($data["identitetype"]=="4") echo "checked"; ?>> CARTE PROFESSIONNELLE </label>
					</div>
				</div>
			</li>
			<li class="list-group-item">  
				<div class="form-group">            
					<label class="col-sm-2  col-md-2 control-label"><b> Numéro*:</b> </label> 
					<div   class="col-sm-10 col-md-10">
						<div class="input-group"><input type="text" maxlength="250" class="form-control" title="Numéro de la pièce d'identité" placeholder="Numéro de la pièce d'identité" id="<?php echo $fn['numidentite'];?>" name="<?php echo $fn['numidentite'];?>" value="<?php echo $data['numidentite'];?>"> </div> 
					</div>					    
				</div>
                <p id="numero_identite-validation-message" class="validation-message"></p>				
			</li>
			<li class="list-group-item">  
				<div class="form-group">            
					<label class="col-sm-2  col-md-2 control-label"><b> Organisme d'étalissement*:</b> </label> 
					<div   class="col-sm-10 col-md-10">
						<div class="input-group"><input name="<?php echo $fn['organisme_etablissement'];?>" id="<?php echo $fn['organisme_etablissement'];?>" type="text" maxlength="150" class="form-control" title="Organisme d'étalissement de la pièce d'identité" placeholder="Organisme d'étalissement de la pièce d'identité" value="<?php echo $data['organisme_etablissement'];?>"> </div> 
					</div>					    
				</div> 
				<p id="organisme_identite-validation-message" class="validation-message"></p>
			</li>
            <li class="list-group-item"> 			
				<div class="form-group">    
					<label class="col-sm-2  col-md-2 control-label"><b> Date & lieu d'étalissement*:</b> </label> 
					<div   class="col-sm-10 col-md-10">
						<div class = "input-group">
						   <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect($fn["date_etablissement_day"] , $data["date_etablissement_day"]  , array("class" => "form-control chosen grpChosen"),array("00"=>"Jour")+createDatesArray());?></span>
						   <span class="input-group-btn" style="width:0px;"></span>
						   <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect($fn['date_etablissement_month'],$data["date_etablissement_month"], array("class" => "form-control chosen grpChosen"),array(0 =>"Mois")+$this->months()); ?> </span>
						   <span class="input-group-btn" style="width:0px;"></span>
						   <span class="input-group-btn" style="width:125px;"><?php echo $this->formSelect($fn['date_etablissement_year'], $data["date_etablissement_year"] , array("class" => "form-control chosen grpChosen"),array(0 =>"Année")+createYearsArray(1900, intval(date("Y")) ) );?></span>
						   <span class="input-group-btn" style="width:0px;"></span>
						   <input style="height:40px;" type="text" name="<?php echo $fn['lieu_etablissement'];?>" id="<?php echo $fn['lieu_etablissement'];?>" class="form-control" value="<?php echo $data["lieu_etablissement"]; ?>" placeholder="Lieu d'établissement" title="Lieu d'établissement de la pièce" />
						</div>
					</div>                    				
			    </div>
			    <p id="lieu_identite-validation-message" class="validation-message"></p> 		
			</li>
			<li class="list-group-item">
			    <div class="form-group">
					<label class="col-sm-hidden col-xs-hidden col-md-2 control-label">  <b> Termes du service </b> </label>
					<div   class="col-sm-12 col-md-10">
						<div style="border: 1px solid #e5e5e5; height: 200px; overflow: auto; padding: 10px;">
							<p>Lorem ipsum dolor sit amet, veniam numquam has te. No suas nonumes recusabo mea, est ut graeci definitiones. His ne melius vituperata scriptorem, cum paulo copiosae conclusionemque at. Facer inermis ius in, ad brute nominati referrentur vis. Dicat erant sit ex. Phaedrum imperdiet scribentur vix no, ad latine similique forensibus vel.</p>
							<p>Dolore populo vivendum vis eu, mei quaestio liberavisse ex. Electram necessitatibus ut vel, quo at probatus oportere, molestie conclusionemque pri cu. Brute augue tincidunt vim id, ne munere fierent rationibus mei. Ut pro volutpat praesent qualisque, an iisque scripta intellegebat eam.</p>
							<p>Mea ea nonumy labores lobortis, duo quaestio antiopam inimicus et. Ea natum solet iisque quo, prodesset mnesarchum ne vim. Sonet detraxit temporibus no has. Omnium blandit in vim, mea at omnium oblique.</p>
							<p>Eum ea quidam oportere imperdiet, facer oportere vituperatoribus eu vix, mea ei iisque legendos hendrerit. Blandit comprehensam eu his, ad eros veniam ridens eum. Id odio lobortis elaboraret pro. Vix te fabulas partiendo.</p>
							<p>Natum oportere et qui, vis graeco tincidunt instructior an, autem elitr noster per et. Mea eu mundi qualisque. Quo nemore nusquam vituperata et, mea ut abhorreant deseruisse, cu nostrud postulant dissentias qui. Postea tincidunt vel eu.</p>
							<p>Ad eos alia inermis nominavi, eum nibh docendi definitionem no. Ius eu stet mucius nonumes, no mea facilis philosophia necessitatibus. Te eam vidit iisque legendos, vero meliore deserunt ius ea. An qui inimicus inciderint.</p>
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="col-xs-6 col-xs-offset-3">
						<div class="checkbox pull-left">
							<label>
								<input type="checkbox" id="<?php echo $fn['agree_tos']; ?>" name="<?php echo $fn['agree_tos']; ?>" value="1" />En cochant cette case, j'accepte et je reconnais avoir pris connaissance des <a href="#" title="Prendre connaissance des termes du services d'utilisation de la plateform">Conditions Générales d'Utilisation des services de la plateforme du Fichier National.</a>
							</label>
						</div>
					</div>
				</div>
			</li> 
		</ul> 
		<div class="panel-footer">
			<div class="btn-group"><button id="cancelButton" class="btn btn-danger  cancelButton"><i class="glyph-icon icon-chevron-left"> </i>  Annuler </button></div> 
			<div class="btn-group"><button id="createButton" class="btn btn-primary createButton"><i class="glyph-icon icon-save"> </i> Enregistrer </button></div>	
		</div>
	</div>
	<input id="<?php echo $fn['socialstate']; ?>" type="hidden" name="<?php echo $fn['socialstate']; ?>" value="Célibataire" />
    <input id="<?php echo $fn['city']; ?>"        type="hidden" name="<?php echo $fn['city']; ?>" value="0" />     
    <input id="registerDoneUri" type="hidden" name="doneUri"    value="<?php echo $urlCreationDone; ?>" /> 
    <input id="t"               type="hidden" name="t"          value="<?php echo $token; ?>" /> 
	<input id="<?php echo $tokenId; ?>"  type="hidden" name="<?php echo $tokenId; ?>"  value="<?php echo $tokenValue; ?>"  />
</form>
