<?php 
   $demandes      = $this->demandes;
   $demandeur     = $this->demandeur;  
   $demandeurid   = $this->demandeurid;
   $ordercart     = $this->ordercart;
   $cartDemandes  = (isset($ordercart->demandes))?$ordercart->demandes : array();
   $linkAddToCart = $this->url(array("module"=>"public","controller"=>"ordercart","action"=>"addrequest"),"default",true) ;
   $linkEdit      = $this->url(array("module"=>"public","controller"=>"requetes" ,"action"=>"edit"),"default",true) ;
   $linkRetry     = $this->url(array("module"=>"public","controller"=>"requetes" ,"action"=>"retry"),"default",true) ;
   $linkDownload  = $this->url(array("module"=>"public","controller"=>"requetes" ,"action"=>"download"),"default",true) ;
   $output        = "";
   $output       .= "<table id=\"demandesListTable\" class=\"table table-hover table-bordered table-responsive sirah-ui-table scrollable\">
						<thead> 
							<tr>
								<th width=\"18%\"> Dates  </th>
								<th width=\"32%\"> Noms commerciaux </th>
								<th width=\"32%\"> Statuts</th>
								<th width=\"18%\"> Tâches </th>
							</tr>
						</thead>";
    if( count(   $demandes)) {
    	foreach( $demandes as $demande) {
				 $demandeid     = intval($demande["demandeid"]);
				 $objetDemande  = $demande["objet"];
				 $dateDemande   = (intval($demande["date"]))?date("d/m/Y \à H:i",$demande["date"]) : "";
				 $statutDemande = $demande["statut"];
				 $statutid      = $demande["statutid"];
				 $rejected      = $demande["rejected"];
				 $typeDemande   = $demande["type"];  	  	    	  	
     	  	     $linkInfos     = $this->url(array("module"=>"public","controller"=>"requetes","action"=>"infos","demandeid"=>$demandeid), "default",true);
				 $bgColor       = $this->cycle(array("#FFFFFF","#F5F5F5"))->next();
				 $spanBadge     = "";
				 $bgColorClass  = "class=\"table-columns\" ";
				 if( $statutid == 3 || $statutid == 5) {
					 $bgColorClass  = "class=\"table-columns alert danger\"";
					 $spanBadge     = "<span class=\"bs-badge badge-absolute float-right badge-danger\"> Indisponible/Rejeté</span>";
				 } elseif( $statutid == 4) {
					 $bgColorClass  = "class=\"table-columns alert success\"";
					 $spanBadge     = "<span class=\"bs-badge badge-absolute float-right badge-success\">Reservé</span>";
				 }

				 $output       .="<tr id=\"demandeId-".$demandeid."\" ".$bgColorClass." style=\"background-color:".$bgColor."\">";
						$output.="
						                <td ".$bgColorClass." style=\"text-align:left;background-color:".$bgColor."\"><a title=\"Consulter les informations de cette demande\" href=\"".$linkInfos."\">".$dateDemande  ."</a></td>
									    <td ".$bgColorClass." style=\"text-align:left;background-color:".$bgColor."\"><a title=\"Consulter les informations de cette demande\" href=\"".$linkInfos."\"> ".$spanBadge." ".$objetDemande ."</a></td>
									    <td ".$bgColorClass." style=\"text-align:left;background-color:".$bgColor."\"><a title=\"Consulter les informations de cette demande\" href=\"".$linkInfos."\">".$statutDemande."</a></td>";
						if((intval($statutid)==7) && !isset($cartDemandes[$demandeid])) {
							$output.="  <td ".$bgColorClass." style=\"text-align:left;background-color:".$bgColor."\">
											<button type=\"button\" class=\"btn btn-danger addRequestToCart\" title=\"Ajouter au panier\" id=\"addRequestToCartId-".$demandeid."\"><span class=\"glyph-icon icon-shopping-cart\"></span> Ajouter</button>	
										</td>";
						} elseif( isset($cartDemandes[$demandeid])) {
							$output.="  <td ".$bgColorClass." style=\"text-align:left;background-color:".$bgColor."\">
											<button type=\"button\" disabled=\"disabled\" class=\"btn btn-success\"><span class=\"glyph-icon icon-shopping-cart\"></span>Ajouté au panier</button>	
										</td>";
		                } elseif( intval($statutid)==3 || intval($statutid)==5 || intval($rejected)) {
							$output.="  <td style=\"text-align:left;background-color:".$bgColor."\">
							                
											<button type=\"button\" class=\"btn btn-primary retryRequest\" id=\"retryRequestId-".$demandeid."\"><span class=\"glyph-icon icon-edit\"></span> Réessayer </button>	
										</td>";
		                } elseif( intval($statutid)== 4 ) {
							$output.="  <td ".$bgColorClass." style=\"text-align:left;background-color:".$bgColor."\">
											<button type=\"button\" class=\"btn btn-primary downloadRequest\" id=\"downloadRequestId-".$demandeid."\"><span class=\"glyph-icon icon-file-pdf\"></span> Attestation</button>	
										</td>";
						} else {
							$output.="  <td ".$bgColorClass." style=\"text-align:left;background-color:".$bgColor."\"></td>";
						}
						
				 $output.="</tr>";
				 $output.=" <input type=\"hidden\" name=\"objet-".$demandeid." id=\"objet-".$demandeid."\" value=\"".$objetDemande."\" />";
    	  }    	  
    }  else {
		$output .= "<tr id=\"demandeId-0\"><td colspan=\"3\" style=\"text-align:center !important;\"> AUCUNE DEMANDE N'A ETE TROUVEE. </td></tr>";
    }
    $output     .= "</table>";
    
    echo  $output ;
        
    $jq      =  $this->jQuery();
	$onLoad  = "
	    jQuery('.addRequestToCart,.retryRequest,.donwloadRequest').css('cursor','pointer');
		jQuery('.retryRequest').click(function(event){ 
		    event.preventDefault();
			var demandeBtn = jQuery(this);
			var demandeKey = jQuery(this).attr('id');
            var demandeid  = demandeKey.replace('retryRequestId-','');
			document.location.href=\"".$linkRetry."/demandeid/\"+demandeid;
		});
		jQuery('.downloadRequest').click(function(event){ 
		    event.preventDefault();
			var demandeBtn = jQuery(this);
			var demandeKey = jQuery(this).attr('id');
            var demandeid  = demandeKey.replace('downloadRequestId-','');
			document.location.href=\"".$linkDownload."/demandeid/\"+demandeid;
		});
        jQuery('.addRequestToCart').click(function(){      
		    var demandeBtn = jQuery(this);
			var demandeKey = jQuery(this).attr('id');
            var demandeid  = demandeKey.replace('addRequestToCartId-','');
			demandeBtn.html('Ajout au panier...');demandeBtn.addClass('disabled');
			jQuery.ajax({url:'".$linkAddToCart."',async:true,dataType:'json',data:{'demandeid':demandeid},type:'GET',
				beforeSend:function(){demandeBtn.html('En cours...');demandeBtn.addClass('disabled');},
				success  : function(data) {
					if( data.error !== undefined) {
						alert(data.error);
						demandeBtn.addClass('addRequestToCart');
						demandeBtn.removeClass('disabled');
						demandeBtn.html('<span class=\'glyph-icon icon-shopping-cart\'></span> Ajouter au panier');
					} else if(data.success !== undefined && data.counter !==undefined ) {
						jQuery('#cartCounter').html(data.counter); 
						jQuery('#cardUpdateBtn').trigger('addProduct');
						demandeBtn.removeClass('addRequestToCart');								
						demandeBtn.removeClass('btn-danger').addClass('btn-success').addClass('disabled');
						demandeBtn.html('<span class=\'glyph-icon icon-check\'></span>Ajouté au panier');
					}
				}
			}); 
		});
	
	
	";    
    $jq->addOnLoad($onLoad);
?>
             