<?php 
    $member      = $this->member;
    $documents   = $this->documents;  
	$model       = new Model_Document();
    
	$output      = "";
    $output     .= "<ul class=\"list-group documentList\">";
    $totalSize   = 0;
    if( count(   $documents)) {
    	foreach( $documents as $document) {
				 $documentid   = intval($document["documentid"]);
				 $filename     = $document["filename"];
				 $fileExtension= strtolower($document["fileExtension"]);
				 $filemetadata = $document["filemetadata"];
				 $filesize     = $document["filesize"];
				 $libelle      = $model->filterIndex($filename, $document["userid"] );
				 $documentTitle= $document["categorie"];
				 $icone        = "glyph-icon icon-file-pdf";
				 $class        = "openDocumentDialog";
				 $title        = "Accéder au document";
				 if( empty($documentTitle) ) {
					 $documentTitle = sprintf("%s : %d",$libelle,$document["catid"]);
				 }
				 if( isset($document["categorie"]) && !empty($document["categorie"])) {
					 $libelle  = $document["categorie"];
				 }  
				 if( isset($document["facture"]) && !empty($document["facture"])) {
					 $libelle  = $document["facture"];
				 }
				 if( isset($document["attestation"]) && !empty($document["attestation"])) {
					 $libelle  = $document["attestation"];
				 }
				 $filesize     = (isset($document["filepath"]) && file_exists($document["filepath"]))? filesize( $document["filepath"] ) : $document["filesize"] ;
				 $sizeKo       = Sirah_Functions::toByteString( $filesize, "" , 2 );
				 $totalSize   += $filesize;
				
				 switch( $fileExtension ) {
					case "pdf":
						$icone = "glyph-icon icon-file-pdf";
						break;
					case "png":
					case "gif":
					case "jpg":
					case "jpeg":
					case "bmp":
						$icone = "glyph-icon icon-file-image-o";
						$class = "dialogViewInfos";
						break;    	  			
				 }    	  	    	  	
				 $linkView  = $this->url(array("module"=>"public","controller"=>"userdocuments","action"=>"download","id"=>$documentid),"default",true);    	  	
				 $output   .= " <li id=\"documentId-".$documentid."\" class=\"list-group-item\">
									<div class=\"row\">						  
										<div class=\"col-md-1\"><span title=\"Télécharger le document\" id=\"fileId-".$documentid."\"  class=\"glyph-icon icon-download downloadDocument\"></span></div>   
										<div class=\"col-md-8\"><span class=\"".$icone."\"></span><a class='".$class."' title='".$title."' href='".$linkView."'>".$libelle." </a></div>
										<div class=\"col-md-3\"><p class=\"text-mute\"> ".$sizeKo."</p> </div>                                                             
									</div>
							    </li> ";
		}
		$totalSizeKo = Sirah_Functions::toByteString( $totalSize );
		$output     .= "<li id=\"documentId-".$documentid."\" class=\"list-group-item\">
							<div class=\"row\">
								<div class=\"col-md-9\"> <p class=\"list-group-item-text\"> Taille totale : </p> </div>
								<div class=\"col-md-3\"> <p class=\"text-mute\"> ".$totalSizeKo."</p> </div>
							</div>
						</li> ";
    }  else {
    	$output    .= " <li class=\"list-group-item\" id=\"documentId-0\"><p class=\"list-group-item-text\"> Aucun document n'a été rattaché à votre compte. </p></li>";
    }
    $output     .= "</ul>";
    
    echo  $output ;
        
    $jq      =  $this->jQuery();
     
    $jq->addOnLoad($onLoad);
?>
             