<?php 
   $member      = $this->member;
   $memberid    = $this->memberid;
   $me          = Sirah_Fabric::getUser();
   $paiements   = $this->paiements;
   $canRemove   = $me->isAllowed("paiements", "delete");
   $linkDelete  = $this->url(array("module"=>"public","controller"=>"paiements","action"=>"delete"),"default",true) ;
   $linkCreate  = $this->url(array("module"=>"public","controller"=>"paiements","action"=>"create" ,"memberid"=> $memberid),"default",true) ;
   $output      = " <table id=\"paiementsList\" class=\"table table-striped table-responsive paiementsList\">
                        <thead>
                            <tr>
							    <th style=\"text-align:left;\"  width=\"width:15%\"> Dates    </th>	
							    <th style=\"text-align:left;\"  width=\"width:20%\"> N° transactions </th>								
                                <th style=\"text-align:left;\"  width=\"width:35%\"> Statuts  </th>							
                                <th style=\"text-align:right;\" width=\"width:30%\"> Montants </th>
								
                            </tr>
                        </thead>";
   
    if( count(  $paiements ) ) {
   	            $paiementTotal = 0;
   	            $soldeTotal    = 0;
   	            $lastSolde     = 0;
   	            $valCommande   = isset($paiements[0]["totalAPayer"] ) ? $paiements[0]["totalAPayer"] : 0;
   	    foreach($paiements as $paiement ) {
   	   	        $paiementid    = $paiement["paiementid"];
   	   	        $numero        = $paiement["transid"];
   	   	        $statut        = $paiement["statut"];
   	   	        $montant       = number_format( $paiement["montant"], 0, ","," ");
				$datePaiement  = (isset($paiement["date_paiement"]))?$paiement["date_paiement"] : "";
   	   	        $paiementTotal+= $paiement["montant"];
                if( isset($paiement["date"]) && intval($paiement["date"])) {
					$zendDate  = new Zend_Date($paiement["date"],Zend_Date::TIMESTAMP);
					if( $zendDate ) {
						$datePaiement  = $zendDate->toString("dd MMM Y");
					}
				}
   	   	        $rowBg         = $this->cycle(array("#F0F0F0","#F5F5F5"))->next();
   	   	        $linkInfos     = $this->url(array("module"=>"public","controller"=>"paiements","action"=>"infos","paiementid"=>$paiementid), "default",true);
   	   	        
   	   	        $output       .="  <tr id=\"paiementId-".$paiementid ."\" style=\"background-color:".$rowBg."\"> ";
                       $output.="     <td style=\"text-align:left;\"> ".$datePaiement."</td>";
					   $output.="     <td style=\"text-align:left;\"> ".$numero      ."</td>";				  
					   $output.="     <td style=\"text-align:left;\"> ".$statut      ."</td>";
   	   	               $output.="     <td style=\"text-align:right;\">".$montant     ."</td>";
   	   	              
					  
				$output       .=" </tr>";
   	    }
   	    $rowBg                 = $this->cycle(array("#F0F0F0","#F5F5F5"))->next();
   	    $paiementTotalFormat   = sprintf("%s F CFA",number_format( $paiementTotal, 0 , ",", " " ));
 
   	    $output               .="<tr id=\"paiementId-Total\" style=\"background-color:".$rowBg."\"> 
								    <td style=\"text-align:center;\" colspan=\"3\"> TOTAL </td>
								    <td style=\"text-align:right;\"> ".$paiementTotalFormat." </td>
   	                             </tr>";
   } else {
   	    $output     .=" <tr> <td style=\"text-align:center;\" colspan=\"4\"> Aucun paiement n'a été trouvé.</td> </tr>";
   }
   $output.= " </tbody></table>";   
    
   echo  $output ;
        
$jq      =  $this->jQuery();
 
?>
             