<?php 
$demandeur   = $this->demandeur;
$member      = $this->member;
$memberid    = $this->memberid;

$basePath    = VIEW_BASE_PATH;
$jq          = $this->jQuery();
$birthDate   = "00/00/0000";
if( $member->birthday ) {
    $zendBirthDate = new Zend_Date( $member->birthday, Zend_Date::DATETIME );
    $birthDate     = ($zendBirthDate)?$zendBirthDate->toString("dd MMMM YYYY") : "Pas renseigné";
}
$numPassport = ($demandeur)?sprintf("%s n° %s du %s établi par %s %s",$demandeur->typePiece,$demandeur->numeroPiece,$demandeur->date_etablissement,$demandeur->organisme_etablissement,$demandeur->lieu_etablissement) : $member->passport;
$sexeValue   = ($member->sexe=="M" || $member->sexe=="Masculin")?"Homme" : "Femme";
?>
<ul  class="list-group">
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b>Pièce Identité:</b></div> 
			<div class="col-md-8"><?php echo $numPassport; ?></div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Nom :</b></div> 
			<div class="col-md-8"><?php printf("%s %s", $member->lastname, $member->firstname ); ?></div>
		</div>
	</li> 
 
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Sexe :</b></div> 
			<div class="col-md-8"><?php echo $sexeValue; ?></div>
		</div>
	</li>
 
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Email:</b></div> 
			<div class="col-md-8"><?php echo $member->email; ?></div>
		</div>
	</li>
	<li class="list-group-item">
		<div class="row"> 
			<div class="col-md-4"> <b> Téléphone:</b></div> 
			<div class="col-md-8"><?php printf("%s %s", $member->tel1, $member->tel2); ?></div>
		</div>
	</li>                          
</ul>
<?php 
    if( $this->isAjax ) {
     	echo $this->jQuery();
	    echo $this->headStyle();
    }
?>