<?php   
    $invoice             = $this->invoice;
	$invoiceid           = $this->invoiceid;
    $commande            = $this->commande;
    $commandeid          = $this->commandeid;
	$client              = $this->client;
    $lignes              = $this->products;
	$products            = $this->products;
 
    $documents           = $this->documents;
 
    $valeur              = ($commande->valeur_ht       )? number_format($commande->valeur_ht , 0, ", ", " ") : 0;
	$valeurSubTotal      = ($commande->valeur_sub_total)? number_format($commande->valeur_sub_total, 0, ", ", " ") : 0;
	$valeurHT            = ($commande->valeur_ht       )? number_format($commande->valeur_ht , 0, ", ", " ") : 0;
	$valeurTTC           = ($commande->valeur_ttc      )? number_format($commande->valeur_ttc, 0, ", ", " ") : 0; 
	
    $statut              = $this->statut;
    $me                  = Sirah_Fabric::getUser();
    
    $basePath            = VIEW_BASE_PATH;
    $jq                  = $this->jQuery();
    
    $linkBack            = $linkCancel = $this->url(array("module"=>"public","controller"=>"invoices","action"=>"list"),"default",true);
    $linkCreate          = $this->url(array("module"=>"public","controller"=>"invoices","action"=>"create"), "default");
    $linkGet             = $this->url(array("module"=>"public","controller"=>"invoices","action"=>"get","invoiceid"=>$invoiceid),"default",true);
	$linkDownload        = $this->url(array("module"=>"public","controller"=>"invoices","action"=>"download","id"=>$invoiceid,"invoiceid"=>$invoiceid),"default",true);
        
	$buttonBar           = $this->Btnbar(array("class" => "button-pane"), $this->jqueryHandler());

	$buttonDownload      = $buttonBar->button("Imprimer"            , "print");
    $buttonCancel        = $buttonBar->button("Revenir sur la liste", "chevron-left");
        
	$buttonBar->add( $buttonCancel, "cancelButton");    
	$buttonBar->add( $buttonDownload, "downloadButton");

    $buttonDownload->setAttributes(array("type"=>"submit", "class"=>"btn btn-primary"));
    $buttonCancel->setAttributes(  array("type"=>"submit"));
	
	$buttonDownload->onClick(sprintf("event.preventDefault();document.location.href=\"%s\"",$linkDownload));
	$buttonCancel->onClick(  sprintf("event.preventDefault();document.location.href=\"%s\"",$linkBack));
    
	$invoiceDate         = "00/00/0000";
    if( $invoice->date ) {
    	$zendInvoiceDate = new Zend_Date( $invoice->date, Zend_Date::TIMESTAMP );
    	$invoiceDate     = ($zendInvoiceDate)?$zendInvoiceDate->toString("d MMM Y à H:m") : $invoiceDate;
    }
	$linkCommande        = $this->url(array("module"=>"public","controller"=>"orders","action"=>"infos","commandeid"=>$commandeid),"default",true);
?>
<div class="row mrg20B mrg5L"><?php echo $buttonBar; ?></div>
<div id="invoiceInfosWrapper" class="row"> 
    <div  class="col-sm-12 col-md-5">
        <div class="panel panel-primary">
            <div class="panel-heading"> <h4 class="panel-title"> Détails de la facture</h4>  </div>
			<div class="list-group pad4A">
			    <a class="list-group-item">
					<div class="row"> 
					   <div class="col-md-4 col-sm-4"> <b> Référence:</b></div> 
					   <div class="col-md-8 col-sm-8"><?php echo $invoice->numero; ?></div>
				    </div>
				</a>
			    <?php if( $commande): ?>
				<a href=" <?php echo $linkCommande; ?>" class="list-group-item">
					<div class="row"> 
					   <div class="col-md-4 col-sm-4"> <b> Commande N°:</b></div> 
					   <div class="col-md-8 col-sm-8"><?php echo $commande->ref; ?></div>
				    </div>
				</a>
				<?php endif; ?>
				<a class="list-group-item">
					<div class="row"> 
					   <div class="col-md-4 col-sm-4"> <b> Date :</b></div> 
					   <div class="col-md-8 col-sm-8"><?php echo $invoiceDate; ?></div>
					</div>
				</a>
				<a class="list-group-item">
					<div class="row"> 
					   <div class="col-md-4 col-sm-4"> <b> Montant HT:</b></div> 
					   <div class="col-md-8 col-sm-8"><?php printf("%s F CFA",$valeurHT); ?></div>
					</div>
				</a>
				<a class="list-group-item">
					<div class="row"> 
					   <div class="col-md-4 col-sm-4"> <b> Montant TTC:</b></div> 
					   <div class="col-md-8 col-sm-8"><?php printf("%s F CFA",$valeurTTC); ?></div>
					</div>
				</a>
				<?php if( $statut ): ?>
				<a class="list-group-item">
					<div class="row"> 
					   <div class="col-md-4 col-sm-4"> <b> Statut:</b></div> 
					   <div class="col-md-8 col-sm-8"><?php echo $statut->libelle; ?></div>
				    </div>
				</a>
				<?php endif; ?>
			</div>                             
        </div>    
    </div>    
    <div class="col-md-7 col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading"> <h4 class="panel-title"> <span class='glyph-icon icon-list-alt'></span> Les produits et/ou services commandés </h4></div> 
            <?php echo $this->partial("invoices/products.phtml", array("products"=>$products,"lignes"=>$lignes,"commandeid"=>$commandeid,"commande"=>$commande)); ?>
        </div>         
    </div>
</div>