<?php 
    $commande   = $this->commande;
    $commandeid = $this->commandeid;
	$products   = $this->products;
	$total      = 0;
	$output     = "";
    $output    .= " <table id=\"commandeProducts\" class=\"table table-hover table-striped\" >
                        <thead><tr> <th width=\"60%\">Désignations</th><th style=\"text-align:left;\" width=\"10%\">Qté</th><th width=\"15%\">Valeur HT</th><th width=\"15%\">Valeur TTC</th></tr></thead>
						<tbody>";
    if( count(  $products)) {
    	foreach($products as $product) {
				$productid    = intval($product["productid"]);
                $produitCode  = sprintf("%s",$product["produitCode"]);
				$produitLib   = sprintf("%s",$product["produit"]);
				$quantite     = (floatval($product["quantite"]  ))?sprintf("%s", number_format($product["quantite"]  ,0," ", " ")) : 0;
				$valeurHT     = (floatval($product["valeur_ht"] ))?sprintf("%s", number_format($product["valeur_ht"] ,0," ", " ")) : 0; 
				$valeurTTC    = (floatval($product["valeur_ttc"]))?sprintf("%s", number_format($product["valeur_ttc"],0," ", " ")) : 0;
				$linkProduct  = $this->url(array("module"=>"admin","controller"=>"products","action"=>"infos","productid"=>$productid),"default",true);
				$total        = $total + $valeurTTC;
				$output      .= "<tr id=\"productId-".$productid."\">";
				    $output  .= "   
					                <td style=\"text-align:left;\"> <a class=\"dialogViewInfos\" href=\"".$linkProduct."\" title=\"Consulter les informations de l'élement\">".$produitLib ."</a></td>
									<td style=\"text-align:left;\"> <a class=\"dialogViewInfos\" href=\"".$linkProduct."\" title=\"Consulter les informations de l'élement\">".$quantite   ."</a></td>
									<td style=\"text-align:right;\"><a class=\"dialogViewInfos\" href=\"".$linkProduct."\" title=\"Consulter les informations de l'élement\">".$valeurHT   ."</a></td>
									<td style=\"text-align:right;\"><a class=\"dialogViewInfos\" href=\"".$linkProduct."\" title=\"Consulter les informations de l'élement\">".$valeurTTC  ."</a></td>
							    ";
				$output      .= "</tr>";
		} 
		        $montantTotal = (floatval($total))?number_format($total,0,",",".") : $total;
		        $output      .= "<tr id=\"productId-0\">";
				$output      .= "   <td colspan=\"2\" style=\"text-align:center;\"><strong>TOTAL: </strong></td>";
				$output      .= "   <td colspan=\"2\" style=\"text-align:center;\"><strong>".$montantTotal." F CFA </strong> </td>";
				$output      .= "</tr>";
    }  else {
    	        $output .= "<tr id=\"productId-0\"><td colspan=\"4\" style=\"text-align:center !important;\"> AUCUN PRODUIT N'A ETE ASSOCIE A CETTE COMMANDE</td></tr>";
    }
    $output     .= "</tbody></table>";
    
    echo  $output ;     
?>
             