<?php 
    $keyword     = $this->keyword;
   
    $linkEdit      = $this->url(array("module" => "admin","controller" => "demandeblacklist", "action" => "edit" , "id" => $keyword->itemid) , "default" ) ;
    $linkCancel    = $this->url(array("module" => "admin","controller" => "demandeblacklist", "action" => "list"), "default" ) ;
     
    $buttonbar     = $this->Btnbar(array("id" => "MyBtnBar") , $this->jqueryHandler());  
    $buttonEdit    = $buttonbar->button(" Modifier", "edit")->setPriority("primary");
    $buttonCancel  = $buttonbar->button(" Revenir sur la liste", "chevron-left");
   
    $buttonbar->add( $buttonCancel , "cancelButton");
    $buttonbar->add( $buttonEdit   , "editButton");
     
    $buttonEdit->onClick("  event.preventDefault(); document.location.href='".$linkEdit."' ;");
    $buttonCancel->onClick("event.preventDefault(); document.location.href='".$linkCancel."' ;");
?>
  
 <div class="container pagecontainer col-md-12" style="text-align:left;">
    <ul class="list-group">
		<li class="list-group-item">
		    <div class="row"> 
				<div class="col-md-4"> <label class="label" for="libelle"> <b>  Désignation: </b> </label></div> 
				<div class="col-md-8"> <?php echo $this->escape($keyword->libelle);  ?></div>
		    </div>
		</li>             
		<li class="list-group-item">
		    <div class="row"> 
				<div class="col-md-4"> <label class="label" for="description"> <b> Description :</b> </label></div> 
				<div class="col-md-8"> <?php echo $this->escape($keyword->description);  ?> </div>
		    </div>
	    </li>     
	</ul>
</div>
    <?php 
          if(!$this->isAjax) {
          	 echo $buttonbar;
          } else {
          	 echo $this->jQuery();
          }
      ?>   